### ISSUE TITLE
Example config for LDAP user registry

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#1091]
https://www.openliberty.io/docs/ref/feature/#ldapRegistry-3.0.html

Add the following config examples to the LDAP feature. I talked to Jesse about this as part of a separate discussion so I'm capturing it here as we hadn't previously created an issue for LDAP.

SME: Jesse Van Hill

According to Jesse, this is about the minimal most users would ever need for LDAP config. You'll need to explain what the example is doing so you'll maybe need to talk to Jesse about it (eg what's the idsFilters bit about - he said that's probably needed). The following info is what he provided in comments in the config example but that's not the approach we take (for example, that wouldn't be translated as part of the sample code so it's better to be in the main text). See if the following text makes sense to you and ask Jesse to clarify anything that doesn't.

Minimum example that anyone needs to be able to use an LDAP registry:

```<ldapRegistry baseDN="o=ibm.com" host="bluepages.ibm.com"
		ldapType="IBM Tivoli Directory Server" port="389" realm="BluePages" />
```
[You (ID) can try this out with an internal test LDAP server if you want. Let me know and I'll give you the details.] 

The example shows a sample IBM Tivoli LDAP Registry. Customize the group and user filters that will be used to perform searches. Use '%v' for attribute value assertions that will replaced by the login name.

```
	<ldapRegistry baseDN="o=acme.com" host="ldap.acme.com"
		ldapType="IBM Tivoli Directory Server" port="389" realm="AcmeLdap">
		<idsFilters
			groupFilter="(&amp;(cn=%v)(objectclass=customGroup))"
			userFilter="(&amp;(objectclass=customPerson)(|(uid=%v)(mail=%v)))" />
	</ldapRegistry>
```

Another example. Add in the ldapEntityType elements to xxxx (ask Jesse). These were part of his original server.xml example but he said they weren't essential for someone who could just use the default values.
 
```
		<ldapEntityType name="PersonAccount">
			<objectClass>customPerson</objectClass>
			<searchBase>ou=users,o=acme.com</searchBase>
		</ldapEntityType>
		<ldapEntityType name="Group">
			<objectClass>customGroup</objectClass>
			<searchBase>ou=groups,o=acme.com</searchBase>
		</ldapEntityType>
```

Another. Again, find out what this is for. Again, this was part of his original example but he said they weren't essential.

```
        <groupProperties>
            <memberAttribute name="member" objectClass="customGroup" />
        </groupProperties>
```

Then confirm with Jesse that these three examples are actually the most useful bits that 80% of users would need to know to be able to successfully set up LDAP in most cases.

**Comment by dmuelle** [comment]
draft was SME reviewed by @jvanhill in #119
view draft at:
https://github.com/OpenLiberty/docs/blob/fcb5021bbfb43a9948cb6a50b0c8473f84abd345/ref/feature/LDAP/example.adoc

**Comment by lauracowen** [comment]
⁃ Remove the first sentence instructing to configure in server.xml - that bit is covered by the auto-generated previous section ("Enabling this feature" section). Just go straight into the example (maybe replace this first 'simple' example with the one you had in the concept topic if it's a better example?).
⁃ Be consistent in capitalisation of Distinguished Name - does it need to be capitalised at all?
⁃ There's a `&amp;` code in the last example - I'm not sure if that's right or whether it should be rendered as `&`?
⁃ In the LDAPS example, is the `idsFilters` section essential to that example? If not, can you remove it to keep each example as small as possible and so it's clear that you don't need to include everything.
⁃ Can you explain what the attributes are for when mentioned (as long as it's not obvious)? eg where it mentions `ssl id` - is it useful to explain what that is?
⁃ As a general style thing (maybe something to discuss/agree with Charlotte), I don't know if it's necessary to append "example" to the end of each sub-heading. Maybe it is - I know the JDBC page is inconsistent in this. We don't append it to the headings in the Social Media Login page, which I think helps you read the meaningful bit of the heading - "example" doesn't really add much when it's on all of them.

**Comment by dmuelle** [comment]
@lauracowen new draft that addresses your comments and brings in the federated example:

https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#ldapRegistry-3.0.html

**Comment by lauracowen** [comment]
Nice. Thanks. Happy to set this to be published.

**Comment by jvanhill** [comment]
Developer approved.

**Comment by Charlotte-Holt** [comment]
@dmuelle Peer review feedback:

Looks good! I have just two questions: 
- Is there anything to link to for this sentence: "For more information, see the configuration element for the LDAP type that you want to specify."? Or are there different configuration elements that are scattered throughout the docs, so it's not possible to link to just one place? 
- Regarding this sentence, "If you configure the LDAP User Registry feature version 3.0 or later, the Federated User Registry feature is enabled by default.", I only see the LDAP User Registry feature version 3.0 and later in the OL docs. Is earlier than 3.0 available with OL?

**Comment by dmuelle** [comment]
Thanks @Charlotte-Holt 

- the feature configs for various LDAP types are listed under `Feature configuration elements` on this page, but I can't anchor link to the section because of the include structure- I could add "For more information, see the configuration element for the LDAP type that you want to specify in the Feature configuration elements section." Do you think that would help?
- Only 3.0 is available today but my thinking was that if 3.1 etc comes out in the future it will let user know that it works for both versions. I guess I could leave that part off since this basically means it would work for all. I think 2.x and earlier are just in wlp

**Comment by Charlotte-Holt** [comment]
@dmuelle 
- No, I think it's fine as you have it. I was thinking it would mostly be helpful if a link could be included, but since it can't, I think it's good as is. 
- Yeah, I think that if it'll work for all, then it's not worth mentioning versions.

**Comment by dmuelle** [comment]
@Charlotte-Holt thanks for reviewing, removed the version number per your recommendation.

**Comment by dmuelle** [comment]
new draft URL: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/reference/feature/ldapRegistry-3.0.html

**Comment by dmuelle** [comment]
Edits
- LDAP registry--> LDAP User Registry (Throughout doc) DQTI Ch6 Clarity:  Use technical terms consistently and appropriately
- If you need to configure search behavior to include custom classes or attributes---> If you need to include custom classes or attributes in searches of an LDAP user registry DQTI ch7 Concreteness: Use specific language

**Comment by chirp1** [comment]
@dmuelle Hi David,
Here are my comments:
- Make the intro paragraph two sentences.
- For "Bind distinguished name and password ...", put a definite or indefinite article in front of "Bind".
- Add a link for "see the documentation for the configuration element for the LDAP type that you want to specify ". Make the link the appropriate wording in the sentence. I believe the link would be to another autogen topic.
- For "If you need to configure support for custom or non-default object classes....", rewrite the sentence as start with "You can..." instead of "If you need to....".
- You breifly explained the purpose of the bind credentials, but not the base distinguished name et al. and not the search base. Add brief explanations for both.
- For "...groups, make sure to update your ...", get rid of the extra words.
- Change "..example shows configuration ..." to "...example shows the configuration...".  <= Add "the".
- Add "user" in front of "registry" or "registries".
- The link on the "Federated user registry" feature text doesn't seem to be working correctly. It isn't linking to the feature info.
- Under "Federation of LDAP registries" you say "LDAP registries are federated by default." and you say "f you configure the LDAP User Registry feature version 3.0 or later, the Federated User Registry feature is enabled by default." Are they saying the same thing, but the second sentence is more accurate? If they mean the same thing rewrite the paragraph.
- Don't put parentheses around the term participatingBaseEntry . If you specify the term, put a noun or noun phrase after the term. Note that a KC topic gives a noun phrase for the term.
- Change "...with configuration specified..." to "...with the configuration specified ...". <= Add "the".
- You say "If you configure more than one LDAP user registry in your server.xml file,...". However, in "Federated User Registry 1.0" you say "If two or more user registries are configured in your server.xml file or in a userRegistry.xml file,....". Should you include "userRegistry.xml" in your description?

**Comment by dmuelle** [comment]
- [x] Make the intro paragraph two sentences. **the first sentence on the page is part of the autogen, I [opened a doc bug](https://github.com/OpenLiberty/docs/issues/2873) to update it.** 

- [x] For "Bind distinguished name and password ...", put a definite or indefinite article in front of "Bind".

- [x] Add a link for "see the documentation for the configuration element for the LDAP type that you want to specify ". **The configuration elements for each LDAP type are listed under the "Feature configuration elements" section of this page. Each LDAP type is a separate link. I added an anchor link to that section of the page**

- [x] For "If you need to configure support for custom or non-default object classes....", rewrite the sentence as start with "You can..." instead of "If you need to....".

- [ ] You breifly explained the purpose of the bind credentials, but not the base distinguished name et al. and not the search base. Add brief explanations for both. **I'm not sure what section this is in reference to? I can't seem to match it up with any of the examples, can you clarify please?**

- [x] For "...groups, make sure to update your ...", get rid of the extra words.

- [x] Change "..example shows configuration ..." to "...example shows the configuration...". <= Add "the".

- [x] Add "user" in front of "registry" or "registries".

- [x] The link on the "Federated user registry" feature text doesn't seem to be working correctly. **fixed**

- [x] Under "Federation of LDAP registries" you say "LDAP registries are federated by default." and you say "f you configure the LDAP User Registry feature version 3.0 or later, the Federated User Registry feature is enabled by default." Are they saying the same thing, but the second sentence is more accurate? If they mean the same thing rewrite the paragraph.
**they aren't the same. LDAP federates by default- however, if you want to customize federation, you need to enable the fed user registry feature. However, if you are using the LDAP 3.0 or higher, the federated user registry is enabled by default. If a user was using less than LDAP 3.0, they would need to manually enable the federated user registry feature to customize federation.**

- [x] Don't put parentheses around the term participatingBaseEntry . **fixed**

- [x] Change "...with configuration specified..." to "...with the configuration specified ...". <= Add "the".

- [x] You say "If you configure more than one LDAP user registry in your server.xml file,...". However, in "Federated User Registry 1.0" you say "If two or more user registries are configured in your server.xml file or in a userRegistry.xml file,....". Should you include "userRegistry.xml" in your description? **In this case, I don't think so because LDAP registries are external. The config in the server.xml points to the external LDAP sever and is specified as part of the LDAP feature config, which wouldn't be in a userRegistry.xml file.**

**Comment by chirp1** [comment]
@dmuelle Hi David,

- For my comment about the opening paragraph, I see that you opened a doc bug. I also think that for that paragraph, "Multiple LDAP registries " could be changed to ' Multiple LDAP user registries " and "a single logical registry view." could be changed to "a single logical user registry view.". <= add "user" to both
For "For more information, see the documentation for the configuration element for the LDAP type that you want to specify. The configuration elements for the available LDAP types are listed in the feature configuration elements section. ", get rid of the second sentence, In the first sentence, change "see the documentation for the configuration element " to something like "see the feature configuration elements section" and make "feature configuration elements section" a link.
- I still seem to see "If you need to configure support...".
- For "You briefly explained the purpose of the bind credentials", never mind. I don't think we need further changes.
- For the item of that says "Under "Federation of LDAP registries" you say .." I believe I understand what you are saying. What do you think about a change something like this: Change "You can adjust the configuration by enabling the Federated User Registry feature and configuring the federatedRepository element." to "You can adjust the configuration when the Federated User Registry feature is enabled and the federatedRepository element is configure.". After " If you configure the LDAP User Registry feature....", add a sentence something like "Otherwise, you must manually enable the feature and configure the element.".

**Comment by dmuelle** [comment]
Hi @chirp1, I made the following changes per your review

- [x] For "For more information, see the documentation for the configuration element for the LDAP type that you want to specify. The configuration elements for the available LDAP types are listed in the feature configuration elements section. ", get rid of the second sentence, In the first sentence, change "see the documentation for the configuration element " to something like "see the feature configuration elements section" and make "feature configuration elements section" a link.

- [x]  I still seem to see "If you need to configure support...". **removed** 

- [x]  Change "You can adjust the configuration by enabling the Federated User Registry feature and configuring the federatedRepository element." to "You can adjust the configuration when the Federated User Registry feature is enabled and the federatedRepository element is configure.". After " If you configure the LDAP User Registry feature....", add a sentence something like "Otherwise, you must manually enable the feature and configure the element.".

**Comment by chirp1** [comment]
@dmuelle Hi David,
- I don't think I see the changes for the bullet that says "For "For more information, see the documentation for the configuration...", which is a good thing as I have somewhat different advice that will make the change more succinct: Remove " For more information, see the documentation for the configuration element for the LDAP type that you want to specify. The configuration elements for the available LDAP types are listed in the feature configuration elements section. ". Replace it with "For more information about the LDAP type, see Feature configuration elements.". Make the "Feature configuration elements" a link.

**Comment by chirp1** [comment]
@dmuelle Hi David. The updates look good!

**Comment by dmuelle** [comment]
moved to vNext for 20.0.0.11 release. Closing this issue
