### ISSUE TITLE
Example config for requestTiming feature

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#1094]
Reach out to Don Bourne to determine the SME for this. 

https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/rwlp_requesttiming.html

**Comment by Rwalls1** [comment]
Link to current draft: https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#requestTiming-1.0.html

**Comment by Rwalls1** [comment]
@pgunapal I have the following topic ready for review: https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#requestTiming-1.0.html. This draft is intended to add relevant config snippets examples that help to understand the configuration of the feature. Please review to verify whether the included examples are relevant to the feature and suggest any examples that should be added.

**Comment by pgunapal** [comment]
@Rwalls1 Looks good, but its missing some key information that is found from its Knowledge Center equivalent: https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_requesttiming.html

It would be good to add the "requestTiming-1.0 feature restrictions", to let users know of the restrictions. I added below some sections that I think would be useful to add. One example config to add is an example using the JDBCTiming child element, under the ServletTiming child element, as follows:

```
	<requestTiming slowRequestThreshold="10s" hungRequestThreshold="10m">
    	 <jdbcTiming dataSourceName="testDBSource" slowRequestThreshold="500ms" hungRequestThreshold="5m"/>
	</requestTiming>  
```

The appName (e.g. SecurityExchangeApp) in the below ServletTiming example has the wrong ending quote being used, so it is not formatted correctly.
```
  <servletTiming appName="SecurityExchangeApp” hungRequestThreshold=”2h”/>
```

Under "Slow and hung request threshold configuration" section, it would be useful to add the following line:
```
The event log contains the type and context information for each request that was processed by the server. With type and context information, you can create a <servletTiming/> or <jdbcTiming/> configuration in the server.xml file for the requests that require different threshold values.
For more information about what context information is provided for each request, see Event Logging in the product documentation. A <servletTiming/> or <jdbcTiming/> configuration can only be used to time a root level request. For example, if a servlet request makes a JDBC query, the JDBC query cannot be timed because the servlet request is the root level request.
```

Under the "Slow request detection" section, it would be good to add the contents from https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_requesttiming.html, where it talks about the details of the table, such as REQUEST ID/STACK TRACE/DURATION AND OPERATION TABLE: 

```
The request continues to be monitored, and a further warning is logged if the request is running beyond another 10 seconds. The log messages are in the following format:
TRAS0112W: Request <(Request ID)> has been running on thread <THREADID> for at least <DURATION>. The following stack trace shows what this thread is currently running.
<STACK TRACE>
<DURATION AND OPERATIONS Table>

REQUEST ID
This same ID can be used to search for log and trace messages corresponding to the request. In particular, if you use binary logging, you can search for log and trace entries with the same requestID extension by using the binary log command.
STACK TRACE
Indicates the method that is running. In the previous sample, you can see a stack trace of the current request after TRAS0112W line.
DURATION AND OPERATIONS Table
After the stack trace, you can find the tabular format of the request that shows the duration and operation (also referred to as the event). The Duration column indicates the time that is taken by the corresponding operation of the request. The plus sign (+) indicates events within the request that are still running. The next line shows the duration without +, which indicates that the corresponding operation completed in the specified duration. Operation shows the EVENT TYPE and CONTEXT INFO (optional) for that operation. For more information about event types and context information, see Event Logging.
By analyzing the messages, you can figure out why the request is slow. However, it might be difficult to determine whether the request is stuck at that point or is still running slowly. Hence you can see three messages that are logged for any slow request at the interval of specified <slowRequestThreshold>. Using the three different stack trace and request data, you get a better insight into the issue. After the third warning, no further warnings are logged about the request unless the duration of the request crosses the hung request detection threshold.
```

Under the "Hung Request Detection" section, it would be useful to add the Notes from https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_requesttiming.html

**Comment by Rwalls1** [comment]
@pgunapal Please review the latest update: https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#requestTiming-1.0.html

**Comment by pgunapal** [comment]
@Rwalls1 Looks good, just a few minor updates:
1) I think the `servletTiming` element example config was accidentally removed after the latest update, we should put it back, in addition to the `jdbcTiming` example:

```
<requestTiming slowRequestThreshold="10s" hungRequestThreshold="10m">
  <servletTiming servletName="Arm10Servlet" hungRequestThreshold=”20s”/>
  <servletTiming appName="SecurityExchangeApp” hungRequestThreshold=”2h”/>
</requestTiming>
```

2) The `<STACK TRACE>` should also be highlighted in grey.

**Comment by Rwalls1** [comment]
@pgunapal Please review the latest update: https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#requestTiming-1.0.html

**Comment by pgunapal** [comment]
@Rwalls1 looks good!

**Comment by Rwalls1** [comment]
@lauracowen Please review: https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#requestTiming-1.0.html

**Comment by lauracowen** [comment]
The purpose and content of this topic seems to have got mixed up with the separate Request Timing topic that @ManasiGandhi is working on. There's a lot of good conceptual explanation in here that should probably be in Manasi's concept topic (which she's still working on).

The purpose of the Examples section of this topic is purely to provide example configurations that users commonly need and can therefore copy/paste from this topic. The text around an example should just provide a little explanation about what's happening in that example.

For example, see https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#jdbc-4.3.html and https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#socialLogin-1.0.html (though this latter one probably has too many examples).

Start by identifying which are the most important/likely/common config examples that a user might need. Put the examples in order of likelihood of being needed. Make sure they (and especially the first example) are as simple as possible; the minimal config needed to make each thing work. Put each in a separate sub-section with a heading that clearly states what the config provides. Then give a brief explanation of why you might need the config and/or what it provides. You don't need to provide instructions in the text about what attributes to set because that's clear from the example provided; instead focus on explaining what the key parts of the config shows/provides (like we do in the guides).

You can link to the relevant concept topics and/or other config topics where needed, if necessary.

In the topic currently, find out whether the first example is the minimal needed to set request timing. Is it necessary to have the `jdbcTiming` element to config request timing or is just the `requestTiming` element needed? Does this example need to be split into two separate examples for different purposes? (eg one basic config and one with additional capability?)

Also, check whether this is only relevant to JDBC (cc @dmuelle as he's currently looking at JPA vs JDBC) or whether it's relevant to JPA. I suspect the JDBC example should either be removed or should be moved to be the last example (David will explain why I'm saying that might be the case - probably need to check with Fred about that).

The second example looks ok but could maybe be simpler. Could the servlet's threshold be configured without also configuring an app's threshold?

Also modify the intro sentence so it's less focused on the config elements and more on its value to the user (what does it provide?); eg
> Heading: Slow or hung servlet requests
The following example shows the number of seconds that a servlet waits when a hung request is detected:

Is there a simple configuration that can be set that doesn't specify individual servlets or apps etc and instead just applies the same threshold to everything? If so, that should be the very first, most basic example. Then provide examples of increasing detail (as long as they're useful). Ultimately, the aim of any topic is to be useful to the target reader.

**Comment by lauracowen** [comment]
I've updated the guidance on writing these topics - shout if there's anything else that should be included: https://ibm.box.com/s/v3oejxfcv1e63me9hxgot3qdkjrmjby4

**Comment by Rwalls1** [comment]
@pgunapal Based on the feedback given above, I have tried to revise the topic to include only the minimal configuration needed to illustrate the feature capability. Please review and offer any further guidance: https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#requestTiming-1.0.html

**Comment by lauracowen** [comment]
@Rwalls1 Just taken a quick skim over it:

- The examples look a lot better/simpler. Thanks. Find out from @pgunapal which is the most likely example needed and order them from most to least.
- Can you provide a sub-heading for each example (so each is in a separate section). Make sure the same level heading for all three.
- Can you condense down the explanatory text above each example XML snippet. It doesn't need to describe what's in the example in terms of instructions about what attributes to set - that's obvious from the example (eg remove "The slow and hung request thresholds are configured by setting the slowRequestThreshold and hungRequestThreshold attributes within the <requestTiming/> element configuration in the server.xml file. "). Instead, focus the text on explaining the effect of the configuration and what the relevant values in the example contribute to that. eg instead of "The following example shows the <requestTiming/> element configuration with the embedded <jdbcTiming/> element configuration:", say something like "The following example shows that slow and hung requests to services are cancelled after 10 minutes of attempts if the service is detected to be hung, or after 10 seconds if the service is detected to be slow." (That's probably an incorrect explanation so find out what the configuration actually means but that's the kind of information that the topic needs to provide. @pgunapal can help explain what the effect of each of the config examples is.)

**Comment by pgunapal** [comment]
@Rwalls1 The most likely example is already the first one, where it is the most simplest configuration the users can set, where it applies the threshold to everything. The following in-depth examples related to JDBC and Servlet are also in the right order.

I agree, the in-depth examples should have sub-heading, so its easier for the users to catch on.

For the first example, the explanation is:
The following example sets the slow and hung request thresholds for all requests, where it will detect requests as slow if it took more than 10 seconds to complete, or as hung if it did not complete in 10 minutes.

For the second example, the explanation is:
The following example shows uses the embedded `<jdbcTiming/>` element to set the slow and hung JDBC request thresholds. It will detect JDBC request with a datasource name of testDBSource to be slow, if it took more than 500ms to complete or hung if it does not complete in 5 minutes.

For the third example, the explanation is:
The following example shows uses the embedded `<servletTiming/>` elements to set the slow and hung request thresholds for two servlets. It will detect Servlet requests with a servlet name of Arm10Servlet and application name of SecurityExchangeApp to be hung, if it does not complete in 20 seconds and in 2 hours, respectively.

Generic to both examples, The embedded configurations will always override the configured slow and hung request threshold that are defined in `<requestTiming/>`.

I think the following statement is good to add with the above examples of using the embedded configurations, as we have seen some customers get confused on why this feature does not work for non-root events.

`A <servletTiming/> or <jdbcTiming/> configuration can only be used to time a root level request. For example, if a servlet request makes a JDBC query, the JDBC query cannot be timed because the servlet request is the root level request.`

**Comment by Rwalls1** [comment]
@pgunapal Please review the latest update: https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#requestTiming-1.0.html

**Comment by pgunapal** [comment]
@Rwalls1 A few comments:

- In the "Configuring JDBC request thresholds" section, the following should be changed from:
`The <requestTiming> element detects that the JDBC request with a datasource name`
 to: 
`The <jdbcTiming> element detects that the JDBC request with a datasource name`

- In the "Configuring servlet request thresholds" section, the first `<servletTiming/>` should be highlighted. The following should be changed from:
`The <requestTiming> element detects that the Arm10Servlet servlet request is hung if the request does not complete in 20 seconds and that the SecurityExchangeApp servlet request is hung if the request does not complete in 2 hours:`
to:
`The <servletTiming> elements detects that the Arm10Servlet servlet request is hung if the request does not complete in 20 seconds and that the servlet request from the application SecurityExchangeApp is hung if the request does not complete in 2 hours:`

**Comment by Rwalls1** [comment]
@pgunapal Please review, I think I've addressed the most recent comments: https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#requestTiming-1.0.html

**Comment by pgunapal** [comment]
@Rwalls1 Looks good, just a minor styling comment:
In the example snippet:
`<servletTiming appName="SecurityExchangeApp” hungRequestThreshold=”2h”/>`
 The quotes should be fixed, so the styling is correctly displayed.

`The embedded configurations always override the configured slow and hung request thresholds that are defined in the <requestTiming/> element configuration.`

The `<requestTiming/>` should be highlighted as well.

**Comment by Rwalls1** [comment]
@pgunapal Please review the latest update: https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#requestTiming-1.0.html

**Comment by pgunapal** [comment]
@Rwalls1 Everything looks good! Thanks!

**Comment by Rwalls1** [comment]
@lauracowen Please review the latest update: https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#requestTiming-1.0.html

**Comment by lauracowen** [comment]
In general, this looks great. Thanks both!

Some minor changes but then it should be done:

- Can you remove the triangular brackets from element names when mentioned in the text? It just adds clutter. So "the `requestTiming` element" instead of "the `<requestTiming>` element".
- By "embedded", does it mean "nested elements"? I don't think you need that detail as it's clear from the example. So just simplify the first sentences to:
  - "The following example sets the slow and hung JDBC request thresholds within the <requestTiming> element configuration. "
  -  "The following example sets the slow and hung request thresholds for two servlets within the `requestTiming` element configuration."
- Instead of the generic explanation about root level requests at the end, can you instead put a specific version of the message at the end of each of the two relevant sections? So that the reader sees the information alongside the example without having to read the whole page. So...
  - "The `jdbcTiming` configuration always overrides the `requestTiming` element configuration. The `jdbcTiming` configuration can be used only to time a root level request. For example...etc"
  - And similarly for the `servletTiming` one.

**Comment by Rwalls1** [comment]
@lauracowen Please review the latest update: https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#requestTiming-1.0.html

**Comment by lauracowen** [comment]
I wasn’t very clear but I meant you to put the two sentences from the end of the topic after each of the two examples (not above it). It’s a trivial thing but I think it works better to have the lead-in sentence the way you had it: what the example describes at a high level. Then the example. Then the two sentences about the overrides.

But other than that, all's good.

**Comment by chirp1** [comment]
Hi Richard, Did you make the last changes that Laura mentioned? If you did, would you add a comment to this issue indicating that you made the changes? If you didn't make the changes, would you make them and then add a comment that you made them? Also, would you have one of the other OL writers peer edit your topic and add their comments in this issue? Then, move this issue to the editorial column.

**Comment by ManasiGandhi** [comment]
#peer review 

@rw2513 The topic looks good. A minor edit suggestion:

- In the section 'Configuring JDBC request thresholds' in the first paragraph, it says, "The jdbcTiming element detects that the JDBC request is slow, if the request requires more than 500 ms to complete or hung if the request does not complete in 5 minutes". Can you move the comma to ""The jdbcTiming element detects that the JDBC request is slow if the request requires more than 500 ms to complete, or hung if the request does not complete in 5 minutes" for clarity?

**Comment by Rwalls1** [comment]
@ManasiGandhi Thanks, I've addressed your feedback.

**Comment by Rwalls1** [comment]
I've addressed Laura's feedback.

**Comment by Rwalls1** [comment]
New link to topic: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/reference/feature/requestTiming-1.0.html

**Comment by Rwalls1** [comment]
PR: https://github.com/OpenLiberty/docs/pull/1726/files

**Comment by Rwalls1** [comment]
@pgunapal Please review: https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/requestTiming-1.0.html

**Comment by pgunapal** [comment]
@Rwalls1 Looks good, it would also be beneficial to add the following as well, as the thread dumps that get created are different based on the JDK being used:

```Also, whenever hung requests are detected, the thread dump files that get created are named differently, based on the Java being used. I suggest adding the following snippet, as the description for the new server configuration attribute:```
**enableThreadDumps:**
```Indicates whether thread dumps will be created if a hung request is detected. A thread stack of the particular thread exceeding the threshold is always produced as part of the hung thread warning in messages.log; however, thread dumps are additional diagnostics showing details of all threads in the process at the time. For OpenJ9 and IBM Java, these are called Java Dumps and are each written to a unique javacore.txt file (e.g. into the current working directory of the process). For HotSpot Java, these are each text snippets appended to stdout (e.g. console.log). Thread dumps may be useful to investigate a broader range of issues such as lock contention, deadlocks, etc. They are generally lightweight (e.g. up to a few hundred milliseconds); although, by default, both JVMs do not bound their disk usage (as compared to messages.log), so extra configuration (e.g. -Xdump) or additional care must be taken to avoid disk exhaustion with many hung threads.```

**Comment by Rwalls1** [comment]
@pgunapal Thanks, that update would actually be better suited to be added to the server config attribute page for requestTiming here: https://draft-openlibertyio.mybluemix.net/docs/latest/reference/config/requestTiming.html. This page requires updates to autogen files. Are you familiar with that process? If not, I can help to make the update.

**Comment by pgunapal** [comment]
@Rwalls1 Yes, I am familiar with that process. Since, this is targeted for 21.0.0.4, hence, the translation deadline has passed, so I think it would be good to make the change that I suggested for the server config attribute update, after 21.0.0.4, for 21.0.0.5, as its not a hard requirement to get that in for the 21.0.0.4 release. I can include it in the GA blog.

**Comment by dmuelle** [comment]
## Content review

Examples look good, very clean and concise. Just a few comments

### Global concerns
I think there are two main issues that might be unclear to someone who is not familiar with this feature:

- [ ] the feature not only detects slow and hung requests, but causes messages to be sent to the logs.
 This is not mentioned on this page. I think we should add an extended description of 1-2 sentences (like we do for the audit-1.0 feature) that explains that the feature initiates log messages for slow/hung requests and then points to the [Slow and hung request detection topic]([url](https://draft-openlibertyio.mybluemix.net/docs/latest/slow-hung-request-detection.html)) for more info.

- [ ] Are requests in question incoming requests that an app/servlet/server is handling, or outgoing requests that the app is waiting for a response to?
This isn't specified anywhere on this page. The [KC topic](https://www.ibm.com/docs/en/was-liberty/base?topic=liberty-slow-hung-request-detection) says "The request timing feature can track the duration of every request that is coming into the system." So I am assuming the feature only times incoming requests but confirm that assumption before editing. I think the extended description as well as the example descriptions should make this distinction clear.

Also- all the examples use attribute values of `slowRequestThreshold="10s" hungRequestThreshold="10m"`, but these are the default values, so why would you need to specify them? 

I think it would be better to  show non-default values (5s, 5min?) and then mention the defaults in the first example. If it is the case that you need to re-specify global default values for these attributes whenever you specify particular `jdbcTiming` or `servletTiming` values for them, we should make that clear.

### Configure Slow and hung request thresholds

- [x] Re defaults, the Slow hung topic says "The default duration value is 10 min. The value that is configured in the following example is 4 min." Something along those lines would work here. It lets the user know there are sensible defaults and you only need to specify the attributes if you want to change them

### Configure JDBC request thresholds

- [x] I think this example needs an additional sentence to clarify that the `jdbcTiming` element specifies defaults for a particular JDBC `dataSource`. 

- [ ] I think it would also be helpful to clarify what a datasource request is in this context- is it a request the server or app sends to the datasource, and the time measured is time spent waiting for a response? Or is it time the server/app takes to respond to an incoming request from the dataSource? This should be more clear throughout the examples and the slow/hung concept topic.
- [x] root level request---> root-level request
- [x] This sentence from the KC topic was omitted, but would add concreteness to the examnple: "For example, if a servlet request makes a JDBC query, the JDBC query cannot be timed because the servlet request is the root level request."

### Configure servlet request thresholds

- [ ] I think it should be clear whether requests timed are outgoing from a servlet or incoming, or both
- [x] I think "the Arm10Servlet servlet request is hung if... "--->"a request to/from the Arm10Servlet servlet request is hung if...", depending on the resolution of the previous comment
- [x] root level request---> root-level request

### Control thread dump collection when hung requests are detected

- [x] "When hung requests are detected with Request Timing,"--->"When the Request Timing feature detects a hung request,"
- [x] I dont think you need quotes around `"false"` in the description because all attribute values are enclosed in quotes. 
- [x] If the enableThreadDumps attribute is set to true or not specified at all, thread dumps are still generated.---> If the enableThreadDumps attribute is set to true or is not specified, thread dumps are generated. 
- [x] In the following example, the enableThreadDumps attribute is set to "false" in the servletTiming element:---> In the following example, the enableThreadDumps attribute is set to "false" in the servletTiming element so no thread dumps are generated for the `myApp` application:

### Related doc bugs to open for 21.0.0.5

- [x] update enableThreadDumps description per @pgunapal suggestion
- [ ] update information in the [Slow request detection section of the Slow and hung request detection doc](https://draft-openlibertyio.mybluemix.net/docs/21.0.0.4/slow-hung-request-detection.html#_slow_request_detection) to give a better explanation of the example format of log messages. The descriptions for REQUEST ID, STACK TRACE, and
DURATION AND OPERATIONS Table [from the KC topic ](https://www.ibm.com/docs/en/was-liberty/base?topic=liberty-slow-hung-request-detection) are useful and not documented elsewhere. Should review the whole topic to see if there is other relevant info to add .

**Comment by Rwalls1** [comment]
Thanks @dmuelle, I've addressed your feedback, I'll open the related docbug issues: https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/requestTiming-1.0.html

- [ ] the feature not only detects slow and hung requests, but causes messages to be sent to the logs.
 This is not mentioned on this page. I think we should add an extended description of 1-2 sentences (like we do for the audit-1.0 feature) that explains that the feature initiates log messages for slow/hung requests and then points to the [Slow and hung request detection topic]([url](https://draft-openlibertyio.mybluemix.net/docs/latest/slow-hung-request-detection.html)) for more info.
 **I think this something we discussed as an initiative to take with each feature page by assessing the need to include a description in joint effort. This might be something we should do for 21.0.0.5 since there is minimal feature work.**
 - [ ] Are requests in question incoming requests that an app/servlet/server is handling, or outgoing requests that the app is waiting for a response to?
This isn't specified anywhere on this page. The [KC topic](https://www.ibm.com/docs/en/was-liberty/base?topic=liberty-slow-hung-request-detection) says "The request timing feature can track the duration of every request that is coming into the system." So I am assuming the feature only times incoming requests but confirm that assumption before editing. I think the extended description as well as the example descriptions should make this distinction clear.
**I think this explanation would be better served to be included in a conceptual topic, since we already have one with the slow and hung request detection, it should be included there. I think there is enough information in the descriptions to understand the examples, which is the purpose of the reference page. I think once we have included this information in the slow and hung request detection topic, we should link to it from this page to fill in any gaps, which I think should be the purpose of larger concept topic** 
- [ ]  I think it would also be helpful to clarify what a datasource request is in this context- is it a request the server or app sends to the datasource, and the time measured is time spent waiting for a response? Or is it time the server/app takes to respond to an incoming request from the dataSource? This should be more clear throughout the examples and the slow/hung concept topic.
**I think this is also detail that should be included in the slow/hung concept topic, that this section would contain a link to.**

**Comment by ManasiGandhi** [comment]
# Peer review

@Rwalls1  The topic looks good! Just a couple comments:

- Typo in the heading from "Configure Slow and hung request thresholds". Change to "Configure low and hung request thresholds".
- I would avoid "always" in these two sentences
"The jdbcTiming element configuration always overrides the requestTiming element configuration for the slow and hung request thresholds.", and
"The servletTiming element configuration always overrides the requestTiming element configuration for the slow and hung request thresholds."
As in the [KC](https://www.ibm.com/docs/en/was-liberty/nd?topic=configuration-requesttiming) it says,

 "jdbcTiming overrides defaults that are specified in the root attributes of requestTiming for JDBC requests.", and

 "servletTiming overrides defaults that are specified in the root attributes of requestTiming for servlet requests."

**Comment by Rwalls1** [comment]
@ManasiGandhi Thanks, I've addressed your feedback: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.4/reference/feature/requestTiming-1.0.html
