### ISSUE TITLE
TLS concept topic

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#1096]
SME: Alaine Demyers

This is a concept topic about securing transport between services (was known as SSL but never mention SSL now) - should refer to TLS (not SSL). They are mostly the same thing, but TLS is newer and includes additional functionality. This topic should be written to provide context around when and why to use TLS, not just technical details about what TLS is.

**Comment by dmuelle** [comment]
Draft at https://draft-openlibertyio.mybluemix.net/docs/ref/general/#csec-tls.html

**Comment by dmuelle** [comment]
Draft is SME reviewed by Alaine- made her suggested updates

**Comment by lauracowen** [comment]
- "TLS is a widely adapted protocol" or a "widely adopted protocol"?
- not sure `not secure` needs to be highlighted? It looks a bit odd. No strong feeling if you disagree tho.
- not sure you always need "The" at the start of the sub-headings. If the noun is singular, it kind of implies there's only one of them, maybe? eg "TLS handshake" (meaning the process) vs "TLS handshakes" (meaning multiple instances of the process?)
- Something's gone wrong here "the TLS protocol they to use, select "
- missing a "the"? in "chance for key to be exposed"
- "The TLS record" heading -> "TLS record protocol", maybe?
- Don't include the config example here. Move it to the TLS feature autogen topic. Also, if this is the minimum that is needed, it should definitely be in the autogen topic instead of what's currently there as the 'minimal' config example (which makes it look a lot more complicated than it should). Then link to that topic from here.
- Typo: "Open liberty"
- Actually, I think this whole "TLS and Open Liberty" section (inc the default TLS config section) should be in the TLS autogen topic instead of the more complex "minimal" example that's there now. Then remove from this concept topic.
- Add a summary couple of sentences or something maybe?

**Comment by dmuelle** [comment]
- Can you avoid using the `csec-` format file name for now. Use something more readable like eg `secure-communication-tls.adoc`? **fixed**
- "TLS is a widely adapted protocol" or a "widely adopted protocol"?**fixed**
- not sure `not secure` needs to be highlighted? It looks a bit odd. No strong feeling if you disagree tho.**revised**
- not sure you always need "The" at the start of the sub-headings. **revised**
- Something's gone wrong here "the TLS protocol they to use, select " **fixed**
- missing a "the"? in "chance for key to be exposed" **fixed**
- "The TLS record" heading -> "TLS record protocol", maybe? **revised**
- Don't include the config example here. Move it to the TLS feature autogen topic. **moved to config example &  revised**
- Typo: "Open liberty" **fixed**
- Actually, I think this whole "TLS and Open Liberty" section (inc the default TLS config section) should be in the TLS autogen topic **moved**
- Add a summary couple of sentences or something maybe? **added a section to conclude and link to config**

**Comment by lauracowen** [comment]
Great, thanks.
I think this is ready to publish when the rest of the security topics set are reviewed as a whole. Move it to Ready To Publish but don't include it in PRs to publish yet.

**Comment by dmuelle** [comment]
Requesting full peer review from @Charlotte-Holt

**Comment by Charlotte-Holt** [comment]
# Peer review feedback
## TLS handshakes
- Most of what I'm finding online has "cipher suites" rather than "CypherSuites", although this topic may be referring to something more specific. 
- To me, this sentence reads better without "being": "Since this shared key is privately generated by each party, rather than being exchanged between them, there is less chance for the key to be exposed to eavesdroppers."

## See also
- Change "Also" to lowercase in the section title

**Comment by acdemyers** [comment]
Developer reviewed by Alaine DeMyers

**Comment by lauracowen** [comment]
Thanks
- I wonder if, in the first para (maybe and second para), it should say something about if you’re building/deploying your services with Open Liberty, can enable TLS to encrypt…etc? The fact we have a topic on it says that implicitly but it doesn’t actually state up-front how this applies to OL.
- I think the topic is better in terms of scope but still feels a little dry or abstract. Maybe give a concrete example of the concepts described? eg maybe when saying client and server applications early on. Then refer back to it when talking about confidentiality - what would be kept confidential (eg data transmitted between services, SSO tokens transferred between services when authenticating that users are authorized to access the info?).
- Do you think the TLS protocol section (the first three paragraphs) could be more condensed? Maybe into one paragraph? Feel free to get Alasdair’s opinion though. In fact, might be worth getting his thoughts on this particular topic anyway - he had a better idea of what might be needed to be understood.
- TLS handshakes - Would it make sense to split this paragraph into two, so that the first deals with handshakes process, and the second deals with handshakes failing? I’m not aware of any more information to include here. I’ve also added the handshake failure potential causes to this new issue: https://github.com/OpenLiberty/docs/issues/1686 where I think we should try to compile anything we come across that might cause problems.

- I’m not convinced about the style of always using “For more information,…” to introduce links as it takes up a lot of space. eg in the TLS and OL section, I think it would be reasonable to just make “Transport Security feature” into a link to that feature’s gendoc page. Could say the same for the securityUtility command. I know having “For more information” gives a clear flag of what’s coming, I think people are used to the internet enough that as long as inline links are clear (and not confusing/ambiguous about where they’re targeting), we could go with the more condensed approach, like you’ve done with the TLS Basics link in the final sentence.. Then save “For more information…” for situations where you really are providing more information about the topic you’ve just been talking about if the reader is interested (as opposed to information they have to read if they want to act on that topic). I know that’s not necessarily a perfect distinction but see what you think.
- Your link points to a page called “IPv6 Basics” not “TLS Basics”. Think this is the URL you meant? https://www.internetsociety.org/deploy360/tls/ Hmm, that’s not so different from what I see when I hover over your link…but I don’t get the same page. Oo, weird, on my third click, now I do…. Okay, maybe it’s not a problem??
- Maybe link “Transport Security feature” and “Secure Sockets Layer feature” mentions in the TLS/SSL section to their gendoc feature pages?

**Comment by dmuelle** [comment]
@lauracowen @NottyCode 
edits addressed in revision:

- I wonder if, in the first para (maybe and second para), it should say something about if you’re building/deploying your services with Open Liberty, can enable TLS to encrypt…etc? **added  to 2nd para**
- I think the topic is better in terms of scope but still feels a little dry or abstract. Maybe give a concrete example of the concepts described? **added some examples and made the protocol section more concise**
- Do you think the TLS protocol section (the first three paragraphs) could be more condensed? Maybe into one paragraph? **done**
- TLS handshakes - Would it make sense to split this paragraph into two, so that the first deals with handshakes process, and the second deals with handshakes failing? **done**

- I’m not convinced about the style of always using “For more information,…” to introduce links as it takes up a lot of space. **fixed**
 -Your link points to a page called “IPv6 Basics” not “TLS Basics”. Think this is the URL you meant? https://www.internetsociety.org/deploy360/tls/ Hmm, that’s not so different from what I see when I hover over your link…but I don’t get the same page. Oo, weird, on my third click, now I do…. Okay, maybe it’s not a problem?? **link seems to work as expected now**
- Maybe link “Transport Security feature” and “Secure Sockets Layer feature” mentions in the TLS/SSL section to their gendoc feature pages? **done**

**Comment by dmuelle** [comment]
HI @lauracowen @NottyCode 

After our convo on the call yesterday about this topic I wanted to revisit. I have made all the updates from the last review but I'm wondering if more is still needed here- or if the discussion for this topic yesterday was more about _where_ this topic goes in the nav as opposed to what's in it.

Right now it's a brief overview of TLS and why you should care about it, that also points out to the transport security feature and securityUtility command for config examples- but that's server.xml  config info, rather than the application-side, web.xml config that came up on yesterday's call.

Does the web.xml stuff belong in this topic? Or should this topic point to some kind of web.xml schema (which we don't have yet but have discussed)?

If possible, can you let me know by Friday 6/19? This topic is targeted for final editorial review this iteration. Thanks!

**Comment by NottyCode** [comment]
@dmuelle I think this is much better. I have some comments, but I don't think we need to pull web.xml into this topic.

**Intro**

I don't think this adds anything. It is kind of an example of the prior bit, but I don't think TLS is necessarily more important for SSO than it is for any authentication so it seems like a strange thing to focus on to me:

>It is also an important protocol for single sign-on (SSO) authentication. By securing the transmission of JSON Web Tokens with TLS, you can help ensure that user credentials are not exposed or tampered with as they are passed among different applications and services.

maybe something like this would work:

>It is also an important protocol for authenticated access to websites. By securing the transmission of authentication tokens like JSON Web Tokens with TLS, you can help ensure that user credentials are not exposed or tampered with as they are passed among different applications and services.


I think this paragraph is a little strange:

>Although SSL is still used, it entails many known security vulnerabilities that can be avoided by using TLS instead. Most websites now use TLS, which can be easily identified by the presence of the padlock icon in the address bar of an internet browser. In order for a website to comply with the secure HTTPS protocol, its communications must be encrypted according to the TLS protocol. Most web browsers flag sites that do not comply with the HTTPS protocol as not secure.

I would suggest removing mention of SSL which is mentioned in the bottom and seems a little out of place here. Also I would not describe a website as complying with https, I would say use. If a website uses https then it must be using TLS. In the last sentence I'd also say that Most web browsers flag sites that do not use HTTPS as not secure, rather than complying. Maybe something like this:

>Most websites now use HTTPS which requires the use of TLS to authenticate and encrypt traffic with the website. The use of HTTPS can be easily identified by the presence of the padlock icon in the address bar of an internet browser. Most web browsers flag sites that do not use HTTPS as not secure.

**TLS and SSL**

I think this can be simplified to something like:

> Prior to wide adoption of the TLS protocol people used the SSL protocol. SSL has since been proven to be insecure and as a result in no longer in widespread use. However for historic reasons the term SSL is often used to refer to encrypted network connections even when TLS is in use. In Open Liberty this is revealed in the use of ssl in feature and configuration names even though SSL will not be used. Effectively SSL is now a synonym for TLS.

**Comment by dmuelle** [comment]
Thanks, @NottyCode , I've updated the doc per your suggestions above with a few minor edits, let me know if anything further is needed.

https://draft-openlibertyio.mybluemix.net/docs/ref/general/#secure-communication-tls.html

**Comment by lauracowen** [comment]
Looks good.

One question though, was there a reason not to go with "SSL has since been proven to be insecure and as a result in no longer in widespread use."? I ask because "deprecated" isn't really that useful to know (and it's not clear whether that was down to us or to the spec), whereas spelling out that SSL is insecure gives a reason why it's important not to use it.

**Comment by dmuelle** [comment]
Good point- honestly, I was just trying to avoid past perfect tense because Acrolinx flags it. I went with "Over time, many security vulnerabilities were identified for SSL and it is no longer in widespread use." Let me know if that needs more work. Doc is updated

**Comment by lauracowen** [comment]
Sounds good. Thanks

**Comment by dmuelle** [comment]
new draft URL: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/secure-communication-tls.html

**Comment by dmuelle** [comment]
updates made in new editing pass:

- `You can configure TLS to specify how the details of the handshake and other aspects of the protocol are implemented for your application.` --> `You can configure the feature to specify how the details of the TLS handshake and other aspects of the TLS protocol are implemented for your application.`  DQTI ch6 Avoid Ambiguity

- `You can also create and configure a TLS certificate for your Open Liberty server by specifying the `createSSLCertificate` action for the securityUtility command.` --> `You can also create and configure a TLS certificate for your Open Liberty server by using the securityUtility createSSLCertificate command` DQTI ch6 Use technical terms consistently and appropriately

**Comment by lauracowen** [comment]
@dmuelle Just found this SSL article on WASdev - is it any use (here or elsewhere)? https://github.ibm.com/was-WASdev/WASdevnet-website/tree/master/developer.ibm.com/wasdev/docs/configuring-ssl-liberty

**Comment by chirp1** [comment]
@dmuelle Hi David, here are my comments:
- Use "on" instead of "upon". "upon" is more formal.
- For "securityUtility createSSLCertificate command ", you were basically right with your original wording. Look up the command in KC instead of OL because we're still editing the OL topics, and you'll notice that securityUtility is the command and createSSLCertificate is, as you originally said, the action (although in the securityUtility command topic, it's incorrectly called a task). So, instead say "by specifying the createSSLCertificate action on the securityUtility command.". (I changed "for" to "on"), or maybe "running the securityUtility command with the createSSLCertificate action.", or other wording that you might come up with.
-  Look up "historic" versus "historical". Although "historic reasons" might be considered correct by some, generally, we would want to use "historical reasons" instead. 
- Instead of linking to the internet society, link to the TLS specification.and specify the RFC in the link text.
- Change "client and server agree " to "the client and server agree ".

**Comment by dmuelle** [comment]
Hi @chirp1  thanks for reviewing. I made the following changes per your review:

- [x] Use "on" instead of "upon".

- [x] "securityUtility createSSLCertificate command " I changed this but then put it back to the way it was after this morning's conversation re command topics, for consistency with the server command and securityUtility command topics.

- [x] Look up "historic" versus "historical"- noted, changed the ref to to "historical"

- [x] Instead of linking to the internet society, link to the TLS specification.and specify the RFC in the link text

- [x] Change "client and server agree " to "the client and server agree ".

https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/secure-communication-tls.html

**Comment by chirp1** [comment]
@dmuelle Hi David,
Almost there! Your link for the TLS specification seems to be to version 1.2, but the transport security feature seems to indicate that we support through TLS 1.3: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/reference/feature/transportSecurity-1.0.html How about if you change to the TLS specification link to 1.3, which I believe came out in 2018?   

The rest of your updates look good.

**Comment by dmuelle** [comment]
@chirp1 - thanks for catching that. I've updated the link to https://tools.ietf.org/html/rfc8446

**Comment by chirp1** [comment]
@dmuelle The updates look good. Moving to "Ready to Publish".

**Comment by dmuelle** [comment]
moved to `vNext` to publish with 20.0.0.11. Closing this issue.
