### ISSUE TITLE
A new Document for Logstash and Liberty- optimizing data collection for the cloud

### ISSUE THREAD

**Issue by tomjenningss** [OpenLiberty/docs#1133]
As WASdev.net is being closed down, it has been decided that "Logstash and Liberty - optimizing data collection for the cloud" should be moved over to Open Liberty docs. The URL has ben redirected to Openliberty.io landing page.

**Comment by Rwalls1** [comment]
@tomjenningss Do you have a link to or copy of the "Logstash and Liberty - optimizing data collection for the cloud" doc that you can provide?

**Comment by tomjenningss** [comment]
Hi @Rwalls1 the link from the wasdev website gets redirected to openliberty.io now. 
I have got a copy of the content from wasdev and attached it. 
Feel free to ask if there is anything else I can help with.
[logstash.txt](https://github.com/OpenLiberty/docs/files/4481555/logstash.txt)

**Comment by Rwalls1** [comment]
@lauracowen Will this topic need to be refocused towards a specific developer use case or is it intended to be a direct adaptation of the original blog?

**Comment by lauracowen** [comment]
@Rwalls1 Good question. This issue came about because we (Tom and I) were reviewing the old WASdev.net website and taking old articles offline but trying to identify ones that contain useful info that could be incorporated into OL docs and/or blog posts.

I believe you're also working on a topic in #1200 about logging. So I think you should talk to Don about it - eg whether he feels this is WASdev article worthy of updating and making a whole new doc topic from, or whether the info overlaps with other topics we already have in OL docs and should be incorporated in the relevant places.

**Comment by Rwalls1** [comment]
@donbourne For the content referenced above,  how do you assess the information in regards to its potential usefulness? Should the content be adapted for a new topic?

**Comment by donbourne** [comment]
@Rwalls1 the content in that article is obsolete.  The article described how to parse unformatted logs.  It predates the availability of our JSON log format which people would more naturally use now to feed logs to Logstash (or other consumers).

**Comment by lauracowen** [comment]
Ok, that makes it easy then. @Rwalls1 I think we should just close this issue then.
