### ISSUE TITLE
Introduction to dev mode

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#1198]
Write a new concept topic about dev mode. What is it? Why is it useful? What problems does it address? When might you use it? This doc will be pulled into the RHR build. 

**Scenario 1**:  Developers writing cloud-native apps that will be containerized and deployed to the cloud.
**SME**: Eric Lau 
**Resources**:
- https://openliberty.io/blog/2019/10/22/liberty-dev-mode.html
- https://openliberty.io/blog/2019/11/28/dev-mode-liberty-maven-plugin.html
- https://openliberty.io/blog/2019/11/13/liberty-dev-mode-vscode.html
- https://openliberty.io/blog/2019/10/17/dev-mode-developer-experience.html
- https://blog.sebastian-daschner.com/entries/openliberty-plugin-dev-mode
- The **Updating the server configuration without restarting the server** section of https://openliberty.io/guides/getting-started.html
- https://github.com/OpenLiberty/ci.maven/blob/master/docs/dev.md#dev

**Comment by dmuelle** [comment]
Draft available for review: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#intro-dev-mode.html

**Comment by lauracowen** [comment]
- The sentence "Dev mode provides an enhanced developer experience..." is a bit ra-rah. I don't think it should assert here that the devx is "enhanced" - just tell them what it does and why and let the reader conclude that it's awesome. Not sure that sentence adds much as it stands but I get that it's useful to mention "deploying changes..." etc so maybe just reword that sentence to say something like "Dev mode detects, recompiles, and redeploys code changes as you code...."something...something...debugging...running tests. Try to make it a bit more than you said in the intro section, otherwise it's just repeating what's already there.
- where does the "install the Open Liberty Maven plug-in" link target? Do you actually install the plugin? Or do you modify the Maven pom.xml for your app to pull it down when you next run a Maven build?
- Detect, compile,... section:
  - heading "...pick up code changes" sounds a bit the same as "Detect". Maybe "Detect, recompile, and redeploy code changes"?
  - The second sentence should be appended to the first para rather than starting a new para?
- Run unit and integration... section:
  - Can you define what "hot tests" are?
- Run... section:
  - The second sentence should probably follow on from the first as a single para?

Otherwise, looks good and I think is ready to go. Thx

**Comment by dmuelle** [comment]
- Title - can you make it something like "development mode" and make the url match **DONE**.
- The sentence "Dev mode provides an enhanced developer experience..." **REVISED**
- where does the "install the Open Liberty Maven plug-in" link target? Do you actually install the plugin? Or do you modify the Maven pom.xml for your app to pull it down when you next run a Maven build?**Link targets the "Run" section of this page- revised to include gradle per E Lau**
- Detect, compile,... section:
  - heading "...pick up code changes" sounds a bit the same as "Detect". Maybe "Detect, recompile, and redeploy code changes"? **Revised**
  - The second sentence should be appended to the first para rather than starting a new para?
- Run unit and integration... section:**Revised**
  - Can you define what "hot tests" are?**Revised**
- Run... section:
  - The second sentence should probably follow on from the first as a single para? **revised**

**Comment by lauracowen** [comment]
Excellent. Thank you.
We can publish this one. Also, can you make sure it gets included in RHR builds (both the published one - we may as well - and the prototype one)?

**Comment by chirp1** [comment]
@dmuelle Hi David, Here is the start of my review comments. I'll add to the list and let you know when I'm done.
- Rerun Acrolinx and fix the various outstanding issues. Note that "It is" is not flagged, but fix it in the same way that you would fix "there is".

**Comment by chirp1** [comment]
Hi David, 
I'm adding my review comments to this issue. I'll let you know when I am done adding comments.
- Althought the intro paragraph is well, written, I would like to see maven and gradle mentioned in this paragraph to improve SEO. You might move this entire sentence to the intro paragraph: "Dev mode is available as a goal of the Open Liberty Maven plug-in or as a task of the Liberty Gradle plug-in." You will likely need to rework "What is dev mode?" or even remove it and put any additional elsewhere.

**Comment by dmuelle** [comment]
edits addressed in #1306:

- Let's rename the file, following some of the conventions that we have discussed, although I believe we are still discussing them. **what should I rename it to?do we have a convention to follow** 
- Althought the intro paragraph is well, written, I would like to see maven and gradle mentioned in this paragraph to improve SEO. You might move this entire sentence to the intro paragraph: "Dev mode is available as a goal of the Open Liberty Maven plug-in or as a task of the Liberty Gradle plug-in." You will likely need to rework "What is dev mode?" or even remove it and put any additional info in this section elsewhere. **revised**
- Change "testing and debugging so you can focus" to "testing and debugging so that you can focus". **removed as part of revision**
- "Dev mode supports a streamlined workflow for iterative application development." doesn't seem necessary. Remove it. **removed as part of revision**
- Remove the "What is dev mode?" title and append the remaining wording of this third paragraph to the second paragraph. **removed as part of revision**
- To make the change and addition bullets parallel, change "Addition of new dependencies" to "New dependency additions" and change "Addition of new features" to "New feature additions". **revised**
- For the 5 bullets, do some pieces apply just to gradle, such as the build.gradle file, and some apply just to Maven? If so, spell out here and where appropriate in any other part of the topic, what pieces apply to only gradle or maven. **the only differences here are in how dependencies are handled, I added For Maven users/ for Gradle users to that bullet**
- Change "effect until dev mode is restarted." to "effect until you restart dev mode.". <= switching wording to active voice. **revised**
- Does "pressing CTRL+C, or by typing q and pressing Enter. " apply to all operating systems? If not, specify what the user needs to do for each operating system. **this is the only way it's documented by I messaged the SME to confirm**
- I'm not sure what you mean by "this capability". How about changing "This capability runs the unit tests and integration tests that are configured for your project." to "Unit tests and integration tests that run are configured for your project.". **revised**
- For "The default debug port is 7777. If the default port" you say "default debug port" and "default port". How about if we change the wording to make the terminology consistent? Change the wording to "The default port for debugging is 7777, If the default port...". **revised**

**Comment by chirp1** [comment]
Hi David, 
I'm reviewing your changes. The topic looks great! I have a few comments:
- The following wording seems to be more or less redundant between the two sentences. Would you rework, likely into just a single sentence: "You can use development mode through either the Open Liberty Maven plug-in or the Open Liberty Gradle plug-in. To use development mode, enable the Open Liberty Maven plug-in or the Open Liberty Gradle plug-in and run one of the following commands:"?
- For Where to next, I believe that the first link applies to maven and gradle, while the second applies just to maven. Would you reword so that the user knows the differences?
- I think that you don't need "See also" since you introduced both links to the topics at the beginning of the Development mode topic and then had links to specific parts of these two topics in other parts of the Development mode topic.

-

**Comment by dmuelle** [comment]
doc is now published: https://www.openliberty.io/docs/ref/general/#development-mode-applications.html

**Comment by chirp1** [comment]
Hi David, switching wording from "development mode" to "dev mode" in the body of the topic, as requested by Alasdair, looks fine to me. 
Also, would you have the SME add a statement that they approve to this issue?

**Comment by ericglau** [comment]
SME approved.

**Comment by dmuelle** [comment]
Leaving this issue open until updates for "dev mode" and guide link publish with 20.0.0.5

**Comment by dmuelle** [comment]
@chirp1 approved this topic, adding the editorial review label

**Comment by dmuelle** [comment]
Remaining updates are live w/ 20005, closing this issue
