### ISSUE TITLE
Topic about managing logging 

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#1200]
This is a new concept topic about managing/collecting logs. First, talk about the approach for the cloud-native/Kubernetes approach using JSON logging.

Then include a section about the logstash collector - What is it? Why use it? How to use it? Link to the reference topic about it. From Don Bourne about logstash collector (**SME**) - This relates to the audit stuff. Needs some guidance on when you’d use the logstash collector - as don’t want to encourage use of it if they’re in environments that manage logging for you, e.g., Kubernetes (when you’d use JSON logging (including on OpenShift)). Still use the logstash collector in environments like Cloud Foundry - so we have some customers who are somewhat passionate about the logstash approach, but they’re probably a minority. 

**Resources**:
- JSON logging - https://openliberty.io/blog/2019/12/03/custom-fields-json-logs.html
- JSON logging - https://openliberty.io/blog/2019/10/11/configure-logs-JSON-format-190010.html#jlog
- Logstash collector - https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/cwlp_analytics_collectors.html

**Comment by Rwalls1** [comment]
Link to current draft: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#managing-logging.html

**Comment by Rwalls1** [comment]
@donbourne Please review:  https://draft-openlibertyio.mybluemix.net/docs/ref/general/#managing-logging.html

**Comment by NottyCode** [comment]
My first take on this is why is this separate from the Logging and tracing document we have. 

I'm not too sure what the purpose of this article is. If it is to discuss how to configure logging and tracing then I think the Logging and tracing document does this much better. If it is to talk about the value of good logging then I don't think this really does a good enough job of explaining why this is useful, I think some use cases would be helpful.

I think the most useful part of this is probably logstashCollector, but I think that could be covered in the logstashCollector feature documentation and in Logging and tracing.

**Comment by Charlotte-Holt** [comment]
@Rwalls1 Like we talked about, try to refocus this topic on feeding logs into different log aggregation tools/systems, including JSON logging, logstashCollector, ELK stack (or Elastic stack), ESK stack, and Splunk. When would you use each? How is each helpful?

**Comment by Rwalls1** [comment]
@donbourne Please review the latest update: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#managing-logging.html

**Comment by donbourne** [comment]
I think if we are going to have a topic on log management we would want it to have some intro describing or depicting our two main supported scenarios:

1. Liberty emitting JSON formatted logs, which can be ingested into popular log aggregation and analysis tools, such as Elastic Stack, Splunk or others.

1. Liberty running logstashCollector, sending logs directly to Logstash for ingestion into the ELK stack.

I'm not sure if that's enough for a topic on its own.  For the description of how to use Liberty with logstashCollector, we should have info covering the whole setup (as we did in the WL KC), not just the server.xml snippet.

The other info in this topic about configuring JSON logging is already covered in the logging and tracing topic.

**Comment by Rwalls1** [comment]
@lauracowen Do you have any guidance on how we would differentiate this topic in a meaningful way from the logging and tracing topic or the logstashcollector feature doc?  After further reviews, I think the purpose may need to be more tightly defined.

**Comment by Rwalls1** [comment]
@donbourne Please review, what are your thoughts on the primary benefits and use cases of tools such as Splunk and Elastic Stack: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#managing-logging.html

**Comment by donbourne** [comment]
Hi @Rwalls1 , here are my comments...

- need to change the layout of this doc so that JSON logging is shown to be the most common choice and logstashCollector is presented as an option for cases where JSON logging doesn't fit.  JSON logging is the more native way to do things as it provides ability for any log analysis solution to tap into the logs.
- "Logs contain the data that is generated by applications" -- avoid calling logs "data" -- it's too general.  Normally I'd refer to logs as log events, log messages or log records.  Saying logs contain the data generated by applications makes me think they contain things like customer shopping cart contents :-).  In general, the word "data" probably doesn't belong in this topic.

- first paragraphs should communicate
    - Liberty servers produce a variety of logs - message, trace, access logs, ffdc, audit
    - You may want to use them for troubleshooting, traffic analysis, security analysis, or other reasons
    - It's common to aggregate logs from all servers so that they can be more easily searched or analyzed
    - to that end it's common to use log analysis tools to analyze the logs
    - rather than set up your log aggregation tools to read from each of Liberty's different log files (each with different log formats and with log file rollover behaviors), you can take advantage of either JSON logging or logstashCollector.
        
- JSON logging
    - easy for log analysis tools to parse
    - can be sent to Liberty's stdout (console) or to a rolling log (messages.log)
    - sending JSON logs to console is typical for Docker / Kubernetes deployments
    
- logstashCollector
    - for circumstances where JSON logging doesn't fit
        - for some reason you can't set up a log ingestion tool alongside your servers
        - the platform you're running your servers in doesn't automatically ingest logs sent to stdout or you don't like where the platform automatically puts your logs
    - provides a means to directly send to a specified Logstash server

- Splunk / Elastic
    - Splunk and Elastic Stack are 2 of many possible log analysis solutions.  They are useful for being able to easily see patterns in your logs (eg. is error X appearing across all of my servers, and when did that problem start?).  Often log analysis tools also provide ML features such as detecting log entries that are atypical/unexpected and which may merit a closer look. 
    - I'd actually suggest we don't call out Splunk or Elastic stack specifically.  We should describe what log analysis tools are for, but shouldn't endorse or promote specific 3rd party products.

**Comment by Rwalls1** [comment]
@donbourne In response to: **"Logs contain the data that is generated by applications" -- avoid calling logs "data" -- it's too general. Normally I'd refer to logs as log events, log messages or log records. Saying logs contain the data generated by applications makes me think they contain things like customer shopping cart contents :-). In general, the word "data" probably doesn't belong in this topic.**
I used the word data because  I think it helps to make terms such as "logs" ,"log events", "log records" less abstract and provides more context for a user to understand what those terms mean, which is important for any concept topic. I may be misinterpreting your comment but I think just referring to logs as log events or log records may not be clear enough without further context. My understanding is that when you're discussing managing logs, log events, or log records, you're ultimately discussing managing data, which I think highlights the value of logs. How would you define logs and their significance?

**Comment by Rwalls1** [comment]
@donbourne In response to: "Logs contain the data that is generated by applications" -- avoid calling logs "data" -- it's too general. Normally I'd refer to logs as log events, log messages or log records. Saying logs contain the data generated by applications makes me think they contain things like customer shopping cart contents :-). In general, the word "data" probably doesn't belong in this topic.
I used the word data because I think it helps to make terms such as "logs" ,"log events", "log records" less abstract and provides more context for a user to understand what those terms mean, which is important for any concept topic. I may be misinterpreting your comment but I think just referring to logs as log events or log records may not be clear enough without further context. My understanding is that when you're discussing managing logs, log events, or log records, you're ultimately discussing managing data, which I think highlights the value of logs. How would you define logs and their significance?

**Comment by lauracowen** [comment]
Reading through both the previous two comments, I think I understand why Don wants to avoid using "data". The first sentence of the topic "Logs contain the data that is generated by applications." (and similarly "application data") reads like the logs contain data such as output from a request by the application, but they don't. The logs are a separate set of 'data' that occurs.. I think you're safer in this topic to use the term "log events", which I think describe each entry in the log file (I'm not sure if "log events", "log messages", "log records" are synonymous or subtley different parts of a log - check with @donbourne. If they are synonymous, stick with "log events").
- So, maybe change the first sentence (which I agree would need the word "data" as it currently stands) to be more explicit like "Logs contain a record of events that occur while the application is running. With effective log management, you can analyze the log events to better understand the behavior of applications." (check that makes sense with Don obvs). Then subsquently you should be fine to say "log events" wherever you currently have "data".
- "utilizing" -> "using"

I like [Don's proposed](https://app.zenhub.com/workspaces/open-liberty-docs-backlog-5c7031f61d4580192beb4070/issues/openliberty/docs/1200#issuecomment-649515949) structure/ordering of the sections, and the points he makes about stating when to use each approach, etc. Can you adjust the article to address the points in his comment above? Thx.

**Comment by donbourne** [comment]
log events is a good term -- I would stick with that throughout to keep consistency.

**Comment by Rwalls1** [comment]
@donbourne Thanks,  I think I've addressed most of your feedback. In regards to the reference to "stdout" and "rolling log", I wasn't sure how to characterize those terms within the context of sending logs to them as the log and trace configuration topic, https://draft-openlibertyio.mybluemix.net/docs/ref/general/#log-trace-configuration.html, seems to indicate that they are files. Can you expand a bit more on that process so that it is correctly specified in the doc?: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#log-management.html

**Comment by donbourne** [comment]
Hi @Rwalls1 , I think there's a fair bit of nuance to this that I'm not sure I can convey well enough to make it easy to write up without a lot of back and forth.  To try to get us to end of job quickly on this one I'll propose the following content...

___

Logs are a record of events that occur during the operation of your servers.  They collect important information useful for diagnosing problems and help you understand the behavior of your applications.

Open Liberty servers and applications produce a variety of logs that can be used for different forms of analysis. These include logs such as the message log, trace log, first failure data captures (FFDC), audit logs and access logs.

Message logs record errors, warnings and general info as the server runs.  These are the logs you will likely look at most often to understand the general health of the server.

Trace logs provide details about the inner workings of components or applications running on the server.  Trace can be enabled for specific components when problems arise, often in consultation with the developers of your applications or support teams.

First failure data capture logs record information for specific exception conditions, including the details of the exception stack and dumps of objects from the server that relate to the cause of the exception.  They are typically only of interest to support teams.

Audit logs record events from the server that are important to assessing security issues and are useful for security analysis.

Access logs record every HTTP request made to the server.  They are useful for traffic analysis.

It is common to aggregate logs from all servers so that they can be more easily searched or analyzed.  Aggregating logs makes it possible to determine which events occur in proximity to one another, which servers are encountering the same problems, and to determine when problems first happened.  It is common to use log analysis tools to analyze the logs.


**JSON Logs**

While log aggregation and analysis tools can typically be configured to understand different log file formats a simpler approach is to emit all logs from Open Liberty in a JSON format.

As JSON is a self describing format, log analysis tools are typically able to consume it without the need for format-specific parsing instructions.

Open Liberty provides the ability to format its message log and console output in JSON format.  

By writing your logs to the console in JSON format, and relying on the server management system to automatically consume and parse console logs, you can easily run your servers in different environments without modifying the server logging configuration.


**Logstash Collector**

Open Liberty provides a Logstash collector feature which can send logs directly to a Logstash server.  Logstash is a log aggregation tool from elastic.co.  The Logstash collector feature can watch for message, trace, FFDC, audit and access log events in your Open Liberty server at runtime and forward those events securely to the host and port where your Logstash server is running.

Logstash collector is convenient to use when your target log aggregator is Logstash, and where the environment your server is running in doesn't automatically aggregate and forward log events.

For more information see Forwarding logs and events to Logstash with Logstash collector.

**Comment by Rwalls1** [comment]
@donbourne Thanks, I've incorporated your suggested updates: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#log-management.html

**Comment by donbourne** [comment]
comments...

for the paragraph starting with...
    "Message logs record errors..."
... is it possible to show each log type in a list?  It seems a bit harder to see the big picture with it all in one paragraph.

"Analyzing JSON logs" - the text in this section is more about explaining what JSON logs are (we don't explain how to analyze them).  I was thinking of just having the sections be "JSON logs" and "Logstash collector".  If it's better to have this start with a verb, perhaps it could be "Simplying log parsing with JSON" and "Forwarding log events with the Logstash collector"

I believe it's better to say "...in JSON format" than "in the JSON format" since JSON can represent a variety of formats (schemas):
    "emit all logs from Open Liberty servers in the JSON format"
    "console output in the JSON format."
    "console in the JSON format"

"The feature can view message..." - Logstash collector is an event forwarder -- "view" is probably not the right word for what it does.  Perhaps say "The feature collects message... and forwards those events..."

**Comment by Rwalls1** [comment]
@donbourne Thanks,  For "Message logs record errors", if a list format is more suitable, it may be better to just link to  the JSON log events reference list topic to avoid redundancy: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#json-log-events-list.html

**Comment by donbourne** [comment]
@Rwalls1 , that sounds reasonable.  So perhaps after...

Open Liberty servers and applications produce a variety of logs that can be used for different forms of analysis. These include logs such as the message log, trace log, first failure data captures (FFDC), audit logs and access logs.

you could add something linking off to the json log events page for more information?

**Comment by lauracowen** [comment]
Thanks, both. I think that looks good. It gives a nice clear overview of what the options are (JSON/Logstash collector), and makes it clear when to use each.

@Rwalls1 Can you check the syntax of the links that point to the other topics? They're opening the pages in new tabs when they should just open in the same tab.

**Comment by Rwalls1** [comment]
@donbourne I've added the link and removed the referenced paragraph: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#log-management.html

**Comment by donbourne** [comment]
Looks good.  Thanks to everyone on this chain for helping.

**Comment by lauracowen** [comment]
Yep. I'll sign this off too. I think David said you'd been looking at the link syntax and I know he's been looking at what it should be consistently across the topics now.

**Comment by Rwalls1** [comment]
@donbourne @lauracowen Thanks, I think I've addressed the linking issue and will follow up with David to discuss any further guidance.

**Comment by Rwalls1** [comment]
@dmuelle Please peer review: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#log-management.html

**Comment by dmuelle** [comment]
# Peer review

## Intro

`Logs are a record of events that occur during the operation of your servers. As records of events, logs...`

a minor thing, but in the first sentence you say logs are "a record"  (singular), then in the next sentence you refer to them as "records" (plural). I think either singular or plural can work, but it should be the same in both sentences.

`These logs include the message log, trace log, first failure data captures (FFDC), audit logs, and access logs.`

I think it would be helpful to briefly describe the function of each of these log types in this doc (a sentence or two). I don't think we have this information concisely stated anywhere else in our OL docs. I believe you had this in an earlier draft and replaced it with a link to the JSON ref list- which is a good link to have- but that doc just lists the fields available for each log type, it doesn't explain what the logs are for. I think this doc is a good place to explain them.  Agree w/ @donbourne comment above that the info would be easier to read in list format. Also- could link first mention of Audit logs to `xref:audit-logs.adoc[Audit logs]` .

Link to "JSON log events reference list" is broken. New format is  `xref:json-log-events-list.adoc[JSON log events reference list]`

`As records of events, logs collect important information that is useful for diagnosing problems and helping you understand the behavior of applications.`

suggested edit for concision:
`Logs collect information that helps you diagnose problems and understand the behavior of applications.`

-----

`Aggregating logs enables simpler log analysis that helps to determine which events occur in proximity to each other, which servers encounter the same problems, and to determine when problems first occur.`

Suggested edit
`When logs are aggregated, you can use log analysis tools to determine which events occur in proximity to each other, which servers encounter the same problems, and when problems first occur.`

## Simplifying log parsing with JSON logs

since this doesn't describe a particular task, recommend changing the heading to "Simplify log parsing with JSON logs"

`While log aggregation and analysis tools can typically be configured to understand different log file formats, a simpler method is to emit all logs from Open Liberty servers in JSON format.`

Suggested edit to avoid passive construction:

`Although you can configure log aggregation and analysis tools to understand different log file formats, a simpler method is to emit all logs from Open Liberty servers in JSON format.`

recommend adding a link to this section for the JSON logging section of the Log and Trace configuration page, which I am in the process of updating. `For more information, see xref:log-trace-configuration.adoc#_json_logging[JSON logging].`

## Forwarding log events with the Logstash collector
since this doesn't describe a particular task, recommend changing the heading to "Forward log events with the Logstash collector"

link the feature on first mention- `xref:reference:feature/logstashCollector-1.0.adoc[Logstash collector feature]`

-----

`The Logstash collector is best used when your target log aggregator is Logstash, and when the environment your server runs in doesn’t automatically aggregate and forward log events.`

Check with @donbourne on this, but I believe this is not just the best use case, but the only use case for this feature. You wouldn't need to use it at all if you were running your server in a Kubernetes cluster or other managed environment. Here's what Don helped me come up with for the Forwarding events with Logstash Collector task:

"If your Open Liberty server is deployed in a managed environment, such as a Kubernetes cluster, your logs are typically aggregated by agents in that environment. However, some server configurations cannot use an external agent to manage log data. In these cases, you can use the Open Liberty Logstash collector feature to internally collect your log data at run time and send it directly to a Logstash server.

If your log data is managed by an external agent, you do not need to use the Logstash collector feature. For more information, see Analyzing logs with the Elastic stack."


Another thing to consider is that using the Logstash collector feature is probably the less-likely scenario, ie most applications will run in an environment where they don't need this feature to send their data to the ELK stack. It's good to mention it here but you might want tot explain that and also link to the "Analyzing Logs with the Elastic Stack" topic.

Link to "Forwarding logs and events to Logstash with Logstash collector" is broken, new format should be:
`xref:forwarding-logs-logstash.adoc[Forwarding logs and events to Logstash with Logstash collector]`

Might be helpful to include a `See also` section that links to Log and trace configuration, possibly to other logging topics as well (JSON and Logstash ref lists, Analyzing and Forwarding tasks). @lauracowen may have thoughts about whether or not to include links in `See also` that are already linked in the body of the topic.

**Comment by Rwalls1** [comment]
@dmuelle Thanks, I've incorporated your feedback, I will follow up with Laura regarding the See also section

**Comment by Rwalls1** [comment]
New link to topic: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.8/log-management.html

**Comment by Rwalls1** [comment]
New link to topic: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/log-management.html

**Comment by Rwalls1** [comment]
PR: https://github.com/OpenLiberty/docs/pull/1923/files

**Comment by Rwalls1** [comment]
New link: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/log-management.html

**Comment by dmuelle** [comment]
Doc is now on vNext branch, will publish with 20.0.0.12 on 11.20

**Comment by chirp1** [comment]
@Rwalls1 Hi Richard, nice job! My comments are just editorial ones:

- For "that collect important information about the servers" doesn't seem to convey info beyond what is already said in the opening paragraph. Also, the "that" at the beginning seems awkwardly placed. So, remove the phrase. 
- Change "...use logs to help diagnose problems..." to "...use logs to diagnose problems ...".
- Change "... include the message log, trace log,..." to "... include the message logs, trace logs,...".
- Put headers on the table.
- Change "Record events from the server that are important to assessing security issues and are useful for security analysis." to "Record events from the server that are useful for analysis of security issues." to reduce wordiness.
-  Put a period after "...see JSON log events reference list".
- Reword "It is common to aggregate logs..." to get rid of the empty "it".
- For "For more information, see JSON logging.", make the link go to the section on JSON logging.

**Comment by Rwalls1** [comment]
@chirp1 Thanks, I've addressed your feedback: https://draft-openlibertyio.mybluemix.net/docs/latest/log-management.html

**Comment by chirp1** [comment]
@Rwalls1 

Hi Richard, 
I have one comment. I see that you added in "also" in "When logs are aggregated, you can also use log analysis tools to determine which events occur in proximity to each other, which servers encounter the same problems, and when problems first occur.". My thought is leave "also" out because to me it implies "in addition to". I gathered from the preceding sentence in your topic that the log analysis tools are used to analyze the logs.  I think that "determine which events occur in proximity to each other, which servers encounter the same problems, and when problems first occur." is a description of the log analysis, not something in addition to it. Let me know what you think.

**Comment by Rwalls1** [comment]
@chirp1 Thanks, I've made that update: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.7/log-management.html

**Comment by chirp1** [comment]
@Rwalls1 The topic looks great! Moving to Ready to Publish.

**Comment by Rwalls1** [comment]
Staging: https://staging-openlibertyio.mybluemix.net/docs/21.0.0.7/log-management.html

**Comment by Rwalls1** [comment]
The latest updates have been merged to Vnext and will publish with 21.0.0.7.
