### ISSUE TITLE
JAX-RS integration with CDI

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#1274]
This is for a new concept topic about JAX-RS integration with CDI. From the KC topic, only focus on JAX-RS integration with CDI. Integration with EJB will be split out into another topic. 

**Resource**: https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/rwlp_jaxrs2.0_ejbcdi.html

**SME**: 
Andy McCright

**Comment by dmuelle** [comment]
Hi @andymc12 , can you provide technical review of this draft topic: [JAX-RS integration with CDI](https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/jaxrs-integration-cdi.html) ?

It's info that came over from this Liberty KC topic, which we discussed in our call about JAX-RS doc a while back: [JAX-RS 2.0 integration with EJB and CDI](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/rwlp_jaxrs2.0_ejbcdi.html). Per our conversation, we're just bringing over the JAX-RS info and will deal with the EJB stuff separately later.

I think this still needs some work and I have a couple questions-

Global questions:
- should this be it's own page or could it just be a section of the [Context and dependency injection beans](https://www.openliberty.io/docs/20.0.0.11/cdi-beans.html) page?
- This doc seems mostly to tell the user what they _can't_ do with JAX-RS and CDI. Are we missing any info on why they would want to do it or how to configure?

For the code example, it's not clear from the description how this code is relevant to  integrating JAX-RS with CDI. 

- Can you suggest a better description? I know that `@ApplicationScoped ` is a CDI scope, but what does this code tell the reader about using it in  JAX-RS context?

For the "JAX-RS 2.0 scope and CDI scope lifecycle" table:

- The column headings seem unnecessarily vague. Should "Application" be "Bean" instead? Is the application a resource class/ Provider or is it the bean?
- The "Result" column- is the result the bean (or application?) lifecycle that you get when the scopes conflict? Could this column more precisely named as "Bean lifecycle" or similar?

This table seems like an inefficient way to get this info across. It seems like a couple conditional statements could give the user the same information, without being so repetitive. At least the bottom four rows could be replaced by something like:

"If the application is a provider, the JAX-RS scope must be singleton and the resulting bean lifecycle is also singleton, regardless of the CDI scope annotation."

I wonder if there couldn't be a similar statement or two that would sum up the resource class lifecycle scope as well. Or if it would just get too complicated and a table really is best? It just seems really inefficient and repetitive.

For the conflict messages- these just repeat the message info exactly as it appears elsewhere. Is there any other information users need about these messages? If not I'd recommend removing them here to avoid redundancy.

Let me know what you think. Thanks!

**Comment by andymc12** [comment]
> should this be it's own page or could it just be a section of the Context and dependency injection beans page?

I think it should be it's own page - or a section under a general JAX-RS topic if we have one.

> This doc seems mostly to tell the user what they can't do with JAX-RS and CDI. Are we missing any info on why they would want to do it or how to configure?

Good point.  Really, the intent of the page should be to describe the behavior when both features are in play.  The JAX-RS feature is useful for building and/or consuming RESTful services.  CDI provides a variety of uses - like dependency injection, intercepting method invocations, or being a base requirement for other specialized features (like MicroProfile Config, etc.).  The JAX-RS spec defines how JAX-RS should behave when CDI is available - and unfortunately there are some gray areas - so this doc is intended to describe how Liberty functions when both features are enabled.

> For the code example, it's not clear from the description how this code is relevant to integrating JAX-RS with CDI.
> * Can you suggest a better description? I know that @ApplicationScoped is a CDI scope, but what does this code tell the reader about using it in JAX-RS context?

The `@ApplicationScoped` annotation tells CDI that there should only be one instance of this bean for the lifetime of the application.  Normally, JAX-RS resources are per-request (i.e. the JAX-RS engine would create a new instance of the class for each HTTP request) - this is desirable in some cases but it is also less efficient than a per-application resource (where the same instance is used for every HTTP request).

The `@Inject` annotation tells CDI that it should inject an instance of the `SimpleBean` class into the instance of the `ApplicationScopedResource` bean.  CDI has a number of rules for determining what to inject - for example, it could inject one thing in a test environment, and something else in production.  Rather than describing the rules here, I'd recommend adding a link to the CDI spec and/or the CDI docs in OL.io.

> For the "JAX-RS 2.0 scope and CDI scope lifecycle" table:
> * The column headings seem unnecessarily vague. Should "Application" be "Bean" instead? Is the application a resource class/ Provider or is it the bean?

Instead of "Application" for the column header, I'd use something like "JAX-RS Component Type".  The JAX-RS defines different component types - mainly "resources" (the classes annotated with `@Path` that actually return content to client HTTP requests) and "providers" (classes that provide some broad function - like serializing objects to JSON, converting an exception into an appropriate HTTP response, verifying that the client is authorized to invoke the target resource, etc.).

> The "Result" column- is the result the bean (or application?) lifecycle that you get when the scopes conflict? Could this column more precisely named as "Bean lifecycle" or similar?

Yes, the result column is the end-behavior.  I agree with you that this could be simplified... Providers component types are always singletons (i.e. there is only one instance of each provider for the lifetime of the application).  For resources, the CDI annotation "wins".  So if you were to configure a JAX-RS resource to be per-request, but then put `@ApplicationScoped` on it, it would be a singleton (which is synonymous with application-scoped).  

Maybe something like this?
| Component Type | Configured JAX-RS Scope | Configured CDI Scope | Resulting Lifecycle |
| ----------------- | -------------------------- | ----------------------- | ------------------- |
| Resource              | PerRequest                          | @ApplicationScoped    | Singleton                  |
| ...                           |                                              |                                         |                                  |
| Provider                | *                                            | *                                      | Singleton                 |

\* \- All Providers are required to have a singleton lifecycle.


----
Other comments:
* Can we either remove the JAX-RS version number (2.0) or replace it with "2.0 and 2.1"? 
Even the message text has changed to remove the version number:
`CWWKW1001W: The scope {1} of JAXRS Resource {0} does not match the CDI scope {2}. Liberty gets resource instance from {3}.`
and
`CWWKW1002W: The CDI scope of JAXRS Provider {0} is {1}. Liberty gets the provider instance from {2}.`

* We should update this line:
`If a class is registered in both the getClasses and getSingletons methods of the application class, the JAX-RS 2.0 engine uses the instance from the getSingletons method and ignores the getClasses instance.`
In general, the `getSingletons` method should be avoided - particularly when using CDI.  This method will be removed in future versions of the spec due to some problems that it causes.  For example, objects returned from it will not be managed by CDI - and if users try to force CDI to create an instance for them and then return it in the `getSingletons` method, any JAX-RS-specific injection will fail.  Maybe we should change it to something like:
`If a class is registered in both the getClasses and getSingletons methods of the application class, the JAX-RS engine uses the instance from the getSingletons method and ignores the getClasses instance. Note that objects returned in the getSingletons method will not be managed by CDI.  In general use of the getSingletons method should be avoided as it will be deprecated and eventually removed in future versions of the JAX-RS specification.`. WDYT?

Thanks!

**Comment by dmuelle** [comment]
Thanks @andymc12, very helpful info. I've revised the draft - https://draft-openlibertyio.mybluemix.net/docs/21.0.0.1/jaxrs-integration-cdi.html

 I made edits per your comments above. I changed "JAX-RS 2.0" to just "JAX-RS" throughout so it's version agnostic.

I added an explanation for how conflicting CDI and JAX-RS scopes resolve for resource and provider component types. I removed the table because it just repeats the same info without explaining the underlying logic. I can restore it if you think it's needed, but have a look at the text explanation and lmk what you think.

I also removed the messages because they are available elsewhere (in KC and soon from the OL site) and including them here just means they'd have to be manually maintained, which is why these were out of date. If a user searches on the message code, we want them to find the source that is auto-updated to stay current.

Let me know what other edits are needed- when you're satisfied with it, you can add the `technical reviewed` label to sign off. Thanks!

**Comment by dmuelle** [comment]
updated draft URL: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.1/jaxrs-integration-cdi.html

**Comment by andymc12** [comment]
Just two minor comments - I'll go ahead and mark it reviewed, but these would be good things to fix before publishing.

- Typo in the second paragraph:
> It provides a common mechanism to inject components such as enterprise beans or managed beans into other components such as JavServer Pages (JSP) files or other enterprise beans.

"JavServer" should be "JavaServer"

- Section "Restrictions on JAX-RS 2.0 with CDI" should remove the "2.0" version number.

Thanks @dmuelle!

**Comment by dmuelle** [comment]
Thanks @andymc12 ! I've made both those changes and they'll be picked up with the next draft build

**Comment by lauracowen** [comment]
Looks good. Will sign off but I wondered if there's any reason why the Restrictions section comes before the scopes section? There's info in the scopes section (eg about singletons) that is referred to by the Restrictions section. Wondered if it would make sense to switch the order? Up to you tho.

**Comment by dmuelle** [comment]
That's a good point- I think it would work better with the restrictions at the end. I've updated the draft:
https://draft-openlibertyio.mybluemix.net/docs/latest/jaxrs-integration-cdi.html

Requesting peer review from @Charlotte-Holt

**Comment by Charlotte-Holt** [comment]
@dmuelle Peer review feedback:

- [x] By integrating JAX-RS with CDI, you can annotate CDI beans or managed beans as REST endpoints and use CDI injection for web services. - **Should "web" be capitalized? When I do a Google search, I'm finding it capitalized in "Web services" quite often.** 
- [x] It also supports CDI-style beans as root resource classes, providers, and application subclasses. - **Are CDI-style beans the same thing as CDI beans? I think maybe use the term consistently if so.**  
- [x] It provides a common mechanism to inject components such as enterprise beans or managed beans into other components such as JavaServer Pages (JSP) files or other enterprise beans. - **1) Consider starting the sentence with "This specification". I first had to read back to see what "It" was referencing. 2) Not sure on this one, but Jakarta Server Pages instead of JavaServer Pages?**
- [x] Normally, JAX-RS resources are per-request, the JAX-RS engine creates a new instance of the class for each HTTP request. - **Should this be, "Normally, JAX-RS resources are per-request, meaning that the JAX-RS engine creates a new instance of the class for each HTTP request"?** 
- [x] Per-request classes are beneficial in some cases but they are generally less efficient than a per-application resource, where the same instance is used for every HTTP request. - **Should this be "Per-request classes are beneficial in some cases but they are generally less efficient than per-application resources..."? Not sure, but it read better with both plurals.**
- [x] For more information about CDI, see Context and dependency injection beans. - **I think the title should be "Context and Dependency Injection beans". Maybe we need to open a doc bug to fix the title in the other doc.** 

### JAX-RS and CDI scopes

- [x] A bean lifecycle can be singleton, so that the same instance is used for every HTTP request, or per request, so that a new instance is created for each HTTP request. - **"per-request" instead of "per request"?** 
- [x] Similarly, if you configure a JAX-RS resource scope as singleton, but then specify the @RequestScoped CDI scope on it, the resource lifecycle is per request, as specified the CDI annotation. - **1) "per-request" instead of "per request"? 2) "as specified _by_ the CDI annotation", I think.** 

### Restrictions on JAX-RS with CDI

- [x] If a RESTful resource is also a CDI-managed bean and its scope is javax.enterprise.context.Dependent, the PreDestroy method cannot be called because of the CDI restriction. - **Are CDI-managed beans the same thing as CDI-style beans and/or CDI beans? I think maybe use the term consistently if so.**

**Comment by dmuelle** [comment]
Thanks for reviewing @Charlotte-Holt . I made the changes you suggested, with exceptions noted below

**Should "web" be capitalized? When I do a Google search, I'm finding it capitalized in "Web services" quite often.**
I don't think so- looking at [the Oracle docs](https://docs.oracle.com/cd/E19798-01/821-1841/6nmq2cp1v/index.html), "web services" is only capitalized when part of the API name, generic references aren't capitalized.

**CDI beans, CDI-style beans, CDI-managed beans**
there is a distinction between these terms- here's Andy's response:
"In the JAX-RS spec, they use the term "CDI-style beans" to indicate that a JAX-RS resource or provider class might be used as a CDI bean even though there is no explicit annotation that would indicate it was a CDI bean.
So, for example you might have a "CDI bean" like:
```
@ApplicationScoped // this is a CDI annotation, so explicitly makes this a CDI bean
public class MyCDIBean implements SomeInterface { //...
```

but a JAX-RS resource class like this would be managed by CDI even though it doesn't have any CDI annotations:
```
@Path("/somePath") // this is a JAX-RS annotation, not CDI
public class MyJaxrsResource { //...
```

So, my view of the world is:
CDI beans = Java classes explicitly annotated with CDI annotations
CDI-style beans (in the context of JAX-RS) = JAX-RS components when CDI is enabled
CDI-managed beans = all beans managed by CDI, i.e. 1 + 2"

**I think the title should be "Context and Dependency Injection beans". Maybe we need to open a doc bug to fix the title in the other doc.**
Agree, I [opened a bug](https://github.com/OpenLiberty/docs/issues/3467)

**Comment by dmuelle** [comment]
https://openliberty.io/docs/latest/jaxrs-integration-cdi.html
