### ISSUE TITLE
JMX metrics catalog

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#1286]
Write a topic that includes the JMX metrics in a format similar to the table in https://openliberty.io/docs/ref/general/#metrics-catalog.html. Go through a description of the metrics you can get. Generated Javadoc wouldn’t necessarily show all the reference info in these topics. The current metrics catalog topic covers most of the metrics, but it's not meant to cover JMX metrics. 

**Resources**:
- https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_mon_request.html
- https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_mon_jvm.html
- https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_mon_webapp.html
- https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_mon_threadpool.html
- https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_mon_webservice.html
- https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_sip_pmi_counters.html
- https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_mon_sessionstats.html
- https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_mon_connectionpools.html
- https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_mon_finegrain.html

**SME**: Don Bourne

**Comment by Charlotte-Holt** [comment]
Link to the topic: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#jmx-metrics.html.

**Comment by donbourne** [comment]
I think leaving out the JConsole connection information is fine, as this topic is already quite long and as you mentioned in slack is basically a reference topic.

Given the Object Name is constant within the scope of each MXBean, would it make sense to move that above each table?

You can use the ConnectionPool MXBean for monitoring the connection pool in Open Liberty. 
->
You can use the ConnectionPool MXBean for monitoring connection pools in Open Liberty. 

In the SIP section, you call out use of PMI, which is really an implementation detail.  I would avoid mentioning that in this doc.  Also, for SIP, you call out how to enable SIP itself, which you didn't do for servlets or other dependencies of the other MXBeans.  Should try to be consistent on that (either include that info for all MXBeans or omit for all).

**Comment by donbourne** [comment]
looks good!

**Comment by lauracowen** [comment]
- I think I would call this topic "Performance monitoring with JMX metrics" and drop the OL bit?
- I think this topic is almost two (or three) separate topics combined: it has a conceptual intro, then how to enable, then the actual list of metrics which is really a reference topic in its own right.
  - I think the JMX Metrics list should be a separate topic, to mirror your existing metrics list topic. "JMX metrics reference list"
  - Would it make sense for the conceptual intro to be part of the Microservice observability topic? Could have a section called "Performance metrics" at the same level as "Metrics and annotations" (maybe rename that to "Application metrics"?). I know that topic would then be long so see what you think...

**Comment by Charlotte-Holt** [comment]
@lauracowen Addressing your feedback: 

- [X] I think I would call this topic "Performance monitoring with JMX metrics" and drop the OL bit?
- [X] I think this topic is almost two (or three) separate topics combined: it has a conceptual intro, then how to enable, then the actual list of metrics which is really a reference topic in its own right.
- [X] I think the JMX Metrics list should be a separate topic, to mirror your existing metrics list topic. "JMX metrics reference list"
- [X] Would it make sense for the conceptual intro to be part of the Microservice observability topic? Could have a section called "Performance metrics" at the same level as "Metrics and annotations" (maybe rename that to "Application metrics"?). I know that topic would then be long so see what you think...

Here's the link to what is now the **JMX metrics reference list** topic: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#jmx-metrics.html. And here's the link to the updated **Microservice observability with metrics** topic: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#microservice-observability-metrics.html. I think this is much better, but see what you think upon reading.

**Comment by lauracowen** [comment]
I like the reference topic. The only thing that occurred to me is in the SIP section, it's a bit odd the way the name and description are in the first column when the description is separately in the last column for all the other tables. Was that intentional to make it fit? It's a little harder to scan down the names in the table when it has multiple types of data in the same cell....

Observability topic. Three things:
1. If the JMX section goes in here, I think the paragraph that starts "Different types of metrics are available ..." should be moved up to the top of the MP Metrics section (before the Counters heading); "Metrics and annotations" heading should be changed to "Application metrics" or similar; and the "Add MicroProfile Metrics..." section doesn't quite make sense (firstly because it's written a bit task-y but mainly because it implies all types of metrics discussed are added in that way, when I think the JMX ones are added in the server config); maybe needs something introducing the two types of metrics discussed in this topic explicitly so you can skim or even link down to the type you're interested in.
2. Can you double-check which persona would configure the JMX metrics? A developer would configure the server but would they also configure the JMX metrics? If it wouldn't be the developer, we probably shouldn't include this info here, but it's fine if they would.
3. Is the sentence about the server script relevant here? The app developer wouldn't be concerned about using the server script to launch the server (they just use maven and however Maven does it). Would the developer know how the server's started in production?  (may be one for @NottyCode ?)

**Comment by Charlotte-Holt** [comment]
@lauracowen I created issue #1891 on the backlog for the JMX metrics stuff that I'd moved over to the Microservice observability with metrics topic. The dev-focused, MP Metrics topic has been restored to its original content. 

Regarding the SIP metrics - I did talk with @donbourne about these, and they're a bit different than all the other metrics in the information that we need to provide. I was trying to avoid having too many columns so things don't get squished. Do you think I should try to separate out the name and description: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#jmx-metrics-list.html?

**Comment by lauracowen** [comment]
I think we should try to separate out the name and description and see if we can get it to work. Ideally the name column would wrap when necessary so that long names won't cause that column to be really wide.

Or, is it possible to make the description text in the first column indent slightly so that it's inset from the name slightly?

**Comment by Charlotte-Holt** [comment]
@lauracowen Updated :) I took out the units and added a sentence above the tables about how most of them don't have units because they're basic counters. Only task duration has units.

**Comment by lauracowen** [comment]
Yes, think that works okay. :) Thanks, signing off.

**Comment by Charlotte-Holt** [comment]
Requesting peer review from @dmuelle: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#jmx-metrics-list.html.

**Comment by dmuelle** [comment]
# Peer review

## Intro
I wonder if this intro/ shortdesc wouldn't benefit from a single-sentence explanation of what JMX metrics or why they matter. Maybe it's not necessary since anyone looking at this list would already know? But if there are any common concepts or terms associated (MXBeans for example), mentioning them in the shortdesc could help with SEO. In that case, you could move the sencond sentence in the shortdesc down to the following pp, just before you introduce the tables. 

All of the tables are introduced in this format:
`The following attributes are available for the JvmStats MXBean. The object name of the MXBean for these attributes is WebSphere:type=JvmStats:`

Does it make sense to switch the order of these sentences, so the sentence that intros the table directly precedes it, ending with a colon? Like

`The object name of the MXBean for these attributes is WebSphere:type=JvmStats. The following attributes are available for the JvmStats MXBean:`

Also many of the statements use this format, with a gerund verb

`You can use the ThreadPoolStats MXBean for thread pool monitoring in Open Liberty.`

That could be more direct like

`You can use the ThreadPoolStats MXBean to monitor thread pool in Open Liberty.`



## JvmStats MXBean

Question- why are units not applicable to heap memory? Isn't heap memory measured in bytes?

I was wondering if you needed to specify "heap memory" and not just "heap" (for translation purposes mainly). IBM terminology recognizes "heap" as a noun so I guess its ok as is


## ServletStats MXBean

`RequestCount` details that include the last time stamp.- Should this be in plain text?
Request count details
or 
Details about the RequestCount attribute value, including the last time stamp

Similar question for ResponseTime

## ConnectionPool MXBean

` Connection pools manage connections from data sources and connection factories, and performance data is made available for each connection pool. The ConnectionPool MXBean is responsible for reporting metrics for a single connection manager.`

In this case, what is a connection manager? Is it a connection pool? This description seems to imply that but it's not clear. If they are the same thing, probably better to say

` Connection pools manage connections from data sources and connection factories, and performance data is made available for each connection pool. The ConnectionPool MXBean is responsible for reporting metrics for a single connection pool.`

Or if they're separate, explain how

I think in-use should be hyphenated here:
`In use time details that include the total number of granted connections (excluding the ones that are currently in use), minimum in use time, and maximum in use time.`

For consistency, I think this should be "wait time", as in the attribute and the following description, rather than "waiting time"
`The average waiting time until a connection is granted...`

I think wait-time should be hyphenated here (though not in the previous description, where it's a noun)
`Wait time details that include...`

## SIP application MXBeans
`a component that collects SIP performance metrics of a running application server.`
 _from_ a running server ?

## Basic counters

`The size of the invoke queue in the product.`
What is " the product" ? Is it an Open Liberty server? I wonder if this description originated in tWAS, where the server is referred to as "the product"  in docs for compatibility with stack products. If so, can probably call it "the server"  or "Open Liberty" here.

Don't think you need "that it takes" here:
`The average amount of time that it takes between when a message gets into the container and when a response is sent from the container.`

`The number of invocations of the SIP timers (Timer A, Timer B, Timer C, Timer D, Timer E, Timer F, Timer G, Timer H).`
What's that parenthetical list for? It's not clear.

**Comment by Charlotte-Holt** [comment]
@dmuelle Thanks for the great review! I incorporated all your comments, except I left tables introduced in this format:

```The following attributes are available for the JvmStats MXBean. The object name of the MXBean for these attributes is WebSphere:type=JvmStats:```

Reordering the sentences made the reference to "these" feel out of place to me.

**Comment by Charlotte-Holt** [comment]
@chirp1 Topic at https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/jmx-metrics-list.html.

**Comment by Charlotte-Holt** [comment]
Editing updates made:

- "The sessions that are associated with a single web application have their own `SessionStats` MXBean, meaning that there's one `SessionStats` MXBean for each web application." --> "The sessions that are associated with a single web application have their own `SessionStats` MXBean, meaning that one `SessionStats` MXBean exists for each web application." - DQTI, Chapter 6, Clarity, Use pronouns correctly
- "Because all the metrics that are listed in the following table are counters, there aren't any units that are associated with them:" --> "Because all the metrics that are listed in the following table are counters, no units are associated with them:" - DQTI, Chapter 6, Clarity, Eliminate wordiness

**Comment by Charlotte-Holt** [comment]
@chirp1 I'd gone back through this one and focused on updates relating to the chapter on clarity. Some specific updates I made:

- "The sessions that are associated with a single web application have their own SessionStats MXBean, meaning that there's one SessionStats MXBean for each web application." --> "The sessions that are associated with a single web application have their own SessionStats MXBean, meaning that one SessionStats MXBean exists for each web application." - DQTI, Chapter 6, Clarity, Use pronouns correctly
- "Because all the metrics that are listed in the following table are counters, there aren't any units that are associated with them:" --> "Because all the metrics that are listed in the following table are counters, no units are associated with them:" - DQTI, Chapter 6, Clarity, Eliminate wordiness

I also went back and checked through the KC topics that relate to this topic, and I don't believe I'm missing any information that would be helpful to readers.

**Comment by donbourne** [comment]
would like to reference this topic to address a customer question at https://groups.io/g/openliberty/topic/78185136 .  Can this please be published?

**Comment by chirp1** [comment]
Hi Charlotte,
A nice, thorough topic! I have a few comments:
- Global comment: The links at the top of the page have one name, such as  "JAX-WS monitoring", but the section title that it links to is the MXBean name, such as "WebServiceStats MXBean". Could the section titles change to include the link name and the MXBean, something like, for example: "JAX-WS monitoring: WebServiceStats MXBean" or "JAX-WS monitoring for the WebServiceStats MXBean". Note that if you do change the section titles, I'd say, leave the titles for the SIP  application section as they are.
- The link for "Perfomance Monitoring feature " seems to link to the topic that the link is in, which is https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/jmx-metrics-list.html#reference:feature/monitor-1.0.adoc. I think you want to link to https://openliberty.io/docs/20.0.0.12/reference/feature/monitor-1.0.html .
- For "WebSphere:type=ServletStats,name=*: ", From rwlp_mon_webapp.html, I believe it should be:WebSphere:type=ServletStats,name=<AppName>.<ServletName>   from https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_mon_webapp.html
- For the WebServiceStats MXBean, I'm looking here: https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_mon_webservice.html  The MXBean seems to have 
org.apache.cxf:bus.id=<bus.name>,type=Performance.Counter.Server,service="<NameSpace><ServiceName>",port="<PortName>"
org.apache.cxf:bus.id=<bus.name>,type=Performance.Counter.Client,service="<NameSpace><ServiceName>",port="<PortName>"
- For "ConnectionPool MXBean", I think from https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_mon_connectionpools.htmlthat the object name is "WebSphere:type=ConnectionPoolStats,name=<IDENTIFIER_OF_CONNECTION_MANAGER>", where the type is ConnectionPoolStats, not ConnectionPool 
- For "InUseTimeDetails" for "ConnectionPool MXBean attributes ", change "granted connections excluding the " to "granted connections, excluding the " (add comma).
- For "REST_Stats MXBean", I alternatively see RESTStatus at https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.javadoc.liberty.doc/com.ibm.websphere.appserver.api.jaxrs20_1.0-javadoc/com/ibm/websphere/jaxrs/monitor/RestStatsMXBean.html  Change to RESTStatus if appropriate.

**Comment by Charlotte-Holt** [comment]
@chirp1 Updated:

https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.3/jmx-metrics-list.html

- [x] Global comment: The links at the top of the page have one name, such as "JAX-WS monitoring", but the section title that it links to is the MXBean name, such as "WebServiceStats MXBean". Could the section titles change to include the link name and the MXBean, something like, for example: "JAX-WS monitoring: WebServiceStats MXBean" or "JAX-WS monitoring for the WebServiceStats MXBean". Note that if you do change the section titles, I'd say, leave the titles for the SIP application section as they are.
- [x] The link for "Perfomance Monitoring feature " seems to link to the topic that the link is in, which is https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/jmx-metrics-list.html#reference:feature/monitor-1.0.adoc. I think you want to link to https://openliberty.io/docs/20.0.0.12/reference/feature/monitor-1.0.html .
- [x] For "WebSphere:type=ServletStats,name=*: ", From rwlp_mon_webapp.html, I believe it should be:WebSphere:type=ServletStats,name=. from https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_mon_webapp.html
- [x] For the WebServiceStats MXBean, I'm looking here: https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_mon_webservice.html The MXBean seems to have
  - org.apache.cxf:bus.id=<bus.name>,type=Performance.Counter.Server,service="",port=""
  - org.apache.cxf:bus.id=<bus.name>,type=Performance.Counter.Client,service="",port=""
- [x] For "ConnectionPool MXBean", I think from https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_mon_connectionpools.htmlthat the object name is "WebSphere:type=ConnectionPoolStats,name=<IDENTIFIER_OF_CONNECTION_MANAGER>", where the type is ConnectionPoolStats, not ConnectionPool
- [x] For "InUseTimeDetails" for "ConnectionPool MXBean attributes ", change "granted connections excluding the " to "granted connections, excluding the " (add comma).
- [x] For "REST_Stats MXBean", I alternatively see RESTStatus at https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.javadoc.liberty.doc/com.ibm.websphere.appserver.api.jaxrs20_1.0-javadoc/com/ibm/websphere/jaxrs/monitor/RestStatsMXBean.html Change to RESTStatus if appropriate.

**Comment by chirp1** [comment]
Hi Charlotte- a very small tweak:
- I think we want to remove "(monitor-1.0)" to be consistent with other feature references.
- Note: Charlotte verified with Don Bourne that the MXBean is REST_Stats, not RESTStats.

**Comment by chirp1** [comment]
The updates look good!

**Comment by Charlotte-Holt** [comment]
Merged to `vNext` in https://github.com/OpenLiberty/docs/pull/3731 and added to the KC spreadsheet.
