### ISSUE TITLE
Work out Antora navigation for OL docs 

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#1435]
We need to decide on a navigational structure for the OL docs before we move to Antora. The prototype from the `antora` branch is https://antora.mybluemix.net/docs/latest/developing/overview.html. The first idea that @lauracowen, @dmuelle, and I came up with was built around using the categories in the [guides navigation](https://demo1-openlibertyio.mybluemix.net/guides/). However, this structure needs to be better thought out and discussed. 

This issue is to facilitate discussion about the nav, so add any concerns, thoughts, or suggestions.

**Comment by NottyCode** [comment]
I think it is a good start, but I have some thoughts.

1. I think right now we can merge monitoring and troubleshooting and call it Observability. I think we do need a troubleshooting category bu the content in that section isn't troubleshooting, it is observability.
2. I'm not sure I'd put test under a build section. Writing tests is something I do when I'm developing
3. I feel like security should be top level. It kind of cross cuts between deployment, operations and development, so just having it in development seems strange. I also don't think the CVE page should be under development.

I like the proposal currently because it is simple and also follows the dev/ops lifecycle from the start point of the first cycle through.

**Comment by Charlotte-Holt** [comment]
Updated nav at https://antora.mybluemix.net/docs/latest/overview.html.

**Comment by chirp1** [comment]
Hi!
A few points that I mentioned previously:
- I'd like to see an example nav that has one top level entry, and then the sections underneath it. The user would be able to get to the sections by clicking the twistie to expand the top level. The reason to have only one top level is so that we can move topics around without having to code a redirection.. The top-level sections are in different directories. If a topis is moved from one top-level section to another the URL changes and the topic must be redirected programmatically.
- I'd like to see something that addresses topics that are tasks.

**Comment by Charlotte-Holt** [comment]
Notes from 6/16: 

- GitHub structure okay as it is 
- Visual indicator for guides in TOC 
- Using gerunds for task topic titles
- Pull out security to high-level section, and keep developer-specific stuff in Development
- Rename Metrics to Observability

**Comment by dmuelle** [comment]
New nav that reflects comments from 6/16 meeting and subsequent discussion:

https://github.com/OpenLiberty/docs/pull/1927

- Guides added in relevant sections
- gerunds in task topics only
- Security is now a high level section
- Metrics is now Observability, with sections in both development and operations

**Comment by dmuelle** [comment]
Posted nav for published topics only: https://antora.mybluemix.net/docs/latest/overview.html

**Comment by Charlotte-Holt** [comment]
Settled on a nav for the go-live of Antora. Closing this issue.
