### ISSUE TITLE
Classloading in OpenLiberty

### ISSUE THREAD

**Issue by ggam** [OpenLiberty/docs#1439]
The documentation explains very little about classloading in OpenLiberty. The best resource I could find on the internet is [this presentation](https://publib.boulder.ibm.com/infocenter/ieduasst/v1r1m0/topic/com.ibm.iea.was_v8/was/8.5/ProgrammingModel/WAS85_LP_Class_Loading.pdf), which is nice but difficult to find.

Also, it doesn't explain classloading for `bell`'s, which is a feature I can't hardly find information about.

**Comment by dmuelle** [comment]
Hi @ggam, Thanks for your feedback, we are investigating new doc for bells. In the meantime here is the [feature doc](https://www.openliberty.io/docs/20.0.0.8/reference/feature/bells-1.0.html) and [a reference for the bell configuration](https://www.openliberty.io/docs/20.0.0.8/reference/config/bell.html)

**Comment by ggam** [comment]
Thanks a lot @dmuelle. Please note that besides expanding `bell`s documentation, my main trouble has been in understanding Liberty classloading in general.

To give you some more detail and concrete examples, I come from WildFly where the concept of "libraries" is based on JBoss modules. You define a module and the packages it imports and exports. The application depends on a module that only exposes some specific packages (I think the way to do that on Liberty would be to develop a custom feature based on an OSGi bundle).

Now I have an application deployed on Liberty, which uses Hibernate as JPA implementation and Jaeger client as OpenTracing collector. Things I don't understand:
- I define the hibernate library, I set the `jpaContainer` to use that library... but then I have to refer the library from the application. The application needs access to Hibernate classes (with its bunch of of transitive dependencies).
- Something similar happens with Jaeger... only that the application not only needs to see Jaeger classes, but also OpenTracing client classes, which means I have to add `apiTypeVisibility="+third-party"` to the application. I don't know what exactly is that giving access to my application, but I'm concerned about dependency collisions. 

I'm probably doing something wrong, or perhaps there's really no problem at all, but these are the kind of things I'd like to understand from a classloading article.

Hope this helps!

**Comment by andymc12** [comment]
Hi @ggam,

It sounds like you are mostly on the right track.  In your server configuration (server.xml, etc.) you should define one or more `library` elements to include your Hibernate JAR(s) and Jaeger JAR(s).  Both elements should include an `id` attribute for you to reference from other configuration elements (like `jpaContainer`) and the `application` element(s).  For example:
```
<library id="hibernateLib" apiTypeVisibility="+third-party" ...>
    <fileset dir="/path/to/hibernateJars" includes="*.jar"/>
</library>

<library id="jaegerLib" apiTypeVisibility="+third-party" ...>
    <fileset dir="/path/to/jaegerJars" includes="*.jar"/>
</library>

<application id="myApp"...>
    <classLoader apiTypeVisibility="+third-party" privateLibraryRef="hibernateLib" commonLibraryRef="jaegerLib" />
</application>
```

The difference between a private library and a common library is that private library class paths are appended to the application's classloader's class path, while a common library has it's own classloader that the application will delegate to.

I believe that the reason that you need to add third-party API type visibility is so that the Jaeger classes can load the `io.opentracing.*` classes from Liberty's OSGi bundles.  The image below shows the classloading hierarchy in Liberty:

![OL-ClassLoading-Hierarchy](https://user-images.githubusercontent.com/21365299/90680993-502e4400-e228-11ea-9e05-8304672edf95.png)

When you add third-party type visibility, that does "open the floodgates" so that your application can now (via the Gateway Loader / OSGi Bundle Loaders) load all classes that Open Liberty has designated as third-party.  However, that is controlled by which features you have enabled.  For example, if you have the `jsf-2.3` feature enabled, then your application will be able to load the version of Apache MyFaces that is provided by Liberty - if you included your own version of MyFaces in your application this could cause a conflict.  If you need to rely on third-party APIs that Liberty provides in some cases but not others, I would recommend packaging your own API and implementation JARs with your app - so in this hypothetical case where you want Liberty's MP OpenTracing to use Jaeger, but you want to use a different version of MyFaces for JSF, then you should remove the `<feature>jsf-2.3</feature>` from the server configuration and package your own JSF APIs with your application.  It is also possible to use parentLast delegation to work around some of these issues, but in my experience, parentLast tends to cause more problems than it solves.

Hope this helps,
Andy

**Comment by ggam** [comment]
Thanks a lot @andymc12! It definitely made things clearer. 

So to sum up, regarding `+third-party`:
* It only applies to OSGi bundles (Liberty features)
* It only adds visibility to some APIs specifically defined by Liberty as visible. It doesn't make *every* third party class visible to the referring classloader.

~Currently the documentation shows the Standard, IBM and Stable APIs, but not these 3rd party. I suggest adding these too (I can open a new issue for this if you like).~ My fault. I was looking at the from feature. Its `opentracing and not `mpOpentracing which provides those 3rd party APIs.

And, for swapping a Liberty implementation or isolating custom libraries, I have the following options:
* Remove the feature from `server.xml and put the dependency on my WAR. Seems to be the recommended way. I don't like it as e.g. Hibernate and Jaeger will collide with different versions of Log4j.
* Define a library and reference it from the application as a `commonLibrary`. That will isolate library classloaders, but eventually, my application is still able to see (one version) of the classes. That isn't a problem in most cases even if the application bundles the same library, due to delegation, but would be problematic if I do some `Class.forName()` hack to verify the existence of some class. If the application classloader doesn't have it, it will delegate to the library, which can contain it.
* There are the `jpaContainer`, `jsfContainer` and `jsonbContainer`, which are based on `bell`s.  This seemed to be the solution I was looking for, but it wasn't. I thought only the `bell` needed class visibility, but I found the application also needs it (at least in the case of the `jpaContainer`, I haven't tried the other ones). Is this really by design? If that's the case, what's the benefit of using those `*Container` features?
* In case I desperately needed isolation, I guess another solution is to write a custom bundle and define it as a user feature (again, little and difficult to grasp documentation).

**Comment by andymc12** [comment]
Hi @ggam - sorry for the slow response, I was out on PTO a bit last week.

> There are the jpaContainer, jsfContainer and jsonbContainer, which are based on bells. This seemed to be the solution I was looking for, but it wasn't. I thought only the bell needed class visibility, but I found the application also needs it (at least in the case of the jpaContainer, I haven't tried the other ones). Is this really by design? If that's the case, what's the benefit of using those *Container features?

I don't know too much about the `jpaContainer` or `jsfContainer` features.  The `jsonbContainer` is intended for the same use case that you originally described - "I want to use JSON-B, but I prefer a different implementation than the one Liberty ships with by default".  So in that case, you could, for example, tell Liberty to use Johnzon for JSON-B (rather than Yasson) - there is an example test case of this available at https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.jsonb_fat/publish/servers/com.ibm.ws.jsonb.inapp/server.xml.  Notice in that case, that Johnzon is stored in a library element and referenced by the application - the same library could also be referenced by a bell (which is done in a different test case).  Perhaps the JPA Container feature does the same thing, which would allow you to use Hibernate instead of EclipseLink - somebody like @jgrassel or @dazey3 might be able to confirm.

> In case I desperately needed isolation, I guess another solution is to write a custom bundle and define it as a user feature (again, little and difficult to grasp documentation).

Yes, if you can avoid a user feature, I would recommend it.  

HTH

**Comment by ggam** [comment]
Thanks @andymc12, it definitely helps. A lot. I didn't know about those fat tests, but they are a true gem. I can gather a lot of config examples that are still undocumented from them. Absolutely fantastic.

I've looked a little more at the `jsfContainer` and `jpaContainer` features and I've seen the JSF one is intented to bundle the implementation on the WAR. The JPA container isn't (fat) tested in combination with a BELL so I'll have to dig a bit more on the source code. Perhaps it's not intented to work or maybe there's a bug.

Thanks a lot again

**Comment by dmuelle** [comment]
The doc for this issue is now being tracked in #2419
