### ISSUE TITLE
Configuring SPNEGO authentication

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#1479]
New task topic for configuring SPNEGO. See https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_spnego_config.html. Link to and from feature config and SSO topics. 

Comments from LC: The info about how to config (inc config examples) should go in the SPNEGO feature doc as normal, though clearly linked to from the task topic in the relevant place. Occurrences of ‘Note’
 should just be sentences in the appropriate places in the topic (if needed). And bits that have been retrofitted for newer releases of Liberty and Java in that KC topic should just be integrated into the appropriate places - there’s no need to highlight the instruction as exceptional.

**Comment by Charlotte-Holt** [comment]
@utle Please review https://draft-openlibertyio.mybluemix.net/docs/ref/general/#configuring-spnego-auth.html.

**Comment by utle** [comment]
` IWA but not for Kerberos and NT LAN Manager (NTLM). `
Change to
` IWA but not for NT LAN Manager (NTLM) token. `

`First, create a Kerberos service principal name and keytab file and enable them for SPNEGO authentication. Then, configure the SPENGO feature for Open Liberty and the client application.`
maybe something?
`First, create a Kerberos service principal name and keytab file and copy the keytab file to Open Liberty. Then, configure the SPENGO feature for Open Liberty and the client application.`

`Enable the Kerberos keytab and configuration files and SPNEGO web authentication`
maybe?
`Install/copy? the Kerberos keytab and configuration files and SPNEGO web authentication`

**Comment by Charlotte-Holt** [comment]
@utle I incorporated your feedback into the draft. Please review https://draft-openlibertyio.mybluemix.net/docs/ref/general/#configuring-spnego-auth.html.

**Comment by utle** [comment]
developer approved

**Comment by utle** [comment]
https://draft-openlibertyio.mybluemix.net/docs/ref/general/#configuring-spnego-auth.html
I see "copy" at the end of the following commands, not sure what is it for?

`ktpass -in myOtherKrb5.keytab -out krb5.keytab -princ HTTP/myLibertyMachine.example.com@MYDOMAIN.EXAMPLE.COM -mapUser myLibertyMachine_http -mapOp set -pass security -crypto RC4-HMAC-NT -ptype KRB5_NT_PRINCIPALCopy`

`klist -k -t /etc/krb5.keytabCopy`

`"HTTP/" + java.net.InetAddress.getLocalHost().getCanonicalHostName();Copy`

Also, which article that link all the SPNEGO sub articles?

**Comment by utle** [comment]
https://draft-openlibertyio.mybluemix.net/docs/ref/general/#configuring-spnego-auth.html

It's not quite clear the order of steps that customer need to follow, it maybe just me. But we need the following steps in order:
1) Create user, spn, keytab from the AD machine
2) Copy keytab from AD machine to Liberty machine,.
3) create Kerberos configuration file on Liberty machine
4) Configure SPNEGO feature

Step 2) and 3) can combine.
Configure the browser client could be step 4 or separate a client configuration article.

**Comment by utle** [comment]
We now have the following articles
https://draft-openlibertyio.mybluemix.net/docs/ref/general/#sso-config-spnego.html
https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#spnego-1.0.html
https://draft-openlibertyio.mybluemix.net/docs/ref/general/#configuring-spnego-auth.html


https://draft-openlibertyio.mybluemix.net/docs/ref/general/#authentication-open-liberty.html
has a link to article Simple and Protected GSS-API Negotiation Mechanism (SPNEGO)
https://draft-openlibertyio.mybluemix.net/docs/ref/general/#sso-config-spnego.html

These article kind of dis-connect 
https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#spnego-1.0.html
https://draft-openlibertyio.mybluemix.net/docs/ref/general/#configuring-spnego-auth.html

**Comment by Charlotte-Holt** [comment]
The [feature topic](https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#spnego-1.0.html) links to the [SSO w/ SPNEGO overview](https://draft-openlibertyio.mybluemix.net/docs/ref/general/#sso-config-spnego.html) and the task on [configuring SPNEGO](https://draft-openlibertyio.mybluemix.net/docs/ref/general/#configuring-spnego-auth.html).

The task topic also links to the feature config topic and the overview topic. @Rwalls1, could you update the SSO w/ SPNEGO topic to link out to the Configuring SPNEGO task topic and the feature topic where it makes sense?

**Comment by utle** [comment]
developer approved

**Comment by Charlotte-Holt** [comment]
Notes from call w/ Ut: 

- Step 3 substeps - User wouldn't know if there were errors running the first command, so do substeps to check that it worked. "To make sure that the command worked properly..."
- Can remove "If your Microsoft setspn..." substep 
- "If you have multiple SPNs, you need to merge keytab files" And make step 3b into its own step
- New server, windows 
- Create the file manually - as opposed to tWAS where you can run a command to create the file
- "by using the fully qualified hostname"
- Ut hasn't seen any customer use Edge yet.

**Comment by Charlotte-Holt** [comment]
@lauracowen Thanks for the feedback. I spoke with Ut and made updates to https://draft-openlibertyio.mybluemix.net/docs/ref/general/#configuring-spnego-auth.html. 

- [ ] In general, the task approach for this info is ok but needs verifying against modern machines. This whole topic needs testing (a la Red Hat’s QA process that we don’t have yet…). I don't think we can publish it until we know it actually works. - **Agreed**
- [X] Don’t think the step should be in bold. Just use indented paragraphs under the first sentence if you want to make the first sentence stand out (but don’t worry about this for now - it might be that we can simplify the topic by getting it up-to-date first).
- [X] How does step three work? there is a command (weird example - think the command should be separate from the output illustration) and then the sub-steps? When/why would you do these sub-steps? After running the command? Or are they describing the command? Are the sub-steps even necessary? 
- [X] Step 3a has a bit about supporting the -X option and using setspn -X - why/when would you use that? - I worked with Ut to _hopefully_ clarify this step.
- [X] "If your Microsoft setspn command version supports the -X option” - probably all the versions of MS Windows now support it and probably don't need to say “If”. These bullets in this step seem to offer alternative ways to do the same thing. Don’t document both command approaches - just doc the one that’s most common/useful.
- [ ] C:C: in Step 3 - should be single C: - This is a strange one because it's not `C:C:` in the source, so I'm trying to figure out what's going on there. 
- [X] For Windows platforms, the default location is probably not c:\winnt\... now.
- [X] On OL, check which unixes we talk about in OL.
- [X] “default location is the same directory as the Kerberos configuration file.” - but where is that? it reads as if it’s part of liberty and it’s not.
- [ ] examples in first section are all windows. then later talks about linux and aix (but they’re not mentioned earlier).
- [X] "For Open Liberty servers, you must create this file manually." - must create this file manually - as opposed to doing what?
- [X] Step 4 (Configure and enable SPNEGO web authentication for Open Liberty.) - why is it providing a code example? should just say it’s using the localhost/canonical hostname. Shouldn’t define it in terms of java code. If you’re an operator that might not know what that means. In fact, Alasdair can’t tell you what that means, and he is a Java developer.
- [ ] The browsers mentioned are out-of-date - most likely now would be Edge and Chrome and Firefox. - Trying to work with Ut on this to get instructions for Chrome. He said that he sees customers use Internet Explorer more often than Edge. 
- [X] no HP or Solaris

**Comment by lauracowen** [comment]
- Think the intro needs to be clearer about why this topic might be relevant to the reader. eg, I think the stuff in "About this task" should just be part of the intro (between the shortdesc and the Prereqs section) but it needs to be clearer about why you should care. eg see text about SPNEGO in https://draft-openlibertyio.mybluemix.net/docs/ref/general/#single-sign-on.html (could just copy/include that). The first para in About this task currently just focuses on the tech but not what benefit it brings if you actually do this task.
- After Procedure heading, would it make sense to have a very brief intro before the first sub-section that says something like "There are three main things you need to do: 1. Create a kerberos...etc, 2. Copy the kerberos..., 3. Configure the client app." (would it make more sense to most users here just to say "Configure the web browser on the client laptop/desktop" or similar? - bit more concrete). The numbered list could just be a linked list of the three sub-headings or it could include slightly more text that says why you need to do that step (or that brief explanation could start each of the sub-sections before the first step). At the moment, I think the topic is long and windy and you don't really know where it's going or where you're up to - having a summary at the top of the main steps would help orientation and navigation of the long topic (it's fine that it's long if it's all necessary info; it just needs to be navigable). Just realised that that's summarise in the About section - I think it might be more relevant as part of the Procedure section?
- Minor thing but the browser names could be sub-sub-headings rather than a bulleted list?
- How would you know if a given browser supports SPNEGO? Can we give a minimum version level? Or can we assume _all_ browsers support it nowadays?
- We need Chrome instructions - it's the most popular browser (https://www.zdnet.com/article/whats-the-most-popular-web-browser-in-2020/). According to that article, Safari is more popular than IE and Firefox.
- In the final para (Results), it might be good to clarify who "you" is a bit more? So rather than "After you configure SPNEGO authentication, you can use applications", say something like "After you configure SPNEGO authentication, you can deploy applications in your company that users can log into once...etc etc". Separate the end-user of the app from the audience of this topic (the admin/ops person doing the config); doing that also implicitly makes it clearer that we understand the situation/scenario that they're working in.
- is this sentence "Open Liberty supports SPNEGO for IWA but not for NT LAN Manager (NTLM) tokens." still relevant? (I don't know - just wondering if NT LAN Manager is still a thing?)
- Is it relevant to mention the RFC (standardisation doc) - seem a bit too much detail for someone just wanting to use it? "that supports the SPNEGO authentication mechanism as defined in IETF RFC 2478" would it work to just say "that supports SPNEGO"? Richard is looking for links where readers can find more info about each SSO method so could provide that same link here, if it seems useful? Though I think if they're reading this, it's because they already know what it is.
- "by using a native Open Liberty server authentication mechanism" - I think maybe we need to point them to examples of what this might be - eg would that be Social Media Login?
- I like the "To verify that the command worked correctly" bit - I don't think it needs to be a sub-step though. Could just make it another paragraph in that step (put a blank line then put `+` on the line before the new para and that should keep it as part of the numbered step). In the next section, the 'verify' step is a separate full step though; should it be the same format here too?
- `C:C:\>` looks wrong in step 3 (two instances).

**Comment by Charlotte-Holt** [comment]
New link to the topic: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#configuring-spnego-authentication.html

**Comment by Charlotte-Holt** [comment]
@lauracowen Making updates to this. Still working to find someone to test it and write Chrome/Safari instructions. 

- [X] Think the intro needs to be clearer about why this topic might be relevant to the reader. eg, I think the stuff in "About this task" should just be part of the intro (between the shortdesc and the Prereqs section) but it needs to be clearer about why you should care. eg see text about SPNEGO in https://draft-openlibertyio.mybluemix.net/docs/ref/general/#single-sign-on.html (could just copy/include that). The first para in About this task currently just focuses on the tech but not what benefit it brings if you actually do this task.
- [X] After Procedure heading, would it make sense to have a very brief intro before the first sub-section that says something like "There are three main things you need to do: 1. Create a kerberos...etc, 2. Copy the kerberos..., 3. Configure the client app." (would it make more sense to most users here just to say "Configure the web browser on the client laptop/desktop" or similar? - bit more concrete). The numbered list could just be a linked list of the three sub-headings or it could include slightly more text that says why you need to do that step (or that brief explanation could start each of the sub-sections before the first step). At the moment, I think the topic is long and windy and you don't really know where it's going or where you're up to - having a summary at the top of the main steps would help orientation and navigation of the long topic (it's fine that it's long if it's all necessary info; it just needs to be navigable). Just realised that that's summarise in the About section - I think it might be more relevant as part of the Procedure section?
- [X] Minor thing but the browser names could be sub-sub-headings rather than a bulleted list?
- [ ] How would you know if a given browser supports SPNEGO? Can we give a minimum version level? Or can we assume all browsers support it nowadays?
- [ ] We need Chrome instructions - it's the most popular browser (https://www.zdnet.com/article/whats-the-most-popular-web-browser-in-2020/). According to that article, Safari is more popular than IE and Firefox.
- [X] In the final para (Results), it might be good to clarify who "you" is a bit more? So rather than "After you configure SPNEGO authentication, you can use applications", say something like "After you configure SPNEGO authentication, you can deploy applications in your company that users can log into once...etc etc". Separate the end-user of the app from the audience of this topic (the admin/ops person doing the config); doing that also implicitly makes it clearer that we understand the situation/scenario that they're working in.
- [X] is this sentence "Open Liberty supports SPNEGO for IWA but not for NT LAN Manager (NTLM) tokens." still relevant? (I don't know - just wondering if NT LAN Manager is still a thing?)
- [X] Is it relevant to mention the RFC (standardisation doc) - seem a bit too much detail for someone just wanting to use it? "that supports the SPNEGO authentication mechanism as defined in IETF RFC 2478" would it work to just say "that supports SPNEGO"? Richard is looking for links where readers can find more info about each SSO method so could provide that same link here, if it seems useful? Though I think if they're reading this, it's because they already know what it is.
- [ ] "by using a native Open Liberty server authentication mechanism" - I think maybe we need to point them to examples of what this might be - eg would that be Social Media Login?
- [X] I like the "To verify that the command worked correctly" bit - I don't think it needs to be a sub-step though. Could just make it another paragraph in that step (put a blank line then put + on the line before the new para and that should keep it as part of the numbered step). In the next section, the 'verify' step is a separate full step though; should it be the same format here too?
- [ ] C:C:\> looks wrong in step 3 (two instances).

**Comment by Charlotte-Holt** [comment]
@lauracowen I've addressed all your comments except the following things: 

- This whole topic needs testing
-  We need Chrome instructions
- The examples in first section are all windows, then it later talks about linux and AIX.

I talked with @chirp1, and we're definitely going to get it tested and get the Chrome instructions from a dev, but we were thinking it could be a good idea to get this one through your initial approval, then through Karen's, and then it can be tested and Chrome instructions will be added. Then it may have to go back to you and Karen. I think this one may just be a little more iterative because it has to be validated. If you're good with that approach, could you take another look at it and add any additional feedback that needs to be addressed? 

Link to the topic: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#configuring-spnego-authentication.html.

**Comment by lauracowen** [comment]
Re testing - would it make sense to have a label of something like `needs testing` which is then replaced by your `doc tested` label? That way we know that it's in need of another step even if everything else is signed off (probably wouldn't need many re-reviews after testing unless it all went really wrong). I'd be happy signing off with just that to go.

But, I don't think I want to actually sign it off (with the approved label) without the Chrome instructions and the platform stuff because they're things I raised as being needed before publishing. However, I think it's fine if Karen wants to get on with doing an editorial review and treat it iteratively like that. I've just done another quick review of the topic and I think (within the constraints of my technical knowledge of this subject!) the topic looks a lot better for the stuff you've changed already. I can't imagine much would change as long as what's there actually works when tested (I don't think it'd waste Karen's time to do her review at this stage).

**Comment by utle** [comment]
```
Google Chrome
For Windows:
Open the Control Panel to access the Internet Options dialog. Use the same configuration as detailed in Configuration changes required are the same as those described above for Internet Explorer.
For Linux or MacOS:
Add the --auth-server-whitelist parameter to the google-chrome command. For example, to run Chrome from a Linux prompt, run the google-chrome command as follows:
> google-chrome --auth-server-whitelist = "hostname/domain"
```

We tested the crome for window

**Comment by Charlotte-Holt** [comment]
@lauracowen I added the new **requires doc testing** label. I also updated the topic to add Ut's Chrome instructions (thanks, @utle!) and slightly reworded the Kerberos step per our conversation with Ut last week. If you're good with these changes, I'll move this over for Karen to review, and then it can go back to doc testing. 

Link to the topic: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#configuring-spnego-authentication.html.

**Comment by Charlotte-Holt** [comment]
Requesting peer review from @ManasiGandhi

**Comment by ManasiGandhi** [comment]
#peer review @Charlotte-Holt The topic looks good! A few edit suggestions

**Introduction**

- In the second paragraph, change " SPNEGO can be used to provide SSO in an application if the organization uses Microsoft Active Directory. SPNEGO can also be configured to work on Linux operating systems. ", to, "You can use SPNEGO to provide SSO in an application if the organization uses Microsoft Active Directory. You can also configure SPNEGO to work on Linux operating systems.", to avoid passive voice.
Also,
"SPNEGO enables users to log in to applications by using their Microsoft Windows account login instead of using a separate account to log in to their Windows operating system." to "SPNEGO enables users to log in to applications with their Microsoft Windows account login instead of a separate account to log in to their Windows operating system.", 
and,
"This task demonstrates how to configure an Open Liberty server to support SSO for HTTP requests by using SPNEGO."
to
"This task demonstrates how to configure an Open Liberty server to support SSO for HTTP requests with SPNEGO."

**Prerequisites**

- "To enable SPNEGO, the clocks for the client, Active Directory server, and Open Liberty server must be synchronized to within 5 minutes of each other.", remove "to" in "synchronized to within "

- Change, "This allowable difference in synchronization is configurable." to "You can configure this allowable difference in synchronization." to avoid passive voice.

**Procedure**

- "To configure SPNEGO, you complete the following items:", remove "you".

**Copy the Kerberos keytab and configuration files and enable SPNEGO web authentication**

- In point 4, "For information about how to enable this feature and configuration examples, go to the Open Liberty feature documentation.", can you say "For information about how to enable this feature and configuration examples, see the Open Liberty feature documentation."

**Configure the client application on the client computer**

- In the first line "The following steps are for users who are accessing SPNEGO-protected resources from a browser and must be completed on the client computer. ", can you change " users who are accessing SPNEGO-protected resources " to " users who access SPNEGO-protected resources"

**Comment by Charlotte-Holt** [comment]
@chirp1 Topic at https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/configuring-spnego-authentication.html.

**Comment by Charlotte-Holt** [comment]
Comment from @wrodrig:

First of all I really like the new approach to this KC. Is really easy to follow and it does a good job explaining the concepts and what steps are needed for the customer to configure it. Really Good Job!

I'm still reading through the information but I wanted to briefly talk about the SPNEGO configuration article.
https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/configuring-spnego-authentication.html

First of all, I love that the steps to generate the keytab file and configure the Browser are clearly outlined. I'm sure that customers are also going to love it. One suggestion is that I think that it would be awesome to add is the Liberty Configuration side as well. The reason why I recommend this, is because it makes it a lot easier for customers to know what they need to do and they would know that once they are done with the documentation, they can proceed to configure the next thing.

I have some thoughts on how it could be done. For example, maybe at the steps at bottom of the same page. If this is not possible, could the team consider adding an arrow, or a large obvious hyperlink that says "Wait there is more...". Basically something that our customers will know that they are not done configuring SPNEGO.

I think that would help a lot and will really enhance this documentation for both our customers and our support team.

Thank you again so much! Really appreciate it.

**Comment by Charlotte-Holt** [comment]
Comment from @wrodrig:

I found something else that might help the consideration of my proposal. I was looking at this link:

https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/single-sign-on.html

In the SPNEGO Section it mentions this

For more information, see Configuring SPNEGO authentication in Open Liberty.

Which redirects to the link that this issue is talking about.

https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/configuring-spnego-authentication.html

If we were to keep the documentation as it is, then the statement Configuring SPNEGO authentication in Open Liberty. will not be accurate since the above link only talks about configuring KDC and the browser. There is no mention of Open Liberty server configuration for SPNEGO. This can result in confusion for our clients.

Thanks again for your consideration.

**Comment by Charlotte-Holt** [comment]
Updates made:

- "You can enable single sign-on (SSO) for HTTP requests by using Simple and Protected GSS-API Negotiation Mechanism (SPNEGO) web authentication for Open Liberty." **-->** "You can enable single sign-on (SSO) for HTTP requests by using Simple and Protected GSS-API Negotiation Mechanism (SPNEGO) web authentication." - **DQTI, Chapter 6, Clarity, Eliminate wordiness**
- "What to do next" **-->** "Verifying that SPNEGO is working" - **DQTI, Chapter 7, Concreteness, Set the context for scenarios**

**Comment by Charlotte-Holt** [comment]
@wrodrig I incorporated your feedback. This topic is ready for you to test when you can: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/configuring-spnego-authentication.html. Thx!

**Comment by Charlotte-Holt** [comment]
Comment from @utle:

It's better to use the same host name and realm name with other examples. I think we want to change the following from:

```
-Djava.security.krb5.kdc=myKdcMachine.example.com
-Djava.security.krb5.realm=EXAMPLE.COM
```

To:

```
-Djava.security.krb5.kdc=myAdMachine.example.com
-Djava.security.krb5.realm=MYDOMAIN.EXAMPLE.COM
```

**Comment by Charlotte-Holt** [comment]
@utle I incorporated your feedback. Thx!

**Comment by wrodrig** [comment]
@Charlotte-Holt 

Here some of my feedback Charlotte. Again thank you so much to you and the team for all the hard work!

### Under  Creating a Kerberos service principal name and keytab file
 
**Step 1**
**Suggestion:**

Could you specify the name of the user account myLibertyMachine_http?

Basically instead of

`Create a user account for the Open Liberty server. This account is used to map to the Kerberos service principal name (SPN).`

Something like this:

`Create a user account for example myLibertyMachine_http for the .....`
 
Reason for this suggestion is because in Step 1 we referred it as “account to map the kerberos service principal name” If a customer did not used _http in the name, it can be confusing.

**Suggestion 2**
Can you make it clear for customers that for this account they should use the <shorthostname>_http
 
 
**Step 3**
Create the Kerberos keytab file by running the Microsoft ktpass command. The default name for the keytab file is krb5.keytab. The following example shows how to run the ktpass command:
 
Original Command:
`ktpass -out krb5.keytab -princ HTTP/myLibertyMachine.example.com@MYDOMAIN.EXAMPLE.COM -mapUser myLibertyMachine_http -mapOp set -pass security -crypto RC4-HMAC-NT -ptype KRB5_NT_PRINCIPAL`
 
**Fix the password**
`ktpass -out krb5.keytab -princ HTTP/myLibertyMachine.example.com@MYDOMAIN.EXAMPLE.COM -mapUser myLibertyMachine_http -mapOp set -pass **<myLibertyMachine_http-password>** crypto RC4-HMAC-NT -ptype KRB5_NT_PRINCIPAL`

**Suggestion** 
`ktpass -out krb5.keytab -princ HTTP/myLibertyMachine.example.com@MYDOMAIN.EXAMPLE.COM -mapUser myLibertyMachine_http -mapOp set -pass security -crypto **RC4-HMAC-NT** -ptype KRB5_NT_PRINCIPAL`
Because RC4-HMAC-NT is not a strong encryption.  Can we add a note that says that if you use this in production, you may want to consider stronger encryption type.  Need to find the article that talks about this. Hardening encryption article in KC.
 
 
Step 4
Original Command:
`ktpass -in myOtherKrb5.keytab -out krb5.keytab -princ HTTP/myLibertyMachine.example.com@MYDOMAIN.EXAMPLE.COM -mapUser myLibertyMachine_http -mapOp set -pass security -crypto RC4-HMAC-NT -ptype KRB5_NT_PRINCIPAL`
 
**Fix the password**
The command should call for the kdc short name. Also update the user account.
`ktpass -in myOtherKrb5.keytab -out krb5.keytab -princ HTTP/myLibertyMachine.example.com@MYDOMAIN.EXAMPLE.COM -mapUser myLibertyMachine_http -mapOp set -pass **<myLibertyMachine_http-password>** -crypto RC4-HMAC-NT -ptype KRB5_NT_PRINCIPAL`
 
 
### Under: Copying the Kerberos keytab and configuration files
 
**Suggestion**
Step 2 Can we provide a sample krb.conf file?

Here is a sample that could be used from the KC
https://www.ibm.com/support/knowledgecenter/en/SSEQTP_8.5.5/com.ibm.websphere.base.doc/ae/rsec_SPNEGO_config_krb5.html
 
We could have used the above link as a reference but we need to update the KRB.CONF file to remove `des-cbc-md5`. 
 
The following could serve as an example for a krb.conf file valid for a Windows OS

```
[libdefaults]
 default_realm = MYDOMAIN.EXAMPLE.COM
        default_keytab_name = FILE:c:\winnt\krb5.keytab
        default_tkt_enctypes = rc4-hmac aes256-cts-hmac-sha1-96
        default_tgs_enctypes = rc4-hmac aes256-cts-hmac-sha1-96
[realms]
        MYDOMAIN.EXAMPLE.COM= {
              kdc = host1.example.com:88
              default_domain = example.com        
}
[domain_realm]
        .example.com = MYDOMAIN.EXAMPLE.COM


```
Let me know if you have any question. 


Also thanks @utle because he reviewed my suggestions as well :)

**Comment by Charlotte-Holt** [comment]
@wrodrig I've addressed your feedback. Please let me know if you have any questions. When the doc has been tested successfully, please add a comment and the **doc tested** label. Thanks! https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/configuring-spnego-authentication.html

**Comment by wrodrig** [comment]
I reviewed the documentation and followed the steps for configuring the keytab file. I also compared the steps to configure the browser and it looks good. Thanks for the hard work!

**Comment by Charlotte-Holt** [comment]
Published at https://openliberty.io/docs/20.0.0.11/configuring-spnego-authentication.html. Still requires final editorial review.

**Comment by chirp1** [comment]
Hi Charlotte, the article is full of useful info for customers! As I mentioned in the slack with you and David, let's make some changes to the structure and then use what we come up with in the guidance for task topics.

- [x] Start by making the headers steps and the steps sub-steps. When you turn the headers into steps, replace the gerunds with the command form of the verbs.
- [x] Remove "by doing the following things:" through "to properly configure SPNEGO with Open Liberty.".
- [ ] Have only the command on the first line of a step or sub-step. Start the supporting information immediately following the step or sub-step. For instance, for step 1of the first heading, move "This account is used..." to the line after the command line. 
- [x] The topic is missing a key reference to "domain controller" that was mentioned in the original WebSphere Liberty topic. Find the missing reference and add it to your topic. 

Let's start with these mainly structural changes. Then, after they are made, I'll go through the topic in more detail.

**Comment by Charlotte-Holt** [comment]
@chirp1 Thanks for your feedback. I updated the draft: https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.3/configuring-spnego-authentication.html.

**Comment by chirp1** [comment]
Hi Charlotte,
Nice! You streamlined the original topic and made the new topic much more succinct.
I'm giving you comments through the end of step 2 while I continue to review the other steps.
- You have the step commands on a single line and the supporting information below it, for example:
1.Create a Kerberos service principal name and keytab file. 
For the substep commands, do the same thing. For example:
Change: "a. Create a user account, for example, myLibertyMachine_http, for the Open Liberty server. This account is used to map to the Kerberos service principal name (SPN)." to:
a. Create a user account, for example, myLibertyMachine_http, for the Open Liberty server.
Then put the "This account is used to map to the Kerberos service principal name (SPN)." after it.
- To make 1d more like a command, change "If you have multiple SPNs, you need to merge your keytab files." to "If you have multiple SPNs, merge your keytab files. 

- For "Copy the Kerberos keytab and configuration files." I think that the wording could be a little different. ****
- For "The default location of the file is the same directory as the Kerberos configuration file, which varies depending on the operating system:  ", I think "which" should be "but". Otherwise "which" seems to go with "Kerberos configuration file", when I think we want it to apply to "default location".
- What you have in steps 2 a and b (kerberos keytab and config file) and step 3 a and b (SPNEGO authentication)  were all under step 2 of the original topic. I think that you should combine them into step 2 again because step two is about setting things up on the Liberty server (Whereas in the original topic step 1 is about doing things on the Microsoft domain controller and step 3 is about configuring the client application.) You could go back to wording similar to the wording on the original step 2.
- The default paths in 2a are a little confusing because although they include the paths for the kerberos keytab file and the kerberos configuration file, the file name listed is just the kerberos configuraiton file. And the substep is missing a reference to the default krb5.keytab . You could, for example, copy the two paths and also put them under the kerberos configuration section, mentioning that they are the default paths. You can could then in 2a  change krb5.ini  and krb5.conf with krb5.keytab on both paths.
- In 2b, update the example code as the code says "c:\winnt\krb5.keytab". Replace the "winnt" subdirectory with the "windows" subdirectory because your more modern topic doesn't reference "winnt" otherwise. winnt seems to be an older path. I did some kerberos updates recently and used windows in the path.

**Comment by Charlotte-Holt** [comment]
@chirp1 Updated:

- [x] You have the step commands on a single line and the supporting information below it, for example:
1.Create a Kerberos service principal name and keytab file.
For the substep commands, do the same thing. For example:
Change: "a. Create a user account, for example, myLibertyMachine_http, for the Open Liberty server. This account is used to map to the Kerberos service principal name (SPN)." to:
a. Create a user account, for example, myLibertyMachine_http, for the Open Liberty server.
Then put the "This account is used to map to the Kerberos service principal name (SPN)." after it.
- [x] To make 1d more like a command, change "If you have multiple SPNs, you need to merge your keytab files." to "If you have multiple SPNs, merge your keytab files.
- [x] For "Copy the Kerberos keytab and configuration files." I think that the wording could be a little different. ****
- [x] For "The default location of the file is the same directory as the Kerberos configuration file, which varies depending on the operating system: ", I think "which" should be "but". Otherwise "which" seems to go with "Kerberos configuration file", when I think we want it to apply to "default location".
- [x] What you have in steps 2 a and b (kerberos keytab and config file) and step 3 a and b (SPNEGO authentication) were all under step 2 of the original topic. I think that you should combine them into step 2 again because step two is about setting things up on the Liberty server (Whereas in the original topic step 1 is about doing things on the Microsoft domain controller and step 3 is about configuring the client application.) You could go back to wording similar to the wording on the original step 2.
- [x] The default paths in 2a are a little confusing because although they include the paths for the kerberos keytab file and the kerberos configuration file, the file name listed is just the kerberos configuraiton file. And the substep is missing a reference to the default krb5.keytab . You could, for example, copy the two paths and also put them under the kerberos configuration section, mentioning that they are the default paths. You can could then in 2a change krb5.ini and krb5.conf with krb5.keytab on both paths.
- [x] In 2b, update the example code as the code says "c:\winnt\krb5.keytab". Replace the "winnt" subdirectory with the "windows" subdirectory because your more modern topic doesn't reference "winnt" otherwise. winnt seems to be an older path. I did some kerberos updates recently and used windows in the path.

**Comment by chirp1** [comment]
Hi Charlotte, here are my remaining comments. They are for your original steps 3 and 4:
- Do we still leave the feature in parentheses or should it be removed: SPNEGO feature (spnego-1.0) ?
- Include a reference to "myClientMachine.example.com " in step 4 since you mentioned it as a resource in "Before you begin". Something like- change "...completed on the client computer. " to "...completed on the myClientMachine.example.com client computer. "
- Change "Ensure that browser supports SPNEGO ..." to "Ensure that the browser supports SPNEGO ...". (Add "the".)

**Comment by Charlotte-Holt** [comment]
@chirp1 Updated: 

- [x] Do we still leave the feature in parentheses or should it be removed: SPNEGO feature (spnego-1.0) ?
- [x] Include a reference to "myClientMachine.example.com " in step 4 since you mentioned it as a resource in "Before you begin". Something like- change "...completed on the client computer. " to "...completed on the myClientMachine.example.com client computer. "
- [x] Change "Ensure that browser supports SPNEGO ..." to "Ensure that the browser supports SPNEGO ...". (Add "the".)

**Comment by Charlotte-Holt** [comment]
Latest draft: https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.3/configuring-spnego-authentication.html

**Comment by chirp1** [comment]
Hi Charlotte,
- For step 2a, add wording similar to "The default name for this file is krb5.keytab.".

In the original topic, step 1 is for the Microsoft domain controller (myAdMachine.example.com, step 2 is for the Liberty server machine (myLibertyMachine.example.com), and step 3 is about client application machine (myClientMachine.example.com). We want to keep that grouping so that customers have a sense of what they are doing, and consequently those three steps. Also, each step mentions the machine in the step command. I'd like us to do the same as having it in the step makes what machine the customers is working with more obvious.
- Change step 1 to something like "On the myAdMachine.example.com domain controller , create a Kerberos service principal name and keytab file.".
- In your topic, combine step2 and step3 to form step 2. What you have as step 2 becomes step 2a. What you have for step 3 becomes 2b.
- Make the step 2 something like "On the Open Liberty server, myLibertyMachine.example.com, set up the Kerberos keytab and configuration files and SPNEGO web authentication."
- Make step 3 something like "Configure the client application on the myClientMachine.example.com client application computer.".

**Comment by Charlotte-Holt** [comment]
- [x] For step 2a, add wording similar to "The default name for this file is krb5.keytab.".
- [x] In the original topic, step 1 is for the Microsoft domain controller (myAdMachine.example.com, step 2 is for the Liberty server machine (myLibertyMachine.example.com), and step 3 is about client application machine (myClientMachine.example.com). We want to keep that grouping so that customers have a sense of what they are doing, and consequently those three steps. Also, each step mentions the machine in the step command. I'd like us to do the same as having it in the step makes what machine the customers is working with more obvious.
- [x] Change step 1 to something like "On the myAdMachine.example.com domain controller , create a Kerberos service principal name and keytab file.".
- [x] In your topic, combine step2 and step3 to form step 2. What you have as step 2 becomes step 2a. What you have for step 3 becomes 2b.
- [x] Make the step 2 something like "On the Open Liberty server, myLibertyMachine.example.com, set up the Kerberos keytab and configuration files and SPNEGO web authentication."
- [x] Make step 3 something like "Configure the client application on the myClientMachine.example.com client application computer.".

**Comment by chirp1** [comment]
The updates look good!

**Comment by Charlotte-Holt** [comment]
Merged to `vNext` in https://github.com/OpenLiberty/docs/pull/3727 and added to the KC spreadsheet
