### ISSUE TITLE
Example config for the Cloudant Integration feature

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#1567]
Enhance the generated feature doc for the Cloudant Integration feature: https://openliberty.io/docs/ref/feature/#cloudant-1.0.html. 

**Resources**:

- https://openliberty.io/blog/2019/09/13/testing-database-connections-REST-APIs.html
- https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_couchdb_configdriver.html

**Comment by Charlotte-Holt** [comment]
First draft is at https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/reference/feature/cloudant-1.0.html. Working with @nmittles to flesh out the example on validating database connections.

**Comment by Charlotte-Holt** [comment]
As discussed with @nmittles and @aguibert, the example from https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_couchdb_configdriver.html isn't a critical example that we'll include in the feature config. Need to determine whether the info from https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_couchdb_config.html should come over in task form or as feature config. 

@nmittles Can you review the example in https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/reference/feature/cloudant-1.0.html? Thx!

**Comment by Charlotte-Holt** [comment]
@lauracowen https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/reference/feature/cloudant-1.0.html is ready for your review!

**Comment by lauracowen** [comment]
Thanks. Signing off.

**Comment by Charlotte-Holt** [comment]
Requesting a peer review from @ManasiGandhi

**Comment by ManasiGandhi** [comment]
@Charlotte-Holt The topic looks good! One edit suggestion:

**First Paragraph**

“This feature enables connections to Cloudant by providing a connector instance configured in the server configuration, which can be injected or accessed through JNDI. Applications use the Cloudant client library to utilize the connector instance.”

I’m aware that you may not have access to change the autogenerated first paragraph, but if there’s anything that can be done or an issue opened, I had a few suggestions. Could you add a noun after “Cloudant” like “Cloudant service” maybe. Also, Java Naming and Directory Interface (JNDI), instead of  “JNDI”, in the next sentence. In the sentence, “Applications use the Cloudant client library to utilize the connector instance.”, could you change “utilize” to “use”.

**Comment by Charlotte-Holt** [comment]
@ManasiGandhi I addressed your feedback. Thanks! https://draft-openlibertyio.mybluemix.net/docs/21.0.0.2/reference/feature/cloudant-1.0.html

**Comment by chirp1** [comment]
Hi Charlotte,
I've been studying the config example, and the blog post and topic mentioned at the top of this issue. Here are my comments:
- For " Applications use the Cloudant client library to use the connector instance.", would "access" work in place of the second "use". It's the "use" that had been "utilize" previously.
- Change the "Viewing and validating Cloudant databases" to the new style for the configuration example titles.
- I found the sentences in the example confusing because the sentences are more or less lifted from the blog, but some of the context is missing.
- I don't know if I have this quite right, but I think that when the <feature>restConnector-2.0</feature> is specified in the server.xml, then any configuration element can be viewed, with the following syntax: /ibm/api/config/{configElementName}/{uid}, which results in the configuration endpoint.
- However, if a configuration element that allows for validation is specified in the server.xml file, then that element can be both viewed and validated. So, the Cloudant configuration element can be both viewed and validated by using this syntax: /ibm/api/validation/{configElementName}/{uid}, which results in the validation endpoint.
- The two endpoints require authentication with the Liberty server. So, the appSecurity-2.0 feature needs to be specified in the server.xml file. Your second sentence in the example follows the first sentence, which discusses validation. So, your second sentence seems to imply that you need the appSecurity-2.0 feature just for validation, but I think you need the appSecurity-2.0 feature for viewing, too, and need to say that in the example. 
- And so, I think you should move the last two sentences, which are about the role access, by the authentication and appSecurity-2.0 feature discussion as the role access goes with authentication.
- You say, because the Test blog said, "...while the myCloudantDB database can be tested by using container authentication....", but I think "tested" should be replaced with "validated" since I think that is what is going on given "validate" in https://localhost:9443/ibm/api/validation/cloudantDatabase/myCloudantDB?auth=container.

**Comment by Charlotte-Holt** [comment]
@chirp1 Thanks for the review! I made the following updates:

- [x] For " Applications use the Cloudant client library to use the connector instance.", would "access" work in place of the second "use". It's the "use" that had been "utilize" previously. - **Opened doc bug #3625** 
- [x] Change the "Viewing and validating Cloudant databases" to the new style for the configuration example titles. - **Updated**
- [x] I found the sentences in the example confusing because the sentences are more or less lifted from the blog, but some of the context is missing. - **No action required**
- [x] I don't know if I have this quite right, but I think that when the restConnector-2.0 is specified in the server.xml, then any configuration element can be viewed, with the following syntax: /ibm/api/config/{configElementName}/{uid}, which results in the configuration endpoint. - **No action required**
- [x] However, if a configuration element that allows for validation is specified in the server.xml file, then that element can be both viewed and validated. So, the Cloudant configuration element can be both viewed and validated by using this syntax: /ibm/api/validation/{configElementName}/{uid}, which results in the validation endpoint. - **No action required**
- [x] The two endpoints require authentication with the Liberty server. So, the appSecurity-2.0 feature needs to be specified in the server.xml file. Your second sentence in the example follows the first sentence, which discusses validation. So, your second sentence seems to imply that you need the appSecurity-2.0 feature just for validation, but I think you need the appSecurity-2.0 feature for viewing, too, and need to say that in the example. - **No action required**
- [ ] And so, I think you should move the last two sentences, which are about the role access, by the authentication and appSecurity-2.0 feature discussion as the role access goes with authentication. - **I thought about this and decided to leave this where it is since it talks about the endpoints that were just mentioned in the above paragraph. Let me know if you still think that I need to change it.** 
- [x] You say, because the Test blog said, "...while the myCloudantDB database can be tested by using container authentication....", but I think "tested" should be replaced with "validated" since I think that is what is going on given "validate" in https://localhost:9443/ibm/api/validation/cloudantDatabase/myCloudantDB?auth=container.

**Comment by chirp1** [comment]
Hi Charlotte,
I think in the last two paragraphs of the example you can make some terms consistent. I see "URL" in the first paragraph and "endpoint" in the second one. How about if you google what a REST endpoint is? I saw a KC topic with some examples.  I believe that the URLs are called endpoint URLs. Some mentions of "endpoint" might be OK in the last two paragraphs while others should likely be "endpoint URL". Make other changes as appropriate so that the paragraphs read correctly.

**Comment by Charlotte-Holt** [comment]
@chirp1 Update made and back with you. Thanks! https://draft-openlibertyio.mybluemix.net/docs/21.0.0.2/reference/feature/cloudant-1.0.html

**Comment by chirp1** [comment]
The updates look good!

**Comment by Charlotte-Holt** [comment]
Merged to `vNext` in https://github.com/OpenLiberty/docs/pull/3642

**Comment by chirp1** [comment]
Note: We changed "You can validate Cloudant database connections..." to "You can view and validate Cloudant database connections ..." based on my previous bulleted comments.
