### ISSUE TITLE
Example config for the Java Servlets feature

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#1570]
Enhance the [Java Servlets feature doc](https://openliberty.io/docs/ref/feature/#servlet-4.0.html) by adding example config. 

**Resources**:

- https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/cwlp_servlet40_http2.html

**Comment by Rwalls1** [comment]
Link to first draft: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/reference/feature/servlet-4.0.html

**Comment by Rwalls1** [comment]
@arkarkala Please review: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/reference/feature/servlet-4.0.html

**Comment by chirp1** [comment]
@Rwalls1 Hi Richard, Have you figured out your technical review person and negotiated a return date for your topic? Would you document the info in this issue?

**Comment by Rwalls1** [comment]
@pmd1nh @pnicolucci Please review, are there any other config examples that are essential or important to include for this feature: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/reference/feature/servlet-4.0.html

**Comment by pmd1nh** [comment]
I'm not aware of any explicit configure for the servlet 4.0 feature.  I reviewed the Servlet Spec 4.0, section "A.1 Changes Since Servlet 3.1" to verify if anything need to be configured.  There is none that is required from the server's perspective.

**Comment by Rwalls1** [comment]
@billw1024 @wtlucy Please review: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/reference/feature/servlet-4.0.html

**Comment by billw1024** [comment]
That page seems a bit disjointed to me.  First it talks about enabling the Servlet 4.0 feature, and then it gives and example of how to change if the http protocol should be enabled for 2.0 or just use 1.1 only.  While the protocol is related to the Servlet 4.0 feature, I don't know really what the "Example" is suppose to be showing the reader.  If the intent is that one can manipulate servlet config options, then I'm not sure that the http protocol version setting best shows that. 

It would be nice to show somewhere how to manipulate the http version between 2.0 and 1.1, just not sure putting it in an "example" under setting the Servlet 4.0 feature makes it easy to find then.

Guess this gets down to what info is trying to be conveyed by the example on this particular page.

**Comment by Rwalls1** [comment]
@lauracowen Do you have a suggestion on how to best approach identifying which examples to include for this feature?, based on the feedback provided there doesn't appear to be a basic/essential configuration and the current included examples don't seem to be valuable as currently presented.

**Comment by lauracowen** [comment]
@billw1024 The aim is to enhance the generated topic about the feature with examples of commonly needed configuration. However, if there is no configuration needed (as @pmd1nh's comment suggests), we can leave it out from this page.

According to the [Liberty KC page](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/cwlp_servlet40_http2.html) from which @Rwalls1 took this information, there seems to be a need to show how to enable/disable the HTTP/2 protocol when using servlet 4.0 or 3.1. Is this not useful to provide?

Regarding servlet 2.0 and 1.1, neither of those versions are provided in the generated feature doc - I assume that's because they're not supported by Open Liberty - is that correct?

**Comment by billw1024** [comment]
@lauracowen , @Rwalls1 
we do explain http/2 and sevlet 3.1 and 4.0 configuration here:
https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_config_servlet40.html
and here:
https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/cwlp_servlet40_http2.html

no one I know of uses servlet 2.0 or 1.1 and I don't know if we have received a question on that for years now.

**Comment by lauracowen** [comment]
@billw1024 We're moving info out of the KC format to the Open Liberty docs format. So if that's important info, we need to doc it in the Open Liberty docs. However, from the point of view of this particular topic that @Rwalls1 is working on, it seems we don't need any additional config examples (beyond enabling the feature which is already in the generated topic). The KC task topic you mention doesn't have any config beyond just enabling the feature (I guess the same goes for Servlet 3.1?).

That KC task topic you mentioned, also talks about conflicts between certain combinations of features. Is any of that information _not_ covered by the explanation in here: https://www.openliberty.io/docs/20.0.0.8/reference/feature/feature-overview.html#_combining_features ? If so, what would we need to add to that section to make sure we do cover it for the combinations with Servlet feature?

Going back to the HTTP/2 enabling/disabling config examples that @Rwalls1 had added to the servlet feature topic (from the other KC topic you mentioned: https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/cwlp_servlet40_http2.html), if that info is relevant to Open Liberty, it seems appropriate for Richard to add it in the way he currently has (though maybe some of the wording needs fixing if you think it seems a bit awkward?), or maybe just the version-specific info on the specific 4.0 or 3.1 pages. I think we would also insert a sentence before his "Overriding the default HTTP/2....etc" heading saying that the servlet feature is configured just by enabling it, so that it's clear the "overriding HTTP/2..." examples are not necessary for just a basic configuration.

**Comment by billw1024** [comment]
In the new document referenced, I don't think mentioning HTTP/2 is necessary.  The user can configure for Servlet 4.0 or for Servlet 3.1,  the fact that Servlet 3.1 does Http/1.1 by default,  and that Serlvet 4.0 does Http/2 (which will also handle http/1.1 traffic) is a detail that most readers need not be aware of.

**Comment by lauracowen** [comment]
@billw1024 Ah cool - thanks, that's the kind of info that's really helpful to know - we'd like to avoid overloading readers with info that they don't really need to be aware of. Sounds like that topic that @Rwalls1 is working on doesn't need any config examples then.

Beyond this topic, regarding my question about feature combination conflicts, is there anything we need to do:

> That KC task topic you mentioned, also talks about conflicts between certain combinations of features. Is any of that information _not_ covered by the explanation in here: https://www.openliberty.io/docs/20.0.0.8/reference/feature/feature-overview.html#_combining_features ? If so, what would we need to add to that section to make sure we do cover it for the combinations with Servlet feature?

**Comment by billw1024** [comment]
@lauracowen I don't know of any other information to add to the "combining_features" section.

**Comment by lauracowen** [comment]
@billw1024 Okay, that's fine. Thanks for your help with this.

@Charlotte-Holt Could you update the KC spreadsheet to note that everything relevant's taken from those KC topics (maybe link to this issue for details?).

@Rwalls1 I think you're done with this one now. :)

**Comment by Rwalls1** [comment]
@lauracowen Thanks, I have removed the examples. I will close the issue

**Comment by chirp1** [comment]
The topic hasn't been through editorial review. I'm reopening it.

**Comment by Rwalls1** [comment]
@chirp1 This topic will not require an editorial review as examples will not be included for this feature after further assessment that is mentioned in the discussion above.

**Comment by chirp1** [comment]
OK
