### ISSUE TITLE
Create server and feature config topics for "Basics" section of the nav

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#1572]
We need to create overview sections for the [server config](https://openliberty.io/docs/ref/config/) and [feature config](https://openliberty.io/docs/ref/feature/) topics to include in the **Basics**-type section in the new OL nav. We could possibly use include statements to pull the necessary info into high-level topics for the **Basics** section and link to the complete topics in the respective **Server config** and **Feature** sections of the nav.

**Comment by Charlotte-Holt** [comment]
For this topic, write a single basics topic that introduces server config and features. Include information like:

- There is an XML file - what is the format
- You can add and remove features - convenience/umbrella features
- Really basic config example
- Maybe include information about the `bootstrap.properties` file
- A high level explanation of variable substitution - when it would be useful?
- It's possible to separate config into multiple files and use include files 
- Dynamic updates - if you make changes to the server.xml config file, it automatically gets updated 
- You add features to the Liberty kernel
- You can combine features, sometimes different versions conflict

**Comment by Charlotte-Holt** [comment]
@lauracowen First draft of this is at https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/server-config-feature-intro.html. I tried doing mostly includes from the more detailed topics to avoid having duplication of the higher level material, but it may need fleshing out in some places? Let me know your thoughts :)

**Comment by lauracowen** [comment]
I've taken another look at the Why Open Liberty? topic. I think we can cover the very basics of this in there instead of as a separate topic. Basically, just that you can add/remove features modularly and it's easy to do that with the XML configuration. I think that's probably all that's needed as an intro.

I think the reason for this issue was just to have something about the features and config in the Basics section of the docs for intro purposes. So I think that would satisfy this requirement. Could maybe close this issue if you're happy to?

**Comment by Charlotte-Holt** [comment]
I'm good to incorporate this into the "About Open Liberty" topic. Closing this issue.
