### ISSUE TITLE
Asynchronous programming w/ MicroProfile Fault Tolerance

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#1645]
Rework information from the [Asynchronous programming made resilient with MicroProfile Fault Tolerance: Part 1](https://openliberty.io/blog/2020/06/04/asynchronous-programming-microprofile-fault-tolerance.html) and [Asynchronous programming made resilient with MicroProfile Fault Tolerance: Part 2](https://openliberty.io/blog/2020/06/05/asynchronous-programming-microprofile-fault-tolerance-part-2.html) blog posts into a new concept topic. 

**SME**: Joseph Cass and Andrew Rouse

**Comment by Charlotte-Holt** [comment]
@Azquelt @Joseph-Cass Please review https://draft-openlibertyio.mybluemix.net/docs/20.0.0.10/async-programming-fault-tolerance.html. Let me know of any necessary updates. Thanks!

**Comment by lauracowen** [comment]
I like it. It's a bit long but I think it works as there are plenty of examples and illustrations. The sections are all relevant and it's nicely written. If the interactions section were longer, I'd be tempted to break it out into a separate topic (partly for SEO reasons) but it's not long enough for that.

The only comment that came to me is that the first sub-heading could drop the "About" (just "The @Asynchronous annotation"). And maybe remove some of the blank lines in the code examples (as long as they don't look less clear without).

I'm happy with this from a format/style/approach perspective and will sign it off.

I guess we still don't have any guides that demonstrate any of this? Would be good to be able to link out to one. I've added a comment to the guides issue.

**Comment by Charlotte-Holt** [comment]
Updated doc with feedback from @lauracowen and @Joseph-Cass: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.10/async-programming-fault-tolerance.html

**Comment by Charlotte-Holt** [comment]
@Azquelt This is ready for your review: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/async-programming-fault-tolerance.html.

**Comment by Charlotte-Holt** [comment]
Feedback from @Azquelt:

![Async doc feedback](https://user-images.githubusercontent.com/48996799/93787288-4bc9c200-fbfe-11ea-8a98-92418969ae56.png)

**Comment by lauracowen** [comment]
There is a new guide that shows `.rx()`: https://openliberty.io/guides/reactive-rest-client.html

**Comment by Charlotte-Holt** [comment]
@Azquelt I've incorporated your feedback. Please take another look when you have a chance. https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/async-programming-fault-tolerance.html

**Comment by Azquelt** [comment]
Looks good :+1:

**Comment by Charlotte-Holt** [comment]
Thanks, @Azquelt. Requesting a peer review from @ManasiGandhi.

**Comment by ManasiGandhi** [comment]
@Charlotte-Holt #peer review The topic looks good! A few edit suggestions:

- **Short description**

- [x] Change,

“MicroProfile Fault Tolerance provides different annotations that can help you deal with failure.”
To
“MicroProfile Fault Tolerance provides annotations that can help you deal with failure.”

- [x] Change,

“Combining the @Asynchronous Fault Tolerance annotation with the CompletionStage interface provides ways for you to write asynchronous code that is resilient to faults.”
To,
“You can combine the @Asynchronous Fault Tolerance annotation with the CompletionStage interface to write asynchronous code that is resilient to faults”, for conciseness.

- **The @Asynchronous annotation**

- [x] Change,

“A method that is annotated with the @Asynchronous annotation runs asynchronously, which means that the method doesn’t run immediately on the main thread when it’s called. Instead, it runs sometime later, usually on another thread.”
To,
“A method that is annotated with the @Asynchronous annotation runs asynchronously, which means that the method doesn’t run immediately on the main thread when called. Instead, the method runs sometime later, usually on another thread.”

- [x] In “To use the @Asynchronous annotation, add the annotation to a method, and ensure that the annotated method returns either a CompletionStage object or a Future object.”, can you remove the links from object in CompletionStage object and Future object?

- [x] “Usually when a method is called, it returns a result. However, when a method is annotated with the @Asynchronous annotation, Fault Tolerance intervenes.” Do we need to capitalize fault tolerance, also throughout the topic?

- [x] Change,

“When the annotated method is called, Fault Tolerance schedules the method to run later on a different thread. Then, it returns a CompletionStage or Future object.”
To,
“When the annotated method is called, fault tolerance schedules the method to run later on a different thread and returns a CompletionStage or Future object.”

- Fault Tolerance applied to an asynchronous API call

- [ ] Suggested change from,

“Without the @Asynchronous annotation, the other Fault Tolerance annotations don’t behave as you might expect.”
To,
“Without the @Asynchronous annotation, the other Fault Tolerance annotations don’t behave as expected.”
Differences in execution flow with the @Asynchronous annotation

- [x] In “After the method returns, the result from the method is then propagated to the CompletionStage or Future object so that the caller can access it.” Is it “after the method returns” or “after the method runs”?

- [x] Also, can you change, “the result from the method is then propagated to the CompletionStage or Future object so that the caller can access it”

To,
“the result from the method is propagated to the CompletionStage or Future object so that the caller can access it” for conciseness.

- **Interaction with the @Bulkhead annotation**

- [x] Change,

“Otherwise, it’s added to a queue.”
To,
“Otherwise, the method is added to a queue.”

- Interaction with the @Timeout annotation

- [x] Change,

“Even if the method is still running, the method is running on another thread so you can signal to a different thread that the result is ready.”
To,
“Even if the method is still running, it is running on another thread so you can signal to a different thread that the result is ready.”

- **Limitations of returning a Future object**

- [x] In this sentence, “Without a callback, Fault Tolerance is applied around the method call, not around the method result. Because a Future object doesn’t have a callback, the following issues arise when you implement Fault Tolerance:” the words call and result are italicized, are they compliant with accessibility.

- [x] Also, in the first bullet point “Without a callback, Fault Tolerance is applied around the method call, not around the method result. Because a Future object doesn’t have a callback, the following issues arise when you implement Fault Tolerance:” the word call is not italicized. Can you make them consistent?

**Comment by Charlotte-Holt** [comment]
@ManasiGandhi Thx! The only change I didn't make was: 

>Suggested change from:
“Without the @asynchronous annotation, the other Fault Tolerance annotations don’t behave as you might expect.”
To:
“Without the @asynchronous annotation, the other Fault Tolerance annotations don’t behave as expected.”

I like the way it read as I had it, so I left it. Let me know if this is an issue!

**Comment by Azquelt** [comment]
> “Without the @asynchronous annotation, the other Fault Tolerance annotations don’t behave as you might expect.”
> To,
> “Without the @asynchronous annotation, the other Fault Tolerance annotations don’t behave as expected.”

I'd leave this as-is. The fault tolerance annotations do behave exactly as expected (and as specified), but in the example given, they're not doing what is intended. We want to say that the user may be surprised by the behaviour, not that the behaviour is incorrect.

Essentially, `@Retry` retries a method until it doesn't throw an exception. However, in the example the user wants to retry until the method returns a `CompletionStage` which completes successfully. `@Retry` and `@Asynchronous` together are needed to accomplish this.

The text could possibly be rearranged to say something like "here, `@Retry` alone won't do what we intend", but I think it would be incorrect to say that the annotations don't behave as expected.

**Comment by Charlotte-Holt** [comment]
@Azquelt Agreed. I left that one unchanged.

**Comment by Charlotte-Holt** [comment]
@chirp1 updated link:https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/async-programming-fault-tolerance.html

**Comment by chirp1** [comment]
Hi Charlotte, for the two graphics, I see that you have alternate text for both, which we need for accessibility. So, that is great! Would you also through text describe the steps in the flow of execution for each graphic? That way a person using JAWS can follow the graphic since JAWS can't read what is going on graphics. The wording can be simple enough, going from one step to the next. OR, For the second diagram, there's "The following changes in execution flow occur when you use the @Asynchronous annotation:" and then the four bullets. That sort of explains what is going on in the diagram. Maybe that sentence and bullets are OK for the second diagram (or we might want to change to something like "The diagram shows the following changes in execution...". And, so maybe the first diagram needs a similar explanation.

**Comment by chirp1** [comment]
Hi Charlotte, Another nicely written topic!
Here are my comments:
- The first blog introduces several fault tolerance annotations, but your topic doesn't. How about if we introduce @Retry since you use it in an example? Change "...the other fault tolerance annotations don’t behave ..." to "...the other fault tolerance annotations, such as @Retry, don’t behave ...".
- Change "After the clientDemo() method is called,..." to "After the clientDemo() method is called without any annotations,...".
- For "...then the @Retry annotation is applied after the CompletionStage object completes, rather than when the method returns:  ...", the sentence uses "after" and then "when". How about if we are consistent and use "when the CompletionStage object" instead of "after"?as the two words are slightlyI see in the blog, part 1 If we add the @Asynchronous annotation and the method returns a CompletionStage, then the Fault Tolerance logic gets applied when the CompletionStage completes, rather than when the method returns: ". This statement in the blog uses "when" instead of "after". Should "...then the @Retry annotation is applied after the CompletionStage object completes ..." change to ""...then the @Retry annotation is applied when the CompletionStage object completes ..."?
- For "Differences in execution flow are noted in dark green in the diagram: ", for accessibility, "dark green" might be difficult for somebody to see. How about something like, "The Return Future or CompletionStage box, is in addition to the boxes in the previous diagram." Or you might say "The Return Future or CompletionStage box, which is green, is in addition to the boxes in the previous diagram." Or use some other wording that you come up with.
- Change "If there’s a fallback, ..." to "If a fallback occurs,...".
- I think that you don't need "Otherwise, the method is added to a queue. " because it seems redundant with the first sentence in the paragraph.
- Globally, for the exceptions, put a noun (exception) after them or same them in English (TimeoutException exception, time out exception, and so on).
- Under the "Interaction with the @Bulkhead annotation" section, the first paragraph says "queue up executions " but the second paragraph says "requests are in the queue ", are they maybe supposed to say the same thing, either "execution" or "request". Make changes as appropriate.

**Comment by Charlotte-Holt** [comment]
@chirp1 Updated:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/async-programming-fault-tolerance.html

- [x] The first blog introduces several fault tolerance annotations, but your topic doesn't. How about if we introduce @Retry since you use it in an example? Change "...the other fault tolerance annotations don’t behave ..." to "...the other fault tolerance annotations, such as @Retry, don’t behave ...".
- [x] Change "After the clientDemo() method is called,..." to "After the clientDemo() method is called without any annotations,...".
- [x] For "...then the @Retry annotation is applied after the CompletionStage object completes, rather than when the method returns: ...", the sentence uses "after" and then "when". How about if we are consistent and use "when the CompletionStage object" instead of "after"?as the two words are slightlyI see in the blog, part 1 If we add the @asynchronous annotation and the method returns a CompletionStage, then the Fault Tolerance logic gets applied when the CompletionStage completes, rather than when the method returns: ". This statement in the blog uses "when" instead of "after". Should "...then the @Retry annotation is applied after the CompletionStage object completes ..." change to ""...then the @Retry annotation is applied when the CompletionStage object completes ..."?
- [x] For "Differences in execution flow are noted in dark green in the diagram: ", for accessibility, "dark green" might be difficult for somebody to see. How about something like, "The Return Future or CompletionStage box, is in addition to the boxes in the previous diagram." Or you might say "The Return Future or CompletionStage box, which is green, is in addition to the boxes in the previous diagram." Or use some other wording that you come up with.
- [x] Change "If there’s a fallback, ..." to "If a fallback occurs,...".
- [x] I think that you don't need "Otherwise, the method is added to a queue. " because it seems redundant with the first sentence in the paragraph.
- [x] Globally, for the exceptions, put a noun (exception) after them or same them in English (TimeoutException exception, time out exception, and so on).
- [x] Under the "Interaction with the @bulkhead annotation" section, the first paragraph says "queue up executions " but the second paragraph says "requests are in the queue ", are they maybe supposed to say the same thing, either "execution" or "request". Make changes as appropriate.

**Comment by chirp1** [comment]
Hi Charlotte, 
The updates look good. We just need the explanation from the developers of the execution flow for "The following diagram shows how the fault tolerance annotations work together without the @Asynchronous annotation:".

**Comment by Azquelt** [comment]
@chirp1 What needs explained about the execution flow without `@Asynchronous`?

**Comment by chirp1** [comment]
@Charlotte-Holt Hi Charlotte, the updates look great! Moving to Ready to Publish.

**Comment by Charlotte-Holt** [comment]
Merged to `vNext` in https://github.com/OpenLiberty/docs/pull/3791
