### ISSUE TITLE
Add MicroProfile Reactive Streams Operators feature to MP intro topic and diagram

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#203]
Update existing topic to include the new MP Reactive Streams Operators feature as part of the bottom (foundational) layer of MP features:

- [x] Update the MicroProfile layers diagram in the .pptx file and export to .png (https://github.com/OpenLiberty/docs/tree/master/img).
- [x] Add a short summary of the new feature in the foundational layer section of the introductory topic (https://github.com/OpenLiberty/docs/blob/master/concept/microprofile.adoc).

**Sources of info**
https://github.com/OpenLiberty/open-liberty/issues/6523

**Comment by lauracowen** [comment]
Potentially useful info: https://openliberty.io/blog/2019/04/26/reactive-microservices-microprofile-19004.html#mpreactive

**Comment by Charlotte-Holt** [comment]
@lauracowen I've made updates for this issue and merged them into `draft`. I also addressed #209 when I made these updates (since it was small and in the same topic). Could you review and let me know what further updates are needed? (I also built it to the draft site: https://draft-openlibertyio.mybluemix.net/docs/intro/microprofile.html.)

**Comment by lauracowen** [comment]
Thanks. The section needs its own sub-heading (eg "Reactive programming in microservices" or something better than that...I notice most but not all of the sub-headings in that article are imperative so maybe it should be more consistent than that but check the phrasing with @hutchig). Reactive programming is a separate thing from the type-safe Java stuff (sorry, I wasn't clear).

@hutchig is your man to review this for technical accuracy. If you need it, you could expand out into ~4 sentences here - it doesn't need to be so concise - but up to you.

**Comment by Charlotte-Holt** [comment]
@hutchig Draft attached here for your review. (Note that I included the entire section from the MP intro topic in my draft for context. My updates are everything in purple.)
[MP Reactive Streams Operators.docx](https://github.com/OpenLiberty/docs/files/3188403/MP.Reactive.Streams.Operators.docx)

**Comment by hutchig** [comment]
I made a slight suggested change to the text to: 
```
MicroProfile Reactive Streams Operators is the enabling technology for MicroProfile reactive programming for microservices. This feature enables creation and manipulation of reactive streams by bundling a Reactive Streams API together with a set of standard operators that apply to streams.
```
This is because we expect and encourage end application users to use the forthcoming MicroProfile
Reactive Messaging technology for their programs rather than the lower level reactive streams API which can be hard to implement well. The main IBM purpose of Reactive Streams Operators is to enable us to build other tech on top of it. We made the API public to enable other 3rd party and tools vendors to muck about with it rather than really targetting typical end users.

**Comment by hutchig** [comment]
I suggest the following slight change to the second paragraph: 

Implement reactive programming for microservices
MicroProfile Reactive Streams Operators provides a way to implement publish/subscribe (pub/sub) pipelines that provide flow control and elegant error handling for asynchronous data streams. This implementation enables the processing of streams of data without publishers overwhelming downstream subscribers. Reactive Streams Operators can increase efficiency under potentially overloading conditions by using a ticketing system that creates 'back pressure' between the subscriber and publisher. Because publishers and subscribers can be directly connected regardless of underlying technology, Reactive Streams serves as an abstraction that can efficiently bind together different technologies.

**Comment by Charlotte-Holt** [comment]
@hutchig Thanks for your feedback! I incorporated your changes and built them to the draft site for you to review: https://draft-openlibertyio.mybluemix.net/docs/intro/microprofile.html. Please let me know if further updates are needed.

**Comment by hutchig** [comment]
The MicroProfile Reactive Streams Operators text (and all the other bits I read) look good to me.

**Comment by lauracowen** [comment]
Looks good - thanks both!

**Comment by Charlotte-Holt** [comment]
Complete and built: https://openliberty.io/docs/intro/microprofile.html
Closing this issue.
