### ISSUE TITLE
Dependency injection in microservices with MicroProfile (MP04)

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#204]
Introduce CDI in MP:

- Base the topic on this topic from the IBM Cloud docs: https://cloud.ibm.com/docs/java?topic=java-mp-cdi#mp-cdi but alter slightly so it's not a straight copy (so we don't screw up their SEO).
- Worth adding a section about annotations? How they make MP nice to write apps with??
- Also:
  - Remove reference to specific versions of CDI and MicroProfile (so that the topic doesn't immediately go out-of-date).
  - Maybe instead of using the example CDI Bean injections from the IBM Cloud topic, use some from the guide apps?

**Sources of info**
https://openliberty.io/guides/cdi-intro.html
https://cloud.ibm.com/docs/java?topic=java-mp-cdi#mp-cdi

**Links**
CDI guide: https://openliberty.io/guides/cdi-intro.html
Consuming RESTful services with template interfaces guide
MP Fault Tolerance concept (MP17, when written)

**Dev contact**
Andrew Rouse

**Comment by ManasiGandhi** [comment]
@lauracowen I am working on writing this content and have a few questions. Can you please answer them?

1. Who is this article targeted at?
2.  'Worth adding a section about annotations?' Can you elaborate?
3. MP Fault Tolerance concept. Can you please provide more info regarding this?

**Comment by lauracowen** [comment]
1. A developer writing a cloud-native microservice (application/web service to be deployed into the cloud).
2. Annotations are a part of CDI and part what makes it nice and usable. Beyond that I'm not sure but when using, say, the Metrics feature, it's much easier to use annotations than to manually code it all. I wanted to try and say something here about how annotations are beneficial to writing microservices.
3. Don't worry about this as it's not written yet.

**Comment by ManasiGandhi** [comment]
// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Contexts and Dependency Injection (CDI) is a framework that improves the structure of application code. It connects different components of an application.
:seo-description: Contexts and Dependency Injection (CDI) is a framework that improves the structure of application code. It connects different components of an application.
:page-layout: general-reference
:page-type: general
= Dependency injection in Microservices with MicroProfile (MP04)

Contexts and Dependency Injection (CDI) is a framework that improves the structure of application code.

The most fundamental services that are provided by CDI are

-	Contexts: This service helps you to bind the lifecycle and interactions of stateful components to well-defined, extensible contexts.
-	Dependency Injection: This service helps you to inject components into an application in a typesafe way.

CDI is an essential element in MicroProfile, as well as in Java EE and Jakarta EE, and connects different components of an application.

MicroProfile specifications take CDI-first approach. They rely on the CDI extension mechanism which implements additional functionalities and enhances existing standards with new capabilities.


== CDI beans
 
Beans are components that can be injected into each other with a dependency injection. Almost every plain old Java&trade object (POJO) with a constructor can be a bean. In CDI, a bean is a source of contextual objects that define application state and/or logic. The beans are managed by CDI containers by using bean-defining annotations. The container instantiates dependencies and controls when and how the components are instantiated and destroyed without your intervention.

Annotations are metadata about code. Use them to decorate a class, method, field, parameter, variable, constructor, or package. You can use annotations to define the scope in which the bean is stored.
= heading2



== CDI Scopes

Use scopes to define the state of a bean. CDI scope type annotations control the bean's lifecycle.

-Use the @ApplicationScoped class-level annotation if an instance is to live as long as the application is active.
-Use the @RequestScoped class-level annotation if a new instance of the bean is to be created for every request (a servlet request, for example).
-Use the @Dependent class-level annotation if the new instance belongs to another object. An instance of a dependent bean is never shared between different clients or different injection points. It is instantiated when the object it belongs to is created, and then destroyed when the object it belongs is destroyed.

If no class-level annotation is defined, @Dependent is the default.

Annotations that define CDI beans must be discovered. CDI annotation scanning can be enabled by using a beans.xml file in the META-INF folder for a .jar archive, or in the WEB-INF folder for a .war archive. This file can be empty, or it can contain something like the following content:

 <?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://xmlns.jcp.org/xml/ns/javaee"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee
            http://xmlns.jcp.org/xml/ns/javaee/beans_1_1.xsd"
      version="1.1" bean-discovery-mode="all">
  // enable interceptors; decorators; alternatives
</beans>

The presence of an empty beans.xml file, or a beans.xml with bean-discovery-mode="all", makes all of the potential objects CDI beans. Otherwise, only objects with CDI bean-defining annotations are CDI beans.

==CDI bean injection

CDI injects defined beans into other components through @Inject. For instance, the following POJO MyBean is a CDI bean:


@ApplicationScoped
public class MyBean {
	int i=0;
	public String sayHello() {
    	return "MyBean hello " + i++;
	}
}
As it is @ApplicationScoped, only one instance is created. In the following, MyRestEndPoint is @RequestScoped, which means an instance is created for each request. CDI injects the same MyBean instance into each.


@RequestScoped
@Path("/hello")
public class MyRestEndPoint {
	@Inject MyBean bean;

	@GET
	@Produces (MediaType.TEXT_PLAIN)
	public String sayHello() {
    	return bean.sayHello();
	}
}









=== See also:
- link:
- link:
- link:

**Comment by lauracowen** [comment]
Looks good, thanks. If you haven't already, could you create the topic as a .adoc file so that we can build it into the draft website? @dmuelle can point you in the right direction if you need help knowing where to put the file.

**Comment by ManasiGandhi** [comment]
Sure

**Comment by ManasiGandhi** [comment]
I created the topic as a .adoc file and built it into the draft website with help from @dmuelle It's not yet showing up on this link https://draft-openlibertyio.mybluemix.net/docs/ref/general/#/docs/concept/rest_clients.html

**Comment by lauracowen** [comment]
Now it's building, can you ask Andrew Rouse to review it for technical accuracy and that it makes sense to him, pls? https://draft-openlibertyio.mybluemix.net/docs/ref/general/#contexts_dependency_injection.html

(If the draft server is down, he can also see it in Github here: https://github.com/OpenLiberty/docs/blob/draft/ref/general/contexts_dependency_injection.adoc

**Comment by lauracowen** [comment]
Re-opened as it's not published yet.

**Comment by lauracowen** [comment]
@Azquelt reviewed and was happy with it as long as someone on the CDI team could check it too.

@tevans78 took a look on 2019-06-25 and said "Hey, this looks good … only comments would be about formatting but I’m guessing that isn’t finished yet".

**Comment by lauracowen** [comment]
Editorial review feedback:
- Can you remove the "(MP04)" bit from the title? That's just an internal reference to tie the backlog issue back to a list of topics we need to write.
- Add a colon (:) to the end of the lead-in sentence before a list, so "The most fundamental services that are provided by CDI are:"
- "Dependency Injection" (second bullet in the list) -> "Dependency injection" (lower-case - it's only upper-case in the name of the feature - could go either way on the opening sentence - I think it's fine to leave that as upper-case but when referring to contexts and dependency injection as concepts, they should be lower-case).
- "CDI is an essential element..." and "MicroProfile specifications take..." should be a single paragraph (just remove the line-break before "MicroProfile specifications take...").
- "MicroProfile specifications take CDI-first approach." is missing "a" before "CDI-first".
- Remove "&trade" - it's not rendering correctly anyway but you don't need to trademark it in the individual topics (we made that the policy of the whole website which does trademark Java on its first mention - if we decide to change this policy, we'll update all topics en masse).

CDI beans section
- Try to avoid saying "and/or". If you absolutely can't use one or the other, take the approach of "can be x or y, or both". At some point we'll probably need to translate so we should ensure sentences are constructed clearly (even though and/or is usually okay for English readers).
- Remove "= heading2" from the end of the section.

CDI scopes section
- "CDI Scopes" heading -> "CDI scopes" - don't let developers make you capitalise nouns unless they're actually proper nouns (eg the name of a feature). Developers try to capitalise nouns like they would capitalise the names of classes in Java. :)
- Probably don't need to say "type" in the first sentence. "CDI scope annotations..." makes sense I think? This sentence should probably end in a colon too if it's introducing the list that follows.
- The list isn't rendering correctly. I think you need a space after the "-" in each item.
- Can you also use backticks (`) around the name of the annotations eg "@ApplicationScoped" as `@ApplicationScoped`. Also around the file name eg `beans.xml`. And around any other quoted bits of code eg `bean-discovery-mode="all"`
- There's a rogue space before the start of the XML code snippet (the `<?xml...` bit is indented slightly when it should start at the beginning of the line).
- The code snippet in this section and following sections need to be marked up with the correct language (eg `[source,xml]` for XML snippets; `[source,java]` for Java snippets, etc.). See the examples in this post: https://raw.githubusercontent.com/OpenLiberty/blogs/master/publish/2019-06-21-microprofile-rest-client-19006.adoc

CDI bean injection section
- The code snippet at the start of the second paragraph is missing its highlighting.
- The second code snippet is highlighted but the first line of the snippet is missing its highlighting.

See also section
- This needs completing with useful links or removing.

Can you also add an inline link:
- On the first instance of "MicroProfile" can you link it to https://openliberty.io/docs/intro/microprofile.html (use the `link:http....` format that you'll find in the example blog post source I mentioned above).

Ping me if any of these comments don't make sense. In general, the article looks great - it just needs the formatting/style tidying up a bit. Thank you!

**Comment by ManasiGandhi** [comment]
https://openliberty.io/docs/ref/general/#contexts_dependency_injection.html
