### ISSUE TITLE
CADF format version of the the JSON events list (for audit events only)

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#2281]
Don asked @Rwalls1 to make all the audit events part of the [JSON log events reference list topic](https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/json-log-events-list.html) which meant they needed to be in JSON format.

The original events Emily supplied were in CADF format. Don suggested creating a separate topic listing the audit events in CADF format (similar structure to the JSON topic but with only the audit events).

For the content of this topic, start by finding the old version of the JSON topic before the audit events were changed to JSON format and use that to create a draft. However, I think there were problems with some of Emily's original event examples (really old dates, mentions of Java versions that predated Liberty, long real URLs instead of shorter example URLs, etc). I don't know whether those problems were fixed in CADF format or only fixed in JSON format. So carefully review them yourself and decide what might need changing, then discuss with Emily about what specific events might need new examples (if any).

Context from conversation with @emilytee :

From Don's perspective, he's looking at what comes out from when a user is making use of his logging feature. But a user that does not need or want to use the logging feature is going to see audit records in their primary state, which is the CADF format. Those users will need to know what a particular CADF field means.
So, where the links are to the individual events, which currently only show Don's logging format, there should also be a table for "Audit Record - CADF format".

A given user will only want either JSON or CADF: A user that is expecting audit records is only going to want CADF style, while one wanting to use logging, will want it in JSON. And we can't require users include the logging feature just for wanting to audit.

So, I (Laura) propose creating a separate topic titled "Audit log events reference list" using a similar structure to the JSON topic (check for any updates needed to the examples as I explained above). The CADF topic obviously will contain only audit events, not any of the other types of events that are in the JSON topic. Then provide a link from the start of the audit section in the JSON topic to the CADF topic, and vice versa.

**Comment by Rwalls1** [comment]
Link to first draft: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/audit-log-events-list.html

**Comment by Rwalls1** [comment]
@emilytee Please review, do you think any new examples are needed?:

**Comment by chirp1** [comment]
@Rwalls1 Hi Richard, have you negotiated a turn around time for your topic? Would you add to this issue when Emily is going to return your topic to you? Also, would you connect your PR's for this issue to this issue?

**Comment by emilytee** [comment]
Looks good.  Minor typos:

SECURITY_Member_MGMT reference should be SECURITY_MEMBER_MGMT (all upper case)

SECURTIY_AUTHN_TERMINATE should be SECURITY_AUTHN_TERMINATE (ITY vs TIY)

JMX_MBEAN_Attributes event should be JMX_BEAN_ATTRIBUTES even (all upper case)

**Comment by Rwalls1** [comment]
@emilytee Please review the latest update: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/audit-log-events-list.html

**Comment by emilytee** [comment]
One  more thing:

SECURITY_JMS_AUTHN
You can use the SECURITY_JMS_AUTHENTICATION event to capture the audit information from JMS authentication. The following table provides the fields for the SECURITY_JMS_AUTHENTICATION event and a description of each field.

It should say SECURITY_JMS_AUTHN, not SECURITY_JMS_AUTHENTICATION

**Comment by Rwalls1** [comment]
@emilytee Thanks, I've made that update: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/audit-log-events-list.html#_security_jms_authn

**Comment by lauracowen** [comment]
Thanks for reconstructing this topic. It's looking good.

- Can you put something like " (CADF format)" at the end of this topic title?
- And append "-cadf" to the filename before ".adoc"? So it's clear which topic this is.
- Can you try sync'ing up the introduction to the [JSON version](https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/json-log-events-list.html#_supported_audit_events_and_their_audit_data) with this version? Specifically, I think the one in the JSON topic is good and could be used in the CADF topic, but I think it's good that the CADF current intro mentions security details, so can you incorporate that into the JSON version? Basically, this CADF topic is the same as the audit section of the JSON topic, so they should be introduced in similar ways.
- In the JSON topic, can you add in mention that these are JSON format but if you're using CADF format, see the CADF topic and link to it. And vice versa from the CADF topic. I think you could probably do this by appending a sentence to the end of the first paragraph of the intro (which starts "The Open Liberty Audit feature captures...").
- Can you make sure that every event that appears in one topic also appears in the other topic? And any other things like that that should be consistent between the two?

Hope all that makes sense!

**Comment by Rwalls1** [comment]
@lauracowen Please review the latest update: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/audit-log-events-list-cadf.html#

**Comment by Rwalls1** [comment]
New link to topic: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.10/audit-log-events-list-cadf.html#

**Comment by lauracowen** [comment]
Some minor things. If you ping me when you're done, I'll try sign off today. Thanks

- [ ] Can you put "(CADF)" in the navigation entry as well (eg "Audit log events (CADF) reference list")? I know it makes the nav title longer but I really struggled to find the topic just now, and the format in that topic is what differentiates it from the related JSON one.
- [ ] Think you have an extra/unnecessary(?) "different" in the second paragraph (I think "in the following CADF format types..." would be fine).
- [ ] I know I said to put the link to the other topic at the end of the second paragraph but it doesn't make sense there - it currently ends in a colon implying that it's introducing the list of formats, when actually the previous sentence does that. Maybe instead, at the end of the first paragraph, have a sentence "Open Liberty can generate audit events in either CADF or JSON format." with the link on "JSON format". (and in the JSON topic, put "JSON" first, then put the link on "CADF format").
- [ ] "JMX MBean Operations (JXM_MBEAN)" - Typo

**Comment by Rwalls1** [comment]
@lauracowen Thanks, I've made those updates: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.10/audit-log-events-list-cadf.html#

**Comment by lauracowen** [comment]
That's great, thank you :) Will sign off now.

**Comment by ManasiGandhi** [comment]
@rw2513 #peer review The doc looks good! Have a few suggestions:

- Under SECURITY_AUDIT_MGMT, in the first sentence it says “The SECURITY_AUDIT_MGMT event captures the start and stop of the Audit Service and implemented handlers such as the default AuditFileHandler.” Could you replace “default AuditFileHandler” with “default audit file handler” or “auditFileHandler element”.
Same for “The following example shows the SECURITY_AUDIT_MGMT event that captures the start of the Audit Service and AuditFileHandler:”
- Saw “i.e.” in some places in the doc. Could you replace the Latin expressions (not sure if they are allowed in tables)?
- “In general, a value of 200 means success” is mentioned a few times. Is 200 the code or is it a value? If it is a value, should it have a unit?
- Under “SECURITY_AUTHZ”, in the first sentence, “You can use the SECURITY_AUTHZ event to capture the audit information from Jacc web authorization, unprotected servlet authorization, Jacc EJB authorization, and EJB authorization.”, should it be “JACC” instead of “Jacc”?
- Could you remove the parentheses used in the doc?

**Comment by Rwalls1** [comment]
@ManasiGandhi Thanks, I have addressed your feedback

**Comment by Rwalls1** [comment]
Editing references: https://learning.oreilly.com/library/view/developing-quality-technical/9780133119046/ch09.html
                                 https://learning.oreilly.com/library/view/developing-quality-technical/9780133119046/ch11.html

**Comment by dmuelle** [comment]
Doc is now on vNext branch, will publish with 20.0.0.12 on 11.20

**Comment by chirp1** [comment]
Hi Richard,

The updates look good! I have a few comments.
Please check all the comments to see whether there are multiple instances of the wording to be fixed. In some cases I added "global" to the comment to indicate that multiple places with the wording need to be fixed, but additional comments without "global" might also need to be fixed globally.
- Italicize "name of handler implementation" to indicate that it is a variable. 
- Change "Note that the name includes.." to "The name includes....".
- For “urbridge", “scim" or “vmmservice", ...." remove the quotes and replace with highlighting.
- Change "....depending on the flow of the request, for example, is it a call coming through scim.." to something like "...depending on the flow of the request. For example, if the call comes through a SCIM operation, the target name is scim." Highlight "scim".
-  Highlight "server/vmmservice/<action>.". Italicize "action". Remove brackets around "action" if that is the style of the OL docs.
- Change "Token type of the user that is performing action,..." to "Token type of the user that is performing the action,...". (Add "the".)
- Remove the stray right bracket immediately above "The following example shows a successful SECURITY_AUTHN_DELEGATION event:".
- Change "Token type of the use that is performing the action,..." to "Token type of the user that is performing the action,...". (Change "use" to "user".)
- Change "Jacc" to "JACC" and spell it out on first use.
- Change "Name of monitoring agent associated with initiator." to "Name of the monitoring agent associated with initiator." (Add "the".)
- For "Roles that are identified as being needed, if not permit all for EJBs.", I'm not sure what it means. Maybe "Roles that are identified as being needed. If none are specified, permit all roles for EJBs.". Rewrite as appropriate.
- Global: Change "...such as HTTP(S), JMS, or EJB, ..." to "...such as HTTP, HTTPS, JMS, or EJB, ...".
- The "SAF resource in SAF Class" wording seems odd. From looking at "target.saf.class" in this table, maybe "the SAF resource in the SAF class", but check with the developer as appropriate.
- Highlight "service/application/web".
- For "SAF Authorization Exception", maybe "SAF authorization exception". (A and E, lowercase)
- Change "True if the user is authorized to access the SAF resource in the SAF Class, otherwise false." to "A true value if the user is authorized to access the SAF resource in the SAF class, otherwise a false value.". (Among other changes in the sentence, "class" is lowercase.).
- Change "Name of the SAF Class..." to "Name of the SAF class...".
- Change "Unique URI of the target of the event:" to "Unique URI for the target of the event:". (Change "of" to "for".)
- Change "MBean action that is being performed on the MBean attribute(s). getAttribute(s) and setAttributes(s) are supported." to something like "MBean action that is being performed on the MBean attribute. getAttribute and setAttribute methods is supported.".
- Change "Name of the attributes(s) being acted upon." to "Name of one or more attributes being acted upon."
- Change "MBean action that is being performed on the MBean attribute(s)" to "MBean action that is being performed on one or more MBean attributes.".

**Comment by Rwalls1** [comment]
@chirp1 Thanks, I've addressed your feedback: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.8/audit-log-events-list-cadf.html

**Comment by chirp1** [comment]
Hi Richard, Almost there!
- Change "Token type of the user that is performing action,..." to "Token type of the user that is performing the action,...". (Add "the".)   (I see one more instance that needs to be changed.)
- Change "Name of monitoring agent associated with initiator." to "Name of the monitoring agent associated with the initiator." (Add "the".)
- Highlight "service/application/web". One more to do- I think 18 out of 18.
- Change "...MBean attribute. getAttribute and setAttributes methods..." to "MBean attribute. getAttribute and setAttribute methods". (Remove "s" from setAttributes.)
- Global: For "MBean attribute. getAttribute and setAttribute methods" don't highlight the attributes.
- Global: Highlight "true" and "false" in "A true value if the user is authorized to access the SAF resource in the SAF class, otherwise false.".

**Comment by Rwalls1** [comment]
@chirp1 Thanks, I've addressed your latest feedback: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.8/audit-log-events-list-cadf.html

**Comment by chirp1** [comment]
Updates look good. Moving to Ready to Publish.

**Comment by Rwalls1** [comment]
Staging: https://staging-openlibertyio.mybluemix.net/docs/21.0.0.8/audit-log-events-list-cadf.html

**Comment by Rwalls1** [comment]
Updates moved to Vnext and will publish with 21.0.0.8.
