### ISSUE TITLE
Kerberos authentication with JDBC data sources

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/docs#2460]
In OpenLiberty we are adding a new authentication mechanism for JDBC datasources which can use the Kerberos protocol. We need to add a page that discusses the various config options and show what the minimum required and recommended configuration is.

OpenLiberty epic: https://github.com/OpenLiberty/open-liberty/issues/9008

**Comment by aguibert** [comment]
The JDBC-specific bits of this documentation is pretty minimal, but I'm having to explain the generic Kerberos bits because I don't think we have that documented yet (in OL). Perhaps it would be better to repurpose this task for generic Kerberos documentation, and then just have a section on JDBC Datasources? @lauracowen WDYT?

In any case, here is an initial draft of the proposed content, assuming we only care about documenting the Kerberos for JDBC path:

-------

### Title: Kerberos Authentication for JDBC DataSource

Summary: [Kerberos](https://web.mit.edu/kerberos/) is a network authentication protocol in which a client and server authenticate by communicating with a third process called a Key Distribution Center (KDC). Kerberos authentication may be used for JDBC DataSources that are backed by one of the following databases:
- IBM DB2
- Oracle Database
- Microsoft SQLServer

## Kerberos global configuration

Kerberos authentication in Liberty builds on top of the [Kerberos Login Module and JGSS API provided by the JDK](https://docs.oracle.com/en/java/javase/11/docs/api/jdk.security.auth/com/sun/security/auth/module/Krb5LoginModule.html), which in turn builds on top of the Kerberos OS libraries for the specific system being used.

The `<kerberos>` configuration element in server.xml provides system-wide configuration options for the Liberty server. For example:

```xml
<server>
  <featureManager>
    <!-- several different feature enable the 'kerberos' config element. Consult the config documentation to determine which ones -->
  </featureManager>

  <kerberos keytab="${server.config.dir}/security/krb5.keytab" configFile="${server.config.dir}/security/krb5.conf"/>
</server>
```

The `keytab` and `configFile` attributes are both optional. Resolution for these values follows the following priority:
1. Value specified in `<kerberos>` element in server.xml
2. Default location(s) defined by the JDK (e.g. `{user.home}/krb5.keytab`, or JDK-defined system properties)
3. Default location(s) defined by the Operating System (e.g. `/etc/krb5.keytab` or OS-defined environment variables)

On Windows the default Kerberos config file name is `krb5.ini`. On other operating systems it is `krb5.conf`.

## Kerberos configuration for JDBC DataSources

Once the Kerberos global configuration has been defined, a Kerberos principal may be configured on an `<authData>` element in server.xml. For example:

```xml
<server>

  <featureManager>
    <feature>jdbc-4.2</feature>
  </featureManager>

  <authData id="myKerberosAuth" krb5Principal="krbUser" krb5TicketCache="${server.config.dir}/security/krb5cc_krbUser"/>

  <library id="db2DriverLib">
    <fileset dir="${server.config.dir}/db2"/>
  </library>

  <dataSource jndiName="jdbc/krb/basic" containerAuthDataRef="myKerberosAuth">
    <jdbcDriver libraryRef="db2DriverLib"/>
    <properties.db2.jcc databaseName="${DB2_DBNAME}" serverName="${DB2_HOSTNAME}" portNumber="${DB2_PORT}"/>
  </dataSource>

</server>
```

- The `krb5TicketCache` attribute is optional. If unspecified, the default Kerberos credential cache of the JDK or OS locations will be checked.
- The `containerAuthDataRef` references the `<authData>` element to be used for authentication when establishing a connection to the database. 
- A `recoveryAuthDataRef` may optionally be specified on the `<dataSource>` element if a different `krb5Principal`/`krb5TicketCache` must be used for authentication during XA recovery. If unspecified, the `<authData>` element referenced by `containerAuthDataRef` will be used for authentication during XA recovery.

## Compatibility with SPNEGO authentication

Liberty also supports [SPNEGO authentication](https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/cwlp_spnego.html) for web authentication and JDBC data source authentication. The specific configuration details of SPNEGO authentication are outside of the scope of this article. In order to use SPNEGO authentication with a JDBC datasource, it is not required to configure a `containerAuthDataRef` or `recoveryAuthDataRef` on your `<datasource>` element.

For example, the following configuration would allow a JDBC datasource to use SPNEGO authentication:

```xml
<server>

  <featureManager>
    <feature>jdbc-4.2</feature>
    <feature>spnego-1.0</feature>
    <feature>appSecurity-2.0</feature>
  </featureManager>

  <spnego servicePrincipalNames="HTTP/my.spnego.server.com" authFilterRef="myAuthFilter"/>
  <authFilter id="myAuthFilter">
    <requestUrl urlPattern="/MySpnegoServlet" matchType="contains"/>
  </authFilter>

  <!-- The kerberos element is optional, but may be used to customize keytab and configFile locations used for SPNEGO -->
  <kerberos keytab="${server.config.dir}/security/krb5.keytab" configFile="${server.config.dir}/security/krb5.conf"/>

  <library id="db2DriverLib">
    <fileset dir="${server.config.dir}/db2"/>
  </library>

  <dataSource jndiName="jdbc/spnegoAuth">
    <jdbcDriver libraryRef="db2DriverLib"/>
    <properties.db2.jcc databaseName="${DB2_DBNAME}" serverName="${DB2_HOSTNAME}" portNumber="${DB2_PORT}"/>
  </dataSource>

</server>
```

**Comment by lauracowen** [comment]
@aguibert I think you’re right that we should really just have something focused on Kerberos that introduces why and how (the basic <kerberos> config element) you’d use Kerberos. Then that could mention JDBC and SPNEGO use of it and link out to your config examples in JDBC feature doc and in SPNEGO feature doc.

BTW, what is the Kerberos Constrained Delegation for SPNEGO 1.0 feature about? Should that also be mentioned in a Kerberos article or is that entirely separate from this?

What are the most likely uses of Kerberos that users would need to know about? Just JDBC? (you said “assuming we only care about documenting the Kerberos for JDBC path”).

@utle this might be more your thing to answer as Kerberos/SPNEGO SME?

Thx

**Comment by utle** [comment]
@lauracowen @aguibert We should have something on Kerberos to introduces why and how then what Liberty support such as JDBC and SPNEGO .. (soon will be LDAP) and link out to detail of JDBC and SPNEGO articles.

Kerberos Constrained Delegation should be mention in the Kerberos article.

BTW,  We have a general Kerberos/SPNEGO article in the infor center.

**Comment by aguibert** [comment]
I've updated my original post with a few feedback comments from Ut.

Regarding page separation, I'm not sure how you plan to structure docs in OL @lauracowen, but a big pet peeve of mine in KC docs is we had all of these "micro pages" with a small/specific amount of info on them, and it was always a chore to hunt for the right page (if you weren't lucky enough to google straight into the page you need).

I really prefer longer pages, which allows the user to visually scan or Ctrl+F for what they need. For this reason, I think it would be good to have just 1 doc page for everything Kerberos related (general concepts, JDBC, SPNEGO, and eventually LDAP). Splitting that info across 4 different pages would make it hard to cross-reference general info from the specific pages and vice versa.

**Comment by utle** [comment]
@aguibert I agreed with one page. But we did not have that choice any more. They now split even for SPNEGO topics into several pages. This will cause problem when customer did not do all the pages. I am a little off topic here.

**Comment by aguibert** [comment]
@utle with docs on OpenLiberty.io we do have full control though. With KC we did not

**Comment by lauracowen** [comment]
Okay, much as I'm sure it's fun to complain about the KC, can we be a bit more constructive?

The SPNEGO topics are _not_ split into several short pages. There are _two_ SPNEGO topics:

1) We are enhancing the generated feature topics with commonly needed (80% of use cases) config examples, including for the [SPNEGO feature doc](https://draft-openlibertyio.mybluemix.net/docs/20.0.0.10/reference/feature/spnego-1.0.html). In fact, the SPNEGO feature only needs to be enabled in order for the server to use its default configuration (the default values have presumably been designed to be relevant to 80% of users?) so that is what's documented there.

2) Very few of our features actually just magically work at that point (sadly). For example, if you want to enable the [JDBC feature](https://draft-openlibertyio.mybluemix.net/docs/20.0.0.10/reference/feature/jdbc-4.3.html), it's not much use to your app unless the app actually contains a servlet that accesses the data source.

   We have [SPNEGO instructions (a 'task' topic)](https://draft-openlibertyio.mybluemix.net/docs/20.0.0.10/configuring-spnego-authentication.html) for creating Kerberos keytabs etc, so the [SPNEGO feature doc](https://draft-openlibertyio.mybluemix.net/docs/20.0.0.10/reference/feature/spnego-1.0.html) provides a link to that topic, in case the user has found the configuration from the SPNEGO feature doc, they'll also find what else they need to do to actually use SPNEGO in their app. Conversely, if they arrived at the task topic, the relevant step informs them that they need to enable the feature (and nothing else in most cases because the default values should apply!). If they fail to notice the instruction that they need to enable the SPNEGO feature, most likely that's because there's too much information in that topic and it should be simplified.

---

Returning to the current issue, if you can help us to understand the technical issues that we're documenting here, we'll be able to make better judgements when designing the documentation. It's great that you can provide well-written information (it helps a lot) but we then need to assess how well the format works within the wider Open Liberty docs (it may or it may not).

So, if you can, it'd be useful to understand the following points better (keeping in mind we're focused on documenting how to do this for writing and deploying cloud-native apps, and we're focusing on what's relevant to 80% of users, not edge cases):

1. In the [Configuring SPNEGO auth topic](https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/configuring-spnego-authentication.html), the prerequisites include (I think) setting up a Kerberos KDC, which I think is not a simple task, so:
   1. Can you provide a link to somewhere about how to do that? (Kerberos project docs?)
   2. Who is the target user here? Is it a Windows admin who'd be asked to set it up by the OL ops team? Or would it be an Open Liberty ops person who has the relevant permissions on the Windows server?

2. About the JDBC example config above and "system-wide configuration" (JVM-wide or server-wide configuration)... In the examples Andy provided above, there are two separate server.xml examples, implying two separate servers. However, in a containerised app, there would be only a single server per app and container anyway, so what does "system" mean in that context?

   Wouldn't it always mean that all that config would be in the same server.xml? So it would actually be appropriate for the `<kerberos>` element to be in the JDBC example as well in reality (I understand about the `<kerberos>` element being a singleton etc and how Liberty collapses them together)?

3. Regarding the JDBC, SPNEGO, LDAP info, I was suggesting having a single Kerberos introduction with a section on each, as Andy mentions above. Then the config example for each of those sections (if it's commonly needed), could be in their respective generated feature doc to provide value there and linked from the topic.

   However, to make that judgement, I would like to understand better what the target user is trying to do at the point where they realise they need help. eg are they really going to be writing an app that uses (say) JDBC _and_ SPNEGO _and_ LDAP? I guess it's possible but is that the likely scenario? Ultimately, what are the main questions that they are asking that we need to answer in this documentation?

4. Which features can use the `<kerberos>` element? Do you have a list?

Thanks

**Comment by aguibert** [comment]
@lauracowen thanks for the detailed info. Here are some direct responses to your questions:

1. Setting up a KDC is a prerequisite, but in most cases I expect a KDC will already be available to devs/users who need to be using Kerberos auth for their datasources. A single KDC can be used by multiple apps/services at once, so it's not like a new KDC needs to be set up just for this use case. We could certainly point people to external docs here though. What links would you recommend here @utle ?

2. The config examples I provided above are actually just meant to be read as snippets of server.xml config. So there would just be 1 Liberty server involved. Would it be more clear if I removed the `<server>` tags surrounding each config snippet?

The `<kerberos>` element _could_ be in the JDBC config snippets, but I just wanted to show the bare-minimum config required. The `<kerberos>` element itself is actually an optional element, so the user only needs to specify it if they need to customize the `keytab` or `configFile` locations. If they are not specified, the JVM and OS defines default locations that will be checked.

3. LDAP isn't a possibility yet, but it may be added in the near future. For now, these are the sorts of questions I expect users will be coming to the documentation for:
 - (plain Kerberos) How do I configure my Liberty instance to point at a KDC that my organization has set up?
 - (plain Kerberos) How do I configure my Liberty instance to use Kerberos credentials that I've stored in a Keytab?
 - (Kerb+JDBC) How do I configure my JDBC datasource to use Kerberos auth?
 - (SPNEGO+JDBC) How do I configure my JDBC datasource to use SPNEGO auth? (keep in mind that SPNEGO is like an extension of Kerberos)

4. There are quite a few public features that enable the `<kerberos>` element. Basically any feature involving security will pull this in. Here is a mostly complete list I created by hand:

- acmeCA-2.0
- appSecurity-2.0
- appSecurity-3.0
- appSecurity-4.0
- batchManagement-1.0
- connectors-2.0
- jca-1.7
- jcaInboundSecurity-1.0
- jdbc-4.0
- jdbc-4.1
- jdbc-4.2
- jdbc-4.3
- jms-2.0
- jwt-1.0
- mpMetrics-1.0
- mpMetrics-1.1
- mpMetrics-2.0
- mpMetrics-2.2
- mpMetrics-2.3
- mpMetrics-3.0
- oauth-2.0
- openapi-3.1
- openidConnectClient-1.0
- passwordUtilities-1.0
- restConnector-2.0
- samlWeb-2.0
- scim-2.0
- socialLogin-1.0
- wasJmsClient-2.0
- wasJmsSecurity-1.0
- wsAtomicTransaction-1.2

**Comment by utle** [comment]
There are several KDCs out there such as MS KDC, zOS KDC, AIX KDC, Linux KDC, MIT KDC ...etc. I don't think we need a link for the KDC.

**Comment by lauracowen** [comment]
@aguibert Awesome, thanks - that's really useful.

> 1. Setting up a KDC is a prerequisite, but in most cases I expect a KDC will already be available to devs/users who need to be using Kerberos auth for their datasources. A single KDC can be used by multiple apps/services at once, so it's not like a new KDC needs to be set up just for this use case. We could certainly point people to external docs here though. What links would you recommend here @utle ?

Okay, that's useful to understand. We've been trying to work out the separation between something the user should go off and make sure they've done vs something that should be available to them and they just need to make sure they know the details of it (eg connection details or whatever's appropriate in the context).

> 2. The config examples I provided above are actually just meant to be read as snippets of server.xml config. So there would just be 1 Liberty server involved. Would it be more clear if I removed the `<server>` tags surrounding each config snippet?
> The `<kerberos>` element _could_ be in the JDBC config snippets, but I just wanted to show the bare-minimum config required. The `<kerberos>` element itself is actually an optional element, so the user only needs to specify it if they need to customize the `keytab` or `configFile` locations. If they are not specified, the JVM and OS defines default locations that will be checked.

Yes, I think remove the `<server>` tags.
Okay, bare-minimum config is great - that's what we need. If the `<kerberos>` element is optional (I didn't realise that), that's maybe a separate example (as you've said) and we just need to clearly indicate when each example is relevant. I think we can do that from the info you've provided, thanks.


> 1. LDAP isn't a possibility yet, but it may be added in the near future. For now, these are the sorts of questions I expect users will be coming to the documentation for:
> 
> * (plain Kerberos) How do I configure my Liberty instance to point at a KDC that my organization has set up?
> * (plain Kerberos) How do I configure my Liberty instance to use Kerberos credentials that I've stored in a Keytab?
> * (Kerb+JDBC) How do I configure my JDBC datasource to use Kerberos auth?
> * (SPNEGO+JDBC) How do I configure my JDBC datasource to use SPNEGO auth? (keep in mind that SPNEGO is like an extension of Kerberos)

Thanks.

> 1. There are quite a few public features that enable the `<kerberos>` element. Basically any feature involving security will pull this in. Here is a mostly complete list I created by hand:
> 
> * acmeCA-2.0
> * appSecurity-2.0
> * appSecurity-3.0
> * appSecurity-4.0
> * batchManagement-1.0
> * connectors-2.0
> * jca-1.7
> * jcaInboundSecurity-1.0
> * jdbc-4.0
> * jdbc-4.1
> * jdbc-4.2
> * jdbc-4.3
> * jms-2.0
> * jwt-1.0
> * mpMetrics-1.0
> * mpMetrics-1.1
> * mpMetrics-2.0
> * mpMetrics-2.2
> * mpMetrics-2.3
> * mpMetrics-3.0
> * oauth-2.0
> * openapi-3.1
> * openidConnectClient-1.0
> * passwordUtilities-1.0
> * restConnector-2.0
> * samlWeb-2.0
> * scim-2.0
> * socialLogin-1.0
> * wasJmsClient-2.0
> * wasJmsSecurity-1.0
> * wsAtomicTransaction-1.2

Much appreciated (also, we're looking into whether we can get the doc to automatically generate such lists in future).

**Comment by aguibert** [comment]
> Much appreciated (also, we're looking into whether we can get the doc to automatically generate such lists in future).

We already generate the opposite list, such as: https://openliberty.io/docs/20.0.0.10/reference/feature/jdbc-4.3.html#_feature_configuration_elements

This provides info on `features-->config`, which answers the question: "What config elements do I get if I enable this feature?"

But I think it would be more useful to provide info in terms of `config-->features` which answers the much more realistic question of "I want to use this config element, what feature(s) do I need to enable in order to get it?"

**Comment by lauracowen** [comment]
@aguibert Yes, I agree. It's something I've wondered about occasionally before so it was useful when you made the point above. At about the same time, an external user also mentioned it: https://github.com/openliberty/docs/issues/2572 We're going to take a look at it next week as part of a few related issues about how we build the generated docs.

**Comment by lauracowen** [comment]
Additional relevant info from separate conversation with Alasdair:

There are 2 possible scenarios:
1) User logs into webapp using SPNEGO and then uses the SPNEGO credentials to login to database
2) Kerberos identity associated with the server is used to authenicate to database

scenario 2 is more likely. For security reasons you rarely give external users access to your database.

**Comment by dmuelle** [comment]
@lauracowen @aguibert initial draft of this topic is now available for review [on the draft site](https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/kerberos-authentication-jdbc.html)

**Comment by lauracowen** [comment]
Looks good.

Minor typo: "Open liberty server" in intro has lower-case L.

**Comment by dmuelle** [comment]
@aguibert - a general question about variables re our discussion in #2867, in this code example

`kerberos keytab="${server.config.dir}/security/krb5.keytab"`

Is it the case that a user doesn't necessarily need to specify the server config directory, but could just specify

`kerberos keytab="security/krb5.keytab"`

  However,  if they did include `${server.config.dir}` in their code, Liberty would resolve it as their local server config directory? Or is `${server.config.dir}` only there for example purposes?

**Comment by utle** [comment]
@dmuelle 
If they did include ${server.config.dir} in their server.xml file, Liberty would resolve it as their local server config directory.

**Comment by dmuelle** [comment]
Thanks @utle !

**Comment by dmuelle** [comment]
@aguibert @utle can either of you provide technical review of this draft:

https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/kerberos-authentication-jdbc.html

Our content cutoff to publish with 20.0.0.12 is Monday, so if any changes are needed, I can prioritize them to be completed before the cutoff. Thanks

**Comment by aguibert** [comment]
looks really good @dmuelle, just 2 small comments:

1. In the code examples the variables starting with `DB2_` are meant to be variables, so they should be wrapped in `${}` like this: `${DB2_HOSTNAME}`
2. For the SPNEGO section, we might want to add the following disclaimer:
> If you use an XA capable datasource with SPNEGO authentication, you must configure a non-SPNEGO `recoveryAuthDataRef` on the datasource, because SPNEGO authentication cannot be used to perform automatic XA recovery.

If the user doesn't configure a `recoveryAuthDataRef` for SPNEGO, the runtime will emit a warning message indicating they need to do so, so it may not be necessary to document this limitation if it's good enough to have the warning message from the runtime.

**Comment by dmuelle** [comment]
Hi @lauracowen @aguibert based on our slack convo and Andy's comments above, I made the following changes

- added statement for `recoveryAuthDataRef` for SPNEGO w/ XA recovery
- restored `${}` variables to the examples. I added a brief callout note in the second example to point out that the DB property values were supplied by variables for portability and included a link to the variable substitution doc (also openede a bug to improve that doc)> I think the note is concise enough that it doesn't distract from the goal of the example but see what you think. 

https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/kerberos-authentication-jdbc.html

Andy, if these changes look good, can you add the `technical reviewed` label to this issue?  Let me know if further edits are needed. Thanks!

**Comment by aguibert** [comment]
Hi David, I just noticed that this XML is incorrect in the first snippet:
```xml
<featureManager>
  <jdbc-4.2>
</featureManager>
```
Instead, it should be:
```xml
<featureManager>
  <feature>jdbc-4.2</feature>
</featureManager>
```

other than this minor change it looks good so I'll add the reviewed label -- thanks!

**Comment by dmuelle** [comment]
Thanks Andy, I've updated that snippet:

https://draft-openlibertyio.mybluemix.net/docs/latest/kerberos-authentication-jdbc.html

**Comment by dmuelle** [comment]
Doc is now on vNext branch, will publish with 20.0.0.12 on 11.20

requesting peer review from @Charlotte-Holt

**Comment by Charlotte-Holt** [comment]
@dmuelle Peer review feedback:

- Just a global thing that I noticed is that you didn't use any contractions throughout the doc, which definitely isn't wrong, but it can read a little more formal that way. I know that we're allowed to use them in the OL docs, so just wanted to mention it. Otherwise, I think the topic reads very well and looks nice. 

### Global Kerberos configuration for Open Liberty
- [x] I think maybe the link text that's currently "kerberos" could be "kerberos element" to make it a little clearer
- [ ] The link to the JDBC feature doesn't go to the latest version of the feature, but maybe that was intentional because the example uses version 4.2? Or could the example be updated? 
- [x] "config file" --> "configuration file"

### Kerberos configuration for JDBC data sources
- [ ] Link to the JDBC feature doesn't go to the latest version here either 
- [x] I think that callouts aren't accessible in our docs, so we're going to have to remove them everywhere and rework the places where we currently have them. (I'll ping @steven1046 in the `openliberty-docs` channel to confirm.)

**Comment by dmuelle** [comment]
Thanks for reviewing @Charlotte-Holt. I made the changes that you suggested, with the exception of the feature version. Andy asked that al links go to JDBC v 4.2 instead of 4.3,  because they are basically the same but most users are likely to be using 4.2
