### ISSUE TITLE
Sychronous and asynchronous REST clients (MP38)

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#268]
sync/async is an advanced concept of REST clients so it might be appropriate to put this info in the REST clients topic (#36) (here’s how you do a REST client, here’s how you make it async, and here’s why you’d do that) or, if there's enough, a separate topic that is linked from the REST clients topic.

See https://openliberty.io/blog/2019/01/24/async-rest-jaxrs-microprofile.html
It may be that most/all of Andy's 'async' blog post should be converted into one or more topics (discuss with Andy whether all of it is relevant to this issue). If the material in the blog post is duplicated in doc topics, the blog post should then be redirected to the most appropriate of the new doc topics (the doc topics can benefit from the blog post's SEO then).

Contact: Andy McCright

**Comment by dmuelle** [comment]
Hi @andymc12,
I'm ready to put together a draft for this topic, but wanted to get your input on the general structure and direction. I think a big part of this will be interpreting your blog post on async services (which will of course be linked here) into a conceptual framework, and extending to include sync. As a loose outline:

*Intro
Something like: 
`REST clients can be implemented either synchronously or asynchronously. A synchronous client constructs an HTTP structure, sends a request, and waits for a response. An asynchronous client constructs an HTTP structure, sends a request, and moves on. In this case, another thread waits for the response and then notifies the client when the response arrives. Although asynchronous behavior can result in faster overall execution, synchronous behavior may be preferred in some cases (such as??) `

*Synchronous REST Clients
A section to briefly explain the advantages and drawbacks. I think I understand the drawbacks, but what are the advantages? Why would a dev want to use sync?  Simplified code? What is a  common or illustrative use case?  Then provide a code example...

*Asynchronous REST Clients
I think I can distill section from your blog post, explaining the advantages, using your example as a demo use case. Since this topic focuses on REST clients, I'll only briefly mention async on the server. Are there drawbacks to async? Things to watch out for? Then a short code example

*Sync/ async & Microprofile
Explain that MP is enabled for both sync and async, and discuss some of the MP features you touch on in your blog post


Let me know what you think and I'll put together a draft for your review- Thanks!

**Comment by andymc12** [comment]
Hi @dmuelle - I think that the outline looks good.  

One comment about the intro sentence - although the response is usually handled by a separate thread, that is not a hard requirement.  Maybe we could change this sentence:
```
In this case, another thread waits for the response and then notifies the client when the response arrives.
```
to something like:
```
In this case, the client is notified when the response arrives and the original or another thread may then process the response.
```

As for benefits to using synchronous clients... I think simplicity is probably the main (maybe only?) one.  No need to worry about callbacks, Futures, CompletionStages, etc.  

Hope this helps.  Thanks for writing this up!

**Comment by dmuelle** [comment]
Hi @andymc12 @lauracowen - here's a first draft for this topic. Let me know if I've left anything out or could explain anything more accurately. I've noted a couple places where we could offer code examples.

https://draft-openlibertyio.mybluemix.net/docs/ref/general/#/docs/concept/sync_async.html

thanks!

**Comment by andymc12** [comment]
Hi @dmuelle,

Looking good - here are a few comments:

> If a client is implemented synchronously, you don’t need to worry about managing callbacks, Futures or CompletionStage return types.

In that sentence, `CompletionStage` is highlighted as code, but `Future` is not.  They both should be highlighted, so it should read like:
If a client is implemented synchronously, you don’t need to worry about managing callbacks, `Future` or `CompletionStage` return types.



> Asynchronous clients rely on callbacks—functions that are executed after another function completes—to manage the transfer of data between microservices. The return type of the interface method determines whether a RESTful service is invoked synchronously or asynchronously. If the return type is a CompletionStage, the service is invoked asynchronously. A CompletionStage acts as a promise to the service that a particular piece of code will be executed. A wide range of callbacks can be attached to a CompletionStage, enabling different functions once the code executes. In this way, non-blocking systems can be implemented among microservices in an application.

This is true for the MP Rest Client, but not for JAX-RS clients.  For JAX-RS clients, the user must explicitly build an async client with an API call like:
```
Client client = ClientBuilder.newClient();
WebTarget target = client.target(url);
Invoker.Builder builder = target.request();
AsyncInvoker asyncInvoker = builder.async();
```

Then, at that point, the user can either choose to provide a callback or they can get a `Future`. For example:
```
Future<MyResponseObject> future = asyncInvoker.get(MyResponseObject.class);
// or
Future<MyResponseObject> future = asyncInvoker.get( new InvocationCallback<MyResponseObject>() {
    @Override
    public void completed(MyResponseObject o) {
        // do something with o
    }

    @Override
    public void failed(Throwable t) {
        // handle the failed request/response
    }
});


Thanks, Andy

**Comment by dmuelle** [comment]
Thanks, @andymc12 
I've updated this doc to distinguish between async with MP Rest client and JAX-RS

Can you provide a code snippet example for MPRC using CompletionStage, similar to the one you provided above for JAX-RS ? (If you think that would be helpful...)

**Comment by andymc12** [comment]
Sure - here is an example MP Rest Client interface that has methods to invoke the same remote service both synchronously and a synchronously:

```
@Path("/somePath")
public interface MyClient {

    @GET
    Widget getSync();

    @GET
    CompletionStage<Widget> getAsync();
}
```

And here is the code that would invoke it:
```
MyClient client = RestClientBuilder.newBuilder().baseUri(someUri).build(MyClient.class);

CompletionStage<Widget> cs = client.getAsync();
// while that request is running, let's invoke it synchronously too:

Widget widgetSync = client.getSync(); // now we have to wait until the request completes
// done.  So now we can see the results of the async request
// that was processing while we did the sync request:

Widget widgetAsync = toCompletableFuture().get();

assertEquals(widgetAsync, widgetSync);
```

**Comment by dmuelle** [comment]
published on Open Liberty, looks good

https://www.openliberty.io/docs/ref/general/#/docs/concept/sync_async_rest_clients.html
