### ISSUE TITLE
Config examples for the JavaMail feature

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#2831]
Example config for [the JavaMail feature](https://openliberty.io/docs/20.0.0.10/reference/feature/javaMail-1.6.html). See #2829:

```
<mailSession 	mailSessionID="examplePop3MailSession"  
		jndiName="ExampleApp/POP3Servlet/exampleMailSession"
		description="POP3 javax.mail.Session"
		storeProtocol="pop3"
		transportProtocol="smtp"
		host="exampleserver.com"
		user="iamanexample@example.com"
		password="example"
		from="smtp@testserver.com">
	 <property name="mail.pop3.host" value="pop3.example.com" />
	 <property name="mail.pop3.port" value="3110" />
</mailSession>
```

Resources:

- https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_admin_javamail.html
- https://github.ibm.com/was-WASdev/WASdevnet-website/tree/master/developer.ibm.com/wasdev/docs/write-application-using-javamail

**Comment by Charlotte-Holt** [comment]
Here's a link to the first draft: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/reference/feature/javaMail-1.6.html.

**Comment by uberskigeek** [comment]
Charlotte, This looks good to me. On a related issue are there plans to do this for Jakarta mail 2.0?

**Comment by neuwerk** [comment]
Looks good to me!

**Comment by Charlotte-Holt** [comment]
@uberskigeek Thx for reviewing! We don't currently have an issue open for config examples for Jakarta Mail 2.0, and I'm not seeing it in the OL feature doc (could just be overlooking it, though). Should it be in the OL docs, or has it not been released yet?

**Comment by lauracowen** [comment]
Jakarta Mail 2.0 seems to be part of Jakarta EE 9 (https://jakarta.ee/specifications/mail/), which will be why it's not part of our OL docs already (Jakarta EE 9 is currently in beta only).

@uberskigeek In general though, yes, this would be done for any new feature version (either the same example as for the previous version or a new example specific to the new version, as appropriate). So if you can provide an example in the UFO for that feature up-front, that would be great, and make it easy for us to add at the relevant time.

**Comment by lauracowen** [comment]
Thanks.

- Some of the info in the intro to the example (definitely the first sentence which talks about the fact that it's for use with an external mail server) would be better in the intro to the topic itself. At least as an "extended description" but, tbh, the intro sentence of "This feature allows applications to utilize the JavaMail 1.6 API." should really be re-written to be more informative. There's instructions on how to get this generated first sentence updated in this Boxnote: https://ibm.box.com/s/90b7dnmkcu9qv4uple03niz6u3wj1np2 (I think Richard's maybe done it recently if you need a pointer; I've done it but can't remember how beyond these instructions).
- I know there's only one example but it could maybe have a sub-heading to show what the example is of eg "Send and receive email from applications".
- Once you've moved the first sentence out of the example intro, I think remove "After  you add the JavaMail feature" as it's not really necessary - any config comes after you've enabled it.
- Then rather than saying "If you want to create..." just assume they want to if they're looking at this example and say something like "Create a javax... object in your application code then configure the mail session in the server.xml. The following example shows...".
- Would it be useful here to show a snippet of Java showing creating the Javax... object? Or do we have a dedicated JavaMail topic to come about that?
- "After the mail session is configured," - is this definitely the right word? The previous sentence says  "configured" to mean the config that's put in the server.xml during the application development. This second sentence seems to be talking about creating sessions at runtime - I'm not sure "configured" is the right word in the second sentence?
- I think you could simplify the text beneath the example to make it easier to read. eg "In the example, the ExampleMail is the name of the WAR file, SMTPSender is the class name that xxxx(does what?), and gmailSMTPSession is the name of the actual session object.  As long as it's easy to see those values in the example XML, I don't think you need to keep flagging up the name of the attribute to which the values belong - it's just harder and clunkier to read. If you think it's not so easy to find the values in the XML example, you could use the callouts to identify which lines they're on? Though with all of them being on the same line at the top of the example in this case, I think just giving the values is fine.

**Comment by uberskigeek** [comment]
Hi Laura do you have a new link for this --> https://ibm.box.com/s/90b7dnmkcu9qv4uple03niz6u3wj1np2 Seems this one has expired?
Thanks!

**Comment by lauracowen** [comment]
@uberskigeek  Try it again now. But I think you'll still need to log in to see it (can't make it publicly accessible while it's still in Box).

**Comment by uberskigeek** [comment]
Thanks Laura! I can get there now

**Comment by Charlotte-Holt** [comment]
@lauracowen Thanks for the review! Addressed as follows:

- [x] Some of the info in the intro to the example (definitely the first sentence which talks about the fact that it's for use with an external mail server) would be better in the intro to the topic itself. At least as an "extended description" but, tbh, the intro sentence of "This feature allows applications to utilize the JavaMail 1.6 API." should really be re-written to be more informative. There's instructions on how to get this generated first sentence updated in this Boxnote: https://ibm.box.com/s/90b7dnmkcu9qv4uple03niz6u3wj1np2 (I think Richard's maybe done it recently if you need a pointer; I've done it but can't remember how beyond these instructions). - **created a doc bug for this (#3232)**
- [x] I know there's only one example but it could maybe have a sub-heading to show what the example is of eg "Send and receive email from applications".
- [x] Once you've moved the first sentence out of the example intro, I think remove "After you add the JavaMail feature" as it's not really necessary - any config comes after you've enabled it.
- [x] Then rather than saying "If you want to create..." just assume they want to if they're looking at this example and say something like "Create a javax... object in your application code then configure the mail session in the server.xml. The following example shows...".
- [x] Would it be useful here to show a snippet of Java showing creating the Javax... object? Or do we have a dedicated JavaMail topic to come about that? - **Confirmed with @uberskigeek that adding the `mailSession` element (shown in the example) creates a `javax.mail.Session` object.**
- [x] "After the mail session is configured," - is this definitely the right word? The previous sentence says "configured" to mean the config that's put in the server.xml during the application development. This second sentence seems to be talking about creating sessions at runtime - I'm not sure "configured" is the right word in the second sentence?
- [x] I think you could simplify the text beneath the example to make it easier to read. eg "In the example, the ExampleMail is the name of the WAR file, SMTPSender is the class name that xxxx(does what?), and gmailSMTPSession is the name of the actual session object. As long as it's easy to see those values in the example XML, I don't think you need to keep flagging up the name of the attribute to which the values belong - it's just harder and clunkier to read. If you think it's not so easy to find the values in the XML example, you could use the callouts to identify which lines they're on? Though with all of them being on the same line at the top of the example in this case, I think just giving the values is fine.

https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/reference/feature/javaMail-1.6.html

**Comment by lauracowen** [comment]
thanks

**Comment by ManasiGandhi** [comment]
@Charlotte-Holt The topic looks good! A few edit suggestions:

- [ ] In "Send and receive email from applications", is this sentence "To enable the following configuration, in addition to enabling the JavaMail feature, you must also enable the Java Naming and Directory Interface feature in your server.xml file:" about configuring the mailSession element. If so, could you change it to "In the following example, in addition to enabling the JavaMail feature, you must also enable the Java Naming and Directory Interface feature in your server.xml file to configure a MailSession element " .

- [x] "Java Naming and Directory Interface feature" Could you remove the link from the word "feature"? 


- [x] In "This example mail session is configured so that it can be used for both SMTP and IMAP on Gmail." shlould the the terms SMTP and IMAP be spelled out.

- [x] "After you configure the mailSession element, the mail session is created and injected by using the Java Naming and Directory Interface (JNDI).", you could spell out JNDI at the first mention in the previous paragraph and just use an acronym here.

**Comment by Charlotte-Holt** [comment]
I addressed your feedback, @ManasiGandhi. Thanks! https://draft-openlibertyio.mybluemix.net/docs/21.0.0.2/reference/feature/javaMail-1.6.html

**Comment by chirp1** [comment]
@Charlotte-Holt 
A particularly nice and detailed write-up for the example! A couple of comments: 
- Would you open a doc bug against development for the opening paragraph for the feature? It just repeats the title. The first paragraph of "About this task" seems to have info appropriate for the opening paragraph: https://www-03preprod.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_admin_javamail.html You could write a suggestion for the opening paragraph for development.
- A couple of comments for "Send and receive email from applications": Do we have a style for the titles in the Example section? They seem to mainly be nouns to me instead of verbs. If that's the case, would you reword to have it start with a noun/noun phrase? Also, I think that the current title is missing "to" (meaning send an email "to" and application and receive an email "from" an application).
- For "In this example, ExampleMail is....". remove "In this example" as it isn't needed. Reword the sentence. Acrolinx flags it as a run on sentence. Also, when you rewrite the it, don't start the sentence/sentences with a value.

**Comment by Charlotte-Holt** [comment]
@chirp1 I addressed all your feedback: 

- [x] Would you open a doc bug against development for the opening paragraph for the feature? It just repeats the title. The first paragraph of "About this task" seems to have info appropriate for the opening paragraph: https://www-03preprod.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_admin_javamail.html You could write a suggestion for the opening paragraph for development. - **opened at https://github.com/OpenLiberty/docs/issues/3617**
- [x] A couple of comments for "Send and receive email from applications": Do we have a style for the titles in the Example section? They seem to mainly be nouns to me instead of verbs. If that's the case, would you reword to have it start with a noun/noun phrase? Also, I think that the current title is missing "to" (meaning send an email "to" and application and receive an email "from" an application). - **We discussed this morning on the OL scrum that we would go with a declarative structure, and David's updating the guidance** 
- [x] For "In this example, ExampleMail is....". remove "In this example" as it isn't needed. Reword the sentence. Acrolinx flags it as a run on sentence. Also, when you rewrite the it, don't start the sentence/sentences with a value.

**Comment by chirp1** [comment]
HI Charlotte, 
One last tweak. For the first sentence in the example configuration, work in send/receive so that send/receive is mentioned not only on the title but in the body of the example- something like "You can call the JavaMail libraries in any application that runs on the server to send and receive emails.".

**Comment by Charlotte-Holt** [comment]
@chirp1 Update made and back with you. Thanks! https://draft-openlibertyio.mybluemix.net/docs/21.0.0.2/reference/feature/javaMail-1.6.html

**Comment by chirp1** [comment]
Updates look good!

**Comment by Charlotte-Holt** [comment]
Merged to `vNext` in https://github.com/OpenLiberty/docs/pull/3642
