### ISSUE TITLE
Add links to relevant guides from each section of the MP Intro topic

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#293]
https://openliberty.io/docs/intro/microprofile.html

Find the relevant guides and add links to each section (find a consistent, as concise as appropriate way to do it).

**Comment by dmuelle** [comment]
Draft up for review now at

https://draft-openlibertyio.mybluemix.net/docs/intro/microprofile.html

- I couldn't find a guide for `Implement reactive programming for microservices`, or anything in the guides about MicroProfile Reactive Streams Operators- am I missing it or is there something in the works?

- as it is now, I've added the links at the end of each section in the format

*Try it out:*  Learn how to x in our interactive guide to [link]

The problem is, the headings for each of these sections are H4, and the styling of the link hypertext stands out more than the section headings. I'm not sure what the best solution is- maybe some kind of custom styling/div for these links? @steven1046 any ideas?

**Comment by lauracowen** [comment]
Thanks.

Comments:
- All the guides you've linked to aren't actually "interactive guides". We use the term "interactive guides" to refer to a specific set of four guides: https://openliberty.io/guides/?search=interactive&key=tag  So can you remove the word "interactive" from each "Try it now" sentence?
- Do you think we could/should include all of the relevant guides in each section (eg Fault Tolerance has about four; Health has two)?

Reactive programming - you're right, there's no guide for that yet. Just leave that section without a link.

Headings - I've raised an issue about H4 being so small: https://github.com/OpenLiberty/openliberty.io/issues/1254
Can you remove the bold from "Try it now"? I think it's fine just as normal text - it's a separate paragraph anyway.

**Comment by dmuelle** [comment]
These edits are now in the draft site-

https://draft-openlibertyio.mybluemix.net/docs/intro/microprofile.html

I've added links to all the relevant guides that I could find for each section, lmk if I've missed anything.

**Comment by lauracowen** [comment]
I think you've got them all. Would it be possible to make the multiple guides entries more concise? (fault tolerance and config)  I'm guessing you've grabbed the descriptions from the guides themselves but in this context, some of the FT descriptions could apply to any of the guides. Maybe just intro them all as making microservices fault tolerant, then providing a list of links?

**Comment by dmuelle** [comment]
Ok I've consolidated the links and it does improve readability I think

https://draft-openlibertyio.mybluemix.net/docs/intro/microprofile.html

However- the heading issue is still hampering readability significantly. The quick fix might be to bump up the headings so that H4 becomes H3 and H3 becomes H2 ( current H2s remain the same). This would put the `MicroProfile simplifies developing cloud-native Java microservices` and related headings on equal footing with `MicroProfile simplifies developing cloud-native Java microservices` and the like. Which I don't think would hurt anything, and furthermore is a change I could make without any additional CSS work needed.

That said: the pie-in-the-sky solution here would be consistent, custom styling for each section of links, preferably including some kind of background shading similar to what is currently in place for the H2 headings (though subordinate to that styling). We'd still need bigger H4 headings. This would make the page easier to read, easier to scan, easier to navigate between info and link resources, esp if someone had the page bookmarked and was working through multiple guides (which is what we want!).

**Comment by lauracowen** [comment]
I agree. I've already raised this issue to fix the headings: https://github.com/OpenLiberty/openliberty.io/issues/1254

However, I think your suggestion of just bumping the headings is reasonable. I think we should avoid H4 where we can anyway to ensure a simpler structure of navigation within the page.

@dmuelle Can you make the change to the headings and then check it on the draft site? If it looks okay, do a PR to `develop`. Thx

I've also created this issue to make the list items more compact: https://github.com/OpenLiberty/openliberty.io/issues/1265

**Comment by dmuelle** [comment]
All headings have been updated to either H2 or H3- I do think this helps readability
Creating PR to dev

https://draft-openlibertyio.mybluemix.net/docs/intro/microprofile.html

**Comment by dmuelle** [comment]
these updates are now live at

https://www.openliberty.io/docs/intro/microprofile.html
