### ISSUE TITLE
Mention IntelliJ plugin in dev mode documentation

### ISSUE THREAD

**Issue by ericglau** [OpenLiberty/docs#3179]
In the dev mode doc, there is currently a section for the Open Liberty Tools VS Code extension https://openliberty.io/docs/20.0.0.11/development-mode.html#_vs_code_extension_for_dev_mode 

Also mention the equivalent Open Liberty Tools plugin for IntelliJ IDEA and link to https://plugins.jetbrains.com/plugin/14856-open-liberty-tools

Reference material:
https://openliberty.io/blog/2020/09/03/open-liberty-tools-intellij.html

**Comment by ericglau** [comment]
cc @kathrynkodama in case more information is needed for this

**Comment by dmuelle** [comment]
Added a section for the Intellij extension:
https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/development-mode.html#_intellij_extension

This update will publish with 20.0.0.12

**Comment by kathrynkodama** [comment]
@dmuelle  Can we match the VS Code section so that it reads:

"After you install the extension and enable either the Maven or Gradle plug-in, your project name is listed under the Liberty Dev Dashboard. You can interact with dev mode by right-clicking on your project name, or selecting a command from the drop-down list for the project name. Alternatively, you can use the Run Liberty Dev Task option in the dashboard toolbar."

I also think we should either remove the commands section or add a similar paragraph to the VS Code extension section. Maybe it could be shortened to "For more information, see the [full list of commands](https://github.com/OpenLiberty/open-liberty-tools-intellij#commands)." and add the same sentence to the VS Code extension section. 

Here is the same commands link for the VS Code extension: https://github.com/OpenLiberty/open-liberty-tools-vscode#commands

**Comment by dmuelle** [comment]
Thanks @kathrynkodama! Working on that change - to clarify

"Alternatively, you can use the Run Liberty Dev Task option in the dashboard toolbar"

Is that option available for both maven and Gradle users or just Gradle? If it's just Gradle, is there an equivalent option for Maven users?

**Comment by kathrynkodama** [comment]
Thank you @dmuelle - the "Run Liberty Dev Task" option is for both Maven and Gradle projects

**Comment by dmuelle** [comment]
Hi @kathrynkodama @ericglau 

TO avoid repeating identical information for each extension, I've combined the common info into one section and supplied links to each download and GitHub repo. See if this makes sense and is accurate for both VS Code and Intellij:

https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/development-mode.html#_open_liberty_tools_for_vs_code_and_intellij

If not, I can edit as needed or revert to the previous content organization.

**Comment by kathrynkodama** [comment]
Thanks @dmuelle, I think the new combined section makes more sense. Just a few notes:
- The "Run Liberty Dev Task" option is only available in the IntelliJ plugin, not the VS Code plugin.
- "Open Liberty Tools for VS Code on GitHub" is all hyperlinked, but only "Open Liberty Tools for IntelliJ" is hyperlinked.

**Comment by ericglau** [comment]
The link to Open Liberty Tools for IntelliJ on GitHub is missing a j in the URL.

**Comment by dmuelle** [comment]
Apologies, I should have checked that closer before sending. Here is an update:

https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/development-mode.html#_open_liberty_tools_for_vs_code_and_intellij

let me know if it needs anything further. Thanks!

**Comment by ericglau** [comment]
I just noticed the IntelliJ one should be written as "JetBrains Marketplace" according to [this](https://plugins.jetbrains.com/docs/marketplace/).  The rest looks good to me, thanks.

**Comment by dmuelle** [comment]
@ericglau  I made that change: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/development-mode.html

This update will publish on Friday 11.20 with the 20.0.0.12 release. Thanks!

**Comment by ericglau** [comment]
@dmuelle Thanks, it looks good.
