### ISSUE TITLE
Update "Health Checks for microservices" document for MpHealth 3.0

### ISSUE THREAD

**Issue by pgunapal** [OpenLiberty/docs#3292]
MP Health 3.0 Epic: https://github.com/OpenLiberty/open-liberty/issues/11472
OL Beta Blog: https://github.com/openliberty/open-liberty/issues/13510

The "Health Checks for microservices" document (https://www.openliberty.io/docs/20.0.0.11/health-check-microservices.html) needs to be updated with the new updates from MpHealth-3.0.

- Add a note/clarification for all references of `@Health` that if the user is using mpHealth-3.0 or later, the `@Health` annotation is no longer available, since the deprecated `@Health` annotation was removed in MpHealth-3.0.
- The following line should be replaced in the `@Liveness` annotation code example, as the `state` method was renamed to `status` in 3.0:
Replace: `.state(memUsed < memMax * 0.9)`
With: `.status(memUsed < memMax * 0.9)`
Similarly, it would be good to add a note/clarification that users can use `.state` in versions earlier than mpHealth-3.0, but starting from mpHealth-3.0, they would have to use `.status` instead.
- Mention a note that the overall default Readiness status will be DOWN, with an empty response until all the deployed application(s) have been started in Open Liberty (existing behaviour since mpHealth-2.0). Starting with mpHealth-3.0, a new MicroProfile Config property (mp.health.default.readiness.empty.response=UP) is introduced to change this overall default Readiness check status to UP, during application start up, that do not have any user-defined health checks.

**Comment by chirp1** [comment]
Prashanth and I made some updates to the description for clarity. The description looks good. Also, I mentioned to Prashanth to be sure to include enough information in the blog post for the feature so that a customer can use the feature.  ID is working down a backlog for Open Liberty, so updates for Open Liberty might or might not be made when the feature goes out.  Approving the Epic.
Also, from Prashanth, here is a link to a discussion about the 1.0 version of the feature: https://www.ibm.com/support/knowledgecenter/SS7K4U_liberty/com.ibm.websphere.wlp.zseries.doc/ae/twlp_microprofile_healthcheck.html     And then, on the WebSphere Liberty side, Prashanth opened issue 2154 for updates to the WebSphere Liberty documentation.

**Comment by dmuelle** [comment]
Hi @pgunapal - I've updated this doc per your instructions. You can review the draft here:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.2/health-check-microservices.html

- [x] Add a note/clarification for all references of @Health that if the user is using mpHealth-3.0 or later, the @Health annotation is no longer available, 
- [x] The following line should be replaced in the @Liveness annotation code example, as the state method was renamed to status in 3.0:
- [ ] Mention a note that the overall default Readiness status will be DOWN... 
**for this last one, I've added the info but I think it needs a little more clarification:**
- What does an "empty status" mean? Does is it mean no values returned for the `name` and `status` keys?
- I'm not sure I understand the following: "change this overall default Readiness check status to UP, during application start up, **that do not have any user-defined health checks**." Can you elaborate? I made a guess at this in the draft, not sure if I got it right.

Let me know what you think, thanks!

**Comment by pgunapal** [comment]
@dmuelle The draft looks good, a few clarification:
- Correct, the empty response means the JSON checks payload response that gets returned when the `/health/ready` endpoint is hit, it will be empty, with an overall status of DOWN, until all the deployed applications are started. The following would be shown:
`{
  "status": "DOWN",
  "checks": []
}`
- I think its best to remove the "that do not have any user-defined health checks." line, since it might lead to confusion. Basically, this property is introduced to revert back to the old behaviour, where users may want the container to be ready, before their deployed applications have fully started up. Its better just stating the following:
"In MicroProfile Health versions 3.0 and later, the `mp.health.default.readiness.empty.response=UP` MicroProfile Config property is available, so you can specify this property to change the overall default readiness status to UP, when deployed applications are still starting up."

**Comment by dmuelle** [comment]
Thanks for clarifying @pgunapal - I've updated the draft per your comment

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.2/health-check-microservices.html

Can you review the updated draft and let me know if any further changes are needed? If the doc looks good, you can add the `technical reviewed` label to this issue to sign off. Thanks!

**Comment by pgunapal** [comment]
@dmuelle Looks good! Just a minor change, in the line `In MicroProfile Health versions 2.0 and later, the overall default readiness status is DOWN, with an empty response, until all the deployed applications in Open Liberty are started.`, the DOWN word should be highlighted as `DOWN`.

**Comment by dmuelle** [comment]
Thanks for the catch @pgunapal - I made that edit: https://draft-openlibertyio.mybluemix.net/docs/latest/health-check-microservices.html

**Comment by pgunapal** [comment]
@dmuelle  Awesome! I added the `technical reviewed` label.

**Comment by Charlotte-Holt** [comment]
@dmuelle - I reviewed this from a content perspective, and I think these changes for MP Health 3.0 all look good. I read back through the entire topic, and I thought it flowed pretty nicely. Adding the content reviewed label.

**Comment by Rwalls1** [comment]
# Peer review
@dmuelle Your updates look good, I just have a few comments related to separate things that I noticed while reviewing your updates
## Intro
- Typo: Change  "Services report as their availability by implementing the API provided by MicroProfile Health.” to “Services report their availability by implementing the API that is provided by MicroProfile Health.
## MicroProfile Health endpoints and annotations
- The `@Liveness` annotation contains the phrase, "// status is up if used memory is < 90% of max”, appears to be a comment that reiterates what was stated in the paragraph above. I think it should be removed as it doesn’t add any value to the example
- The phrase, " add either the `@Liveness` or `@Readiness` annotation to your code.” seems a bit ambiguous and could potentially be confusing. While it is hinted at in the intro, I think specifying the particular API where the annotations are added rather than saying you’re adding the annotations “to your code” would make things clearer by furthering establishing the connection between the annotations and REST API.
- I think you should also specify where the code or annotations reside for both the `@Liveness` and `@Readiness` code examples. I think this would add more valuable context to help better understand how the annotations work within the framework of REST API.
- I think you should clarify the relationship between heap memory usage, memory consumption/usage, and  resource availability/availability to maintain consistency throughout the topic and avoid confusion. In the intro, the topic references the `UP` and `DOWN` statuses for microservices by stating whether they are “available” or unavailable”. Then, when describing the @Liveness annotation, the topic uses the terms “memory consumption” and “memory usage” to refer to the status of the microservice.” Also, the description of the health/live endpoint uses the term “heap memory usage”. I think a single term should be used to reference the use of memory when describing how it affects service status. To show the relationship between the microservice and availability, for example when describing the `@Liveness` annotation, you could say something like, "If memory usage exceeds 90%, it returns a `DOWN` status to indicate that the service is unavailable:" when the statuses are described.

**Comment by dmuelle** [comment]
Hi Richard- Thanks for this review- you helped me catch some imprecision that had been in this doc for a while, hopefully fixed now. I rewrote a good bit of the topic so I sent it back to Prashanth to be reverified from a technical perspective. He said it looked good

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/health-check-microservices.html

- [x] Typo: Change "Services report as their availability by implementing the API provided by MicroProfile Health.” to “Services report their availability by implementing the API that is provided by MicroProfile Health. **fixed**
- [x] The phrase, " add either the @Liveness or @Readiness annotation to your code.” seems a bit ambiguous and could potentially be confusing. **I tried to make this more clear by stating that you add it on a class that implements the HealthCheck interface, and linked to the javadoc for that. This seemed consistent with what I saw in the spec and elsewhere**
- [x] I think you should also specify where the code or annotations reside for both the @Liveness and @Readiness code examples. **added clarification to example intros**
- [x] I think you should clarify the relationship between heap memory usage, memory consumption/usage, and resource availability/availability to maintain consistency throughout the topic and avoid confusion **reworked these sections to be more precise, see if you agree**

**Comment by dmuelle** [comment]
moving this to ready-to-publish but waiting to move to staging until I can conform the updated link to MP 4.0 javadoc. Link will appear broken until autogen updates

**Comment by dmuelle** [comment]
content is on vNext and will publish with 21.0.0.3
