### ISSUE TITLE
Suggested JPA example config

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#3335]
From reviewing KC (check with SMEs for relevance).

This set of topics in the KC https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_config_jpa.html contain various example config and not much else.

Check with SME whether they're useful examples to include in the JPA feature: https://www.openliberty.io/docs/20.0.0.11/reference/feature/jpa-2.2.html

I think Fred had said nothing was needed. But it might be that some of these are useful even if they're not needed in order to just get JPA working - so check with him.

Only mention JPA 2.1 stuff (the rest isn't relevant to Open Liberty).

SME: Fred Rowe

**Comment by dmuelle** [comment]
The JPA info for 2.1 and later is documented by eclipse: https://wiki.eclipse.org/EclipseLink/Examples/JPA/Logging

Could add a statement to the JPA doc to see the eclipselink doc

also, possibly doc adaptations for 2.0->2.1 via eclipse properties in persistence.xml

**Comment by frowe** [comment]
I think the jpa 2.1 logging info is useful for troubleshooting but beyond that, I would suggest referring to the eclipselink doc for further info.

**Comment by dmuelle** [comment]
Hi @frowe , I've added the JPA logging examples/info from KC to the JPA feature page, as well as some links to EclipseLink for more info. Can you please review the draft?

https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/jpa-2.2.html

If any changes are needed, just let me know. Otherwise, you can add the `technical reviewed` tag to this issue to sign off. Thanks!

**Comment by frowe** [comment]
1) "In this example, the JPA=all value you for the traceSpecification attribute specifies that all JPA container trace"
'you' typo?
2) because the point of adding the logging examples is the explain the different log levels (and not the other logging element attributes) consider simpler examples:
Instead of 
```<logging  traceSpecification="JPA=all"
  traceFileName="trace.log"
  maxFileSize="20"
  maxFiles="10"
  traceFormat="BASIC" />
```
consider 
```<logging  traceSpecification="JPA=all />```

**Comment by dmuelle** [comment]
Thanks @frowe - I've made these edits

https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/jpa-2.2.html

If anything further is needed, just let me know. Otherwise, you can sign off by adding the `technical reviewed` label to this issue

**Comment by Rwalls1** [comment]
# Content review
The examples look good, I just have a few comments:
- I think you should change “When the Java Persistence API feature” to “When the Java Persistence API feature (JPA), to clearly identify what the “JPA” abbreviation you use throughout the rest of the example description refers to.
- We can revisit the strategy for these config example pages, but I don’t think the list that begins with the phrase, “The following trace strings” belongs on this page and would be better to include on separate reference page if valuable. However, I think it provides information that isn’t needed to understand the config examples that are mentioned and the list just mostly repeats what’s mentioned in the example descriptions. The only part of that list that a reader needs to know to understand either of the examples is that “sql” is an EclipseLink log category, which can just be mentioned in the "EclipseLink SQL trace" example description. I think rather than including the list, I think this page would be more effective if there were three different sections that aligned with the three different config examples that are mentioned in the list. So, in addition to the “Configure JPA logging”  section, you could add a section that discusses the `eclipselink=all` example and add a section heading for the “EclipseLink SQL trace,” example and description.
- I think the consecutive sentences that start with “For more information about” is too repetitive. I think it would be better to reference these sources more strategically rather than just clustering them at the end of the page. For example, you could provide a link to the “SessionLog interface” when you first mention the EclipseLink log categories. I think you should take a similar approach with the other links if possible.

**Comment by dmuelle** [comment]
Thanks for reviewing @Rwalls1 - I made the following changes per your review:

- [x] I think you should change “When the Java Persistence API feature” to “When the Java Persistence API feature (JPA
- reworked how the examples were presented to show eclipseLink categories without the redundant list
- Revised links to be in the body text instead of collected at the end of the example

**Comment by ManasiGandhi** [comment]
@dmuelle Peer review of JPA example config. Looks good! A couple suggestions:
# Peer review 

- [x] Instead of "Examples", could you say "Example" as currently, there is only one example.
- [x] Typo, please change, "For example, to enable EclipseLink SQL trace, you can specify configuration similar to the following example:"to "For example, to enable EclipseLink SQL trace, you can specify a configuration similar to the following example:"

**Comment by dmuelle** [comment]
Thanks for reviewing @ManasiGandhi - I made both those changes- 

https://github.com/OpenLiberty/docs/issues/3807#issuecomment-840016126
