### ISSUE TITLE
Doc changes needed in Knowledge Center (JAX-RS 2.0 behavior changes)

### ISSUE THREAD

**Issue by jim-krueger** [OpenLiberty/docs#3336]
There are a couple mistakes in the JAX-RS 2.0 behavior changes section of the knowledge Center (https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/cwlp_jaxrs_behavior.html).  IMultipartBody and IAttachment are not annotations.

Current text:
JAX-RS 2.0 includes many API changes when it handles the MultiPart file. For example, in JAX-RS 1.1, the @FormParam can be used to handle the MultiPart file, but in JAX-RS 2.0, only @IMultipartBody or @IAttachment can be used to handle the MultiPart file. For more information, see Configuring a resource to receive multipart/form-data parts from an HTML form submission in JAX-RS 2.0.

Suggested text:
JAX-RS 2.0 includes many API changes when it handles the MultiPart file. For example, in JAX-RS 1.1, the @FormParam can be used to handle the MultiPart file, but in JAX-RS 2.0, only IMultipartBody or IAttachment objects can be used to handle the MultiPart file. For more information, see Configuring a resource to receive multipart/form-data parts from an HTML form submission in JAX-RS 2.0.

**Comment by dmuelle** [comment]
Hi @jim-krueger - since this page doesn't exist in the Open Liberty docs ands is only available in Liberty KC, I've copied the issue to the Liberty docs backlog to track the fix there: https://github.ibm.com/was-liberty/liberty-docs/issues/2163

Since JAX-RS 1.1 is only available in commercial Liberty and not OL, we haven't targeted this behavior differences doc for OL. I'll make the fix in the KC doc.

Closing this issue
