### ISSUE TITLE
Suggested topic area: transactionality

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#3348]
From KC review (check with Alasdair for relevance/priorities).

This needs some introduction about what is transactionality (briefly) and why/when you need it in your app. Then what the options are in OL and when you'd use them. Some of that info might be in this [KC topic](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_admin_trans_service.html) and in this [KC second topic](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_store_logs_in_rdb.html), though that KC topic's focus is on using a relational database rather than generally about transactionality in your OL apps. The info in [this third KC topic](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/rwlp_ds_tx_recovery.html) might also be useful in the introduction when talking about how it works.

**Comment by dmuelle** [comment]
see https://github.com/OpenLiberty/docs/issues/4423

comments from KC tracking sheet for these topics

<div ccp_infra_version='3' ccp_infra_timestamp='1626357664556' ccp_infra_user_hash='3774073639' ccp_infra_copy_id='32e7c29c-d864-4028-8a38-4760d27befaa' data-ccp-timestamp='1626357664556'><html>

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">

</head>

<body link="#0563C1" vlink="#954F72">



Administering the transaction service on Liberty | Transactionality.
-- | --
Configuring the startup of the transaction service | This is reference info that's in the gendoc: https://www.openliberty.io/docs/latest/reference/config/transaction.html
How database transactions are recovered | Bits of info that should be with the first topic.
Storing transaction logs in a relational database | Bits of info that should be with the first topic.



</body>

</html>
</div>

**Comment by dmuelle** [comment]
try to condense down to a single topic

**Comment by dmuelle** [comment]
more general info on transactionality from tWAS: 
https://www.ibm.com/docs/en/was-nd/9.0.5?topic=resources-transaction-support-in-websphere-application-server

**Comment by dmuelle** [comment]
Hi @jonhawkes - can you provide technical review of the draft at

https://draft-openlibertyio.mybluemix.net/docs/latest/transaction-service.html ?

This doc provides the conceptual foundation in the OL docs for the ID updates needed for  #4423 / [8968](https://github.com/OpenLiberty/open-liberty/issues/8968).

It interpolates information from the following KC /IBM Docs topics for WebSphere Liberty:
- [Administering the transaction service on Liberty](https://www.ibm.com/docs/en/was-liberty/nd?topic=manually-administering-transaction-service-liberty)
- [Configuring the startup of the transaction service](https://www.ibm.com/docs/en/was-liberty/nd?topic=liberty-configuring-startup-transaction-service)
- [How database transactions are recovered](https://www.ibm.com/docs/en/was-liberty/nd?topic=liberty-how-database-transactions-are-recovered)
- [Storing transaction logs in a relational database](https://www.ibm.com/docs/en/was-liberty/nd?topic=liberty-storing-transaction-logs-in-relational-database)

I have a few questions about areas of the topic where we could add a little more contextual info, but might be easier if first you can verify what is already there is accurate, relevant, and current. Not sure if any of the info from the  IBM Docs topics was in need of an update.

We can also discuss whether the info for  #4423 should be worked into this topic or placed in its own doc.

If there's anyone else I should contact in addition or instead, please let me know. If possible, this can publish with the 21.0.0.8 docs release next week. Otherwise, it will go out with the #4423 info in 21.0.0.9. Thanks!

**Comment by dmuelle** [comment]
Hi @jonhawkes - I have a couple questions about parts of this topic where we could supply a little more contextual information for users who might not be familiar with  transaction service functions.

- we give an example of configuring recovery to occur at server startup rather than when the service is first used (`recoverOnStartup`). Why or when might someone want to configure this option? What is the benefit?

**You might want transaction recovery to happen at server startup so that the processing overhead happens then rather than right at the time you want to start doing transactional work. By default this setting is false so the server starts up faster.**

> "Setting the acceptHeuristicHazard attribute to false specifies that not all applications on this server accept the possibility of heuristic hazard in a two-phase transaction that contains a one-phase resource." 

What is the result of this setting? How does it change the server behavior or enable the configuration? Generally w/ Open Liberty we focus on  cloud native app scenarios where a single app runs on a server. 

**This setting enables last participant support (LPS). LPS allows a single one-phase resource to participate in a two-phase transaction with one or more two-phase resources. The name of the setting was (back in tWAS days) originally supposed to make it clear that enabling LPS carries some risk of a heuristic outcome for the transaction in the event of a network failure on the commit of the one-phase resource. The sentence here should be replaced.**

> You can configure an Open Liberty server to recover the logs of a different application server. The original owning application server must not be running when you use this procedure. It is typically employed to perform any outstanding transactional recovery when the transaction service logs are available but the original owning application server cannot be started.

This tells you that you can do this and why you would, but it doesn't tell you how. Could we provide a code example?
**This should be removed. This scenario will be covered in the section I will supply for the new feature.**

> If you store transaction logs in an RDBMS, each server must have its own tables. You can specify a unique table suffix by using the transactionLogDBTableSuffix attribute for the transaction element. The value for this attribute is a string that is post-pended to the table name to make it unique to the server where the table is hosted.

Can we provide a code example for `transactionLogDBTableSuffix` ? Is it as simple as

```xml
<transaction transactionLogDBTableSuffix="MyServer1" />
```
**Yes**

Lastly, the "Manual configuration of database tables" section provides DDL examples, but doesn't explain how or where to implement them. Is this code that would go into the `server.xml`? It also says "you must create the two database tables manually..." but doesn't explain why you need two tables. In general seems like a lot of information was missing from [the IBM Docs source](https://www.ibm.com/docs/en/was-liberty/nd?topic=liberty-storing-transaction-logs-in-relational-database), leaving it to the user to either know or not know how to use the DDL examples. If these examples are likely to be useful to a majority of users, we should provide more context to explain how to implement them. Also want to make sure the examples are current- not sure if the "old version of Db2" is still in wide use. If not, we shouldn't document it.

**This part does seem to have lost a lot compared to what we had here. The sentence about providing HA support is not true and the sentence about this being supported for production use is no longer necessary.
This Liberty doc was originally extracted from the tWAS doc and it was assumed the audiences would be the same people. For example it was assumed that anyone contemplating putting their transaction logs in a database would be sys admins who would know how to use DDL. The examples are current but I'm not sure whether they're really necessary anymore. Originally Liberty could only automatically create tables in  DB2 and Oracle for this so we provided the DDL examples so that sys admins could adapt them for whatever other database they wanted to use. (DDL is not standardized so it differs between different database vendors). In practise, the only other databases we've seen in use are PostgreSQL and MSSQL, and they're both automatically supported by Liberty now.**


Thanks!

**Comment by dmuelle** [comment]
updated draft per @jonhawkes email thread:
https://draft-openlibertyio.mybluemix.net/docs/latest/transaction-service.html

**Comment by dmuelle** [comment]
Jon is out though 8/11- pushing this out to 21.0.0.9

**Comment by dmuelle** [comment]
Updated draft that contains the information required for #4423 

https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.9/transaction-service.html
