### ISSUE TITLE
Troubleshooting security

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#3392]
We need a new doc that covers security troubleshooting. Format the doc in terms of "I'm doing x and getting this error." And solution is "do y". Don't just add general information about security issues. Include the relevant sections from https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_trouble.html:
- https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_trouble.html#rwlp_trouble__sec01
- https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_trouble.html#rwlp_trouble__ldap01
- https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_trouble.html#rwlp_trouble__ssl01
- https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_trouble.html#rwlp_trouble__wssec01
- https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_trouble.html?view=kc#rwlp_trouble__saml01

Check with @arkarkala whether the sections in the KC topic are still relevant/useful. Additional items to include from #1686:

- TLS handshake fails (what are the symptoms though?): could be caused by certificate being expired or revoked so one or both parties don't recognised the certificate, or a mismatch between TLS versions used by client and server.

- Issue developers have with realms:
First, in security there is the concept of “realms”, which are sort of like domains or namespaces. Users and groups are scoped to realms. For example, admins at google is not the same as admins at paypal. With single sign on, it’s possible to have authentication provided in multiple realms, such as authenticating with a choice of paypal or google. In that case, liberty needs to know which realm that user or group belongs to. This is where access-ids come in. A user or a group in access-id form is usually (realm)/name. When using Json Web Tokens, a token attribute called the “issuer”, which is usually a URL, is used as the realm. So in the above example it looks like the issuer was https://idp.example.com. There’s a bit of an explanation here https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/cwlp_authorization.html#d337475e272 under “Access IDs and authorization”.
It’s a common developer problem to have applications failing with 403 (unauthorized) and then struggle to get the access-id correct in the xml.
When a “local” registry is used, such as quickStartSecurity or basicRegistry, access id’s aren’t needed, regular old groups and users will suffice.

- Consider adding in the ACME troubleshooting information, too: https://openliberty.io/docs/20.0.0.12/troubleshooting.html

**Comment by dmuelle** [comment]
## Content proposal

In `Troubleshooting Security` section of the TOC:
- Troubleshooting ACME certificates (done)
- Kerberos authentication to LDAP Servers---> Troubleshooting LDAP (include LDAP items from KC topic)
- Troubleshooting SSL (include KC items)
- Troubleshooting SSO (include SAML items from KC and other SSO)
- Troubleshooting Authorization? for non-SSO related auth items from KC

**Comment by ManasiGandhi** [comment]
Teddy's comment on Troubleshooting SSO
`Hi Manasi. This looks good. Please check also with @Ut Le or @areddy.`

**Comment by ManasiGandhi** [comment]
Jesse's comments on Troubleshooting LDAP,

- `The section about "unable to connect... due to exhaustion of usable sockets" seems misleading when you say "Make sure that the socket is not used and try again". They wouldn't know which socket to make sure is not used b/c the client is going to use an ephemeral port to connect to the LDAP server. Is this really a problem that customers hit? If so, they would need to either find which applications are using all the ports or file-handles. Otherwise, they need to increase the number of available file-handles. Is this really a problem that customers hit? If so, they would need to either find which applications are using all the ports or file-handles. Otherwise, they need to increase the number of available file-handles.` Removed, as it is not a common use case.
- `The "You get an exception on the LDAP server with heavy load" section seems very generic (this exception message would occur anytime your login was invalid on ANY registry). I would expect that somewhere in the log you would receive a NamingException with an error code 51 (LDAP_UNAVAILABLE) from the LDAP server. And this section should reference a WIMException.` Later `You can probably remove it.`
- `ServiceUnavailable - Not sure we really need the FFDC error code. That is generic to FFDC.
This section seems confusing...
Occasional connection exceptions accessing the LDAP server. For example, java.net.SocketException: Connection reset
If you experience problems with Kerberos authentication to an LDAP server, refer to error messages from your Open Liberty server or HTTP error messages to debug the problem. The following information can help determine the causes of common problems and error messages that are associated with Kerberos authentication to LDAP servers. This:If multiple user registries are configured for an Open Liberty server, all basic, custom, and LDAP user registries are combined into a single federated user registry.should be:If multiple user registries and repositories are configured for an Open Liberty server, all can combined into a single federated user registry. This part
When Kerberos credentials are ina ccache file, Open Liberty attempts to auto-renew expiring credentials, which can result in slower performance.
probably should clarify WHEN the auto-renew occurs. My assumption is only if they are expired, and it only effects that single request (and any that stack up while renewing). Ask @kristip to verify.`

**Comment by ManasiGandhi** [comment]
Kristi Peterson comments on Troubleshooting LDAP
`We do try to renew shortly before the credentials have expired or when they are expired which is why I used expiring. But yes, the potential slower performance would be when we're attempting the auto-renew which would be shortly before expiration or when expired. Maybe something like When Kerberos credentials are in a ccache file, Open Liberty attempts to auto-renew credentials when the credentials are nearing the expiration time or expired. This can result in slower performance when the credentials are being renewed. `

**Comment by ManasiGandhi** [comment]
Alaine Demyers comments on Troubleshooting SSL

`I don't think You might get an exception if you use an LDAP user registry with sslEnabled
and a sslRef value is not specified is true anymore.  I think if sslEnabled is specified and sslRef is not the SSL default is used.` Removed the content as not applicable.

Later,
`Looks good`

**Comment by dmuelle** [comment]
@dmuelle I worked on your review https://draft-openlibertyio.mybluemix.net/docs/21.0.0.11/troubleshooting.html

## Peer review

Content is looking good but I think the formatting can be improved to remove some errors and make the content more readable. Let me know if you have any questions re description list syntax- I think it will make the page easier to read

### Global comments

- [x]  add a short description
- [x]  add an anchor list to the beginning of the topic that links to each subsection
- [x]  instead of H3 headings for the individual items, use description list syntax, eg
```
The certificate request times out::
If the certificate request times out, you can set a longer timeout value by using the challengePollTimeout and orderPollTimeout properties.
```
- [x]  edit the TOC to remove redundant child topics and make this topic the L2 "Troubleshooting security" entry

- [x] update links in ACME and kerberos topics and LDAP User Registry 3.0 reference page to point to the relevant sections of this doc
- [x] recommend re-running acrolinx as I see a number of minor issues

### Troubleshooting LDAP

- [x] ...you might see an error message like the following example in the messages.log file
---> ..you might see an error message in the messages.log file that is similar to the following example

- [x] `If you see this message, check your LDAP server to verify that it is running and that its IP address can be accessed from the Open Liberty server.` How can you tell if the IP address can be accessed from the OL server?

- [x] `If you enable SSL on your LDAP server without copying the signer of the LDAP server into the truststore that is referenced in the LDAPSSLSettings element, a connection with the LDAP server fails with an SSL handshake error.` This sentence is flagged in acrolinx as too long. Also, should specify the LDAPSSLSettings element in your server.xml file
- [x] need to clarify what is "the signer of the LDAP server" ? Is it a certificate? If so,should probably be something like "Make sure that you copy the signer certificate from the LDAP server into your truststore file."- but check with SME
- [x] Login, authentication, or authorization is slow for LDAP or a federated repository.
I think you need to recheck all three bullet points against what's in IBM docs- they are split up unevenly here and the info is jumbled together

- [x] Ensure that all participating base entries are responding promptly.
-->
Ensure that all participating base entries in the federated repository are responding promptly.

- [x] Occasional connection exceptions accessing the LDAP server. For example, java.net.SocketException: Connection reset
 same problem as previously mentioned- formatting errors and misplaced content: The description beneath it is the shortdesc from the Kerberos LDAP topic, not an actual description

- [x] recommend putting the kerberos stuff in a subsection of LDAP: Kerberos authentication to LDAP servers (include in anchor list). Also provide a link to  [Configure Kerberos authentication for LDAP servers](https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.10/reference/feature/ldapRegistry-3.0.html#krb5) at the end of the section

## SSL

- [x] recommend changing the same to "Troubleshooting SSL and TLS connection. But use TLS in all subsequent references. SSL is deprecated. You might include this explanation:
"Before the wide adoption of the TLS protocol, SSL was the standard protocol to secure web communications. Over time, many security vulnerabilities were identified for SSL and it is no longer in widespread use. However, for historical reasons, the term SSL is often used to refer to encrypted network connections even when TLS is in use. In Open Liberty, the term SSL is still used in feature and configuration names, even though TLS is the underlying protocol. Effectively, SSL is now a synonym for TLS."

- [x] You receive the CWWKS9105E message that the SSL port could not be determined for redirection
check formatting error

- [x] A keystore element exists in the configuration without an ID field and gives you an FFDC1015I error
the error message here seems like several error messages jumbled together that re very hard to read. Recommend putting each message in its own block

- [x] `fullPathTo/my.java.security` --> `_full_path_to_/my.java.security`

## other
### You receive a SESN0008E message...
- [x] This error occurs...
-->
This error might occur...

- [x]  The JSP page, by default, tries...
-->
By default, the JSP page tries...

### You receive a CWWKS9104A message that the user...

- [x] add  a link for "For more information, see [Authorization](https://www.openliberty.io/docs/21.0.0.10/authorization.html)

### Application installation causes unexpected security behavior

- [x] If you specify your application in both the server.xml files by using the application element and in the dropins folder,
--> If you specify your application in the server.xml file by using both the application element and in the dropins folder,

- [x] introduce message example with a colon instead of a comma

- [x] Check the error message-  Only part of the text is the actual message, the other half should be plain text. Edit as needed.
- [x]  If you must leave it in the dropins folder, you must disable the application monitoring by using the following code in your server.xml file, `<applicationMonitor dropinsEnabled="false"/>`.
---> put example code in a code block and don't need to include the `<>`

**Comment by dmuelle** [comment]
Changes look good but I see a few more things that need a fix:

- [ ] in the nav, the topic is nested in a heading with the same title. Remove the nesting so only the topic title is in the nav

### Troubleshooting LDAP

- [ ] the 3rd bullet under "Login, authentication, or authorization is slow for LDAP or a federated repository."

is the same information as whats there for to "Occasional connection exceptions when you access the LDAP server. For example, java.net.SocketException: Connection reset" . Recommend removing that bullet and putting its code example under the latter heading. For example, in that section it says "This process can cause a delay and can cause errors to be logged in the JVM logs. " You could introduce the code example after that sentence

- [ ] Users cannot log in, even if non-Kerberos enabled registries are available.--> this item should be in the kerberos section 
- [ ] For more information, see xref:reference:ldapRegistry-3.0.adoc#krb5 --->link isn't properly formatted

### Troubleshooting SSL and TLS

- [ ] CWWKS9105E: Could not determine the TLS port for automatic redirection. --->message block has stray formatting marks
- [ ] You get an error when you use a JDK from the WebSphere Application Server---> i think we should remove this item as references to tWAS don't belong in OL doc
- [ ] \`applicationMonitor dropinsEnabled="false"`  example has stray formatting marks

**Comment by ManasiGandhi** [comment]
@dmuelle I worked on your review https://draft-openlibertyio.mybluemix.net/docs/21.0.0.11/troubleshooting.html

- [x] in the nav, the topic is nested in a heading with the same title. Remove the nesting so only the topic title is in the nav
### Troubleshooting LDAP
- [x] the 3rd bullet under "Login, authentication, or authorization is slow for LDAP or a federated repository."
is the same information as whats there for to "Occasional connection exceptions when you access the LDAP server. For example, java.net.SocketException: Connection reset" . Recommend removing that bullet and putting its code example under the latter heading. For example, in that section it says "This process can cause a delay and can cause errors to be logged in the JVM logs. " You could introduce the code example after that sentence
- [x] Users cannot log in, even if non-Kerberos enabled registries are available.--> this item should be in the kerberos section
- [x] For more information, see xref:reference:ldapRegistry-3.0.adoc#krb5 --->link isn't properly formatted
### Troubleshooting SSL and TLS
- [x] CWWKS9105E: Could not determine the TLS port for automatic redirection. --->message block has stray formatting marks
- [x] You get an error when you use a JDK from the WebSphere Application Server---> i think we should remove this item as references to tWAS don't belong in OL doc
- [x] \`applicationMonitor dropinsEnabled="false"`  example has stray formatting marks

**Comment by dmuelle** [comment]
looks good- except:

### Users cannot log in, even if non-Kerberos enabled registries are available.
This item appears twice- i think you should remove the instance that is not under the Kerberos subheading

### Troubleshooting SSL and TLS
This section mixes references to SSL and TLS. Except for the introductory explanation, I think you can replace all instances of SSL with TLS.

**Comment by ManasiGandhi** [comment]
https://staging-openlibertyio.mybluemix.net/docs/21.0.0.11/troubleshooting.html

**Comment by dmuelle** [comment]
changes are on vvNext and will publish with the 21.0.0.11 docs release
