### ISSUE TITLE
Add new page documenting metrics changes in Fault Tolerance 3.0

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/docs#3440]
In addition to updating the metrics reference list (#3438), we also think we should have a new page which lists the equivalent new metrics for each old metric, similar to the [page we created for the changes in mpMetrics-2.0][metrics-20-changes].

I've created a table of changed metrics here: https://gist.github.com/Azquelt/86f4aec058c7bfb3350c043226d87df4

[metrics-20-changes]: https://openliberty.io/docs/20.0.0.12/reference/metrics-1-dif.html

**Comment by dmuelle** [comment]
@Azquelt - I'm working on getting this page to draft now. In the introduction, can we add a general statement about the change from `MP Fault Tolerance-2.1 name--> MP Fault Tolerance-2.1 Prometheus Name(s)`? What has fundamentally changed w/ this release that the metric names are now specific to Prometheus, and that in some cases a single metric is replaced by multiple Prometheus names?

**Comment by dmuelle** [comment]
Hi @Azquelt - per our Slack convo, I've added the table changes to the newly titled "Differences in metrics between MicrProfile versions" reference topic. You can review it on our draft site:

https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.2/reference/metrics-1-dif.html#fault

Note that the link to mpFaultTolerance-3.0 will not work until we update the gendoc for 21.0.0.3, which won't until after the GM for that release. If the pagelooks otherwise ok, you can sign ofrf by adding the `technical reviewed` label to this issue. If any changes are needed, just let me know. Thanks!

**Comment by Azquelt** [comment]
Is it possible to change the formatting of the `mpFaultTolerance-3.0` name column?

In the original table linked above, they look like this:
```
base_ft_retry_calls_total{
    method="<name>",
    retried=["true"|"false"],
    retryResult=["valueReturned"
                |"exceptionNotRetryable"
                |"maxRetriesReached"
                |"maxDurationReached"]
}
```

However, in the draft, they look like this:
> base_ft_retry_calls_total{ method="&lt;name>", retried=["true"|"false"], retryResult=["valueReturned" |"exceptionNotRetryable" |"maxRetriesReached" |"maxDurationReached"] }

In the original table, this was accomplished with `cols="l,l,d,l,l,d"` in the table header to indicate that columns 1, 2, 4 and 5 should be treated as literal text so that the linebreaks and spacing are preserved.

**Comment by dmuelle** [comment]
For some reason the original formatting was causing all the cells to be blacked out in my editor preview, so I replaced it to match the other table on this page. But that might just be a quirk in the Atom asciidoc preview that won't show up when I build to draft. I'll give it a shot

**Comment by dmuelle** [comment]
I've tried various options and still can't find a way to preserve the line spacing in the pre-formatted blocks. I tried different approaches to specifying full width for the table but nothing worked. I even applied the formatting at the cell level, which allowed the table as a whole to get to full width, but the individual cells still stubbornly broke the lines in the middle of words. 

I've reverted back to the initial draft state as that was the best solution so far. If you can think of any other approaches I'm happy to give it a try.  
https://docs-draft-openlibertyio.mybluemix.net/docs/latest/reference/metrics-1-dif.html#fault

**Comment by Charlotte-Holt** [comment]
@dmuelle I think these updates look good. Just a couple questions: 

- Should we update the names of both files (the metrics and FT pages) so that they consistently match the new titles? 
- Right now the link to "MicroProfile Fault Tolerance 3.0" is broken, but I'm assuming this'll be fixed when the new gen doc for 21.0.0.3 is on the site?

**Comment by dmuelle** [comment]
Thanks for reviewing @Charlotte-Holt 

- I think the filenames are still close enough- the topics are still about metrics differences and fault tolerance differences respectively
- Yes, the 3.0 link should work once  once the autoogen for 21.0.0.3 is in place. I'll wait to send this topic to staging until  I can verify that.

**Comment by Charlotte-Holt** [comment]
@dmuelle Sounds good. I'll add the content and peer reviewed labels.

**Comment by dmuelle** [comment]
thanks- moving this to Ready to Publish but waiting to send to staging until after the autogen update

**Comment by dmuelle** [comment]
content is on vNext to publish with 21.0.0.3. Will address table formatting issues and update the FT table as part of https://github.com/OpenLiberty/docs/issues/3872
