### ISSUE TITLE
Develop a topic comparing and contrasting JSON-B and JSON-P (MP08, MP09)

### ISSUE THREAD

**Issue by bsbyrd1** [OpenLiberty/docs#35]
- [ ] REST Serialization and deserialization of data - what do these terms mean for Open Liberty and why is it important?
--
- [ ] Why would I use JSON-P insted of JSON-B is what I think we need to know? It would be helpful to include a real-life example of why a developer would want to use JSON-P. A topic comparing and contrasting JSON-B and JSON-P would help identify when to use one over the other, especially in Open Liberty.
--

**Comment by bsbyrd1** [comment]
JSON-B vs JSON-P; Explain why JSON-B is better than JSON-P, and explain why it supersedes it. If you’re using JSON-P, here’s why you should upgrade.

JSON-B
http://json-b.net/getting-started.html - Use this as a base, and customize for OL.

**Comment by bsbyrd1** [comment]
@aguibert @andymc12 Hi guys! Friday, I made updates to the col_JSONp.adoc topic. Feel free to add your own Open Liberty specific content to that topic. It doesn't need to be long, just relevant and enough to help those new to building microservices better understand how JSON-B enables them to do so.

**Comment by bsbyrd1** [comment]
@aguibert I updated the section Why JSON-B is better than JSON-P section of this topic, could you give it a review and open a pull request if you have changes: https://github.com/OpenLiberty/docs/blob/develop/concepts/col_JSONp.adoc

**Comment by dmuelle** [comment]
Feedback from Alasddair in #99 

It would be better if the section identified when to use JSON-B and when to use JSON-P, rather than saying one is always better than the other. Both APIs are provided and both have strengths with particular use cases.

This topic should actually be split into two and describe JSON-B in one and JSON-P in the other. In the relevant topics, the benefits (and not benefits) of each should be described so that developers can decide which is the most relevant to them. Feel free to ping me (Wed to Fri) or Alasdair if you need more input. Thx

**Comment by dmuelle** [comment]
Previous draft: https://github.com/OpenLiberty/docs/blob/91ca3cd91df085fd1a16dee61527432b722855fc/concepts/col_JSONp.adoc

**Comment by dmuelle** [comment]
@lauracowen Pasting the intitial rough draft here until I can figure out how to PR it to Draft

= Serializing data with JSON-P and JSON-B

JavaScript object notation (JSON) has become the go-to format for sharing data among RESTful web services in microservices-based systems. It's lightweight, human-readable, and requires far less formatting than XML. It can also be readily transferred across different platforms and programming languages, in a format that all the participating languages can access.

JSON supports two standard data structures: objects, or sets of key-value pairs usually surrounded by curly brackets, and arrays, which collect objects into larger sets. These objects and arrays are  serialized and deserialized for transfer between different microservices.

Java provides two API specifications for for converting plain Java objects (POJOs) to and from JSON data: JSON processing (JSON-P) and JSON binding (JSON-B). JSON-P provides a Java API for processing JSON-formatted data. JSON-B provides a binding layer on top of JSON-P, making it even easier to convert objects to and from JSON.

== JSON-P: Java's original API
Before there was JSON-B, (which arrived as part of Java EE 8), JSON-P was Java's standardized way to interact with JSON. JSON-P is a lower-level API that provides two models (streaming and object) for JSON processing and transformation. The streaming model  provides an event-based parser that allows a developer to ask for the next event rather than handling the event in a callback, offering more control over the processing. The object model creates a random access structure to represent the JSON data in memory. This programming model is more flexible but sometimes requires more memory than the streaming model.

In contrast to JSON-B, JSON-P avoids data loss by retaining all the information in a call. This can be either an advantage or a liability, depending on what the code is doing. In general, JSON-P is regarded as being less secure than JSON-B, which has emerged as the preferred API for transforming data in microservices.

== Higher level binding with JSON-B
JSON-B is a standard binding layer for converting Java objects to and from JSON messages. It provides default mapping to convert existing Java classes to JSON, but also enables developers to customize  mapping by using Java annotations. JSON-B is a direct object-to-JSON mapping, requiring much less code than JSON-P. Its intuitive default configurations make it easy to use. Even developers with no prior experience with JSON should be able to use JSON-B, because it's based around annotations and semantics that are already commonplace for enterprise developers.

== To B or not to P?
Since it's introduction as part of Java EE 8, JSON-B has become the preferred API for converting Java objects to and from JSON, thanks to it's type safety, ease-of-use and compile-time feedback. However, there are cases where JSON-P might be a better fit.

Consider the subject of data loss. Say you have a Java object that is being sent between microservices in a weather forecast application. The object might contain the following data.

``{ +
  "location" : "Surf City" +
  "temp" : 82 +
  "conditions" : "sunny" +
  "hightide" : 1500 }``

If a service using JSON B received this object, but only asked for location and temperature, the other information would be lost. A service using JSON-P would retain all the data in the object. MicroProfile REST Client supports both JSON-P and JSON-B

==== See also:
- link:http://json-b.net/[JSON-B (JSON-Binding, JSR 367)]
- link:https://javaee.github.io/jsonp/[JSON-P (JSON-Processing, JSR 374)]

**Comment by dmuelle** [comment]
Rough draft/ outline for this topic: 
https://draft-openlibertyio.mybluemix.net/docs/ref/general/#/docs/concept/JSON_P_B.html

Needs developer input/ review. For now both JSONP & B are in the same doc. If the code & configuration examples from the draft above should be included for each API, I'll split into separate docs- but we need content for JSON P  similar to the JSON B examples in the previous draft

**Comment by aguibert** [comment]
hi @dmuelle, great first draft! A few comments:

- In first paragraph, `JavaScript object notation` should have capitalization like `JavaScript Object Notation`
- In the first section, lets include an example of some JSON data. To remain consistent with the "User" example in this article, lets use the following JSON data:
```json
{
  "id" : 5678,
  "name" : "Hank",
  "age": 55,
  "roles" : [ "member" ]
}
```
- Instead of introducing JSON-P and JSON-B with text-only sections, lets include a basic example in each section (towards the end).
- In the `User` class example, it doesn't make sense to have an `id` field of type `String`. Normally it would be a `long`.

Since most of my review comments involve updating code examples, and code examples are quite picky about syntax and whatnot, I'm happy to just do a PR on the docs repo to update the page with my review comments. Is that OK with you David?

**Comment by dmuelle** [comment]
@aguibert that would be great! Thanks

**Comment by lauracowen** [comment]
Where are we up to with this? It sounds like it's getting close to being finished?

**Comment by dmuelle** [comment]
@lauracowen @aguibert I think the draft is pretty much ready to go- just waiting on Andy's code examples (referenced above). If there's anything else I can do just let me know

**Comment by lauracowen** [comment]
@aguibert When do you think you will have the code examples that @dmuelle needs to complete this topic?

**Comment by aguibert** [comment]
@lauracowen I posted a PR yesterday with the updates and @dmuelle and I have since merged it in

**Comment by dmuelle** [comment]
@lauracowen yes- Andy's code is now in the doc and I've made some final edits to clean it up a bit. I think it should be ready to publish now. If you agree, I can create a PR to dev. New draft is on the draft site.  

https://draft-openlibertyio.mybluemix.net/docs/ref/general/#JSON_P_B.html

**Comment by lauracowen** [comment]
Oh cool!

Looks great. Some minor (minor!) tweaks for you:
- Missing a colon at the end of the lead-in sentence to the first code snippet.
- "JSON B" is missing a hyphen in the sentence immediately after the first code snippet.
- Could you add a lead-in sentence (or rejig the sentences above) to the third code snippet to make it clear what it's illustrating (why it's included just here)?
- Similarly for the last code snippet.

I really like the style - I think it works well.

Yes, when you've done the things above, can you creat a PR to dev?

**Comment by dmuelle** [comment]
I've fixed the missing colon &  hyphen but I'll need @aguibert to provide the code introductions. I've just slacked him about it. Once the doc is updated with those I'll PR to develop and request your review.

**Comment by dmuelle** [comment]
requested edits have been made

https://draft-openlibertyio.mybluemix.net/docs/ref/general/#JSON_P_B.html

creating a PR to dev

**Comment by dmuelle** [comment]
Doc is now public at

https://www.openliberty.io/docs/ref/general/#json_p_b.html
