### ISSUE TITLE
mpJwt-1.2 documentation updates

### ISSUE THREAD

**Issue by teddyjtorres** [OpenLiberty/docs#3511]
Summary: Enhancement needed for 2 KC articles described in A and B below and port these two articles to openliberty.io for Epic https://github.com/OpenLiberty/open-liberty/issues/11022

A. We need documentation updates in the KC article, https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_sec_json.html and port these over to openliberty.io under the "Security" topic.

The changes are as follows:

1. Update sentence,
> Install Java™ Platform, Standard Edition (Java SE) 8 or later to use the mpJwt-1.0, mpJwt-1.1, or mpJwt-1.2 feature.

2. Add MP-JWT 1.2 section to "About this task",

> The MicroProfile JSON Web Token 1.2 specification allows using a JWT token for authenticating and authorizing requests to a service. The specification simplifies the configuration for managing the validation of the JWT by introducing new MicroProfile Config properties. Enhanced signature algorithm support is added in this feature. See the [MP-JWT-1.2 specification](https://github.com/eclipse/microprofile-jwt-auth/blob/master/spec/src/main/asciidoc/microprofile-jwt-auth-spec.asciidoc).

3. Add the following to sentence number 3 in the "Procedure" section,

> Version 1.2 of the MicroProfile JSON Web Token specification adds the following MicroProfile Config properties to control different aspects of the JWT validation.

> ### mp.jwt.token.header
> The `mp.jwt.token.header` property allows you to control the HTTP request header which is expected to contain a JWT token. You can specify either Authorization (default) or Cookie values.

> ### mp.jwt.token.cookie
> The `mp.jwt.token.cookie` property allows you to specify the name of the cookie which is expected to contain a JWT token. The default value is `Bearer` if not specified.

> ### mp.jwt.verify.audiences
> The `mp.jwt.verify.audiences` property allows you to create list of allowable "aud" values. At least one of these must be found in the claim. Previously, this had to be configured in the server.xml file. Now, you can configure the audiences in the MicroProfile config property as follows:
>```
>mp.jwt.verify.audiences=conferenceService
>```

> ### mp.jwt.decrypt.key.location
> The `mp.jwt.decrypt.key.location` property allows you specify location of the Key Management Key. This is the Private key to decrypt the Content Encryption Key, which is then used to decrypt the JWE ciphertext. This private key must correspond  to the public key that is used to encrypt the Content Encryption Key.

> ### mp.jwt.verify.publickey.algorithm
> The `mp.jwt.verify.publickey.algorithm` property allows you to control the Public Key Signature Algorithm that is supported by the MP JWT endpoint. The default value is `RSA256` if not specified. Previously, this had to be configured in the server.xml file. Now, you can configure the public key algorithm used for verification of the JWT in the MicroProfile config property as follows:
>```
>mp.jwt.verify.publickey.algorithm=ES256
>```

> The specification also adds support for the ES256 signature algorithm, while this Open Liberty feature supports using the RS384, RS512, HS384, HS512, ES256, ES384, and the ES512 signature algorithms.

B. We also need updates to the KC article https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_sec_build_jwt.html and port these over to openliberty.io under the "Security" topic.

The changes are as follows:

1. Add step 3.d as follows, renaming existing step "d" to "e",
> d. Modify the configured key management algorithm, key management key, and content encryption algorithm:
jwtBuilder.encryptWith(new_key_mgt_algorithm, Key new_key_mgt_key, String contentEncryptionAlg)("new_algorithm", new_key);

**Comment by Charlotte-Holt** [comment]
This work is related to #3439

**Comment by Charlotte-Holt** [comment]
Comment from @lauracowen about work for MP JWT: Investigate what's needed beyond the info in https://www.openliberty.io/docs/latest/single-sign-on.html#_json_web_token_jwt and https://www.openliberty.io/guides/microprofile-jwt.html for the majority of users to use it. We also have javadoc and gendoc for MP JWT, so don't duplicate that.

**Comment by chirp1** [comment]
For the KC topics mentioned that need updating, in each of these topics, at least add links to the new/updated OL topics that will have the info from these KC topics.

**Comment by dmuelle** [comment]
notes from @lauracowen in the [KC spreadsheet](https://ibm.box.com/s/kd2dgqzn58rzgwwts4wk2a2k7k20vhsu) for the [Configuring the MicroProfile JSON Web Token](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_sec_json.html) topic :

"This is far too complicated a topic! The basic required steps are covered by the MP JWT guide (and the guide should be updated to be clearer and current best practice). Of the 'optional' steps in this topic, need to identify which are actually useful to most developers. Also check where they are otherwise documented in reference docs (eg MP Javadoc or generated feature/config doc). When that's done, redirect this KC topic to the MP JWT guide."

**Comment by Rwalls1** [comment]
notes from @lauracowen in the [KC spreadsheet](https://ibm.box.com/s/kd2dgqzn58rzgwwts4wk2a2k7k20vhsu) for the [Building JSON Web Tokens in Liberty](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_sec_build_jwt.html) topic:

"Is this not the same as the "obtaining JWTs" topic? The info in here just explains how to create the JWT that is obtained. So when the JWT feature has some good config examples, this topic can also redirect (at least partly - the section about config in server.xml; not the bit about using the API - but we aren't going to focus on the API in OL docs for now)."

**Comment by Rwalls1** [comment]
Based on Laura's suggestions and further content review, most of the relevant content in the "Building JSON Web Tokens" KC topic is already covered by the [JSON Web Token config examples](https://draft-openlibertyio.mybluemix.net/docs/21.0.0.2/reference/feature/jwt-1.0.html), any further related updates would be added there.

**Comment by Rwalls1** [comment]
Content from the "Building JSON Web Tokens" KC topic is also related to issue #636, the config example is derived from the closely related [Obtaining JSON Web Tokens In Liberty](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_sec_obtain_jwt.html) topic that Laura also mentions in her spreadsheet.

**Comment by Rwalls1** [comment]
Based on Laura's suggestions and further content review, the "About this task" section and steps 1 and 2 of the "Configuring the MicroProfile JSON Web Tokens in Liberty topic" are already largely covered in existing documentation such as the [SSO](https://draft-openlibertyio.mybluemix.net/docs/21.0.0.2/single-sign-on.html) topic, the [MP JWT config examples](https://draft-openlibertyio.mybluemix.net/docs/21.0.0.2/reference/feature/mpJwt-1.1.html), and the [Securing Microservices with JSON Web Tokens](https://openliberty.io/guides/microprofile-jwt.html) guide.

**Comment by Rwalls1** [comment]
# Content strategy assessment for "Configuring the MicroProfile JSON Web Token" topic
## Procedure
- Step 3: Existing MP Config properties along with suggested new properties for MP-JWT 1.2 should be documented in a separate reference page, work will be tracked in issue #505 
- Step 4: Content could be added to MP JWT config examples to provide an example of configuring a truststore with MP JWT
- Step 5: Content could be added to MP JWT config examples to provide an example of configuring role mapping with JWT
- Step 6-8: Content could be added to JAX-RS config examples and/or new JAX-RS concept topic, will need to assess existing OL documentation on the subject
- Step 9: Information is covered in "Securing Microservices with JSON Web Tokens" guide
- Steps 10-11: Content could be added to enhance MP JWT config examples
- Step 12: Content could be added to enhance JAX-RS client config examples
- Step 13: Content is covered in MP JWT config examples and the [Authentication Filters](https://draft-openlibertyio.mybluemix.net/docs/21.0.0.2/authentication-filters.html) topic

**Comment by Rwalls1** [comment]
@teddyjtorres Can you review the [Securing microservices with JSON Web Tokens](https://openliberty.io/guides/microprofile-jwt.html) guide and verify whether any updates need to be made to align with current best practices that may be introduced with mpJWT-1.2 or other feature updates that might change how you should execute the steps in the guide?

**Comment by Rwalls1** [comment]
@teddyjtorres Please review
# Content proposal for [MP JWT config examples](https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/mpJwt-1.1.html) updates
The following suggested updates are drawn from steps 4 and 11 from the [Configuring the MicroProfile JSON Web Token](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_sec_json.html) topic:
## Import a Truststore to verify a MicroProfile JWT
You can configure a Truststore to verify JSON Web Tokens.  The default Keystore for MicroProfile does not contain the root certificates that are used to verify the authentication credentials that are stored in JSON Web Tokens. To verify JSON Web Tokens, you can import the default Java Truststore as shown in the following example:

```xml
<ssl id="defaultSSLConfig" keyStoreRef="defaultKeyStore" trustStoreRef="defaultTrustStore" />
<keyStore id="defaultTrustStore" location="${javaKeystoreLocation}" type="JKS" password="changeit" />
<mpJwt id="mympjwt" issuer="https://example.com"
   jwksUri="https://localhost:19443/jwt/ibm/api/myBuilder/jwk"/>
```
The `id` attribute in the `keyStore` element specifies the `“defaultTrustStore”` value to configure a Truststore within the Keystore. A Truststore contains the certificates that are used to validate the requests that are sent to applications with JSON Web Tokens. The `ssl` element is used to specify how the application validates the SSL connection to a server. Within the `ssl` element, the `id=defaultSSLconfig` attribute sets the SSL configuration as the default SSL configuration for the server that the application connects to. The `trustStoreRef=“defaultTrustStore”` attribute configures the `ssl` element to reference the Truststore so that the application recognizes the Truststore when it attempts to connect to the server. The `jwksUri="https://localhost:19443/jwt/ibm/api/myBuilder/jwk”` specifies the JWK endpoint URL that the application uses to connect to the server and verify the JWT.
## Configure access restrictions with MicroProfile JWT
By default, if the `mpJwt-1.0` feature is configured, all authorized requests must include a valid JSON Web Token in the HTTP header. To modify the default behavior to require JSON Web Tokens  in some applications only, you can add the `ignoreApplicationAuthMethod=“false”` attribute to the  `mpJwt` element as shown in the following example: 
```xml
<mpJwt ignoreApplicationAuthMethod=“false”/>
```
**Teddy's comments:**
> 1. Please change this sentence
>> The `jwksUri="https://localhost:19443/jwt/ibm/api/myBuilder/jwk”` specifies the JWK endpoint URL that the application uses to connect to the server and verify the JWT.
>to
>>The `jwksUri="https://localhost:19443/jwt/ibm/api/myBuilder/jwk”` specifies the JWK endpoint URL that the Liberty server uses to obtain the public keys from to verify the JWT.
> 2. We need to add the rest of the required steps in the "Configure access restrictions with MicroProfile JWT" section as follows:
>> Then, configure the application in one of two ways:
The application has an @LoginConfig annotation with the MP-JWT login method declared as the authentication method.
>> For example,
>> ```
>> @LoginConfig(authMethod = "MP-JWT", realmName = "MP-JWT")
>> ```
>> The web.xml file for the application has a declaration for the MP-JWT authentication method in the login-config element.
>> For example,
>> ```
>> <login-config> <auth-method>MP-JWT</auth-method> <realm-name>MP-JWT</realm-name></login-config>
>> ```

**Comment by teddyjtorres** [comment]
> @teddyjtorres Can you review the [Securing microservices with JSON Web Tokens](https://openliberty.io/guides/microprofile-jwt.html) guide and verify whether any updates need to be made to align with current best practices that may be introduced with mpJWT-1.2 or other feature updates that might change how you should execute the steps in the guide?

The required guides' updates were requested in https://github.com/OpenLiberty/guides-common/issues/525

**Comment by Rwalls1** [comment]
@andymc12 Please review

# Content proposal for [JAX-RS client config examples](https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/jaxrsClient-2.1.html) update
The following suggested update is drawn from step 12 from the [Configuring the MicroProfile JSON Web Token](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_sec_json.html) topic:
## Enable MicroProfile JWT authentication for JAX-RS
If you configure the MicroProfile JWT feature along with the JAX-RS Client feature, you can enable MicroProfile JWT authentication for JAX-RS services. To enable MicroProfile JWT authentication, you can add the `authnToken=“mpjwt”` attribute to the `webTarget` element as shown in the following example:
```xml
<webTarget uri="http://localhost:56789/protectedResourceWithMPJWT*" authnToken="mpjwt" />
```
This attribute adds MicroProfile JWT as an authorization header in the JAX-RS service that is specified by the ` uri="http://localhost:56789/protectedResourceWithMPJWT*”` attribute.

**Comment by andymc12** [comment]
@Rwalls1  - yes, that looks right to me.

**Comment by Rwalls1** [comment]
@andymc12 Please review

# Content proposal for new [JAX-RS config examples](https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/feature/jaxrs-2.1.html)
The following suggested updates are drawn from steps 6 and 7 from the [Configuring the MicroProfile JSON Web Token topic](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_sec_json.html):
## Access security details with a context object
In Jax-RS applications, you can use annotations to access information from HTTP requests with dependency injections of context objects. Context objects are used to access any information that is associated with the application. In the following example, the `@Context` annotation injects the `SecurityContext` context object that provides access to security details:
```java
@GET
@Path("/getGroups")
public Set<String> getGroups(@Context SecurityContext sec) {
       Set<String> groups = null;
       Principal user = sec.getUserPrincipal();
       if (user instanceof JsonWebToken) {
                JsonWebToken jwt = (JsonWebToken) user;
                groups= = jwt.getGroups();
       }
       return groups;
}
```
To access security details, the `SecurityContext` context object uses the `sec.getUserPrincipal()` method that determines the identity of the user that makes the HTTP request. The `if` statement specifies the `JSONWebToken` claims that identify the user.

## Inject the MicroProfile JWT interface
You can inject interfaces in JAX-RS applications to access resources. In the following example, the `@Inject` annotation injects the `JsonWebToken` interface to obtain the `jwtPrincipal` object that contains details that identify the user:
```java
@RequestScoped
public class JwtEndpoint {
       @Inject
       private JsonWebToken jwtPrincipal;
       @GET
       @Path("/getInjectedPrincipal")
       public String getInjectedJWT() {
          return  this.jwtPrincipal.getName();
       }
}
```

For the `Inject the MicroProfile JWT interface` example, I wasn't sure what the phrase "through Raw Type, ClaimValue, javax.inject.Provider, and JSON-P types" from step 7 meant so I just highlighted the injection of the JWT interface. Also, can you review step 8? Do you think the information in that step is important? If so, can you provide an example of what that content would look like?

**Comment by andymc12** [comment]
@Rwalls1 - thanks - this looks good.  Just a few minor comments:


> In Jax-RS applications, you can use annotations to access 

"Jax-RS" should be "JAX-RS".


> Context objects are used to access any information that is associated with the application.

Context objects go beyond just the application so maybe this sentence could say something like:
_Context objects can provide information associated the application, the specific request or response, or the environment that the application is operating in._


The source code for the `getGroups` method is technically correct, however, I have been advising users not to put `@Context` objects in as method parameters. This is because a future version of JAX-RS will replace the `@Context` annotation with `@Inject` and the `@Inject` annotation does not apply to method parameters. So it might make less work in the future to change this code to be:
```
@Context
SecurityContext sec

@GET
@Path("/getGroups")
public Set<String> getGroups() {
       Set<String> groups = null;
       Principal user = sec.getUserPrincipal();
       if (user instanceof JsonWebToken) {
                JsonWebToken jwt = (JsonWebToken) user;
                groups= = jwt.getGroups();
       }
       return groups;
}
```

> The if statement specifies the JSONWebToken claims that identify the user.

"JSONWebToken" should be "JsonWebToken".



As for your questions...
> For the Inject the MicroProfile JWT interface example, I wasn't sure what the phrase "through Raw Type, ClaimValue, javax.inject.Provider, and JSON-P types" from step 7 meant so I just highlighted the injection of the JWT interface.

I'm not entirely sure what that means either... It looks like `ClaimValue` is part of the MP JWT APIs.  I'm not sure what "Raw Type" means in this context... presumably that you can directly inject a `JsonWebToken`.  I don't think it is necessary to mention the `javax.inject.Provider` as that is just another way to inject using CDI.  And I'm not sure how JSON-P relates to injection in this case.  So, I agree with just highlighting the injection of the JWT interface and calling it good.  Teddy or somebody from the security team may have more info.

> Also, can you review step 8? Do you think the information in that step is important? If so, can you provide an example of what that content would look like?

I don't think it is necessary to document, but Teddy or somebody from the security team may have a different opinion.  My preference would be to keep it simple, so I would leave it out.

Thanks again!

**Comment by Rwalls1** [comment]
These updates have been merged to vnext and will publish in the upcoming release.
