### ISSUE TITLE
securityUtility help (MSSEC07)

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#364]
In same format as the server command topics, take the info from two KC topics https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_command_securityutil.html and https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_liberty_ssl_defaults.html (transportSecurity feature only; not ssl feature which is superceded by transportSecurity - it enables the ssl feature under-the-covers I think but user doesn't explicitly enable it now) (current release only; don't show versions of pre-19.0.0.3 as that's doc'd in the KC already - how we link to OL docs should consider this).

**Comment by lauracowen** [comment]
https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_command_securityutil.html

**Comment by Charlotte-Holt** [comment]
Example config for transportSecurity feature w/ #631

**Comment by Charlotte-Holt** [comment]
The link to the working draft on the draft site is at https://draft-openlibertyio.mybluemix.net/docs/ref/general/#securityUtility.html.

**Comment by arkarkala** [comment]
1) It says plain text encryption - it also does hashing and encoding. Should we use another word - obfuscation for eg?
2) We can remove this - "or allow the server to call it to create a default TLS certificate and keystore on server startup."
The server does create the default TLS cert when right config is there but it does not call this utility directly. They all call common methods to create certs underneath.
3) Should we show an example for hash?
4) "This task encodes the provided text by using Base64."  ----> Since we support multiple ways to obfuscate, should be clarified to say something like - it obfuscates (or whatever word we pick) based on the type provided.
5) In the Certificates Detail section, add the following
Subject Alternate Name (SAN) : <hostname>

**Comment by dmuelle** [comment]
Peer review:

##Usage examples
 should the syntax section go before the examples?

@arkarkala should the password obfuscation example here be hash? 

##Synttax

the task and options heading are a little confusing. Would it be better to put in a sentence that says "The `task` specifies the operation the tool will perform. The `options` can be one or more etc etc"  

then go to the examples

`If no options are specified, the command enters interactive mode.` - what is interactive mode? It's not defined. I think I've seen it explained elsewhere in KC but not sure where

## encode
_text_ entry seems strange in context. I think I understand what they're saying - it's italicized because it's just a variable for actual text- but is it an "option"?

## createSSLCertificate

`The options included in the following table are available for the createSSLCertificate task:`

The options that are included....
or
The following options are available for.....

--keyType=keystore type
should this be --keyType=keystore_type
all the other multi-word example fields use underscores

"Distinguished Name" doesn't need capitalization

**Comment by Charlotte-Holt** [comment]
@arkarkala @lauracowen - There's a draft ready for you to review at https://draft-openlibertyio.mybluemix.net/docs/ref/general/#securityUtility.html. This incorporates Ajay's initial feedback and David's feedback.

**Comment by lauracowen** [comment]
Thanks, looks fine.

**Comment by Charlotte-Holt** [comment]
@chirp1 - Ready for your review. Thx!

**Comment by chirp1** [comment]
Hi Charlotte, I'd mentioned a few weeks back that the term "task" needed to be investigated as other commands use the term "action". Did you resolve the difference so that we are consistent when we write topics about commands?

**Comment by Charlotte-Holt** [comment]
Requesting full peer review from @dmuelle

**Comment by dmuelle** [comment]
# Peer review

## Short desc

`The securityUtility command supports plain text obfuscation and TLS certificate creation for Open Liberty. You can call the tool directly from the command line.`

Inn the first sentence securityUtility is a command. In the second, it's referred to as a tool. Should there be just one term?

## Usage examples

`Create a TLS certificate for the myserver server that is valid for 365 days with the mypassword password:`

The example also includes the `subject` option. Is this option required to create a certificate? If so, it needs an explanation. If not, needs an explanation and mention that it's optional. I see that it is defined later in the topic so a full explanation isn't necessary here. But mention it so it's not the only option not mentioned in the description. You might also preface the user examples with some reference to option explanations later in the topic.

`Get help information about the createSSLCertificate action:`

Does the `help` option work for any action, or just `createSSLCertificate` ? If it works for any action, you might explain what the option does in a sentence, then intro this an example in the following sentence.

Should the description of interactive mode from the Encode options section be moved here? or duplicated? Otherwise you reference interactive mode without having explained it.

## Syntax

should this section appear before the usage examples? It provides info that helps in understanding the examples. Also, as is it is seems like another example, rather than a syntax template

This section also mixes "command" and "tool" to mean the same thing. Do they mean the same thing? If so, use one term.

`One or more optional parameters that are different based on the value of action.`

Should this say what options do, rather than just that they are different? For example

`One or more optional parameters that you can specify to modify an action.`

## Actions and options
`Use the following actions with the securityUtility command to get help information, encode passwords, and generate TLS certificates. Some actions can also be used with optional parameters, depending on what you need to accomplish.`

should it be "obfuscate" rather than encode?
Do you need `depending on what you need to accomplish.`? I think it's implied by "optional"

`This action prints help information for a specified action.`

Is "print" the preferred term in this context? I know I've seen it used w/r/t displaying text in the CLI, but there is also a specific CLI `print` command- https://en.wikipedia.org/wiki/PRINT_(command) "displays" might be less ambiguous. I see "display" used elsewhere in this topic .

## encode
`Interactive mode prompts you to enter and confirm your text input, rather than providing text on the command line. Otherwise, the provided text is encoded.`

"rather than providing text on the command line" should this be rather than providing text along with the command" or "on the same line as the command"? Since when the user is prompted, they still technically have to enter the text on the command line (unless I'm misunderstanding the function...)

Should it be "the provided text is obfuscated." ?

 `Supported encodings are..`
should it be  `Supported encoding types are..` for continuity with the preceding example....

 `The key can be provided to the server by defining the wlp.password.encryption.key variable whose value is the key.`

Does this mean the user needs to specify the key as the value of the varibale? Or does the variable retrieve the key value? As written, it sounds like the latter. If that's the case, should still probably revise to remove "whose" eg. "the value of which is the key". 

If the user has to explicitly specify the value, could be 
`You can provide the server with the key  by defining the wlp.password.encryption.key variable with the key as the value.`  or similar

`It is optional to provide password text on the command line` -see above comment re interactive mode

## createSSLCertificate
`Specifies the name of the Open Liberty client for which the keystore and certificate is created.`
should be "are created"

`The PKCS12 format is frequently the format that certificate authorities provide when they issue certificates.` 
suggested revision:
`Certificate authorities frequently issue certificates in the PKCS12 format.`

`The key can be provided to the server by defining the wlp.password.encryption.key variable whose value is the key. ` see previous comment re "whose value"

`If you use certificates that are created with EC keys, then include a customized ciphers list in your TLS configuration to include EC ciphers.`
should this be
`If you use certificates that are created with EC keys, then include a customized ciphers list in your TLS configuration that includes EC ciphers.`

`If the --extInfo option is used, the value is passed directly to the keytool command. Use the syntax of the --ext flag on the keytool command.`

What is the `keytool` command? How would someone get info on its syntax?

**Comment by dmuelle** [comment]
The updated topic looks good to me. Couple minor things:

In the intro to the `encode` action

`This action obfuscates the provided text based on the type that is specified. If no text is provided, the command enters interactive mode. Interactive mode prompts you to enter and confirm your text input, rather than providing text on the same line as the command. Otherwise, the provided text is obfuscated. Text with spaces must be put in quotation marks. `

I think you could do without `Otherwise, the provided text is obfuscated`. It doesn't add any new info and somehow makes the previous statement less clear- IMO.

expletive construction in the `_Text_` description:
`It is optional to provide password text on the same line as the command.` 
rewrite to remove

**Comment by dmuelle** [comment]
Verified suggested peer review edits- doc looks good

**Comment by arkarkala** [comment]
We might need to include additional links/references similar to the ones in https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_command_securityutil.html to complete this.
Based on our discussion the additional items will be added to the backlog to address this.

**Comment by Charlotte-Holt** [comment]
@lauracowen This has now been broken out into: 

- https://draft-openlibertyio.mybluemix.net/docs/ref/general/#securityUtility-createSSLCertificate.html
- https://draft-openlibertyio.mybluemix.net/docs/ref/general/#securityUtility-help.html
- https://draft-openlibertyio.mybluemix.net/docs/ref/general/#securityUtility-encode.html

**Comment by lauracowen** [comment]
I haven't read the details in each description. I'm not keen on all the "in this version", "in that version" but they're versions that are within our 'support' lifespan. When we move to Antora, we could leave them in for the first version of the docs (ie show everything up to that version), then in later versions just state the current situation.

- securityUtility createSSLCertificate
  - I don't think the Keystore details and Certificate details sub-sections should be straight after the intro. It took me a while to work out what info they were showing (I guess it's come from the KC?). Some of the info is shown in the Options table anyway. I think that info should be moved to the relevant rows in the table. Some of the info isn't obviously related to anything - not sure what the reader is meant to do with it (eg the SAN bullet?). Even the 'location' info could probably go in the keystore type row's description cell?
  - The intro should say what the command is for but then go straight into Usage examples, then Syntax (showing what's required vs optional), then Options where the details are described.

- securityUtility encode
  - Does this sentence "This command obfuscates provided text based on the type that is specified. " mean you can obfuscate a password? If so (and the usage examples section suggests so?), can that first sentence be more explicit and say "for example, a password".
  - Then in the Usage examples section, I think "a password" should be "the password that you want to encrypt" (otherwise it reads like you're having to authenticate with a known password).

- securityUtility help
  - In the Options, I don't think it's right to list "actionName" as an option - it suggests there's a literal value called `actionName` that you can enter when actually that's a variable.  I know it's the same in the server help command. I'm not sure what happens if you enter a help command without an additional action name on the command - I think it probably just tells you to add an action name to it.

    I think it should say `securityUtility help actionName` then remove the mention of "option" and instead have a little bold sub-heading of "actionName" with a description of that parameter (like for "serverName" in the [server dump](https://draft-openlibertyio.mybluemix.net/docs/ref/command/#server-dump.html) topic). I just checked and if you just run `securityUtility help` with no action it just tells you to add an action and what actions there are you can add. So I don't think it's worth displaying the actions as an option.
  - This should also be done to the server help command (if you agree in principle, can create a separate issue for that?).

**Comment by Charlotte-Holt** [comment]
@lauracowen Thx for the review! Agreed with what you said about the "...in this version..." stuff. I left it, since most of the instances are within "support", like you said. 

I incorporated all of your suggested updates except moving the keystore and certificate details down into the table of the `createSSLCertificate` command. I wanted to consult @arkarkala about it, and he's out today, so I'll sync up with him tomorrow morning. Part of me thinks that having all the default information in the top could be helpful, rather than people having to pick through the table for it, but I'm not sure...

Here are links to the update topics, please review when you get the chance: 

- https://draft-openlibertyio.mybluemix.net/docs/ref/general/#securityUtility-createLTPAKeys.html
- https://draft-openlibertyio.mybluemix.net/docs/ref/general/#securityUtility-createSSLCertificate.html
- https://draft-openlibertyio.mybluemix.net/docs/ref/general/#securityUtility-encode.html
- https://draft-openlibertyio.mybluemix.net/docs/ref/general/#securityUtility-help.html

**Comment by Charlotte-Holt** [comment]
@lauracowen Update! I spoke with @arkarkala and he agreed that some of the default information could be moved into the table for https://draft-openlibertyio.mybluemix.net/docs/ref/general/#securityUtility-createSSLCertificate.html. I've made that update and moved all default info into the relevant places in the table except for the location of the keystore, because I didn't see a corresponding place where it made sense. I just incorporated it into the top section in paragraph format. The topics are now ready for your review: 

- https://draft-openlibertyio.mybluemix.net/docs/ref/general/#securityUtility-createLTPAKeys.html
- https://draft-openlibertyio.mybluemix.net/docs/ref/general/#securityUtility-createSSLCertificate.html
- https://draft-openlibertyio.mybluemix.net/docs/ref/general/#securityUtility-encode.html
- https://draft-openlibertyio.mybluemix.net/docs/ref/general/#securityUtility-help.html

**Comment by lauracowen** [comment]
Looks great. Yes, the keystore location works where you've got it now that the rest isn't there too. Thanks. Signing off.

**Comment by Charlotte-Holt** [comment]
@chirp1 Topics at 
- https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/reference/command/securityUtility-createSSLCertificate.html
- https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/reference/command/securityUtility-createLTPAKeys.html
- https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/reference/command/securityUtility-encode.html
- https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/reference/command/securityUtility-help.html

**Comment by Charlotte-Holt** [comment]
Updates made:

- "A PKCS12 keystore has a number of advantages over a JKS keystore." **-->** "A PKCS12 keystore has advantages over a JKS keystore." - **DQTI, Chapter 6, Clarity, Eliminate wordiness**
- "Specifies the key to use to encode the keystore password by using AES encryption." **-->** "Specifies the key to use when you encode a password with AES encryption." - **DQTI, Chapter 4, Accuracy, Reuse information when possible**

**Comment by Charlotte-Holt** [comment]
Published at:
- https://openliberty.io/docs/20.0.0.11/reference/command/securityUtility-createLTPAKeys.html
- https://openliberty.io/docs/20.0.0.11/reference/command/securityUtility-createSSLCertificate.html
- https://openliberty.io/docs/20.0.0.11/reference/command/securityUtility-encode.html
- https://openliberty.io/docs/20.0.0.11/reference/command/securityUtility-help.html

Still requires final editorial review.

**Comment by chirp1** [comment]
Hi Charlotte,
I have minor comments:
securityUtility-createSSLCertificate.html:
- For "Create a TLS certificate for the myserver server that is valid for 365 days with the mypassword password:", I know what you mean, and the sentence passes Acrolinx, but with a dependent clause and a prepositional phrase in one sentence, maybe we could make the wording a little clearer - something like "Create a TLS certificate for the myserver server with the mypassword password. Set the validity period to 365 days.".
- For "--password[=pwd]", the only part that is a variable is "pwd". So, make only "pwd" italic. Also, remove the brackets. So, make it "--password=_pwd_". Do the same in other topics that have "--password[=pwd]".

securityUtility-createLTPAKeys.html
- For "--password[=pwd]", the only part that is a variable is "pwd". So, make only "pwd" italic. Also, remove the brackets. So, make it "--password=_pwd_". Do the same in other topics that have "--password[=pwd]".
- Spell out AES on first occurrence.

securityUtility-encode.html
- For the link to "Password encryption.", on further thought, change the title of password-encryption.html to "Password encryption limitations", and then change the title of the link to the same name. Since this topic in the link is really about limitations, I think the topic should have limitations in the title.
- Spell out AES on first occurrence.
- I see that on the external version of this topic that the quickStartSecurity element links to https://openliberty.io/docs/20.0.0.12/reference/config/quickStartSecurity.html , but internally it links to https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/reference/command/securityUtility-encode.html#config/quickStartSecurity.adoc  is that how the link works internally, or is it now broken?
- For"The information consists of:", use a complete sentence to introduce the items.

securityUtility-help.html:
- The topic is OK.

**Comment by Charlotte-Holt** [comment]
@chirp1 I addressed your feedback:

https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.2/reference/command/securityUtility-createLTPAKeys.html
https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.2/reference/command/securityUtility-createSSLCertificate.html
https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.2/reference/command/securityUtility-encode.html
https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.2/reference/command/securityUtility-help.html

securityUtility-createSSLCertificate.html:

- [x] For "Create a TLS certificate for the myserver server that is valid for 365 days with the mypassword password:", I know what you mean, and the sentence passes Acrolinx, but with a dependent clause and a prepositional phrase in one sentence, maybe we could make the wording a little clearer - something like "Create a TLS certificate for the myserver server with the mypassword password. Set the validity period to 365 days.".
- [x] For "--password[=pwd]", the only part that is a variable is "pwd". So, make only "pwd" italic. Also, remove the brackets. So, make it "--password=pwd". Do the same in other topics that have "--password[=pwd]".

securityUtility-createLTPAKeys.html

- [x] For "--password[=pwd]", the only part that is a variable is "pwd". So, make only "pwd" italic. Also, remove the brackets. So, make it "--password=pwd". Do the same in other topics that have "--password[=pwd]".
- [x] Spell out AES on first occurrence.

securityUtility-encode.html

- [x] For the link to "Password encryption.", on further thought, change the title of password-encryption.html to "Password encryption limitations", and then change the title of the link to the same name. Since this topic in the link is really about limitations, I think the topic should have limitations in the title.
- [x] Spell out AES on first occurrence.
- [x] I see that on the external version of this topic that the quickStartSecurity element links to https://openliberty.io/docs/20.0.0.12/reference/config/quickStartSecurity.html , but internally it links to https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/reference/command/securityUtility-encode.html#config/quickStartSecurity.adoc is that how the link works internally, or is it now broken?
- [x] For"The information consists of:", use a complete sentence to introduce the items.

securityUtility-help.html:

- [x] The topic is OK.

**Comment by chirp1** [comment]
Hi Charlotte,
One last thing that I see I didn't mention:
For the SecurityUtility topics where you say _--password=pwd_, just italicize the variable, which is "pwd" so that it looks like --password=_pwd_.

**Comment by Charlotte-Holt** [comment]
@chirp1 Fixed!

https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/command/securityUtility-createLTPAKeys.html
https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/command/securityUtility-createSSLCertificate.html

**Comment by chirp1** [comment]
Hi Charlotte, We slacked yesterday about the italics still being there and that you are going to think about another way to attempt to fix the problem. Moving to In Progress.

**Comment by Charlotte-Holt** [comment]
@chirp1 Okay, got this fixed now:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/command/securityUtility-createLTPAKeys.html
https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/command/securityUtility-createSSLCertificate.html

**Comment by chirp1** [comment]
- Note: To fix the _--password=pwd_ problem so that it would be --password=_pwd_, Charlotte reached out to Steven Z. He fixed an issue with the CSS for the OL site. 
- The doc updates look good. Moving to Ready to Publish.

**Comment by Charlotte-Holt** [comment]
Merged to `vNext` in https://github.com/OpenLiberty/docs/pull/3693 and added to the KC spreadsheet
