### ISSUE TITLE
Windows-only server create command topic not building

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/docs#368]
This topic isn't building because of some error in the file: https://github.com/OpenLiberty/docs/blob/master/ref/commands/server/server-windowsservice.adoc

Work out what the problem is:

asciidoctor: ERROR: server-windowsservice.adoc: line 73: include file not found: /home/pipeline/221e2732-3313-4b77-8763-e0abcd6c4d31/src/main/content/docs/ref/commands/server/server-exitcodes.adoc

Then update the content of the file to match the section ordering/style of the other server command topics (eg server create topic).

It has the wrong page title (that might be why it's failing to build because it's conflicting with the actual server start command topic).

**Comment by lauracowen** [comment]
I see why it doesn't fit but it now seems like a mashup of a reference and task topic. I think you could make it more properly a task topic: remove the 'Syntax' section (inc the servername description), and move that information to the top - now you're explaining how to run OL as a Windows service (something people do request info about for Liberty), rather than describing the command. It means we don't have a reference format description of the command but that's probably not the end of the world (the info is still also available from the cmdline anyway).

**Comment by Charlotte-Holt** [comment]
@lauracowen @NottyCode, updated based on your feedback. I also confirmed with @billw1024 that the `JAVA_HOME` environment variable information is correct. 

Please review and let me know if you think additional changes need to be made. Thanks!!

**Comment by lauracowen** [comment]
Looks fine. Thanks

**Comment by Charlotte-Holt** [comment]
This is live at https://openliberty.io/docs/ref/general/#windows-service.html. Closing this issue.
