### ISSUE TITLE
Automatically cleanup leaked JDBC connections #10907

### ISSUE THREAD

**Issue by jmstephensgit** [OpenLiberty/docs#3691]
Epic 10907: Automatic Cleanup of Leaked Connections in Open Liberty
Epic link: https://github.com/OpenLiberty/open-liberty/issues/10907

An enhancement has been added to EJB Container,  Web Container and EE Concurrency tasks that will now close unshared connections that have not been closed by the application at the end of the request boundaries. This change in behavior was required for improved performance of connection usage and to prevent the connection pool from running out of available connections that remaining in use for an extended time, but are not being used.  An application leaking connections normally causes a connection wait time out exception with no connections available from the connection pool.

This behavior change for Liberty can be disabled with connection manager property autoCloseConnection="false".   Setting autoCloseConnection="false" is not recommended except for applications that may be designed to allow for a connection to remain open outside of the normal scope of the containers.  In this case the application may encounter an exception that the connection is already closed.  If this new function is disabled for applications designed to continue using connections outside the scope of the containers, the Liberty server expects the application will eventually close the connection.   Most applications designed this way are not following normal recommended programming models for connection management of get/use/close for connections.

**Comment by frowe** [comment]
Looks good, Jim.

**Comment by chirp1** [comment]
Fred, Jim, and I concluded that over the topics in this section from WebSphere Liberty: https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_dep_configuring_ds.html  We'll open other issues for these topic. Customers can use the blog post at https://github.com/openliberty/open-liberty/issues/15882  to implement the function until the docs are written.

**Comment by dmuelle** [comment]
Hi @jmstephensgit @frowe I've updated our JDBC connection pooling information to address `autoCloseConnection`. 

https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/feature/jdbc-4.2.html#_customize_connection_pool_settings

We have a call scheduled to review this info and any other possible updates that might be needed. One question I have is about the discrepancy between the issue description here and the info in the [21.0.0.3 beta blog post](https://www.openliberty.io/blog/2021/02/19/mpcontextpropagation-requesttiming-21003-beta.html#leakedConnections).
Here, the `autoCloseConnection` attribute is described from an edge-case perspective, where you might specify `false` to disable the behavior. In the blog post, it's described from the `true` perspective, to enable autoclose function. For now, I have followed the info in the blog post, since that is what is already out there. What is the default behavior?

**Comment by frowe** [comment]
@dmuelle David, we need to hold on this issue for a day or two.  We uncovered some issues in testing that may force some design changes.  We've got a meeting with Alasdair tomorrow to discuss, we'll know more after that.

**Comment by dmuelle** [comment]
After talking with Fred, since this feature is now enabled by default and should only be disabled in rare cases, there is no need to add a doc example. I'll remove the example I added to draft (which is now incorrect/redundant anyway). I suggested adding a statement to the `metatype.properties` file for `connectionManager` re when a user might want to disable the function by specifying `autoCloseConnection="false"` so it will show up in the gendoc.

**Comment by dmuelle** [comment]
copying the text I'm removing from the topic here in the off chance it might be needed at some point:

`Occasionally, application code might not close an unsharable connection that it obtains. Failing to close a connection prevents that connection from being returned to the connection pool for use by other requests. Because such connections are no longer available to the connection pool, they are called leaked connections. Over time, these leaked connections can degrade performance and eventually exhaust the connection pool. `

**Comment by dmuelle** [comment]
@frowe should we keep this issue open until we can determine if updates to metatype.properties file for `connectionManager` are needed ?  The [current description](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.jca.cm/resources/OSGI-INF/l10n/metatype.properties) doesn't seem to address the `autoCloseConnection` function being enabled by default or what value there might be in disabling it.

**Comment by frowe** [comment]
@dmuelle We don't anticipate any needing to disable auto close, it really would be a corner case.  Our L2 has specific instructions to assist customers in troubleshooting for the rare occasion this should happen.  I think the current wording for the metatype is sufficient.

**Comment by dmuelle** [comment]
Ok thanks- in case I'll close this issue
