### ISSUE TITLE
Link to example usages in related feature pages

### ISSUE THREAD

**Issue by sdaschner** [OpenLiberty/docs#371]
The example usages on the feature pages, for example on [Database Connectivity feature page](https://openliberty.io/docs/ref/feature/#jdbc-4.3.html) are helpful.

I believe right now it's rather hard to find these example usages, especially if developers look at other feature pages, (e.g. [Java Persistence API](https://openliberty.io/docs/ref/feature/#jpa-2.2.html) in the above example).

It would help a lot of we put in a pointer, e.g. "for an example usage have a look on _this page_" that links to the corresponding page. All features that enable or are enabled by the said features could link to pages that include example usages.

**Comment by NottyCode** [comment]
Hi, We already have a link from the JPA page to the JDBC feature pages. You need to scroll down a long way to find it, but it is there. I think a more direct example on the jpa feature pages would be good though.

**Comment by dmuelle** [comment]
Hi @sdaschner, was working through the backlog and came across this issue.

 What sorts of configuration examples would be useful for the JPA feature? We are adding an example for [configuring an alternate JPA provider](https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/reference/feature/jpaContainer-2.2.html) to the `jpaContainer-2.2` feature and, separately, [a concept overview for JPA](https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/data-persistence-jpa.html). But are we missing server configuration examples that are particular to the JPA feature you mention above?

In general, we are working on adding config examples to feature pages throughout the docs. But we had not targeted the `jpa-2.2` feature in particular yet, because we had not identified any feature-specific configuration that it required. 

We do have a guide that goes into setting up JPA for an app- [Accessing and persisting data in microservices using Java Persistence API (JPA)](https://www.openliberty.io/guides/jpa-intro.html), but if there are any sort of grab-and-go config examles we should add to the feature page, we can work on adding those as well. Let us know what you think! Thanks

**Comment by Charlotte-Holt** [comment]
JPA examples are being tracked in #3335
