### ISSUE TITLE
Update MP JWT config examples for MP 4.0

### ISSUE THREAD

**Issue by Rwalls1** [OpenLiberty/docs#3721]
SME: Teddy Torres
Proposed updates from issue #3511:

# Content proposal for [MP JWT config examples](https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/mpJwt-1.1.html) updates
The following suggested updates are drawn from steps 4 and 11 from the [Configuring the MicroProfile JSON Web Token](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_sec_json.html) topic:
## Import a Truststore to verify a MicroProfile JWT
You can configure a Truststore to verify JSON Web Tokens.  The default Keystore for MicroProfile does not contain the root certificates that are used to verify the authentication credentials that are stored in JSON Web Tokens. To verify JSON Web Tokens, you can import the default Java Truststore as shown in the following example:

```xml
<ssl id="defaultSSLConfig" keyStoreRef="defaultKeyStore" trustStoreRef="defaultTrustStore" />
<keyStore id="defaultTrustStore" location="${javaKeystoreLocation}" type="JKS" password="changeit" />
<mpJwt id="mympjwt" issuer="https://example.com"
   jwksUri="https://localhost:19443/jwt/ibm/api/myBuilder/jwk"/>
```
The `id` attribute in the `keyStore` element specifies the `“defaultTrustStore”` value to configure a Truststore within the Keystore. A Truststore contains the certificates that are used to validate the requests that are sent to applications with JSON Web Tokens. The `ssl` element is used to specify how the application validates the SSL connection to a server. Within the `ssl` element, the `id=defaultSSLconfig` attribute sets the SSL configuration as the default SSL configuration for the server that the application connects to. The `trustStoreRef=“defaultTrustStore”` attribute configures the `ssl` element to reference the Truststore so that the application recognizes the Truststore when it attempts to connect to the server. The `jwksUri="https://localhost:19443/jwt/ibm/api/myBuilder/jwk”` specifies the JWK endpoint URL that the application uses to connect to the server and verify the JWT.
## Configure access restrictions with MicroProfile JWT
By default, if the `mpJwt-1.0` feature is configured, all authorized requests must include a valid JSON Web Token in the HTTP header. To modify the default behavior to require JSON Web Tokens  in some applications only, you can add the `ignoreApplicationAuthMethod=“false”` attribute to the  `mpJwt` element as shown in the following example: 
```xml
<mpJwt ignoreApplicationAuthMethod=“false”/>
```
**Teddy's comments:**
> 1. Please change this sentence
>> The `jwksUri="https://localhost:19443/jwt/ibm/api/myBuilder/jwk”` specifies the JWK endpoint URL that the application uses to connect to the server and verify the JWT.
>to
>>The `jwksUri="https://localhost:19443/jwt/ibm/api/myBuilder/jwk”` specifies the JWK endpoint URL that the Liberty server uses to obtain the public keys from to verify the JWT.
> 2. We need to add the rest of the required steps in the "Configure access restrictions with MicroProfile JWT" section as follows:
>> Then, configure the application in one of two ways:
The application has an @LoginConfig annotation with the MP-JWT login method declared as the authentication method.
>> For example,
>> ```
>> @LoginConfig(authMethod = "MP-JWT", realmName = "MP-JWT")
>> ```
>> The web.xml file for the application has a declaration for the MP-JWT authentication method in the login-config element.
>> For example,
>> ```
>> <login-config> <auth-method>MP-JWT</auth-method> <realm-name>MP-JWT</realm-name></login-config>
>> ```

**Comment by Rwalls1** [comment]
@teddyjtorres Please review: https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/mpJwt-1.1.html
I added two more examples that were drawn from step 5 and step 10 from the [Configuring the MicroProfile JSON Web Token topic](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_sec_json.html). For the content from step 10, I tried to clarify the wording because I wasn't sure what the phrase "creates a security subject" means.

**Comment by teddyjtorres** [comment]
Hi @Rwalls1 . Thank you for the changes. They look good.

**Comment by dmuelle** [comment]
## content review

### Configure MicroProfile JWT
- The jwksUri attribute points the mpjwt element towards the public key https://localhost:19443/jwt/ibm/api/myBuilder/jwk, to validate the JSON Web Token.
--->
The jwksUri attribute points the mpjwt element toward the https://localhost:19443/jwt/ibm/api/myBuilder/jwk public key to validate the JWT.

- key and trust store-->keystore and truststore

- Since this is optional config except in version 1.0, should mention that and say that you can use MP Config properties to configure JWT auth, then for more information link to the JWT guide, and possibly also the JWT section of the SSO doc, since that has a good general overview

### Configure authentication filter to login with MicroProfile JWT
"a subset of applications, URLs, or IP addresses,. "--> remove extra comma at end of sentence

The `authFilter` element is missing from the "Feature configuration elements" on this page and all feature pages. I opened [this issue](https://github.com/OpenLiberty/open-liberty/issues/16127) to track the problem. No response so far from anyone I've asked about this- might be worth checking with @teddyjtorres to see why this element disappeared from the docs after the 20.0.0.11 release

### Import a truststore to verify a MicroProfile JWT
Is the variable `${javaKeystoreLocation}` a. recognized OL configuration variable? ie could someone specify it directly in their server.xml and it would automatically resolve to the proper location? If not, need to replace it with a plausible example value that uses the correct syntax for the value the user would provide. If so, we need to document ${javaKeystoreLocation} on the [Directory locations and properties](https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/directory-locations-properties.html) page.

### Configure the authentication method with MicroProfile JWT
I think a more precise title could be something like "Specify MicroProfile JWT as the authentication method for only certain applications" or "Designate specific applications to use MicroProfile JWT as the authentication method"

### Define role mapping for MicroProfile JWT
- this example references the `upn` claim without explaining that it's from the JWT. I figured it out only after searching around a little bit and finding the JWT section of the single sign in doc. I think its should say-
"By default, JSON Web Tokens use the `upn` claim from the JWT as the principal name and unique security name of the user."
- same for the reference to the `groups` claim. 
- Also, the example shows the `groupNameAttribute="groups"`, but isn't `groups` the default value? If so, I think you could replace it with a non-default example value, since you wouldn't have to specify the attribute to get the default. If I'm reading that right.

### Validate MicroProfile JWT claims with the user registry
I think this description lost some of the details from the KC example, which says:
"The program searches the principal name against the configured user registry, and creates a security subject based on user attributes from the user registry." I think some version of this statement, replacing "the program" with "Open Liberty", would be helpful

### Global issues
- where the example intros use "as shown in the following example",  set that phrase off with a comma, eg  "you can import the default Java truststore, as shown in the following example:"
- examples should specify that the code is in the `server.xml` file, where appropriate. I think all but a couple examples are server.xml code
- None of the MpJWT-1.0 information from KC has been preserved- do we need this info?
- The KC topic has a line about `keyName`, step 2d, that is not anywhere in the OL doc. The information is not included in the autogen for `keyName`. Should we either add keyName to the first example and put the explanation there? Or open a PR to update the keyName description in the metatype? Is this info still relevant to most users?
- do we have a plan or target to publish info on the relevant MPConfig properties? It seems like they were the main 1.2 update, but they're not being documented anywhere
-

**Comment by Rwalls1** [comment]
@dmuelle Thanks, I've addressed your feedback: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/feature/mpJwt-1.1.html

I think we should update the keyName description in the metatype to align with other issues related to autogen updates. I also don't agree that the examples need to specify the `server.xml` file because the autogen description for "Enabling this feature" already alludes to the `server.xml` file. I think it makes more sense to specify any instances where the example isn't related to a `server.xml` file, which I think I mentioned in each instance. I'll follow up with Teddy Torres regarding the `authFilter` element.

**Comment by dmuelle** [comment]
Ok sounds good- can you open a docbug to update keyName? One other thing:
## Import a truststore to verify a MicroProfile JWT
For the variable ${javaKeystoreLocation}, i think we need to replace that with an example keystore location, rather than an example config varible. In general, should avoid using ${variables} syntax unless its a variable that is defined in the OL server config, ie a user could out it directly into the code. There are some "example" keystore locations [here](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/rwlp_sec_keystores.html).

otherwise looks good

**Comment by Rwalls1** [comment]
@dmuelle Thanks, I've made that update: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/feature/mpJwt-1.1.html. I'll open a docbug for the keyName update.

**Comment by dmuelle** [comment]
Looks good, signing off. @ManasiGandhi this is ready for peer review.

**Comment by ManasiGandhi** [comment]
# Peer review


- “Within the `ssl` element, the `id=defaultSSLconfig` attribute sets the SSL configuration as the default SSL configuration for the server that the application connects to.” Can you change this to, “Within the `ssl` element, the `id` attribute sets the SSL configuration as the `defaultSSLconfig` configuration for the server that the application connects to.”

- Also, “The `trustStoreRef=“defaultTrustStore”` attribute configures the `ssl` element to reference the truststore so that the application recognizes the truststore when it attempts to connect to the server.” To “The `trustStoreRef` attribute configures the `ssl` element to reference the `“defaultTrustStore”`  so that the application recognizes the truststore when it attempts to connect to the server.”

- And, “The `jwksUri="https://localhost:19443/jwt/ibm/api/myBuilder/jwk”` attribute specifies the JWK endpoint URL that the server uses to obtain the public keys from to verify the JWT.” to, “The `jwksUri` attribute specifies the JWK endpoint URL `"https://localhost:19443/jwt/ibm/api/myBuilder/jwk”`that the server uses to obtain the public keys from to verify the JWT.”

- “To modify the default behavior to require JSON Web Tokens in only some applications, you can add the `ignoreApplicationAuthMethod=“false”` attribute to the `mpJwt` element, as shown in the following example:” to, “To modify the default behavior to require JSON Web Tokens in only some applications, you can set the `ignoreApplicationAuthMethod` attribute to `“false” ` in the `mpJwt` element, as shown in the following example:”

- “you can add an `@LoginConfig` annotation that contains the `authMethod = "MP-JWT"` attribute to specify MicroProfile JWT as the authentication method, as shown in the following example:” to, “you can add an `@LoginConfig` annotation that contains the `authMethod` attribute to specify MicroProfile JWT as the authentication method, as shown in the following example:”

- “To modify this behavior, you can add the `mapToUserRegistry="true"` attribute to the `mpJwt` element to, as shown in the following example:” to, “To modify this behavior, you can set the `mapToUserRegistry` attribute  to `"true"`  in the `mpJwt` element , as shown in the following example:”

- “The `mapToUserRegistry="true"` attribute forces JSON Web Tokens to validate user claims with the user registry.”, to, “The `mapToUserRegistry` attribute set to `"true"` forces JSON Web Tokens to validate user claims with the user registry.”

**Comment by Rwalls1** [comment]
@ManasiGandhi Thanks, I've addressed your feedback: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/feature/mpJwt-1.1.html

**Comment by Rwalls1** [comment]
These updates have been merged to vnext and will publish in the upcoming release.
