### ISSUE TITLE
Update JAX-RS client config examples for MP 4.0

### ISSUE THREAD

**Issue by Rwalls1** [OpenLiberty/docs#3723]
SME: Andy McCright
Suggested updates from issue #3511:
# Content proposal for [JAX-RS client config examples](https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/jaxrsClient-2.1.html) update
The following suggested update is drawn from step 12 from the [Configuring the MicroProfile JSON Web Token](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_sec_json.html) topic:
## Enable MicroProfile JWT authentication for JAX-RS
If you configure the MicroProfile JWT feature along with the JAX-RS Client feature, you can enable MicroProfile JWT authentication for JAX-RS services. To enable MicroProfile JWT authentication, you can add the `authnToken=“mpjwt”` attribute to the `webTarget` element as shown in the following example:
```xml
<webTarget uri="http://localhost:56789/protectedResourceWithMPJWT*" authnToken="mpjwt" />
```
This attribute adds MicroProfile JWT as an authorization header in the JAX-RS service that is specified by the ` uri="http://localhost:56789/protectedResourceWithMPJWT*”` attribute.

**Comment by Rwalls1** [comment]
@andymc12 Please review: https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/jaxrsClient-2.1.html

**Comment by Rwalls1** [comment]
@andymc12 Please review: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/feature/jaxrsClient-2.1.html

**Comment by andymc12** [comment]
Looks good - thanks @Rwalls1!

**Comment by Rwalls1** [comment]
@dmuelle Please content review: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/feature/jaxrsClient-2.1.html

**Comment by dmuelle** [comment]
# Content review
Making a few suggestions for examples throughout this doc as long as we're revisiting it

## Examples
The JAX-RS Client APIs allow you to specify properties on the client that configure settings like timeouts, proxy hosts, SSL properties, and so on.
--->
With the JAX-RS Client APIs, you can specify properties on the client that configure settings like timeouts, proxy hosts, and SSL properties.

## Change values when an application moves from development to production environments
When this application is deployed in a production environment, however, it might be necessary to add new settings.
--->
However, when this application is deployed in a production environment it might be necessary to add new settings.

This can be accomplished by adding the following configuration to the server config (server.xml):
--->
You can specify new settings by adding the following configuration to your `server.xml` file:

## Simplify SSL configuration in development
suggested edit:

During development, an SSL certificate might not match the server hostname on which the application is being tested because it matches the server hostname on which the application is ultimately deployed in production. The configuration can be changed during development to use a different SSL configuration or to disable hostname verification of SSL certificates. 

_...example_

To maintain application security, do not disable SSL verification in production environments.

## Set custom properties
suggested edit:

If your application uses providers such as a the `ClientRequestFilter` or `ClientResponseFilter` interfaces, they can read and react to custom properties that are specified on the JAX-RS Client or the `WebTarget` interface. You can also change the Open Liberty client implementation behavior by specifying custom properties. These properties are normally specified programmatically by using the `webTarget.property("myCustomProperty", "someValue")` configuration, but you can also specify custom properties by specifying the `WebTarget` element in your `server.xml` file:

## Enable MicroProfile JWT authentication
One distinction from the KC source is missing here. The KC says 

_If Liberty is also acting as a JAX-RS 2.0 client, you add the authnToken="mpjwt" statement to the <webTarget> configuration element. The Liberty JAX-RS client then automatically adds JWT as an authorization header in the JAX-RS service call._

So in this case, the auth is for OL calling other services, teling the server to add the JWT to the auth header for those calls. This is not clear in your example, which says

 _If you configure the MicroProfile JWT feature along with the JAX-RS Client feature, you can enable MicroProfile JWT authentication for JAX-RS services._

That could mean that it enables OL to accept  JWT as auth for incoming calls to a JAX-RS service that runs on OL. Unless the example here is deliberately different than the KC source, I think you should clarify that the config is to add JWT to auth headers specifically when OL is a JAX-RS client. And if it works both ways, should say so.


Will this example be linked from any other MPJWT docs? Although I agree that it's `jaxrsClient` config, I think users should be able to find it if they look in MPJWT doc. I'm not sure if we are adding a specific MpJWT doc but if so, that would be the place to link to it from. Could also possibly do it from MPjwt feature page but not sure how best to do that.

also:

If you configure the MicroProfile JWT feature
--->
If you configure the feature:mpJwt[display=MicroProfile JSON Web Token] feature

**Comment by Rwalls1** [comment]
@dmuelle Thanks, I've addressed your feedback: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/feature/jaxrsClient-2.1.html

**Comment by dmuelle** [comment]
looks good- a couple minor things:

### Change values when an application moves from development to production environments
If the application is deployed in a different environment, these settings might need to change. 
--->
If the application is deployed in a different environment, certain settings might need to change. 

### Set custom properties
The complete list of pre-defined properties is available here: webTarget.
--->
For a complete list of pre-defined properties, see [webTarget].

### Enable MicroProfile JWT authentication

It's still not particularly clear what enabling MpJWT auth entails. Does it mean the app can send or accept JWT? Or both? The explanation should specify. The KC source (step 12) says 
"Configure Liberty to automatically propagate MP-JWT as an authentication token when Liberty calls other JAX-RS services.... For example, if you add the <webTarget uri="http://localhost:56789/protectedResourceWithMPJWT*" authnToken="mpjwt" /> element to the server.xml file, the JWT token is added to the authorization header when the http://localhost:56789/protectedResourceWithMPJWT/ service is called."  That's more specific than just "enabling" MpJWT and would be important for the user to know, especially if they landed on this page looking for MpJwt info and were not familiar with purpose of the JAX-RS Client feature

**Comment by Rwalls1** [comment]
@dmuelle Please review: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/feature/jaxrsClient-2.1.html

**Comment by Rwalls1** [comment]
@dmuelle Please review: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/feature/jaxrsClient-2.1.html

**Comment by dmuelle** [comment]
LGTM, signing off

@ManasiGandhi this is ready for peer review

**Comment by ManasiGandhi** [comment]
# Peer review


## Examples

- “without having to edit and recompile the Java code”, can you change to “without the need to edit and recompile the Java code”, as you don’t need to edit and recompile the Java code if you set the values in the `server.xml` file. Or maybe, “without editing and recompiling the Java code”

## Change values when an application moves from development to production environments

- The heading says “Change values when an application moves from development to production environments”. The paragraphs, however, refer to changing settings. Can you change the wording for consistency.

- Acrolinx flags the word ‘very’ in the sentence, “If the application is deployed in a different environment, certain settings might need to change. For example, an application might initially be written to run in a development environment, where all remote RESTful services are available without a proxy server and can connect very quickly:”

- “However, when this application is deployed in a production environment it might be necessary to add new settings.” Can you add some context about why it would be necessary to add new settings in production environment? Is it because all remote RESTful services might not be available without a proxy server in a production environment?

- Is it possible to avoid parentheses in these sentences, “This configuration alters the `WebTarget` in the Java code to use the specified HTTP proxy server (myProxyHost:55555) and use connection and receive timeouts of 60 seconds (60,000 milliseconds) instead of the default timeouts.”, also, add element after `WebTarget`

## Simplify SSL configuration in development

- “Simplify SSL configuration in development”, suggested heading, “Modify SSL configuration in development”.

- “During development, an SSL certificate might not match the server hostname on which the application is being tested because it matches the server hostname on which the application is ultimately be deployed in production.”, Suggested change, “During development, an SSL certificate might not match the server hostname on which the application is tested because it matches the server hostname on which the application is deployed in production.”

## Set custom properties

- “Set custom properties”. The paragraph mentions, “specify” with reference to custom properties. Can you make it consistent?

- “These properties are normally specified programmatically by using the `webTarget.property("myCustomProperty", "someValue")` configuration but you can also specify custom properties by specifying the `WebTarget` element in your `server.xml` file:”, remove “normally”. Suggested “These properties can be set programmatically by using the `webTarget.property("myCustomProperty", "someValue")` configuration but you can also set custom properties by specifying the `WebTarget` element in your `server.xml` file:”

## Enable MicroProfile JWT authentication for JAX-RS services

- “With the Open Liberty JAX-RS client, you can send MicroProfile JWT as an authentication method for JAX-RS services, as shown in the following example:”, can you change “send” to “use” as it isn’t sounding right.

- “The `authnToken=“mpjwt”` attribute”, can you change this to “`authnToken` attribute”?

**Comment by Rwalls1** [comment]
@ManasiGandhi Thanks, I've addressed your feedback: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/feature/jaxrsClient-2.1.html

**Comment by ManasiGandhi** [comment]
@Rwalls1 The changes look good to me.

**Comment by Rwalls1** [comment]
These updates have been merged to vnext and will publish in the upcoming release.
