### ISSUE TITLE
Add enabling of allowOpIfRepoDown on FedRepo and Ldap page

### ISSUE THREAD

**Issue by kristip17** [OpenLiberty/docs#3957]
We should suggest that users enable `allowOpIfRepoDown` 

https://openliberty.io/docs/21.0.0.3/reference/feature/ldapRegistry-3.0.html
Under `Federate LDAP user registries`

Add new sentence after, `LDAP user registries are federated by default. If you configure more than one LDAP user registry in your server.xml file, then the user registries are automatically federated into a common user registry. ` To verify that a user is unique in the common user registry, all registries are searched and must return successfully or any search request fails. To avoid failures if one registry is unavailable, set the `allowOpIfRepoDown` attribute to true on the federatedRepository element.

https://openliberty.io/docs/21.0.0.3/reference/feature/federatedRegistry-1.0.html

Under `Custom federation of user registries`, 

After `This configuration can be useful if you want to exclude certain user registries from a federated group by selectively including only the user registries that you want to federate.` Add: To avoid failures if one registry is unavailable, set the `allowOpIfRepoDown` attribute to true on the federatedRepository element.

Also, update the sample server.xml:
From: `<primaryRealm name="PrimaryRealm">`
To: `<primaryRealm name="PrimaryRealm" allowOpIfRepoDown="true">`

**Comment by dmuelle** [comment]
Hi @kristip17 , I went ahead and made these edits while I was working on the krb5 doc. I moved some things around a bit for consistency with the existing info. 

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.4/reference/feature/ldapRegistry-3.0.html#federate
(update is after the example, where the config is explained)

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.4/reference/feature/federatedRegistry-1.0.html

In both of these, I changed:

set the allowOpIfRepoDown attribute to true on the federatedRepository element.
--->
set the allowOpIfRepoDown attribute on the primaryRealm element to true

Because the attribute isn't specified directly on the federatedRepository element in the examples, but on the primaryRealm element. But now Im wondering if it should be "the primaryRealm sub-element" ?

**Comment by kristip17** [comment]
I'm fine with element or sub-element --whatever you think is appropriate for the doc.

**Comment by dmuelle** [comment]
ok, docs are updated
https://draft-openlibertyio.mybluemix.net/docs/21.0.0.4/reference/feature/ldapRegistry-3.0.html#federate

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.4/reference/feature/federatedRegistry-1.0.html

Let me know if any further changes are needed. If not, you can sing off by adding the `technical reviewed` label to this issue. Thanks!

**Comment by dmuelle** [comment]
closing this bug, updates will publish with the rest of the krb5 doc in 21.0.0.5
