### ISSUE TITLE
Add Admin Center feature doc

### ISSUE THREAD

**Issue by aknguyen7** [OpenLiberty/docs#4029]
Add the adminCenter-1.0 feature example.

1. To enable the adminCenter1.0 feature, the doc would include something similar to the Set up Admin Center section of the blog here 
https://blogs-draft-openlibertyio.mybluemix.net/blog/2021/04/15/admin-center-21004.html
2. Release will the runtime updates target? 21.0.0.4

**Comment by dmuelle** [comment]
Hi @aknguyen7 @mbroz2 - 

can you review  the following draft for the admin center feature doc?

https://docs-draft-openlibertyio.mybluemix.net/docs/latest/admin-center.html

I based this draft on both of your blog posts, as well as some of the info from the old KC topics (excluding collective info) and what I saw from trying out Admin Center myself per the blog instructions.

If you see anything that needs an edit, or if there's anyone else I should send this to for review, just let me know. If it looks good, you can sign off by adding the `technical reviewed` label to this issue. Thanks!

**Comment by mbroz2** [comment]
docs/latest/admin-center.html looks great (technically, localhost may not be the loopback address if someone changed it, but lets keep it as written for simplicity).

docs/21.0.0.5/reference/feature/adminCenter-1.0.html has a typo:
`configure at least oi=]ne user in either`


The only other thought is whether we'd want to include a screenshot of the toolbox and especially the Java Batch and OIDC tools, since those sections looks a bit anemic in comparison to Explore and Server Config

**Comment by aknguyen7** [comment]
docs LGTM

**Comment by dmuelle** [comment]
Thanks for reviewing @mbroz2 @aknguyen7 - I added a few more screenshots to the doc and fixed the typo that Michal mentioned

**Comment by Rwalls1** [comment]
# Content review

- I think the title of this doc should be changed to something like “Manage Open Liberty with the Admin Center”. I don’t think it’s important to highlight in the title the Admin center is accessed from a web browser, I think the value of this doc is the management capabilities of the Admin Center not the fact that you can manage Open Liberty “from a web browser”.
- Global comment: Most of the topic describes actions that can be completed and I think the headings for each section should reflect that. I think the section headings should be declarative statements that highlight the action that is completed.
- Global comment: I think each instance of the phrase, “The following screen capture” should be changed to “The following image” to be more concise and maintain clarity as I’m not sure if “screen capture” is a standard term.

## Admin Center setup
- I think you should change “try out Admin Center” to “set up Admin Center” to focus on a more meaningful action that aligns with the purpose of the section that is specified with the section heading.
- I think you should remove the comments from the config example. Any description of the configuration should probably be provided outside of the example.

## Admin Center login
- I think you should change the phrase “point a web browser at the Admin Center login page” to something like “navigate to the Admin Center login page in a web browser with the following URL.”, to avoid potentially ambiguous phrasing
Change “on which the Open Liberty Server is running” to “that the Open Liberty Server runs on”
- I think you should add an identifier after `localhost` to avoid confusion.
Check the Asciidoc syntax reference or IBM style guide to make sure that admin and adminpwd should be in italics. I’m not sure if that’s the proper syntax for referring to screen navigation items.

## The Toolbox

For consistency purposes, I think “Toolbox” should also be in bold as it also refers to a screen navigation item.

## The Server Config Tool

- For clarity and consistency purposes, I think you should add an identifier after “Ctrl+space”. So, maybe change the sentence containing that phrase to something like, “You can use the Ctrl+space keyboard shortcut to use content assist”
- In the phrase “the Design tab of the Server Config tool”, “Design” should also be in bold because it refers to an element on the screen.

## The Explore Tool

For clarity purposes, change “choosing from the menu” to something like “choosing one of the options from the menu”.

**Comment by dmuelle** [comment]
thanks for reviewing @Rwalls1 - I made the following changes per your review

- [x] title of this doc should be changed to something like “Manage Open Liberty with the Admin Center”.
- [x] the section headings should be declarative statements that highlight the action that is completed.
- [ ]   each instance of the phrase, “The following screen capture” should be changed to “The following image”  **left this as is- "screen capture" is the recommended term per acrolinx**
- [x] change “try out Admin Center” to “set up Admin Center”
- [x] remove the comments from the config example.
- [x] change the phrase “point a web browser at the Admin Center login page” to something like “navigate to the Admin Center login page in a web browser with the following URL **IBM terminology recommends "go to" rather than "navigate"**
- [x] add an identifier after localhost to avoid confusion
- [x] _admin-pwd_ ---> `admin-pwd` **per [ibm style guidance for highlighting](https://ibmdocs-test.mybluemix.net/docs/en/ibm-style?topic=format-highlighting)**
- [x] “Toolbox” should also be in bold 
- [ ]  add an identifier after “Ctrl+space”. **left this as is- "Press Ctrl+Space" is consistent with [IBM style guidance for key combinations](https://ibmdocs-test.mybluemix.net/docs/en/ibm-style?topic=elements-keyboard-keys)**
- [x] “Design” should also be in bold because it refers to an element on the screen
- [x] change “choosing from the menu” to something like “choosing one of the options from the menu”.

**Comment by ManasiGandhi** [comment]
@dmuelle The topic looks good! Few suggestions:
# Peer review
## Manage Open Liberty with Admin Center

- [ ] The topic talks about managing server configuration and monitoring sever resources. It doesn’t seem to talk about how to “monitor your server configuration”. Maybe remove “monitor”.

## Set up Admin Center

- [ ] Is it possible to make this example smaller, (since the featuremanager, and basic user registry is already linked), and just mention the keyStore and httpEndpoint elements in the example instead of the whole server. Also, could you link to the app security anchor link to [configure with basic user registry](https://www.openliberty.io/docs/21.0.0.4/reference/feature/appSecurity-3.0.html#_configure_a_basic_user_registry).

## Log in to Admin Center

- [ ] “To access the Admin Center GUI, make sure that your server is running.” Could you change to, “Make sure that your server is running before you access the Admin Center GUI” or something similar for clarity.

- [ ] “If your browser prompts you to confirm that the connection is trusted, specify an exception or otherwise enable the connection to continue to Admin Center.” Remove “or” for conciseness.

- [ ] Are we going to track any changes in UI and change screen captures by opening docbugs?.

## Select tools from the Toolbox

- [ ] What is the OL strategy for making the tools bold, for example, “The **Java Batch** and **Open ID Connect** tools are available” from accessibility point of view? 

## Manage your server configuration with the Server Config tool

- [ ] “If you do not add this element, configuration files are shown in read-only mode.” Maybe add “the” before “configuration files”.

## Monitor your server with the Explore tool

- [ ] “You can use the Applications view on the vertical navigation bar to monitor, stop, start, or restart applications that are running on your server.” Remove “vertical”, it seems unnecessary as there is only one navigation bar. 

## Manage Java batch jobs with the Java Batch tool

- [ ] **View Logs** icon is not visible in the screen capture.

- [ ] configure cross origin region sharing (CORS) link is broken.

**Comment by dmuelle** [comment]
Thanks for reviewing @ManasiGandhi i- I made some of the changes, others are discussed below: 

## Manage Open Liberty with Admin Center

- [x] The topic talks about managing server configuration and monitoring sever resources. It doesn’t seem to talk about how to “monitor your server configuration”. Maybe remove “monitor”.

## Set up Admin Center

- [ ] Is it possible to make this example smaller, (since the featuremanager, and basic user registry is already linked), and just mention the keyStore and httpEndpoint elements in the example instead of the whole server. Also, could you link to the app security anchor link to [configure with basic user registry](https://www.openliberty.io/docs/21.0.0.4/reference/feature/appSecurity-3.0.html#_configure_a_basic_user_registry).

**I think in this case providing the full server.xml is helpful because someone could copy the whole thing if they want to test out the admin center, without having to click through to mulitple topics to get the right config**

## Log in to Admin Center

- [x] “To access the Admin Center GUI, make sure that your server is running.” Could you change to, “Make sure that your server is running before you access the Admin Center GUI” or something similar for clarity.

- [ ] “If your browser prompts you to confirm that the connection is trusted, specify an exception or otherwise enable the connection to continue to Admin Center.” Remove “or” for conciseness. **left as is- i think it would change the meaning to remove "or".**

- [x] Are we going to track any changes in UI and change screen captures by opening docbugs?. 
**good point- i think we will have to keep the doc up to date with any changes, though it is unlikely that it will change often.**

## Select tools from the Toolbox

- [x] What is the OL strategy for making the tools bold, for example, “The **Java Batch** and **Open ID Connect** tools are available” from accessibility point of view?  **I think we're ok accessibility-wise because they are not headings. The[ ibm style guidance for highlighting](https://ibmdocs-test.mybluemix.net/docs/en/ibm-style?topic=format-highlighting#highlighting-by-style) specifies bold for Interface controls.**

## Manage your server configuration with the Server Config tool

- [x] “If you do not add this element, configuration files are shown in read-only mode.” Maybe add “the” before “configuration files”.

## Monitor your server with the Explore tool

- [x] “You can use the Applications view on the vertical navigation bar to monitor, stop, start, or restart applications that are running on your server.” Remove “vertical”, it seems unnecessary as there is only one navigation bar. 

## Manage Java batch jobs with the Java Batch tool

- [x] **View Logs** icon is not visible in the screen capture. **view logs icon is on the far left, there is a tooltip label in the UI when you hover over the tool**

- [x] configure cross origin region sharing (CORS) link is broken. **link works, just not on the `docs-draft/` site because that site doesn't include guide content. If you access it from the `draft/` site, it works.**

**Comment by dmuelle** [comment]
doc is published with 21.0.0.5
