### ISSUE TITLE
CVE-2021-26296 not listed in security-vulnerabilities.html

### ISSUE THREAD

**Issue by jkleinlercher** [OpenLiberty/docs#4228]
Why is  CVE-2021-26296 not listed in  https://openliberty.io/docs/21.0.0.5/security-vulnerabilities.html although CVE-2021-26296 affects Apache Myfaces < 2.3.8 and Apache Myfaces got updated in openliberty 21.0.0.4 with https://github.com/OpenLiberty/open-liberty/issues/15744 ? From my Point of view openliberty < 21.0.0.4 is affected by CVE-2021-26296, right?

**Comment by jkleinlercher** [comment]
And actually this is also mentioned in https://github.com/OpenLiberty/open-liberty/issues/15989

**Comment by dmuelle** [comment]
Hi @jkleinlercher - thanks for opening this- this CVE was omitted from the 21.0.0.4 release due to an oversight. That's fixed in #4239 . The updated entry is now on our draft site: 

https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.6/security-vulnerabilities.html

This update will publish to the production site with the 21.0.0.6 docs release on 6/11. sorry for the confusion. Closing this issue, feel free to reopen if further edits are required.
