### ISSUE TITLE
Does not include details of featuresBom

### ISSUE THREAD

**Issue by mjwhale** [OpenLiberty/docs#4413]
Document: featureUtility installServerFeatures
http://openliberty.io/docs/21.0.0.6/reference/command/featureUtility-installServerFeatures.html

The document is inaccurate, the latest version 21.0.0.6 has the featuresBom option which is not documented but described in the command below, however, the command description doesn't prescribe when or why this option should be used.

```
Usage:
        featureUtility installServerFeatures [options] name...
        featureUtility isf [options] name...

Description:
        Install the required features for a named server.

Options:
    --noCache
        Features installed from a remote repository                          
        (for example, Maven Central) are not cached locally.

    --verbose
        Display additional debug information while the action runs.

    --acceptLicense
        Accepts the license agreement.

    **--featuresBom=Maven coordinate
        Specify the Maven coordinate for the features BOM file. This option  
        allows for the installation of user features from the configured     
        maven repository. Ensure that the repository also contains the       
        associated features JSON file in the same groupId as the BOM.**

    name ...
        The name of an existing server in the same Liberty environment.
```

**Comment by dmuelle** [comment]
Hi @mjwhale - thanks for opening this issue. 
The `featuresBom` option should not display in the command help, it is not a valid command parameter. This was a known issue for the 21.0.0.6 release (documented in the [Release notes: Known Issues](https://www.openliberty.io/blog/2021/06/11/request-timing-21006.html) and [this Git issue](https://github.com/OpenLiberty/open-liberty/issues/17478)), which was fixed in the 21.0.0.7 release, after which the option no longer appears in the help. Sorry for the confusion.
