### ISSUE TITLE
Documentation for Transaction Peer Recovery

### ISSUE THREAD

**Issue by jonhawkes** [OpenLiberty/docs#4423]
Documentation for issue [8968](https://github.com/OpenLiberty/open-liberty/issues/8968)

The ["Administering the transaction service on Liberty"](https://www.ibm.com/docs/en/was-liberty/base?topic=manually-administering-transaction-service-liberty) page needs updating with a new topic "Configuring Peer Recovery".

**Comment by dmuelle** [comment]
Related to https://github.com/OpenLiberty/docs/issues/3348

**Comment by dmuelle** [comment]
Hi @jonhawkes - is there an estimated target release for this feature? I don't see any particular release tagged in the epic yet but would be good to have a general idea so we can plan to migrate the related topics from IBM Docs to Open Liberty docs in the same release.

**Comment by jonhawkes** [comment]
Hi David. Don't have a target release yet. It definitely has to be in before the end of this year. The earlier the better. It's slightly odd in that the code was actually shipped undocumented years ago. This feature will effectively document the feature and declare support.

**Comment by dmuelle** [comment]
Ok thanks- I think as part of the same work we'll want to not only document this feature and migrate the other information, but also provide a little contextual info about transactionality and why/when you might need it in an app. I can go ahead and start working on that and the migration and we can add the new information when we have it.

When you have a chance, would you be able to take a look at the [Administering the transaction service on Liberty](https://www.ibm.com/docs/en/was-liberty/nd?topic=manually-administering-transaction-service-liberty) topics in IBM Docs and let me know if everything there is still current and relevant to OL users?  We will  optimize/update the info and remove any redundancies as part of the migration.

**Comment by dmuelle** [comment]
Updated draft that contains the information required for #4423 

https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.9/transaction-service.html

**Comment by dmuelle** [comment]
per email discussion with Jon, content for this feature is being included as a section in the doc that is being developed for #3348 . Closing this issue and tracking the work for both in that issue

**Comment by dmuelle** [comment]
actually, will keep this one ope since it might be linked from the epic documentation. Will transfer info from #3348 here and close that one

**Comment by dmuelle** [comment]
The following comments were originally in #3348, transferring them here and closing that issue:

This doc provides the conceptual foundation in the OL docs for the ID updates needed for  #4423 / [8968](https://github.com/OpenLiberty/open-liberty/issues/8968).

It interpolates information from the following KC /IBM Docs topics for WebSphere Liberty:
- [Administering the transaction service on Liberty](https://www.ibm.com/docs/en/was-liberty/nd?topic=manually-administering-transaction-service-liberty)
- [Configuring the startup of the transaction service](https://www.ibm.com/docs/en/was-liberty/nd?topic=liberty-configuring-startup-transaction-service)
- [How database transactions are recovered](https://www.ibm.com/docs/en/was-liberty/nd?topic=liberty-how-database-transactions-are-recovered)
- [Storing transaction logs in a relational database](https://www.ibm.com/docs/en/was-liberty/nd?topic=liberty-storing-transaction-logs-in-relational-database)

comments from KC tracking sheet for these topics

<div ccp_infra_version='3' ccp_infra_timestamp='1626357664556' ccp_infra_user_hash='3774073639' ccp_infra_copy_id='32e7c29c-d864-4028-8a38-4760d27befaa' data-ccp-timestamp='1626357664556'><html>

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">

</head>

<body link="#0563C1" vlink="#954F72">



Administering the transaction service on Liberty | Transactionality.
-- | --
Configuring the startup of the transaction service | This is reference info that's in the gendoc: https://www.openliberty.io/docs/latest/reference/config/transaction.html
How database transactions are recovered | Bits of info that should be with the first topic.
Storing transaction logs in a relational database | Bits of info that should be with the first topic.



</body>

</html>
</div>

 I have a couple questions about parts of this topic where we could supply a little more contextual information for users who might not be familiar with  transaction service functions.

- we give an example of configuring recovery to occur at server startup rather than when the service is first used (`recoverOnStartup`). Why or when might someone want to configure this option? What is the benefit?

**You might want transaction recovery to happen at server startup so that the processing overhead happens then rather than right at the time you want to start doing transactional work. By default this setting is false so the server starts up faster.**

> "Setting the acceptHeuristicHazard attribute to false specifies that not all applications on this server accept the possibility of heuristic hazard in a two-phase transaction that contains a one-phase resource." 

What is the result of this setting? How does it change the server behavior or enable the configuration? Generally w/ Open Liberty we focus on  cloud native app scenarios where a single app runs on a server. 

**This setting enables last participant support (LPS). LPS allows a single one-phase resource to participate in a two-phase transaction with one or more two-phase resources. The name of the setting was (back in tWAS days) originally supposed to make it clear that enabling LPS carries some risk of a heuristic outcome for the transaction in the event of a network failure on the commit of the one-phase resource. The sentence here should be replaced.**

> You can configure an Open Liberty server to recover the logs of a different application server. The original owning application server must not be running when you use this procedure. It is typically employed to perform any outstanding transactional recovery when the transaction service logs are available but the original owning application server cannot be started.

This tells you that you can do this and why you would, but it doesn't tell you how. Could we provide a code example?
**This should be removed. This scenario will be covered in the section I will supply for the new feature.**

> If you store transaction logs in an RDBMS, each server must have its own tables. You can specify a unique table suffix by using the transactionLogDBTableSuffix attribute for the transaction element. The value for this attribute is a string that is post-pended to the table name to make it unique to the server where the table is hosted.

Can we provide a code example for `transactionLogDBTableSuffix` ? Is it as simple as

```xml
<transaction transactionLogDBTableSuffix="MyServer1" />
```
**Yes**

Lastly, the "Manual configuration of database tables" section provides DDL examples, but doesn't explain how or where to implement them. Is this code that would go into the `server.xml`? It also says "you must create the two database tables manually..." but doesn't explain why you need two tables. In general seems like a lot of information was missing from [the IBM Docs source](https://www.ibm.com/docs/en/was-liberty/nd?topic=liberty-storing-transaction-logs-in-relational-database), leaving it to the user to either know or not know how to use the DDL examples. If these examples are likely to be useful to a majority of users, we should provide more context to explain how to implement them. Also want to make sure the examples are current- not sure if the "old version of Db2" is still in wide use. If not, we shouldn't document it.

**This part does seem to have lost a lot compared to what we had here. The sentence about providing HA support is not true and the sentence about this being supported for production use is no longer necessary.
This Liberty doc was originally extracted from the tWAS doc and it was assumed the audiences would be the same people. For example it was assumed that anyone contemplating putting their transaction logs in a database would be sys admins who would know how to use DDL. The examples are current but I'm not sure whether they're really necessary anymore. Originally Liberty could only automatically create tables in  DB2 and Oracle for this so we provided the DDL examples so that sys admins could adapt them for whatever other database they wanted to use. (DDL is not standardized so it differs between different database vendors). In practise, the only other databases we've seen in use are PostgreSQL and MSSQL, and they're both automatically supported by Liberty now.**

**Comment by dmuelle** [comment]
current draft: https://docs-draft-openlibertyio.mybluemix.net/docs/latest/transaction-service.html

**Comment by dmuelle** [comment]
[pr.txt](https://github.com/OpenLiberty/docs/files/7000092/pr.txt)

original draft of peer recovery info, which Jon provided by email

**Comment by chirp1** [comment]
John has technically reviewed David's draft. The topic just has to go through peer review. I'm approving the https://github.com/OpenLiberty/open-liberty/issues/8968 epic.

**Comment by ManasiGandhi** [comment]
@dmuelle The draft looks good! A few edit suggestions,

# Content review

## Introduction

- [x] “The Open Liberty transaction service writes information to a transaction log for every global transaction that involves two or more resources, or that is distributed across multiple servers. You can configure the transaction service to control when and how database transactions are recovered after a server failure.” I would interchange the two sentences. The sentence “You can configure the transaction service to control when and how database transactions are recovered after a server failure.”, is a problem statement which a developer might want to work on the developer/user would like to read before what the Open Liberty transaction service has to offer. Suggested edit, “You can configure the Open Liberty transaction service to control when and how database transactions are recovered after a server failure. The transaction service writes information to a transaction log for every global transaction that involves two or more resources, or that is distributed across multiple servers.”
- [ ] “Information is written to the transaction logs in the prepare phase of a distributed transaction.” Could you elaborate more on the “prepare phase” as it may not be obvious to some. Optionally, you could link it to https://docs.oracle.com/cd/B12037_01/server.101/b10739/ds_txns.htm#i1007836.
- [ ] Similarly, in the sentence “If a server with active transactions restarts after a failure, the transaction service is able to use the logs to replay any indoubt transactions.”, could you elaborate on “indoubt transactions”? Also, IBM docs refer to “indoubt transactions” as “in-doubt transactions” in some places. Should we stick to “in-doubt transactions”?
## Transaction service configuration

- [x] “By default, transaction recovery after a server failure happens when the transaction service is first used rather than at server startup.” Change “happens” to “occurs” for consistency with the preceding sentence.
- [ ] “The 0 value for the heuristicRetryWait attribute specifies that the server does not retry a completion signal, such as a commit or rollback. By default, up to five retries occur after a transient exception from a resource manager or remote partner.” Completion signal, transient exception, resource manager, and remote partner need some explanation or linking to a relevant resource.
- [x] Similarly, in this sentence, “However, enabling LPS carries some risk of a heuristic outcome for the transaction in the event of a network failure on the commit of the one-phase resource.”, heuristic outcome needs elaboration.

## Transaction recovery in a cloud environment

- [x] “For more information, see the Transaction log management section.” Add anchor link.

## Transaction log management

- [x] “To store your Open Liberty transaction logs in an RDBMS, you can configure a dedicated, non-transactional data source in your server.xml file.”, elaborate on “non-transactional data source”.

## Manual configuration of database tables

- [x] “For more information, consult the vendor documentation for your chosen database.”, I would remove the term “vendor”, as Laura had previously mentioned about not using it.

Generally, if there is an IBM resource to link to for the topic related concepts similar to Oracle documentation, it would help to include it in a See also section.

**Comment by dmuelle** [comment]
Thanks @ManasiGandhi - I've updated the draft with changes from your review:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.9/transaction-service.html

In general, I've avoided providing explanations of foundational terms that the reader is likely to be familiar with, per Jons email comment. However I did add a sentence or two to clarify in a couple places. @jonhawkes can you review the following two statements and let me know if they are accurate, or ifn there is a better way to concisely and generally explain the term for the purposes of this doc?

heuristic outcome- though this term is widely used, it's usually not explained. I had to dig around to come up with a concise definition. Is this acurate?
_A heuristic outcome is an exception that can occur after a failure when a remote partner anticipates a different outcome for the transaction than what is specified by the resource manager._ 

I added explanation for non-transactional data source, to make it clear how this option is enabled in the example:
_The false value for the transactional attribute specifies that the datasource is non-transactional. Transaction logs can be written to this data source, but it does not participate in transactions._ 

other edits

- reversed the order of the 1st two sentences
- w/r/t "prepare phase", as @jonhawkes mentioned via email, this is a basic concept that the reader is likely to be familiar with and for which information can easily be found elsewhere. As he suggested, I've avoided linking to Oracle, but per our conventions, I didn't link to wikipedia either. This concept is not unique to OL, nor is it the focus of this topic or section so I've left as is.
- "indoubt" is the spelling recognized by [IBM terminology](https://w3.ibm.com/standards/terminology/cgi-bin/lookup?ug=corporate&term=indoubt&submit=Search&source=en&target_switch=none&template=simple&db_name=LOGOS&11=main+form&11=acronym%7Eabbreviation&11=prohibited)
- per Jons email comment, changed "happens" to "occurs" in the sentence you cited
- added anchor link for "Transaction log management section"
- removed reference

**Comment by dmuelle** [comment]
changes are on the vNext branch and will publish with the 21.0.0.9 docs release. Closing this issue
