### ISSUE TITLE
Update dev mode doc with section on Maven projects with multiple modules

### ISSUE THREAD

**Issue by ericglau** [OpenLiberty/docs#4444]
The following feature adds dev mode support for Maven projects with multiple modules: https://github.com/OpenLiberty/ci.maven/issues/697. This feature will be available in the upcoming version `3.4` of the Liberty Maven Plugin.  Note that this will only available for Maven for now (i.e. Gradle multi project builds are not supported with dev mode yet).  For reference, the design document is at https://ibm.box.com/s/lziitxx4jpsmekddi8p0nev90sevqv3l

The dev mode readme in the Liberty Maven Plugin has been updated to describe how to use it with multiple modules: https://github.com/OpenLiberty/ci.maven/blob/main/docs/dev.md#multiple-modules

This functionality is available both for regular dev mode, and for dev mode for containers.

- [x] Update the dev mode documentation at https://openliberty.io/docs/latest/development-mode.html with a section to describe support for multiple modules.  This can be similar to https://github.com/OpenLiberty/ci.maven/blob/main/docs/dev.md#multiple-modules or can point to it.

- [x] To keep the rest of the doc up to date, update the example versions in https://openliberty.io/docs/21.0.0.7/development-mode.html#_start_dev_mode_with_container_support with version `3.4` for Maven, and `3.2` for Gradle.

**Comment by dmuelle** [comment]
Hi @ericglau , I've updated the draft doc with these changes:

https://draft-openlibertyio.mybluemix.net/docs/latest/development-mode.html#_run_multi_module_maven_projects_in_dev_mode

1. added a section for "Run multi-module Maven projects in dev mode" that explains the function and points to the Maven plug-in doc for more information.
2. updated the examples to use Maven 3.4 and Gradle 3.2

Let me know if any further edits are needed. If not, you can add the `technical reviewed label to this issue to sign off.

Not sure when the new Maven plug-in version is available. These updates can publish with 21.0.0.8 docs release on 8/6 or wait until 21.0.0.9

**Comment by dmuelle** [comment]
comments from @ericglau via slack:

The first paragraph mentions dev mode with container support, but we haven’t provided any examples.  Perhaps in the second paragraph where it says “run the mvn liberty:dev command”, it could also mention liberty:devc, e.g. “run the mvn liberty:dev or mvn liberty:devc command”
11:28
The latter example of mvn liberty:dev -pl ear -am stands out on its own, but this is more of a corner case rather than normal usage, and it should be read in context with the paragraph above it (which mentions -pl <_module-with-liberty-config_> -am).   Perhaps make the example in-line with text of the paragraph above it (similar to the formatting of the first mvn liberty:dev example.

**Comment by dmuelle** [comment]
draft is now updated to address these two items:

https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.9/development-mode.html#_run_multi_module_maven_projects_in_dev_mode

@ericglau  when you have a chance, let me know if any further edits are needed. If not, you can add the `technical reviewed` label to this issue to sign off and the update will publish with the 21.0.0.9 docs release. Thanks!

**Comment by ericglau** [comment]
@dmuelle It looks good, thanks.

**Comment by dmuelle** [comment]
Thanks- updates are on the vNext branch and will publish with 21.0.0.9. Closing this issue
