### ISSUE TITLE
Create a reference page for Jakarta EE9 feature updates

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#4626]
we should formally document the tables in [this blog post](https://openliberty.io/blog/2021/03/17/eclipse-transformer.html) under the "Updating Open Liberty features in server configurations" section to align with the OL jakarta EE 9 release, currently targeted for 20.0.0.11. Note that references to 9.0 in the table need to be replaced with 9.1

- [ ]  reproduce the tables and include the introductory information from the blog section, adapted for the docs.
- [ ] mention and provide links for the transformer, but also make clear that features have to be updated manually or by custom code
- [ ] new page should be linked to from the Forthcoming Jakarta EE 9 doc (#4406), the features overview, and possibly from the Jakarta EE 9 umbrella feature page. 
- [ ] investigate whether this new page should be linked from 21.0.0.11 release blog post
- [ ] investigate whether to provide links from each Jakarta EE 9.1 compatible feature page to the table, or automate through the doc generator

**Comment by dmuelle** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Open-Liberty-Docs-backlog-5c7031f61d4580192beb4070/issues/OpenLiberty/docs/4626?planning-poker) with ZenHub @ManasiGandhi @ramkumar-k-9286

**Comment by dmuelle** [comment]
Jakarta EE 9 moved to 21.0.0.12- continue working draft buut do. not publish until 21.0.0.12

**Comment by ManasiGandhi** [comment]
Possible SMEs @mbroz2, @jhanders34

**Comment by ramkumar-k-9286** [comment]
@dmuelle David.

The draft version of the doc:
https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/reference/feature/Jakarta-EE9-feature-updates.html

We need to add navigation, not accessible via TOC.

Also, I think we need to introduce line breaks in the second table. The feature name & short name displayed together, ends up looking like one big complicated name.

**Comment by dmuelle** [comment]
@ramkumar-k-9286 

- For the second table, I think we can put the short names in parentheses, to clarify that they are another name for the same feature, eg. `Enterprise JavaBeans (ejb-3.2)`
- I think we should also link each feature to its page using the macro, eg.` feature:ejb-3.2[display=Enterprise JavaBeans (ejb-3.2)]`. Note that the EE9 features won't be linkable until the autogen is updated. However, you can update the syntax now and the links will work once we update the autogen.
- Throughout the doc: `shortname`---> `short name`
- check the tables to make sure the features are listed in alphabetical order, as they appear in TOC
- `If Jakarta EE 8 feature name is incorrectly used with Jakarta EE 9 version...`--->`If a Jakarta EE 8 feature short name is incorrectly specified  with the Jakarta EE 9 version number in your `server.xml` file...`
- the second and third sentences in the intro should be in the same paragraph
- Remove the Reference Resources section. Instead, add a few sentences to the intro to say what the transformer is, and that you cant use it to update features (move the sentence at the end of the topic to this section). Provide a link to the transformer GitHub for more information.
- Add a See also section lists links to the Jakarta EE overview topic, the Java EE API landing page, and the JakartaEE API landing page.
- add topic to the reference/nav.adoc file, just after Default port numbers
- add a link to this topic from the See also sections of the Jakarta EE overview and Java EE and Jakarta EE API landing pages

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

The review comments specified above were incorporated. Proceeding to Merge the PR.

Link to the draft version of the document:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/reference/feature/Jakarta-EE9-feature-updates.html

Reference links added to the following pages:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/jakarta-ee.html

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/reference/jakarta-ee-api.html

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/reference/java-ee-api.html

I'm not sure about the way more info is added in the jakarta-ee-api.html, java-ee-api.html pages. 

While the[ jakarta-ee.html](https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/jakarta-ee.html) page has a See also section, in the[ jakarta-ee-api.html](https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/reference/jakarta-ee-api.html), [java-ee-api.html](https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/reference/java-ee-api.html) pages this info is put in the last paragraph. does not look OK. wanted to check with you before making any edits to these pages.

Regards,
Ramkumar

**Comment by dmuelle** [comment]
a few comments:

## Jakarta EE 9 feature updates
- change filename to remove caps- link in TOC is not working because nav file doesnt use caps
- suggested revision for the short description:
`For Jakarta EE 9 applications to run in Open Liberty, Jakarta EE 9 features must be specified in the server configuration. In some cases, you must change both the both the feature version and short name to update a feature for Jakarta EE 9.`

Then put the sentence that starts `If a Jakarta EE 8 feature short name is incorrectly specified...` in the next paragraph.
- combine everything after the short description (1st 2 sentences) into the same paragraph.
- suggested edit:
`The Eclipse Transformer transforms existing Java EE resources into their Jakarta EE equivalents. Currently, the transformer cannot update Open Liberty features because it is missing rules data to specify the updates. Features must be updated manually or by custom code. For more information on the Eclipse Transformer, see the [Eclipse Transformer GIT repository].`
--->
`[The Eclipse Transformer] is an open source project that transforms existing Java EE resources into their Jakarta EE equivalents. Currently, the transformer cannot update Open Liberty features because it is missing rules data to specify the updates. Features must be updated manually or by custom code.`

- in table 1, add feature macros to the feature short names so that they link to the appropriate feature versions. eg. 
`feature:appClientSupport-1.0`. You don't need the `[display= ]` syntax for these, because the short name and version are automatically displayed by the macro when you leave it off.

- in the See also section, the `Jakarta EE overview` link is broken, maybe because you need to add ROOT to the xref path, as anytime you link from one module to another, reference to ROOT or vice versa. eg `xref:ROOT:jakarta-ee.adoc`

## Jakarta EE overview
same issue with the link, need to add the module, eg `xref:reference:jakarta-ee9-feature-updates`.

## Jakarta EE API and Java EE API
same issue with link on both pages
on both pages, I suggest the following statement:
`For more information about transitioning your server from Java EE to Jakarta EE, see Jakarta EE 9 feature updates.`

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Comments specified above were incorporated. Proceeding to Merge the PR.

Link to the draft version of the document:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/reference/feature/jakarta-ee9-feature-updates.html

Reference links added to the following pages:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/jakarta-ee.html

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/reference/jakarta-ee-api.html

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/reference/java-ee-api.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
looks like the feature macros aren't working in table 1. I'm not sure why- check to make sure there is a blank space in the file before the word "feature". Otherwise we might need to add some attributes to the columns so the macros are recognized

Also the links between the docs are still broken. we can review at scrum

**Comment by ramkumar-k-9286** [comment]
@dmuelle

Link to the draft version of the document:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/reference/feature/jakarta-ee9-feature-updates.html

Reference links added to the following pages:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/jakarta-ee.html

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/reference/jakarta-ee-api.html

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/reference/java-ee-api.html

Links are still broken. All references to jakarta-ee9-feature-updates from jakarta-ee.adoc, jakarta-ee-api.adoc, java-ee-api.adoc
 Is this because jakarta-ee9-feature-updates.adoc is a new doc ? we added the nav. not sure whats wrong.

Regards,
Ramkumar

**Comment by dmuelle** [comment]
for the broken links

in jakarta-ee.adoc

xref:jakarta-ee9-feature-updates.adoc[Jakarta EE 9 feature updates]
--->
xref:reference:jakarta-ee9-feature-updates.adoc[Jakarta EE 9 feature updates]
 
the reason the other links aren't working is because the `jakarta-ee9-feature-updates.adoc` file is in the wrong folder. It's in `reference/pages/feature/` and it should be one level up in in `reference/pages/`

**Comment by ramkumar-k-9286** [comment]
@dmuelle

Link to the draft version of the document:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/reference/jakarta-ee9-feature-updates.html

Reference links added to the following pages:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/jakarta-ee.html

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/reference/jakarta-ee-api.html

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/reference/java-ee-api.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
LGTM, ready for tech review

**Comment by ramkumar-k-9286** [comment]
Hi Michal @mbroz2 

Could you please review the reference page for Jakarta EE9 feature updates:

Link: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/reference/jakarta-ee9-feature-updates.html

Please review the same. If the section has turned out as expected, please add the `Technical reviewed` label.

In case changes are needed please add your comments to the issue.

Regards,
Ramkumar

CC @dmuelle

**Comment by dmuelle** [comment]
@mbroz2 - hold off on reviewing this for the moment- I'm noticing some errors in the table that need to be cleared up first. We'll work on it today

**Comment by dmuelle** [comment]
@ramkumar-k-9286 

First table:
Java EE
--->
Jakarta EE

Second table:
Java Authentication Service Provider Interface for Containers
--->
Java Authentication SPI for Containers

javaserverfaces 
--->
JavaServer Faces

Java faces Container
--->
JMS Client for Message Server

JMS Client for Message Server 
--->
Message Server Security

**Comment by dmuelle** [comment]
Looking at these tables, there's not much point in sending for technical review until we have the new gendoc on draft and can check some of the guesses and blanks we had for thew feature names, also the new links wont work until the feature pages are updated for 21.0.0.12 on draft.

**Comment by ramkumar-k-9286** [comment]
@dmuelle

Link to the draft version of the document:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/reference/jakarta-ee9-feature-updates.html

Regards,
Ramkumar

**Comment by ramkumar-k-9286** [comment]
David @dmuelle

updated and merged the blanks in the Jakarta reference table. Link to the draft version of the page:

https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.12/reference/jakarta-ee9-feature-updates.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
@ramkumar-k-9286 a few more things to fix:

> ....you must change both the both the feature version and short name...

---> ...you must change both the feature version and short name...

> In those cases, the Jakarta EE 9 features simply have an updated feature version.

---> In those cases, the only change is the feature version number.

> The following table lists the features for which the feature names,...

---> The following table lists the features for which the feature name,...


Suggest adding one more sentence to each table intro to make it clear what you have to do tp use the new feature:

> The following table lists features for which only the feature version is updated:

--->
The following table lists features for which only the feature version is changed. To update one of these features from Jakarta EE 8 tom Jakarta EE 9, you need to change only the feature version number in your server configuration.


> The following table lists the features for which the feature names, short name and the version are updated:

--->

The following table lists the features for which the feature name, short name, and the version number are changed. To update one of these features from Jakarta EE 8 tom Jakarta EE 9, you need to change both the feature short name and version number in your server configuration.

**Comment by ramkumar-k-9286** [comment]
Hi Michal @mbroz2

Could you please review the reference page for Jakarta EE9 feature updates:

Link: https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.12/reference/jakarta-ee9-feature-updates.html

Please review the same. If the section has turned out as expected, please add the `Technical reviewed` label.

In case changes are needed please add your comments to the issue.

Regards,
Ramkumar

CC @dmuelle

**Comment by mbroz2** [comment]
I'm not a fan of the section regarding the Transformer:

> The Eclipse Transformer is an open source project that transforms existing Java EE resources into their Jakarta EE equivalents. Currently, the transformer cannot update Open Liberty features because it is missing rules data to specify the updates. Features must be updated manually or by custom code.

I'm concerned that it's going to be unclear to those reading whether the second and third sentence is intended to be regarding custom user features or Liberty features enabled in the server.xml/config files.

Could we instead change that section to be application focused? Something like:

> To aid with moving your applications from  Java EE (and its `javax` namespace) to Jakarta EE (and its `jakarta` namespace) we recommend trying the [Eclipse Transformer](https://github.com/eclipse/transformer), an open source project originally developed by members of the Open Liberty team and then contributed to the Eclipse Foundation.

@jhanders34 @kwsutter thoughts?

**Comment by ramkumar-k-9286** [comment]
Hi Michal @mbroz2

Based on your suggestion, rephrased the information on the **Eclipse Transformer**:

Link: https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.12/reference/jakarta-ee9-feature-updates.html

If the document has turned out as expected, please add the `Technical reviewed` label.

In case changes are needed please add your comments to the issue.

Regards,
Ramkumar

CC @dmuelle

**Comment by NottyCode** [comment]
@ramkumar-k-9286 @dmuelle 

Some feedback:

1. I think the first paragraph needs to be revised. The first sentence reads like a meaningless tautology and the second talks about changing something that has never been referenced before. I get that you are trying to talk through what you have to do to go from EE 8 to EE 9, but that idea isn't introduced to backup the sentence. The 1st paragraph says:
   > For Jakarta EE 9 applications to run in Open Liberty, Jakarta EE 9 features must be specified in the server configuration. In some cases, you must change both the feature version and short name to update a feature for Jakarta EE 9.
2. The second sentence says that if you specify something incorrectly the server doesn't start, but that really depends on what the "incorrect" thing is. If you use a feature name with a typo in it the server may start, but the application may not. Given the following discussion I think this is trying to discuss the situation where features from mixed EE versions are used in which case the first sentence should be much clearer.
   >If a Jakarta EE 8 feature short name is incorrectly specified with the Jakarta EE 9 version number in your server.xml file, the server does not start
3. The format for the first and second tables are totally different and I do not think they should be. I find the first table much easier to read, so I think the second table should follow a similar format, specifically I think the most important information (the feature names you put into server.xml) are hidden in the second table and they need to be really clear. 
4. Should the tables be numbered? Rather than "the following table", which I thought was an accessibility issue, I think it would be better if the tables were labeled table 1 and 2 and then it could say "table 2".
5. I think it would be good to show an example EE 8 and EE 9 server.xml snippets to demonstrate the difference.
6. I think the feature should say Jakarta EE 9.1
7. I think the document should be in the Development section of the docs rather reference, probably as a topic below the existing Jakarta EE one.

**Comment by dmuelle** [comment]
Thanks for reviewing @NottyCode - the revised draft is at

https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.12/jakarta-ee9-feature-updates.html

Made the following revisions:

1. revised the first 2 paragraphs to provide more context
2. clarified what happens when you mix an older feature name with a new feature version
3. Made the tables parallel. The previous "Java EE" full feature names are no longer included in the second table. Does that matter? 
4. Added numbers for the tables- we don't normally number tables on the OL site but in this case it might be helpful. "The following tables..." is not an accessibility violation, but "The table below..." would be
5. added server.xml code examples
6. changed all EE 9 references to EE9.1
7. moved the topic to the development section of the nav, as a child of the Jakarta EE Overview.
