### ISSUE TITLE
Document new %{remote}p access log option

### ISSUE THREAD

**Issue by kgibm** [OpenLiberty/docs#4646]
As part of [epic #18132](https://github.com/OpenLiberty/open-liberty/issues/18132), additional documentation would be needed on https://www.openliberty.io/docs/latest/access-logging.html

The proposal is to document the new option `%{remote}p` in the "Log format option" table. Mimicking [httpd documentation](https://httpd.apache.org/docs/trunk/mod/mod_log_config.html#formats) would be something like:

> `%{remote}p`: The client's actual (ephemeral) port for the request.

As part of implementing this feature, I also found that there is an undocumented `%p` option which could similarly be mimicked:

> `%p`: The canonical port of the server serving the request.

Target release is next release.

**Comment by ramkumar-k-9286** [comment]
Making few corrections to the document other than the requests :

Based on discussions with Kevin : (Shared below)
**Ramkumar:** Kevin, wrt
|%q
|Output the query string with any password escaped
can we replace escaped with omitted?
**Kevin:**
I guess it depends on what "omitted" means. They are in a sense omitted since they are replaced with stars, but in another sense they are still there, but are just masked
**Kevin:**
So I would recommend something like:
Output the query string with any password masked

|%q
|Output the query string with any password escaped 
--->
|Output the query string with any password masked.

CC @dmuelle

**Comment by ramkumar-k-9286** [comment]
More Corrections were made to the document, the proposed changes made on the suggestion of David, were to improve the overall look and feel of the document.

**Comment by ramkumar-k-9286** [comment]
Hi Kevin @kgibm 

Updates have been made to the document as suggested. Please find the link to the draft document below:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.11/access-logging.html

On review, if you are ok with the changes made to the document, could you add the `Technical Reviewed` label. 

Regards,
Ramkumar.

CC @dmuelle

**Comment by kgibm** [comment]
@ramkumar-k-9286 Looks great, thanks!

**Comment by dmuelle** [comment]
### Peer review

Two minor comments:
- in the field for `%B`, need a period between the definition clause and the subsequent sentence:
`The response size in bytes, excluding the headers. If no value is found, 0 is printed instead of -.` 
- The modifying clause in this sentence is vague:
`The current time when the message to the access log is queued to be logged in normal NCSA format`

does  `in normal NCSA format` refer to "the current time" or how it is "logged"?

If the former, the definition should be:

`The current time in normal NCSA format when the message to the access log is queued to be logged`
 
If the latter, leave as is.

check with @kgibm to clarify

**Comment by chirp1** [comment]
@dmuelle @ramkumar-k-9286 

Hi David, 
- The opening paragraph (short description) needs to follow the short description guidelines, which  are linked to in the peer review cheat sheet. Please point Ram to that info and also work with him as necessary to update the short description. Basically, the short description should be two sentences. We don't want a colon in the short description, indicating a bullet listed that follows, because if only the short description is displayed in some context, the user wouldn't see the bulleted list 
- On your comment of "does in normal NCSA format refer to "the current time" or how it is "logged"?", which one it is needs to be clear. The sentence still needs to be rewritten even if it is for "logged", not left as is.

**Comment by kgibm** [comment]
First, I think there is a doc bug. The page says:

> %(t)W | The current time when the message to the access log is queued to be logged in normal NCSA format.

Running a test with both `%(t)W` and `%{t}W` shows that only the latter works with curly braces rather than parantheses (as I would expect):

```
$ (podman run --rm openliberty/open-liberty:full-java8-ibmjava-ubi sh -c "curl https://raw.githubusercontent.com/kgibm/samplewar/main/samplewar.war -so /config/dropins/sample.war && echo '<?xml version=\"1.0\" encoding=\"UTF-8\"?><server><httpEndpoint id=\"defaultHttpEndpoint\" host=\"*\" httpPort=\"9080\" httpsPort=\"9443\"><accessLogging filepath=\"\${server.output.dir}/logs/access.log\" logFormat=\"%h %u %t &quot;%r&quot; %s %b %D %{t}W %(t)W\" /></httpEndpoint></server>' > /config/configDropins/overrides/server.xml && (/opt/ol/wlp/bin/server run defaultServer &) && sleep 2 && tail -99999f /logs/messages.log | grep -q CWWKF0011I && curl -sv --trace-time http://localhost:9080/sample/servlet && cat /opt/ol/wlp/output/defaultServer/logs/access.log && /opt/ol/wlp/bin/server stop defaultServer") 2>/dev/null | grep GET
0:0:0:0:0:0:0:1 - [18/Oct/2021:14:35:12 +0000] "GET /sample/servlet HTTP/1.1" 200 43 132062 [18/Oct/2021:14:35:12 +0000] %(t)W
```

Therefore, I think it should be changed to `%{t}W`. Copying @mrsaldana to double check if I missed something.

Regarding the question:

> > The current time when the message to the access log is queued to be logged in normal NCSA format
> 
> does in normal NCSA format refer to "the current time" or how it is "logged"?

In normal NCSA format means the actual format of what's printed and refers to the same format used with `%t`. In the example above, you'll see that the third element printed (`%t`) is `[18/Oct/2021:14:35:12 +0000]` and the second-to-last element printed (`%{t}W`) is `[18/Oct/2021:14:35:12 +0000]`. Both are in the same "format" meaning how the date is formatted to a string. It's not quite accurate to say the "current time" without any context. Specifically, it's the time that the request finished and was queued to the async logger to print to the log. However, this seems to me to be an implementation detail that the user shouldn't need to care about. I haven't verified this in the code, but I would expect the time this is queued to be logged is the time of the end of the request. @mrsaldana Is that right?

If so, then I suggest something like the following (based on the `%t` doc):

> NCSA format of the end time of the request

**Comment by ramkumar-k-9286** [comment]
@dmuelle

Peer Review comments incorporated:

Please find the draft links for the documentation:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.11/access-logging.html

**Comment by dmuelle** [comment]
looks good, just one more change for parallelism with other values:

NCSA format of the start time of the request
--->
The start time of the request, in NCSA format

**Comment by ramkumar-k-9286** [comment]
@dmuelle

Peer Review comments incorporated:

Please find the draft links for the documentation:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.11/access-logging.html

**Comment by dmuelle** [comment]
LGTM, thanks

**Comment by ramkumar-k-9286** [comment]
@dmuelle

**For Review: ( Staging Version )**

Please find the draft links for the documentation:

https://docs-staging-openlibertyio.mybluemix.net/docs/21.0.0.11/access-logging.html

**Comment by ramkumar-k-9286** [comment]
Changes are on vNext and will publish with the 21.0.0.11 docs release.
