### ISSUE TITLE
Move OpenID Connect Client topics to openliberty.io

### ISSUE THREAD

**Issue by teddyjtorres** [OpenLiberty/docs#4730]
**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**

Tentative release is 21.0.0.12.

Creating here per @chirp1 Karen's request in https://github.ibm.com/websphere/liberty-docs/issues/2410.

For Epic https://github.com/OpenLiberty/open-liberty/issues/14646, we need to move the https://www.ibm.com/docs/en/was-liberty/nd?topic=connect-configuring-openid-client-in-liberty topic to openliberty.io and add the following steps:

> You can configure a Liberty OpenID Connect Relying Party to process access and ID tokens that are in a JWE format. The corresponding OpenID Connect Provider should support creating JWE access or ID tokens.
> - Set the OpenID Connect Provider with the OpenID Connect Relying Party's public key that is used to encrypt the Content Encryption Key according to the OpenID Connect Provider's documentation.
> - Set the `keyManagementKeyAlias` attribute to the private key alias of the key management key that is used to decrypt the Content Encryption Key of JWE token. The key must exist in the keyStore configured for the SSL configuration referred by the the sslRef attribute. For example,
> 
>     > `<openidConnectClient keyManagementKeyAlias="privateKeyAlias" />`
> 
> Optional: Configure access token cache.
> You can configure a Liberty OpenID Connect Relying Party to cache access token validation results for inbound propagation.
> - Set the `accessTokenCacheEnabled` attribute to "true".
> - Set the `accessTokenCacheTimeout` attribute to a duration specifying how long an authenticated subject that is created by using a propagated access token is cached.
> - Set the `tokenReuse` attribute to "true" if the OpenID Connect Relying Party must cache results for a JWT access token that includes a "jti" claim.
> 
>    Although enabling this support may result in a performance improvement, it is recommended that the value for the `accessTokenCacheTimeout` attribute is short to reduce the possibility of a stale result as compared to what a validation call to the OpenID Connect Provider would have produced.
> 
> You can also configure Liberty OIDC Social Login to process ID tokens that are in a JWE format. The corresponding OpenID Connect Provider should support creating JWE ID tokens.
> - Set the OpenID Connect Provider with the OIDC Social Login's public key that is used to encrypt the Content Encryption Key according to the OpenID Connect Provider's documentation.
> - Set the `keyManagementKeyAlias` attribute to the private key alias of the key management key that is used to decrypt the Content Encryption Key of JWE token. The key must exist in the keyStore configured for the SSL configuration referred by the the sslRef attribute. For example,
> 
>     > `<oidcLogin keyManagementKeyAlias="privateKeyAlias" />`
> 
> The signatureAlgorithm attributes of both elements now support the RS384, RS512, HS384, HS512, ES256, ES384, and ES512 signature algorithms, in addition to RS256, HS256, and none.
>    > `<openidConnectClient signatureAlgorithm="RS384"/>`
>    > `<oidcLogin signatureAlgorithm="RS384"/>` 

Also, please port https://www.ibm.com/docs/en/was-liberty/nd?topic=connect-configuring-json-web-token-authentication-openid to openliberty.io and remove this sentence,

> Encrypted JWT is not supported

and change this sentence from,

> To be accepted as an authentication token, the JWT token must contain iss, sub, and exp claims and be signed with the RS256 or HS256 algorithm.

to

> To be accepted as an authentication token, the JWT token must contain iss, sub, and exp claims and be signed with the ES256, ES384, ES512, HS256, HS384, HS512, RS256, RS384, or RS512 algorithm. An unsigned JWT token is also accepted when the `signatureAlgorithm` attribute is set to `none`. Encrypted JWT (JWE) is also supported.

**Comment by dmuelle** [comment]
per Open Liberty docs content standards, this topic will be reformatted as a set of configuration examples for the openidConnectClient-1.0 feature. Although the IBM docs topic is written as a single task, many of the steps are optional and the task as a whole does not represent a logical flow to configure a single functional objective.

By breaking the steps out into individual configuration examples on the same page, users will have a clearer understanding of the purpose of the various steps and examples, and can refer directly to the outcomes they are looking for.

**Comment by dmuelle** [comment]
Information about SSL and user registry configuration will be added to the beginning of the page and linked to the relevant OL documentation. This information is covered in steps 1 and 3-5. Several of the steps also repeat information that is already documented in the generated doc for [the openidConnectClient element](https://www.openliberty.io/docs/latest/reference/config/openidConnectClient.html). Unless there is info missing from the generated doc, we should avoid duplicating it and link to it instead.
 The other steps will be  represented in the following examples on the OIDC client feature page.

- minimal configuration (step 2)
- Configure a 3rd party OIDC provider (step 6)
- Set an authentication filter (steps 7 & 8)
- Configure a supported ID Token signature algorithm (step 9 + new info)
- ~~Configure an “implicit” grant type (step 10 )~~ covered in generated doc
- ~~Disable LTPA cookies for OIDC (step 11)~~ covered in generated doc 
- Configure an OpenID Connect Client to optionally accept a valid OAuth 2.0 bearer access token as an authentication token without redirecting the request to an OpenID Connect provider (step 12)
- Set a different context root (step 13) -covered in generated doc, but description is missing. Need to open a bug on the main OL repo to update the metatype to add a description
- Configure Liberty to pass additional request parameters to OpenID Connect. (step 14)
- Configure a Liberty OpenID Connect Relying Party or Liberty OIDC Social Login to process access and ID tokens that are in a JWE format (new info)
- Configure access token cache. (new info)
- Configuring JSON Web Token authentication for OpenID Connect (create examples not already covered from "Configuring an OpenID Connect Client in Liberty").

**Comment by dmuelle** [comment]
Epic moved to 22.0.0.1

**Comment by dmuelle** [comment]
Hi @teddyjtorres - I'm working on a new draft for this topic, but have few a few questions about the source docs

## [Configuring an OpenID Connect Client in Liberty](https://www.ibm.com/docs/en/was-liberty/nd?topic=connect-configuring-openid-client-in-liberty)

**Step 1**, in the Avoid trouble note, it says

> The URL that you enter must be visible to both the RP and client (browser or application).

But I thought the Relying Party and the client were the same thing? what is the difference here?


**Step 6**
> To configure the Liberty OpenID Connect client to use a third-party OpenID Connect Provider such as (Microsoft Azure or Google), you must configure the following attributes.

are all the listed attributes required in all cases? Looking at both the [Azure](https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration) and [Google](https://accounts.google.com/.well-known/openid-configuration) discovery docs, neither appear to support a `groups` claim. How would you specify `groupIdentifier` in those cases?

## [Configuring JSON Web Token authentication for OpenID Connect](https://www.ibm.com/docs/en/was-liberty/nd?topic=connect-configuring-json-web-token-authentication-openid)

**Step 8**
>  you can define how to map JWT claims to the subject on the following openidConnectClient element attributes:
would the values for these attributes be claims from the JWT? For example if you wanted to use a calim other than `sub` as the principal name, you'd specify that claim as the value of `userIdentifier`? The doc doesn't really explain this.


**Step 9**
> The Liberty server expects each request to provide a valid JWT token and does not create or use single-sign-on cookies for authentication. To create single-sign-on cookies, set authnSessionDisabled="false" on the openidConnectClient element.

but on the other page it says

> The Liberty OpenID Connect relying party automatically creates a single-sign-on (SSO) token after the ID Token is processed (which you can disable with  `disableLtpaCookie="true"`)

What's the difference between authnSessionDisabled and disableLtpaCookie ? Im probably missing something but it seems like they each apply to the same default behaving two different ways.


**Step 11**
> If the audiences attribute is not configured, but the JWT token contains an aud claim that is a valid URL, the resources service URL must have the aud value as a prefix.

What is the "resources service URL" in this context?

## [In your comment above](https://github.com/OpenLiberty/docs/issues/4730#issue-1012574435):
> Set the keyManagementKeyAlias attribute to the private key alias of the key management key that is used to decrypt the Content Encryption Key of JWE token. _The key must exist in the keyStore configured for the SSL configuration_ referred by the the sslRef attribute.

Most of the other doc talks about having certificates in a truststore rather than a keystore- is this different?


Let me know what you think- thanks!

**Comment by teddyjtorres** [comment]
Hi @dmuelle,

For Configuring an OpenID Connect Client in Liberty, Step 1, the RP is not the same as the client. The client is either another application, such as a CLI, servlet, or user agent (browser), that is used to access the application hosted by the RP server. For Step 6, yes, all the attributes are needed. As for the groupIdentifier, it depends on what it received in the ID token from the third-party OpenID Connect provider.

For Configuring JSON Web Token authentication for OpenID Connect, Step 8, you are correct that one can switch the claim used for creating the subject and the other mappable claims. More information is found in the configuration element document https://www.ibm.com/docs/en/was-liberty/base?topic=configuration-openidconnectclient and article might link to it.

The difference between authnSessionDisabled and disableLtpaCookie is that authnSessionDisabled only applies for when inboundPropagation is set to "required" and a JWT access token is used for authenticating a user. The disableLtpaCookie attribute applies in the regular OpenID Connect flows.

The "resources service URL", in this context, is the resource being accessed, like a servlet, for example. Assuming a "specific" servlet, then a servlet served at `https://<server>:<port>/something/specific` can be accessed by the JWT with an audience claim of `"aud":"https://<server>:<port>/something"`. The alternative example shows that the request must be rejected because the resource being accessed is not part of the audience for this JWT.

As for the keystore comment, yes, it is different for JWE since the private key used to process the JWE for decrypting it must be in a keystore. This is different than using a public key for verifying the signature for a JWS, which are stored in a truststore.

Regards,
Teddy

**Comment by dmuelle** [comment]
Hi @teddyjtorres - the draft for the migrated and updated info is now available for technical review:

https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/openidConnectClient-1.0.html

note that the draft site goes offline briefly during rebuilds, if you get a 404 from this URL, retry after a few minutes.

Let me know if any edits are needed. When you're satisfied with the topic, you can add the `Technical reviewed` label to this issue and the updates will publish with 22.0.0.1. Thanks!

**Comment by teddyjtorres** [comment]
Hi David,

Thank you for the changes! There is a small update. There is an extra tick mark that needs removing,

> headerName="jwt"`

**Comment by ramkumar-k-9286** [comment]
## Peer Review

You can configure an Open Liberty server to function as an OpenID Connect Client, or Relying Party (RP), so that you can use an OpenID Connect Provider (OP) as a single-sign-on identity provider.
--> **( The comma after Relying Party (RP) looks unnecessary)**
You can configure an Open Liberty server to function as an OpenID Connect Client, or Relying Party (RP) so that you can use an OpenID Connect Provider (OP) as a single-sign-on identity provider.
___
To enable the `OpenID Connect Client 1.0` feature, add the following element declaration into your `server.xml` file, inside the `featureManager` element:
--> You do  not use **:** for the rest of the document. 
To enable the `OpenID Connect Client 1.0` feature, add the following element declaration into your `server.xml` file, inside the `featureManager` element.
___
To enable your Open Liberty server to act as an OpenID Connect (OIDC) Client, you must configure the following prerequisites.
-->
To enable your Open Liberty server to act as an OpenID Connect Client (OIDC), you must configure the following prerequisites.
___
Alternatively, you can specify a **nondefault** truststore for OIDC by referencing the truststore configuration from the trustStoreRef attribute for the openidConnectClient element.
-->
Alternatively, you can specify a **non-default** truststore for OIDC by referencing the truststore configuration from the trustStoreRef attribute for the openidConnectClient element.
___
If you do not define claim-to-subject mapping, the following default rules apply:
-->
If you do not define **a** claim-to-subject mapping, the following default rules apply.
___
The issuer (iss) claim is the default realm and used as the subject realm.
-->
The issuer (iss) claim is the default realm and **is** used as the subject realm.
___
A valid JWT must satisfy one of the following conditions:
-->
A valid JWT must satisfy one of the following conditions.
___
If the audiences attribute is configured, the `aud` claim value in the JWT must be one of the configured audiences.
--->
If the `audiences` attribute is configured, the `aud `claim value in the JWT must be one of the configured audiences.
___
When you set this attribute to `true`, the Open Liberty OIDC client accepts only authentication requests that previously authenticated with the configured OP.
--->
When you set this attribute to `true`, the Open Liberty OIDC client accepts only authentication requests that **were** previously authenticated with the configured OP.
___
This function enables the Open Liberty server to serve both the browser client and nonbrowser client like a RESTful client.
--->
This function enables the Open Liberty server to serve both the browser client and **non-browser** client like a RESTful client.
___
Across the document, I noticed that there are 2 ways you have mentioned the following:
**OIDC client**
**OIDC Client**
I believe we should stick to one way across the doc.
___
If you are developing a feature that depends on this feature, include the following item in the `Subsystem-Content` header in your feature manifest file.
--->
If you are developing a feature that depends on this feature, include the following item in the `Subsystem-Content` header of your feature manifest file.
___

Regards,
Ramkumar

**Comment by dmuelle** [comment]
Thanks for reviewing @ramkumar-k-9286 - all suggestions implemented, except for the following:

- ( The comma after Relying Party (RP) looks unnecessary)
It's needed to set off `, or Relying Party (RP),` as a modifier that restates "client"
- `To enable the OpenID Connect Client 1.0 feature, add the following element declaration into your server.xml file, inside the featureManager element:` This statement is generated from the code and is not in the example file
-  `OpenID Connect (OIDC) Client` vs `OpenID Connect Client (OIDC)` OIDC stands for Open ID Connect, not  OpenID Connect CLient
- non-default , non-browser- acrolinx advises not to use a hyphen with "non" prefix
- If you do not define **a** claim-to-subject mapping, the following default rules apply.
claim-to-subject mapping is in a general sense here, the "a" is not incorrect but is awkward
- I made ODIC client lowercase, except when used in the feature name
- `If you are developing a feature that depends on this feature, include the following item in the Subsystem-Content header in your feature manifest file.` This statement is generated from the code and is not in the example file

**Comment by ramkumar-k-9286** [comment]
LGTM - Adding the `Peer Reviewed` label.

**Comment by dmuelle** [comment]
topic is on Vnext and will publish with 22.0.0.1
