### ISSUE TITLE
ID for Introspector for Zip Cache

### ISSUE THREAD

**Issue by tbitonti** [OpenLiberty/docs#477]
Design Issue: "Introspector for Zip Reaper": https://github.com/OpenLiberty/open-liberty/issues/7868
Issue/Story: "Implement Introspector for Zip Reaper": https://github.com/OpenLiberty/open-liberty/issues/8441
Pull Request: https://github.com/OpenLiberty/open-liberty/pull/8148

Draft content:
[zipCacheIntrospector.draft.01-Aug-2019.txt](https://github.com/OpenLiberty/docs/files/3457598/zipCacheIntrospector.draft.01-Aug-2019.txt)

**Comment by lauracowen** [comment]
Taking the content in the .txt file, I think there needs to be a new topic created which introduces/describes the zip cache introspector and explains its output (basically most of the .txt file). This would be a combined concept/reference topic (technically) but that would be in keeping with other troubleshooting documentation so that's fine.

Then the existing [server dump topic](https://openliberty.io/docs/ref/command/#server-dump.html) should be updated to mention it in an appropriate place and link to the new topic.

Does that seem sensible?

**Comment by tbitonti** [comment]
Hi,

That sounds about right.

Thx!

Thomas F. Bitonti
WebSphere Application Server Group / WCCM
(919) 486-0867

**Comment by dmuelle** [comment]
Removed from docs queue because audience is internal support. See https://github.com/OpenLiberty/open-liberty/issues/8445 for more info
