### ISSUE TITLE
Doc for Jakarta RESTful Web Services (JAX-RS) 3.0 (part of EE 9/9.1)

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/docs#4825]
ID work is needed for Jakarta RESTful Web Services (JAX-RS) 3.0 as part of epic issue https://github.com/OpenLiberty/open-liberty/issues/11803.  Like other EE 9/9.1 technologies, the API is effectively the same as it's EE 8 counterpart with the major exception being the package names (`javax.*` -> `jakarta.*`).  

However, JAX-RS is somewhat unique in that we have changed the underlying implementation from Apache CXF to RESTEasy. As a result there are various behavior changes that may not be expected by users.  These changes have been documented in our migration issue https://github.com/OpenLiberty/open-liberty/issues/12742. 

In addition to the usual new feature docs (server config page, javadocs, etc.) we will need a behavior change page similar to https://www.ibm.com/docs/en/was-liberty/base?topic=liberty-jax-rs-21-behavior-changes and https://www.ibm.com/docs/en/was-liberty/base?topic=liberty-jax-rs-20-behavior-changes.  

@jim-krueger is working on a Skills Transfer Education document and demo for L2 that may also be useful for crafting the doc pages for this feature.  If you have any questions or concerns, please let us know. Thanks!

**Comment by dmuelle** [comment]
Thanks Andy- is this update targeted for 21.0.0.12?

**Comment by andymc12** [comment]
Hi @dmuelle - yes, currently targeted for 21.0.0.12.  Thanks!

**Comment by dmuelle** [comment]
Hi @andymc12 @jim-krueger - looking at the migration issue, I'm having trouble telling what the specific changes we want to document are vs discussion about those changes. Can you provide an outline of the changes we want to communicate in a "Differences between JAX.RS 2.1 and JAX-RS 3.0" reference topic? 

Also, will we need to update any of the info in [JAX-RS integration with CDI](https://www.openliberty.io/docs/latest/jaxrs-integration-cdi.html) or [Send and receive multipart/form-data parts in JAX-RS](https://www.openliberty.io/docs/latest/send-receive-multipart-jaxrs.html) ?

**Comment by jim-krueger** [comment]
@dmuelle I will contact you via slack and send my STE charts that detail the migrations issues better.  It may not be the final version of these, but it should help you to understand.

**Comment by andymc12** [comment]
> Can you provide an outline of the changes we want to communicate in a "Differences between JAX.RS 2.1 and JAX-RS 3.0" reference topic?

@jim-krueger is working on a skills transfer document that specifically mentions those differences.  He should be contacting you to give you an early copy of the doc.

> Also, will we need to update any of the info in JAX-RS integration with CDI or Send and receive multipart/form-data parts in JAX-RS ?

The "JAX-RS integration with CDI" document will probably need updating. Most of the info is still accurate, but there are a few changes: (1) CDI is on by default in 3.0, where it was off by default in 2.X. (2) It is not required to specify `@RequestScoped` for resources or `@ApplicationScoped` for providers or application subclasses - these are now the default (Jim's doc covers this). 

The multipart document will not need to be modified - all the info in it is still relevant.  Thanks!

**Comment by dmuelle** [comment]
Hi @andymc12 @jim-krueger - to make sure we have everything we need for @chirp1 to provide ID approval, I'm going to outline the info from this discussion + the KT slides that Jim shared with me.  would attach those here but GH doesn't allow pptx attachments.

Let me know if I'm missing anything or if anything here is more under the covers than what most users will need to know.  Our docs are generally more focused on server side config but JAX-RS is one of the areas where we do doc more application code so just want to be sure what we have is in line with what users would expect to find in OL doc vs stuff that might be documented elsewhere that we would just point out to (spec/ javadoc). 

There appears to be more info/detail in the slides than what we had for the 2.1 behavior changes in IBM docs, though about equal with what was there for the 2.0 changes. Ideally, what we'll end up with is a concise reference doc that users can easily scan to pick out the bits that are important for their apps rather than having to dig through line by line to see whats there and whether they care about it.

I'm considering putting these differences in table format but not sure it will be a good fit- still mulling it over

## Differences between JAXRS 2.1 and  RESTfulWebServices 3.0
- brief introduction re API changes related to ee9, links for more info
- possibly a high-level explanation (underlying implementation change), if there are clear implications to be drawn from the results
### HttpHeaders.getRequestHeader(String headerName) when the specified headerName does not exist
- JAXRS-2.x behavior: Returns null
- RESTfulWS-3.0 behavior: Returns Collections.emptyList()
- link to javadoc ? https://jakarta.ee/specifications/restful-ws/3.0/apidocs/jakarta/ws/rs/core/httpheaders#getRequestHeader(java.lang.String)
### Liberty ClientBuilder properties deprecated 
- JAXRS-2.x properties:
  - com.ibm.ws.jaxrs.client.receive.timeout
  - com.ibm.ws.jaxrs.client.connection.timeout
- RESTfulWS-3.0 ClientBuilder additions/replacements
  - ClientBuilder.connectTimeout(long timeout, TimeUnit unit) _note that these methods also exist in JAX-RS 2.1, but Liberty still supported the timeout properties - in 3.0, Liberty only supports the methods_
  - ClientBuilder.readTimeout(long timeout, TimeUnit unit)
 ### RESTful WS parameter non-CDI injection 
 - JAXRS-2.x behavior: JAX-RS parameters are allowed to be injected into a resource class constructor
- RESTfulWS-3.0 behavior:
  - JAX-RS parameters are NOT allowed to be injected into a resource class constructor
  - Resources are now CDI beans
  - Only CDI injection may only occur in resource class constructors
- Include code examples?
### Subresource locator methods path names
- explanation with code example
- **the before/ to be is less clear here from the slide- is this documented anywhere else?**

### Application subclasses using CDI injection must be annotated with  @ApplicationPath
- JAXRS-2.x behavior: Application subclasses are treated as managed beans and do not require the @ApplicationPath annotation for CDI injection.
- RESTfulWS-3.0 behavior: 
  - Application subclasses are not treated as managed beans and therefore require the @ApplicationPath annotation if they want to include CDI injection.
  - Resources are now CDI beans
  - Only CDI injection may only occur in resource class constructors
- **can this be combined with "RESTful WS parameter non-CDI injection " somehow? They share some of the same  RWS behaviors.**  _yes, I think that would be a good idea_
### CDI and bean-defining annotations
- JAXRS-2.x behavior:  Users explicitly enabled CDI (via CDI feature / annotations) to allow for CDI  in applications
- RESTfulWS-3.0 behavior:
  -RESTful WS  will always use CDI
  - @ApplicationPath, @Path, and @Provider are now CDI bean-defining annotations
 - RESTful WS resources annotated with @Path will be request-scoped by default
 - RESTful WS resources annotated with @Provider and @ApplicationPath respectfully will be application-scoped by default
### EJBs in an Application subclass’s getClasses() method
- JAXRS-2.x behavior:  Local interfaces of the EJB bean listed in the getClasses() method were ignored.
- RESTfulWS-3.0 behavior:
  - Local interfaces of the EJB bean listed in the getClasses() method causes an exception that prevents the application from starting.
  - More information: https://github.com/OpenLiberty/open-liberty/issues/18210
### Wildcards in @ApplicationPath 
- JAXRS-2.x behavior:  Wildcard characters are accepted in @ApplicationPath (eg (@ApplicationPath(value="/rest1/*")
- RESTfulWS-3.0 behavior:
  - Wildcard characters are not accepted in @ApplicationPath,  results in the request being rejected:
  eg  RESTEASY003210: Could not find resource for full path: http://localhost:8010/helloworld/rest1/helloworld)
  - _Technically, the wildcard character is supported, but becomes part of the path - which is usually undesirable - for example: http://localhost:8010/helloworld/rest1/*/helloworld - so the net is that if 2.X users have wildcards in their paths, they will need to remove them if they want the same paths to work in 3.X._
## Other updates
- Update  "JAX-RS integration with CDI" document: (1) CDI is on by default in 3.0, where it was off by default in 2.X. (2) It is not required to specify @RequestScoped for resources or @ApplicationScoped for providers or application subclasses these are now the default

**Comment by andymc12** [comment]
@dmuelle I edited the previous comments with answers and additional info. Overall, this looks good to me.  Thanks!

**Comment by chirp1** [comment]
David has the info that he needs. Andy is good with the info that David proposed. Approving the epic.

**Comment by dmuelle** [comment]
Hi @andymc12 @jim-krueger , I have the initial draft of this doc ready for review on our draft site:

https://docs-draft-openlibertyio.mybluemix.net/docs/latest/reference/jaxrs-dif.html

Let me know if any edits or additions are needed. When you're ready to sign off, you can add the `technical reviewed label to this issue and the doc will publish with the 21.0.0.12 release. Thanks

**Comment by andymc12** [comment]
Hi @dmuelle  - thanks for putting this together.  Overall, I think it looks good.  Here are a few comments:

* I would use `jaxrs-2.1` instead of `jaxrs-2.x` - while many of the 2.X (2.0 and 2.1) behaviors are similar, they're not always the same.  The behavior differences that we noted in the STE document are primarily the differences between 2.1 and 3.0.  Also, `jaxrs-2.x` is not an actual feature name, so somebody doing a text search for it might not find the results they are looking for.
* This sentence seems to imply that the jaxrs-2.x/2.1 feature is not available now that 21.0.0.12 is shipped.
> Before 21.0.0.12, JAX-RS 2.x functions were available through the Java RESTful Services feature (jaxrs-2.x).

Maybe we could change it something like "The JAX-RS 2.0 and 2.1 implementations are available with the `jaxrs-2.0` and `jaxrs-2.1` features, respectively."?

* I think a code example might help users in the "Null properties in the jakarta.ws.rs.client API" section - something like:
```
ClientBuilder cb = ClientBuilder.newBuilder().property("someProp", null);
System.out.println("containsProp? " + cb.getConfiguration().getProperties().containsKey("someProp"));
// for jaxrs-2.1, this outputs: containsProp? true
// for restfulWS-3.0, this outputs: containsProp? false
```

* In the "Response.readEntity() method return when it is called on an empty entity" section, we should not use code formatting for "emptyString".  Instead, we should phrase it like: "The method returns an empty string object." or "The method returns an empty string (`""`) object."

* In the "Subresource locator methods path names" section, the feature name is misspelled - `RESTfulWebServices-3.0` should be `restfulWS-3.0`.   There are a few places where the casing is off: `RESTfulWS-3.0` - I believe that feature names can be case-insensitive, so technically both should work, but I think we should be consistent with the casing and it is documented in the feature code as `restfulWS-3.0` (everything but W and S are lowercase).

The links in the first few paragraphs (other than the link to CXF and RESTEasy) don't work - but that may be expected since the other docs may not be done yet.

Other than that, I think it looks great!  Thanks again!

**Comment by dmuelle** [comment]
Thanks @andymc12 - I made those fixes:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/reference/jaxrs-dif.html

- [x] jaxrs-2.x --> jaxrs-2.1
- [x] Before 21.0.0.12, JAX-RS 2.x functions were available through the Java RESTful Services feature (jaxrs-2.x)---> The JAX-RS 2.0 and 2.1 implementations are available with the through the Java RESTful Services feature (jaxrs-2.0 and jaxrs-2.1).
- [x] added code example to Null properties item
- [x] emptyString object---> empty string object
- [x] throughout, `restfulWS-3.0` as the correct short name
- [x] The links to restfulWS-3.0 won't be active until we upload the new autogen later this week. All links will be checked during peer review

Based on recent discussions, there is a chance that this and all the similar pages about changes between feature versions will be moved to be appended directly on the feature pages, rather than as distinct reference pages. If we go that route, would it make sense for this info to show up on the restfulWS-3.0 page, the jaxrs-2.1 page or both? Not sure exactly how we'll handle it but let me know what you think. Thanks!

**Comment by andymc12** [comment]
Hi @dmuelle - thanks for the changes. I noticed a capitilization inconsistency in sections "Response.readEntity() method return when it is called on an empty entity" and "HttpHeaders.getRequestHeader(String headerName) method return when the specified headerName value does not exist".  Both `restfulWS-3.0` behaviors show that they return an empty string, but one uses capital "String" while the other uses lowercase "string". I think either way is fine, but we should use the same for both.  Other than that, I think it looks good. 

> Based on recent discussions, there is a chance that this and all the similar pages about changes between feature versions will be moved to be appended directly on the feature pages, rather than as distinct reference pages. If we go that route, would it make sense for this info to show up on the restfulWS-3.0 page, the jaxrs-2.1 page or both? Not sure exactly how we'll handle it but let me know what you think. Thanks!

My preference would be to put it on the `restfulWS-3.0` page. I'd rather not duplicate the content, but maybe we could add some sort of "supersedes"/"superseded by" link in these features so that users can quickly discover that `restfulWS-3.0` supersedes `jaxrs-2.1` from either page. 

Thanks again!

**Comment by dmuelle** [comment]
Thanks Andy- I've fixed the capitalization issue. If everything else looks good, can youa dd the `technical reviewed` label to the issue? 

This content might move to the `restfulWS-3.0` before it publishes with 21.0.0.12. I'll know more about that soon.

**Comment by ramkumar-k-9286** [comment]
# Peer Review

With the release of the RESTful Web Services 3.0 feature (restfulWS-3.0), the underlying Jakarta RESTful Web Services implementation for Open Liberty changed from Apache CXF to RESTEasy. This change results in certain API behavior changes that might require you to update your application code.
------->
With the release of the RESTful Web Services 3.0 feature (restfulWS-3.0), the underlying Jakarta RESTful Web Services implementation for Open Liberty **has** changed from Apache CXF to RESTEasy.

behavior or behaviour -- confused wrt the spelling -- google goes with **behaviour**. --- should we be using behavioural in this case?  - if so, across the doc we might need to fix the spelling. 
---> 
This change results in certain API **behavioural** changes that might require you to update your application code.

Jakarta RESTful Web Services ( formerly JAX-RS) is a Jakarta EE platform API.
-->
Jakarta RESTful Web Services (formerly JAX-RS) is a Jakarta EE platform API.(removed spece in the brackets)

Jakarta RESTful Web Services ( formerly JAX-RS) is a Jakarta EE platform API. In Open Liberty 21.0.0.12 and later, you can use Jakarta RESTful Web Services 3.0 functions by enabling the RESTful Web Services 3.0 feature (restfulWS-3.0).
---->
you have said  RESTful Web Services 3.0 feature **(restfulWS-3.0)** in the first paragraph, do we need to keep putting this  (restfulWS-3.0) again in the 2nd paragraph?

The JAX-RS 2.0 and 2.1 implementations are available with the through the Java RESTful Services feature (jaxrs-2.0 and jaxrs-2.1).
-->
The JAX-RS 2.0 and 2.1 implementations **are available with the Java RESTful Services feature** (jaxrs-2.0 and jaxrs-2.1).

If you are updating your server configuration from using the jaxrs-2.1 feature to the restfulWS-3.0 feature, certain changes in API behavior might require you to update your application code.
--->
previous comment on behavior Spelling
certain changes in **the** API behavior might require you to update your application code.

The change in feature name and version reflects the change in API package name prefixes from javax.* to jakarta.*, which is common to all Jakarta EE 9.1 features. 
-->
The change in feature name and version reflects the change in API package name prefixes from **java.*** to jakarta.*, which is common to all Jakarta EE 9.1 features. ---> **Not sure if its java or Javax**

link not working --> Response.readEntity() method return when it is called on an empty entity

Should restfulWS-3.0 behaviour under Server-side asynchronous support be mentioned using bullets for the 2 cases that are mentioned?

Null properties in the jakarta.ws.rs.client API
jaxrs-2.1 behavior
A Client property with a null value is maintained as part of the Client internal configuration state.
--->
**Client** caps in both cases??

For a application that runs on a server that specifies the restfulWS-3.0 feature, you must rewrite the code similar to the following example.
--->
For **an** application that runs on a server that specifies the restfulWS-3.0 feature, you must rewrite the code similar to the following example.

Subresource locator methods can share the same path as a regular subresouce method.
-->
Subresource locator methods can share the same path as a regular **subresource** method. (for both cases -restfulWS-3.0 behavior and jaxrs-2.1 behavior)


Only CDI injection may only occur in resource class constructors.
--->
CDI injection can only occur in resource class constructors.

**Comment by ramkumar-k-9286** [comment]
@dmuelle 

i am not sure about some of the comments. but i have still added them as review comments. fyi

Regards,
Ramkumar

**Comment by dmuelle** [comment]
@ramkumar-k-9286 - thanks for reviewing. Here's my response/ changes

https://draft-openlibertyio.mybluemix.net/docs/latest/reference/jaxrs-dif.html

- [ ] With the release of the RESTful Web Services 3.0 feature (restfulWS-3.0), the underlying Jakarta RESTful Web Services implementation for Open Liberty **has** changed from Apache CXF to RESTEasy.

**don't want to use past perfect tense, acrolinx will ding it**

- [ ] behavior or behaviour
**behaviour is the Brittish spelling- IBM style uses American spelling in most if not all  cases. You can always check any term you're unsure about by running the Termbot slack app against it**

- [x] Jakarta RESTful Web Services ( formerly JAX-RS) is a Jakarta EE platform API.
**fixed by removing brackets**

- [x] you have said  RESTful Web Services 3.0 feature **(restfulWS-3.0)** in the first paragraph, do we need to keep putting this  (restfulWS-3.0) again in the 2nd paragraph? **removed**

- [x] The JAX-RS 2.0 and 2.1 implementations are available with the through the Java RESTful Services feature (jaxrs-2.0 and jaxrs-2.1). **fixed**


- [ ] certain changes in **the** API behavior might require you to update your application code. **leaving as is, to indicate "API behavior" as a concept... hard to explain why but I think it's closer to the intended meaning :)**

- [ ] Not sure if its java or Javax **the pacjkage names start with `javax`

- [x] link not working --> Response.readEntity() method return when it is called on an empty entity **fixed**

- [x] Should restfulWS-3.0 behaviour under Server-side asynchronous support be mentioned using bullets for the 2 cases that are mentioned? **updated**

- [x] **Client** caps in both cases?? **fixed**

- [x] For **an** application that runs on a server that specifies the restfulWS-3.0 feature, you must rewrite the code similar to the following example. **fixed**

- [x] Subresource locator methods can share the same path as a regular **subresource** method. (for both cases -restfulWS-3.0 behavior and jaxrs-2.1 behavior) **fixed


- [x] Only CDI injection may only occur in resource class constructors. **fixed**

**Comment by ramkumar-k-9286** [comment]
# Peer Review

David @dmuelle 

I have a few more minor suggestions, I missed the first time.

- [ ] Jakarta RESTful Web Services, formerly known as JAX-RS, is a Jakarta EE platform API. In Open Liberty 21.0.0.12 and later, you can use Jakarta RESTful Web Services 3.0 functions by enabling the RESTful Web Services 3.0 feature. ---> **The RESTful Web Services 3.0 link not working.**

- [ ] CDI and bean-defining annotations
jaxrs-2.1 behavior
To use CDI in applications, users must explicitly enable CDI with the Contexts and Dependency Injection feature.  ----> **Remove the link from the word `feature` limit link to Contexts and Dependency Injection.**

- [ ] Wildcard characters in the @ApplicationPath annotation
restfulWS-3.0 behavior
Wildcard characters are not accepted for the @ApplicationPath annotation all such requests are rejected. ---> **Wildcard characters are not accepted for the @ApplicationPath annotation, all such requests are rejected.**

**Comment by dmuelle** [comment]
thanks Ram- made the following changes:

- [x] The RESTful Web Services 3.0 link not working. **autogen is updated and it works now**
- [x] Remove the link from the word feature limit link to Contexts and Dependency Injection. **fixed**
- [x] Wildcard characters are not accepted for the @ApplicationPath annotation all such requests are rejected.  **fixed**

https://draft-openlibertyio.mybluemix.net/docs/latest/reference/jaxrs-dif.html

**Comment by ramkumar-k-9286** [comment]
David @dmuelle 

Checked the draft link. LGTM.

Adding Peer-Reviewed label.

Regards,
Ramkumar

**Comment by dmuelle** [comment]
content is now on vNext and will publish with 21.0.0.12. However, it will not appear in the navigation until leadership determines the proper placement for topics of this type- a call is scheduled for 12/2 to decide how to treat this and all other "behavior changes" topics, which have been removed from the nav in the meantime. The functional URL for this info will be 
https://openliberty.io/docs/21.0.0.11/reference/jaxrs-dif.html

Discussion and work for placement of these topics will be tracked in #4841
