### ISSUE TITLE
A new OCSP (Certificate Revocation Check) topic in Liberty doc

### ISSUE THREAD

**Issue by una-tapa** [OpenLiberty/docs#4852]
This is a serviceability request from our support team. 
It will be helpful if Liberty has a new topic that points to customer the list of "certificate revocation" Java properties. 

A very short topic that has the title and contents like below. 
```
"How to check the certificate revocation" 

Liberty relies on Java to check the certificate revocation.  
Liberty does not have the functionality to check the certificate revocation. 

https://www.ibm.com/docs/en/sdk-java-technology/8?topic=certpath-appendix-c-runtime-properties 
```

Reference: [RTC287011: Add certificate revocation links to Liberty KC](https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=287011)

**Comment by dmuelle** [comment]
Hi @una-tapa , rather than create a new topic with only a few lines, I've added the info to our Secure communication with TLS topic under the heading "[TLS certificate revocation checks with OCSP](https://draft-openlibertyio.mybluemix.net/docs/latest/secure-communication-tls.html#_tls_certificate_revocation_checks_with_ocsp)" so that users searching for Liberty + OCSP will find it. Let me know if any further edits are needed. This update will publish with 22.0.0.3. Thanks!
