### ISSUE TITLE
(sec-29) document OIDC tools in Admin Center

### ISSUE THREAD

**Issue by lavenal** [OpenLiberty/docs#490]
When Admin Center is moved from CL to OL, the OL article talking about various tools in the Admin Center should include the OIDC UI tools. Following the current article in KC on "Administrating Liberty using Admin Center" (I understand that OL may change the doc so different from what is in KC. It's just to give an idea what the new contents are and where they should belong if they are under KC.),

https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_ui.html

The OIDC UI tools should be documented after #7 

7. Optional: View the progress and status of Java batch jobs in the Java Batch tool.

There will be three more tools to mention. They are:

8. Optional: Use the OpenID Connect Client Management tool to allow an administrator to manage clients on an Open Liberty's OpenID Connect provider.
9. Optional: Use the OpenID Connect Personal Token Management Tool to allow a user to manage application passwords and application tokens on an Open Liberty's OpenID Connect provider.
10. Optional: Use the OpendID Connect Users Token Managment Tool to allow an administrator to revoke application passwords and application tokens of other users on an Open Liberty's OpenID Connect provider.

The tools listed above (OpenID Connect Client Management tool, OpenID Connect Personal Token Management tool, OpenID Connect Users Token Management tool) should be a link to a page explaining how to use each tool. The pages are 

### OpenID Connect Client Management Tool

This tool is used to add, modify, and delete an OAuth client and to regenerate a client secret on an OpenID Connect provider.

Enable the use of this tool through the Admin Center by configuring the server.xml to include the following:
-  Both adminCenter-1.0 and openidConnectServer-1.0 are listed as the features.
- The AdminCenter login user must have the clientManager role to access this tool. 
    
   ```
   <administrator-role>
         admin
   </administrator-role>
   <oauth-roles>
      <clientManager>
         <user name="admin" />
      </clientManager>
   </oauth-roles>
   ```
   See xxxxx (should provide a link here to point to the security doc talking about clientManager role and the registration API tool). 
- The invalidateOnUnauthorizedSessionRequestException attribute is set for httpSession.

   `<httpSession invalidateOnUnauthorizedSessionRequestException="true" />`

If there are existing clients on the provider belonging to the login user, the tool displays a list of existing clients. The table rows are unsorted. Click the **Name** column header to sort the table rows in ascending or descending order. Alternatively, use the filter box to look for clients with matching client name. 

![image](https://user-images.githubusercontent.com/25039033/62736323-b451e180-b9f2-11e9-84fd-4ed0024c0a67.png)

Use the **Add New** button to bring up the "Register New OAuth Client" dialog to add a new    client.  All fields on the dialog are optional.  Some fields in the dialog are populated with the default values. Change the values as needed. Click the **Register** button to create a new client and to copy the client ID and secret in the "OAuth Registration Saved" dialog. Click the **Done** button to dismiss the dialog.

Click **Edit** on the table row to bring up the "Edit OAuth Client" dialog to change an existing client. Update the client field values as needed. Click the **Update** button to save the changes. To generate a new client secret, blank out the value of the **Client secret** field and click the **Update** button.  The "OAuth Registration Updated" dialog appears with the regenerated client secret. You can copy the new client secret by clicking on the copy icon. Click the **Done** button to dismiss the dialog.

Click **Delete** on the table row to bring up the delete confirmation dialog. Click the **Delete** button in the dialog to confirm the delete.

### OpenID Connect Personal Token Management Tool

This tool allows a user to create, delete, and regenerate app-passwords and app-tokens on an OpenID Connect provider.

Enable the use of this tool through the Admin Center by configuring the server.xml to include the following:
-  Both adminCenter-1.0 and openidConnectServer-1.0 are listed as the features.
- The invalidateOnUnauthorizedSessionRequestException attribute is set for httpSession.

   `<httpSession invalidateOnUnauthorizedSessionRequestException="true" />`
- Configure an OAuth provider to set the internalClientId and internalClientSecret attributes to the ID and secret of an OAuth client which is configured to allow the use of app-passwords and/or app-tokens. See Configuring and Using an OpenId Connect Provider to use Application Passwords, Configuring and Using an OpenId Connect Provider to use Application Tokens, and web pages for users and administrators  (these three links should point to the doc pointed by Bruce).

The tool displays a list of existing app-passwords and app-tokens on an OpenID Connect provider belonging to the logged in user. The table rows are unsorted. Click the **Name** column header to sort the table rows in ascending or descending order.

![image](https://user-images.githubusercontent.com/25039033/62736422-ef541500-b9f2-11e9-9043-7958802ecf53.png)

If the OAuth client provided in this OAuth provider in the server.xml is defined to allow the use of app-passwords or app-tokens, the **Add New** button is enabled. Use the **Add New** button to bring up the "Register New Authentication" dialog. Provide a name and select an authentication type.  Click the **Generate** button. The dialog will be updated with the newly generated app-password or app-token. Click the copy icon to copy it. Click the **Done** button to dismiss the dialog.

If the OAuth client provided in this OAuth provider in server.xml is defined to allow the use of app-passwords and/or app-tokens,  **Regenerate** is enabled on the table row for the allowed authentication type. Click **Regenerate** on the table row to bring up the "Regenerate App-Password" or "Regenerate App-Token" dialog. Click the **Generate** button to regenerate the authentication. The dialog will be updated with the newly generated app-password or app-token. Click the copy icon to copy it. Click the **Done** button to dismiss the dialog.

Click **Delete** on the table row to bring up the delete confirmation dialog. Click the **Delete** button in the dialog to confirm the delete.

### OpenID Connect Users Token Management Tool

This tool is used to revoke app-passwords and app-tokens of other users on an OpenID Connect provider.

Enable the use of this tool through the Admin Center by configuring the server.xml to include the following:
-  Both adminCenter-1.0 and openidConnectServer-1.0 are listed as the features.
- The AdminCenter login user must have the tokenManager role to access this tool. 
    
   ```
   <administrator-role>
         admin
   </administrator-role>
   <oauth-roles>
      <tokenManager>
         <user name="admin" />
      </tokenManager>
   </oauth-roles>
   ```
   See xxxxx (should provide a link here to point to the security doc talking about tokenManager role if there is one). 
- The invalidateOnUnauthorizedSessionRequestException attribute is set for httpSession.

   `<httpSession invalidateOnUnauthorizedSessionRequestException="true" />`
- Configure an OAuth provider to set the internalClientId and internalClientSecret to the ID and secret of an OAuth client which is setup to allow the use of app-passwords and/or app-tokens. See Configuring and Using an OpenId Connect Provider to use Application Passwords, Configuring and Using an OpenId Connect Provider to use Application Tokens, and web pages for users and administrators  (these three links should point to the doc pointed by Bruce).

Once you are in the tool, enter a user name in the search field and hit "Enter" to get a list of app-passwords and app-tokens for the specified user. The table rows are unsorted. Click the **Name** column header to sort the table rows in ascending or descending order. 

![image](https://user-images.githubusercontent.com/25039033/62736499-17dc0f00-b9f3-11e9-8389-82ba08f019d2.png)

If the user has existing app-passwords and app-tokens, the authentication could be revoked in one of the three ways:
- Click **Delete**  at the end of each table row to delete a specific app-password or app-token.
- Click the "checkbox" at the beginning of the table header next to the **Name** column to select all app-passwords and app-tokens for the specified user for deletion. The table summary is updated to show the number of items selected. Click the **Delete** button in the table summary header.
- Individually click the "checkbox" at the beginning of each table row for the authentications that should be revoked. Click as many "checkboxes" that apply. The table summary is updated to show the number of items selected. Click the **Delete** button in the table summary header to delete the selected app-password or app-token authentications.

A delete confirmation dialog will appear. Click the **Delete** button to confirm the action.

**Comment by Charlotte-Holt** [comment]
Admin center hasn't moved to OL yet

**Comment by lavenal** [comment]
AdminCenter is in OL starting 21.0.0.4.

**Comment by dmuelle** [comment]
Hi @lavenal , a draft of this topic is now available for review on our draft site:

https://docs-draft-openlibertyio.mybluemix.net/docs/latest/oidc-tools.html

Are you able to provide technical review of this draft? If any edits are required, just let me know. Otherwise, you can sign off by adding the `Developer reviewed` label to this issue. Thanks!

**Comment by lavenal** [comment]
Hi @dmuelle, the draft looks good except for two minor changes for the OIDC Client Management Tool. 

1. For the bullet on unsorted table rows, please change the column name from **Name** column header to **Client name** column header, i.e.
The table rows are unsorted. Click the **Client name** column header to sort the table ...

2. I would like to rearrage these two bulleted list
  - To edit an existing client, click Edit on the table row to display the Edit OAuth Client window. Update the client field values as needed and click the Update button to save the changes.
  - To generate a new client secret, delete the value of the Client secret field and click the Update button. The OAuth Registration Updated window appears with the new client secret. You can copy the new client secret by clicking the copy icon.

to 

- To edit an existing client, click Edit on the table row to display the Edit OAuth Client window. Update the client field values as needed and click the Update button to save the changes.
  - To generate a new client secret in the Edit OAuth Client window, delete the value of the Client secret field and click the Update button. The OAuth Registration Updated window appears with the new client secret. You can copy the new client secret by clicking the copy icon.

Thanks!

**Comment by dmuelle** [comment]
Hi @lavenal - thanks for reviewing. The draft is now updated with the  requested changes:

https://docs-draft-openlibertyio.mybluemix.net/docs/latest/oidc-tools.html

Let me know if anything further is needed. If not, you can sign off by adding the `Developer reviewed` label to this issue. Thanks!

**Comment by lavenal** [comment]
Thanks @dmuelle for the update!

**Comment by Rwalls1** [comment]
# Content review
  
## Intro    

I think you should change “The Open Liberty Admin Center provides the following three tools to help manage OIDC authentication on your server:” to “The Admin Center provides the following tools to help manage OIDC authentication on your Open Liberty server”, to maintain consistency with how you refer to the Admin Center and remove an unnecessary word to be more concise

## Prerequisites

- To maintain consistency with referencing, I think after the first use of “Open ID Connect (OIDC) Admin Center tools”, you should use “OIDC” to refer to related phrases, so for example, change “Open ID Connect Admin Center tools” to “OIDC Admin Center tools” and change “configure OpenID Connect to “configure OIDC”. This convention should be consisted throughout.
- I don’t think the bulleted sublist that describes OAuth role requirements is needed as it doesn’t add any clear value. I think since the bullets contain complete sentences that it would be more logical to remove the bullets. Also, I don’t think any of the bullets in this section are needed and it would be more logical to structure the content in paragraph format. 

## OIDC Client Management Tool    

-  There’s some inconsistency in how the tools are referred to. For example, in the introduction and in the “Manage Open Liberty with Admin Center” doc, the OIDC Client Management Tool is referred to as “OIDC Client Management” but throughout other sections, it is referred to as “the OIDC Client Management Tool”. I think you should maintain a consistent naming convention change the title of this section to reflect that decision. I think you should make a similar change for the other tool sections.
- Typo: Change “matching client name” to “a matching client name”
- I think the names of each of window, such as the “Register New OAuth Client window”, should also be bolded as they also reflect points of navigation.  I think you should make a similar change for each of the tool sections.

## OIDC Users Token Management Tool

- Acrolinx flag: Change “hit Enter” to “press Enter”
- On the first instance, add the bold style to “Delete” in the phrase “Click the Delete button” to indicate the navigation point.

**Comment by dmuelle** [comment]
Thanks for reviewing @Rwalls1 - I made the following edits per your review

- [x] change “The Open Liberty Admin Center provides the following three tools to help manage OIDC authentication on your server:” to “The Admin Center provides the following tools to help manage OIDC authentication on your Open Liberty server”
- [x] after the first use of “Open ID Connect (OIDC) Admin Center tools”, you should use “OIDC” to refer to related phrases
- [x] since the bullets contain complete sentences that it would be more logical to remove the bullets (prereq section)
- [x] maintain a consistent naming convention for tools (omit "Tool" from tool names)
- [x] Typo: Change “matching client name” to “a matching client name”
- [ ] I think the names of each of window, such as the “Register New OAuth Client window”, should also be bolded as they also reflect points of navigation **Left this as is- [IBM style guide for highlighting](https://ibmdocs-test.mybluemix.net/docs/en/ibm-style?topic=format-highlighting) says window titles with headline capitalization should not have any highlighting**
- [x] Acrolinx flag: Change “hit Enter” to “press Enter”
- [x] On the first instance, add the bold style to “Delete” in the phrase “Click the Delete button” to indicate the navigation point.

https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.8/oidc-tools.html

**Comment by Rwalls1** [comment]
@dmuelle The updates look good.

**Comment by dmuelle** [comment]
content is on vNext, will publish with 21.0.0.8
