### ISSUE TITLE
Collate all MP Config properties to understand how/if to document them as reference

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#505]
Some MP Config properties are from the spec and some are from Liberty implementation of the spec (NB MP are apparently looking at making the naming of the spec properties more consistent). There are several properties and they're important for configuration but our docs currently only list the `server.xml` config properties, not properties that can be put in, say, `bootstrap.properties`.

Collate in this issue all the MP Config properties we have so far...

* MP Reactive Messaging
  * From spec
    * Channel attributes are defined using the following pattern  
      `mp.messaging.<incoming|outgoing>.<channelname>.<attributename>=value`
    * Channel attributes
      * `connector=<connector-id>` - the ID of the connector to use for this channel
        * E.g. the ID for the liberty kafka connector is `io.openliberty.kafka`
      * All other attributes configured are passed on to the connector
    * Attributes can also be set for a connector, which will be passed to the connector whenever is is used on a channel.
      * `mp.messaging.connector.<connector-id>.<attributename>=value`
      * e.g. `mp.messaging.connector.io.openliberty.kafka.bootstrap.servers=mybrokerhostname`
  * From liberty
    * Kafka Connector (incoming)
      * `topics` - comma separated list of topics to receive messages from
      * `unacked.limit` - the allowed number of messages which have been delivered to the channel but have not yet been acknowledged. If the number of messages outstanding reaches this limit, further messages will not be delivered to the channel until some messages have been acknowledged.
      * all other attributes are passed directly to the underlying `KafkaConsumer`
    * Kafka Connector (outgoing)
      * `topic` - the topic to send messages to
      * all other attributes are passed directly to the underlying `KafkaProducer`
* MP Fault Tolerance
  * From spec
    * Override a value set in a fault tolerance annotation  
      applied to a method - `<classname>/<methodname>/<annotationname>/<parametername>=newvalue`  
      applied to a class - `<classname>/<annotationname>/<parametername>=newvalue`  
      e.g. `com.acme.ClassA/methodB/Retry/maxRetries=5`
    * Disable a fault tolerance annotation  
      applied to a method - `<classname>/<methodname>/<annotationname>/enabled=false`  
      applied to a class - `<classname>/<annotationname>/enabled=false`  
      all annotations of a particular type - `<annotationname>/enabled=false`  
      `com.acme.ClassA/methodB/Retry/enabled=false`
    * `MP_Fault_Tolerance_NonFallback_Enabled=false` - disable all Fault Tolerance annotations except `@Fallback`
    * `MP_Fault_Tolerance_Metrics_Enabled=false` - disable metrics produced by Fault Tolerance

**Comment by lauracowen** [comment]
- MP JWT
  - From spec (https://github.com/eclipse/microprofile-jwt-auth/blob/master/spec/src/main/asciidoc/configuration.asciidoc)
    - Supply public key as a string - `mp.jwt.verify.publickey`
    - Provide external or internal location of the public key - `mp.jwt.verify.publickey.location`
    - Specify the expected value of the `iss` claim - `mp.jwt.verify.issuer`

**Comment by lauracowen** [comment]
https://download.eclipse.org/microprofile/microprofile-open-api-1.1/microprofile-openapi-spec.html#_core_configurations

**Comment by Charlotte-Holt** [comment]
Different specs to check for properties https://download.eclipse.org/microprofile/microprofile-3.3/microprofile-spec-3.3.html#microprofile3.3

**Comment by Charlotte-Holt** [comment]
Contact Tom Evans

**Comment by Rwalls1** [comment]
New MP Config properties being added for MP-JWT-1.2, also mentioned in issue #3511:

> ### mp.jwt.token.header
> The `mp.jwt.token.header` property allows you to control the HTTP request header which is expected to contain a JWT token. You can specify either Authorization (default) or Cookie values.

> ### mp.jwt.token.cookie
> The `mp.jwt.token.cookie` property allows you to specify the name of the cookie which is expected to contain a JWT token. The default value is `Bearer` if not specified.

> ### mp.jwt.verify.audiences
> The `mp.jwt.verify.audiences` property allows you to create list of allowable "aud" values. At least one of these must be found in the claim. Previously, this had to be configured in the server.xml file. Now, you can configure the audiences in the MicroProfile config property as follows:
>```
>mp.jwt.verify.audiences=conferenceService
>```

> ### mp.jwt.decrypt.key.location
> The `mp.jwt.decrypt.key.location` property allows you specify location of the Key Management Key. This is the Private key to decrypt the Content Encryption Key, which is then used to decrypt the JWE ciphertext. This private key must correspond  to the public key that is used to encrypt the Content Encryption Key.

> ### mp.jwt.verify.publickey.algorithm
> The `mp.jwt.verify.publickey.algorithm` property allows you to control the Public Key Signature Algorithm that is supported by the MP JWT endpoint. The default value is `RSA256` if not specified. Previously, this had to be configured in the server.xml file. Now, you can configure the public key algorithm used for verification of the JWT in the MicroProfile config property as follows:
>```
>mp.jwt.verify.publickey.algorithm=ES256
>```

**Comment by dmuelle** [comment]
Slack discussion re how to document MP config prooperties:

https://ibm-cloud.slack.com/archives/C31GEJTQD/p1618429945125400

**Comment by Emily-Jiang** [comment]
@dmuelle can you create a table to populate the tables with the properties mentioned on this converation and then we can fill in the missing ones. The column should contain the following: (please come up with better names)
`Name`, `Description`, `Spec`, `When runtime read it`

**Comment by dmuelle** [comment]
Properties by spec- will continue to build the list in this comment and then put into tables for each spec in the doc draft.

## MP Health

- **mp.health.disable-default-procedures**
When set to true, disables all default vendor procedures so the application processes and displays only the user-defined health check procedures
- **mp.health.default.readiness.empty.response**
set  this property to UP to change the overall default readiness status to UP while deployed applications are starting up. 3.1 and later
-  **mp.health.default.startup.empty.response**
set  this property to UP to change the overall default readiness status to UP while deployed applications are starting up. 3.1 and later

## Metrics
-  **mp.metrics.tags**
supply tags for a metric- mp config 2.0 and later
- **mp.metrics.appName**
pass the value of the _app tag from the application server to the application 

## OpenAPI
- **mp.openapi.extensions.liberty.merged.include**
This property specifies which modules or applications are included in the generated OpenAPI documentation.
- **mp.openapi.extensions.liberty.merged.exclude**
This property overrides the mp.openapi.extensions.liberty.merged.include property to specify which applications or web modules are excluded from the generated OpenAPI documentation.
- **mp.openapi.extensions.liberty.merged.info**
This property sets the info section of the final Open API document. If it is set, the info section in the final OpenAPI document is replaced with the value of the property. This replacement is made after any merging is completed.
- **mp.openapi.model.reader**
Configuration property to specify the fully qualified name of the [OASModelReader](https://github.com/eclipse/microprofile-open-api/blob/master/spec/src/main/asciidoc/microprofile-openapi-spec.asciidoc#oasmodelreader) implementation.

- **mp.openapi.filter**
Configuration property to specify the fully qualified name of the [OASFilter](https://github.com/eclipse/microprofile-open-api/blob/master/spec/src/main/asciidoc/microprofile-openapi-spec.asciidoc#oasfilter) implementation.

- **mp.openapi.scan.disable**
Configuration property to disable annotation scanning. Default value is false.

- **mp.openapi.scan.packages**
Configuration property to specify the list of packages to scan. Classes within the package and any subpackages will be scanned for annotations. For example, mp.openapi.scan.packages=com.xyz.packageA,com.xyz.packageB

- **mp.openapi.scan.classes**
Configuration property to specify the list of classes to scan. For example, mp.openapi.scan.classes=com.xyz.MyClassA,com.xyz.MyClassB

- **mp.openapi.scan.exclude.packages**
Configuration property to specify the list of packages to exclude from scans. Classes within the package and any subpackages will be excluded from scans. For example, mp.openapi.scan.exclude.packages=com.xyz.packageC,com.xyz.packageD

- **mp.openapi.scan.exclude.classes**
Configuration property to specify the list of classes to exclude from scans. For example, mp.openapi.scan.exclude.classes=com.xyz.MyClassC,com.xyz.MyClassD

The following rules are used to determine whether a class is scanned for annotations:

A class is not scanned if it’s listed in mp.openapi.scan.exclude.classes

A class is scanned if it’s listed in mp.openapi.scan.classes

A class is not scanned if its package, or any of its parent packages are listed in mp.openapi.scan.exclude.packages, unless a more complete package or parent package is listed in mp.openapi.scan.packages

A class is scanned if its package or any of its parent packages are listed in mp.openapi.scan.packages

A class is scanned if mp.openapi.scan.classes and mp.openapi.scan.packages are both empty or not set

- **mp.openapi.scan.beanvalidation**
Configuration property to enable or disable the scanning and processing of Jakarta Bean Validation annotations. Defaults to true.

- **mp.openapi.servers**
Configuration property to specify the list of global servers that provide connectivity information. For example, mp.openapi.servers=https://xyz.com/v1,https://abc.com/v1

- **mp.openapi.servers.path**
Prefix of the configuration property to specify an alternative list of servers to service all operations in a path. For example, mp.openapi.servers.path./airlines/bookings/{id}=https://xyz.io/v1

- **mp.openapi.servers.operation**.
Prefix of the configuration property to specify an alternative list of servers to service an operation. Operations that want to specify an alternative list of servers must define an operationId, a unique string used to identify the operation. For example, mp.openapi.servers.operation.getBooking=https://abc.io/v1

- **mp.openapi.schema**.
Prefix of the configuration property to specify a schema for a specific class, in JSON format. The remainder of the property key must be the fully-qualified class name. The value must be a valid OpenAPI schema object, specified in the JSON format. The use of this property is functionally equivalent to the use of the @Schema annotation on a Java class, but may be used in cases where the application developer does not have access to the source code of a class.

## REST client
- **org.eclipse.microprofile.rest.client.propagateHeaders**
specify which headers to propagate from the inbound JAX-RS request to the outbound MP Rest Client request, users must use a comma-separated list of headers

- **<client_interface_name>/mp-rest/url**: The base URL to use for this service,
the equivalent of the baseUrl method. This property (or */mp-rest/uri) is considered required,
however implementations may have other ways to define these URLs/URIs.
- **<client_interface_name>/mp-rest/uri**: The base URI to use for this service,
the equivalent of the baseUri method. This property (or */mp-rest/url) is considered required,
however implementations may have other ways to define these URLs/URIs. This property will
override any baseUri value specified in the @RegisterRestClient annotation.
- **<client_interface_name>/mp-rest/scope**: The fully qualified classname to a
CDI scope to use for injection, defaults to jakarta.enterprise.context.Dependent as mentioned
above.
- **<client_interface_name>/mp-rest/providers**: A comma separated list of
fully-qualified provider classnames to include in the client, the equivalent of the register
method or the @RegisterProvider annotation.
- **<client_interface_name>/mprest/providers/com.mycompany.MyProvider/priority** will override the priority of the provider for
this interface.
- **<client_interface_name>/mp-rest/connectTimeout:** Timeout specified in
milliseconds to wait to connect to the remote endpoint.
- **<client_interface_name>/mp-rest/readTimeout**: Timeout specified in
milliseconds to wait for a response from the remote endpoint.
- **<client_interface_name>/mp-rest/followRedirects**: A boolean value (Any
value other than "true" will be interpreted as "false") used to determine whether the client
should follow HTTP redirect responses.
- **<client_interface_name>/mp-rest/proxyAddress**: A string value in the form
of <proxyHost>:<proxyPort> that specifies the HTTP proxy server hostname (or IP address) and
port for requests of this client to use.
- **<client_interface_name>/mp-rest/queryParamStyle**: An enumerated type
23
string value with possible values of "MULTI_PAIRS" (default), "COMMA_SEPARATED", or
"ARRAY_PAIRS" that specifies the format in which multiple values for the same query parameter
is used.

For CDI injected clients, the trust store can be specified with MicroProfile Config properties:
- **myClient/mp-rest/trustStore** to set the trust store location. Can point to either a classpath
resource (e.g. classpath:/client-truststore.jks) or a file (e.g. file:/home/user/clienttruststore.jks)
- **myClient/mp-rest/trustStorePassword** to set the password for the keystore
- **myClient/mp-rest/trustStoreType** to set the type of the trust store. Defaults to "JKS
-  **myClient/mp-rest/hostnameVerifier**: specifies a custom HostnameVerifier to determine if an SSL connection that fails on a URL’s hostname and a server’s identification hostname mismatch should be allowed.

For the CDI usage, the keystore can be specified with MicroProfile Config properties similar to the
trust store properties:
• myClient/mp-rest/keyStore to set the key store location. Can point to either a classpath resource
(e.g. classpath:/client-keystore.jks) or a file (e.g. file:/home/user/client-keystore.jks)
• myClient/mp-rest/keyStorePassword to set the password for the keystore
• myClient/mp-rest/keyStoreType to set the type of the key store. Defaults to "JKS"

## GrapQL
- **mp.graphql.defaultErrorMessage**
set the default error message
- **mp.graphql.exceptionsWhiteList**
specify a comma-separated list of unchecked exception messages to be included 
- **mp.graphql.exceptionsBlackList**
'hide' this message for checked exception

## COntext propagation

Specifying Defaults via MicroProfile Config
MicroProfile Config properties can be used to specify defaults for configuration attributes that are not otherwise configured on ManagedExecutor and ThreadContext instances. Here is an example that includes all of the available attributes that can be defaulted:

```
mp.context.ManagedExecutor.propagated=Security,Application
mp.context.ManagedExecutor.cleared=Remaining
mp.context.ManagedExecutor.maxAsync=10
mp.context.ManagedExecutor.maxQueued=-1

mp.context.ThreadContext.propagated=None
mp.context.ThreadContext.cleared=Security,Transaction
mp.context.ThreadContext.unchanged=Remaining
```


## JWT

> ### mp.jwt.token.header
> The `mp.jwt.token.header` property allows you to control the HTTP request header which is expected to contain a JWT token. You can specify either Authorization (default) or Cookie values.

> ### mp.jwt.token.cookie
> The `mp.jwt.token.cookie` property allows you to specify the name of the cookie which is expected to contain a JWT token. The default value is `Bearer` if not specified.

> ### mp.jwt.verify.audiences
> The `mp.jwt.verify.audiences` property allows you to create list of allowable "aud" values. At least one of these must be found in the claim. Previously, this had to be configured in the server.xml file. Now, you can configure the audiences in the MicroProfile config property as follows:
>```
>mp.jwt.verify.audiences=conferenceService
>```

> ### mp.jwt.decrypt.key.location
> The `mp.jwt.decrypt.key.location` property allows you specify location of the Key Management Key. This is the Private key to decrypt the Content Encryption Key, which is then used to decrypt the JWE ciphertext. This private key must correspond  to the public key that is used to encrypt the Content Encryption Key.

> ### mp.jwt.verify.publickey.algorithm
> The `mp.jwt.verify.publickey.algorithm` property allows you to control the Public Key Signature Algorithm that is supported by the MP JWT endpoint. The default value is `RSA256` if not specified. Previously, this had to be configured in the server.xml file. Now, you can configure the public key algorithm used for verification of the JWT in the MicroProfile config property as follows:
>```
>mp.jwt.verify.publickey.algorithm=ES256
>```
- **mp.jwt.verify.publickey**
The embedded key material of the public key for the MP-JWT signer in PKCS8 PEM or JWK(S)
format. If not found the mp.jwt.verify.publickey.location needs to be checked.
- **mp.jwt.verify.publickey.location**
The relative path or full URL of the public key. All relative paths will be resolved within the
archive using ClassLoader.getResource. If the value is a URL it will be resolved using new
URL(“…”).openStream()
- **mp.jwt.verify.issuer**
The expected iss claim value to validate against an MP-JWT.

## MP Reactive Messaging

  * From spec
    * Channel attributes are defined using the following pattern  
      `mp.messaging.<incoming|outgoing>.<channelname>.<attributename>=value`
    * Channel attributes
      * `connector=<connector-id>` - the ID of the connector to use for this channel
        * E.g. the ID for the liberty kafka connector is `io.openliberty.kafka`
      * All other attributes configured are passed on to the connector
    * Attributes can also be set for a connector, which will be passed to the connector whenever is is used on a channel.
      * `mp.messaging.connector.<connector-id>.<attributename>=value`
      * e.g. `mp.messaging.connector.io.openliberty.kafka.bootstrap.servers=mybrokerhostname`
  * From liberty
    * Kafka Connector (incoming)
      * `topics` - comma separated list of topics to receive messages from
      * `unacked.limit` - the allowed number of messages which have been delivered to the channel but have not yet been acknowledged. If the number of messages outstanding reaches this limit, further messages will not be delivered to the channel until some messages have been acknowledged.
      * all other attributes are passed directly to the underlying `KafkaConsumer`
    * Kafka Connector (outgoing)
      * `topic` - the topic to send messages to
      * all other attributes are passed directly to the underlying `KafkaProducer`

## MP Fault Tolerance

  * From spec
    * Override a value set in a fault tolerance annotation  
      applied to a method - `<classname>/<methodname>/<annotationname>/<parametername>=newvalue`  
      applied to a class - `<classname>/<annotationname>/<parametername>=newvalue`  
      e.g. `com.acme.ClassA/methodB/Retry/maxRetries=5`
    * Disable a fault tolerance annotation  
      applied to a method - `<classname>/<methodname>/<annotationname>/enabled=false`  
      applied to a class - `<classname>/<annotationname>/enabled=false`  
      all annotations of a particular type - `<annotationname>/enabled=false`  
      `com.acme.ClassA/methodB/Retry/enabled=false`
    * `MP_Fault_Tolerance_NonFallback_Enabled=false` - disable all Fault Tolerance annotations except `@Fallback`
    * `MP_Fault_Tolerance_Metrics_Enabled=false` - disable metrics produced by Fault Tolerance
    * `mp.fault.tolerance.interceptor.priority` - The Fault Tolerance interceptor base priority can be configured via MicroProfile Config with the property name of mp.fault.tolerance.interceptor.priority. The property value will only be read at application startup. Any subsequent value changes will not take effect until the application restarts.
    *

**Comment by dmuelle** [comment]
Hi @Emily-Jiang , I'm drafting the tables for the MP Config properties. What does the `When runtime read it` column contain? Does that mean the point at which the runtime implements or processes the property, eg, `at server startup` ? What are some example values? I can leave it blank for now but just trying to get a better understanding as I didn't see an obvious answer when I was going through the specs. Thanks

**Comment by Emily-Jiang** [comment]
> Hi @Emily-Jiang , I'm drafting the tables for the MP Config properties. What does the `When runtime read it` column contain? Does that mean the point at which the runtime implements or processes the property, eg, `at server startup` ? What are some example values? I can leave it blank for now but just trying to get a better understanding as I didn't see an obvious answer when I was going through the specs. Thanks

It will be either `at server startup` or `during invocation`. You can leave it blank for now and the relevant component will need to fill in the info.

**Comment by dmuelle** [comment]
First draft is now available for review: https://draft-openlibertyio.mybluemix.net/docs/latest/microprofile-config-properties.html

**Comment by Azquelt** [comment]
I think we need to document which versions of the feature support each property. For example, `mpOpenApi-3.1` is introducing `mp.openapi.scan.beanvalidation=true|false` but that property is not supported on previous versions of `mpOpenApi`.

One option to get around this problem would be to list it on the feature reference page (e.g. https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/mpOpenAPI-3.0.html).

**Comment by dmuelle** [comment]
@Azquelt I agree  support level must be taken into account, Currently, I've included the level at which a property becomes available in the `Description` column, eg `This property is available in MicroProfile OpenAPI 2.0 and later.` The same thing would be applied to any new properties that are added in the future. Is that sufficient?

We can certainly break this page out and keep this information with the features if that is more useful, but adding different property tables to each feature version page for each feature is more difficult to maintain. I was planning to add links to the relevant table from each feature page, but also wanted to see what everyone thought about the most useful way to host the info.

**Comment by dmuelle** [comment]
Hi @Emily-Jiang @Azquelt @pgunapal @Channyboy @jim-krueger @teddyjtorres @njr-11 

This is the docs issue for the MP Config properties reference that was discussed on today's call. The current draft has a table for each spec:
[MicroProfile Config properties](https://draft-openlibertyio.mybluemix.net/docs/latest/microprofile-config-properties.html) 

If each of you could review the table for your spec and leave a comment here for what to put in the `When the runtime reads it` column for each property, as well as any other information or properties that are missing from the table, I will update the doc accordingly. The draft still needs some work but for now, just trying to get all the relevant information into each table. 

Before this goes to publish I'll add links to the relevant table from each MP feature page. Any additional general feedback about how to provide this information is certainly welcome.

Thanks!

**Comment by Azquelt** [comment]
Here are the changes for my features:

### MicroProfile Fault Tolerance
`_classname_/_methodname_/_annotationname_/_parametername_=_newvalue_`
`_classname_/_annotationname_/_parametername_=_newvalue_`
`MP_Fault_Tolerance_NonFallback_Enabled`
For mpFaultTolerance-3.0+, these are read once per method per bean class, on the first execution of the method
For earlier versions, they're read once per method per bean instance, on the first execution of the method

`MP_Fault_Tolerance_Metrics_Enabled`
Read at application startup
This property only applies to mpFaultTolerance 1.1 and newer (since that was the version that introduced metrics)

`mp.fault.tolerance.interceptor.priority`
This property only applies to mpFaultTolerance-2.0 and newer

### MicroProfile Open API
`mp.openapi.extensions.liberty.merged.exclude`
`mp.openapi.extensions.liberty.merged.include`
Read at server startup
This property only applies to mpOpenAPI-2.0 and newer

`mp.openapi.extensions.liberty.merged.info`
Read on each request to the `/openapi` endpoint
This property only applies to mpOpenAPI-2.0 and newer

All other MP OpenAPI properties:
Read at application startup

### MicroProfile Reactive Messaging
All properties:
Read at application startup

**Comment by njr-11** [comment]
> If each of you could review the table for your spec and leave a comment here for what to put in the `When the runtime reads it` column for each property, as well as any other information or properties that are missing from the table, I will update the doc accordingly.

`mp.context.ManagedExecutor.propagated` :
When `ManagerExecutor.builder()` is used to build a `ManagedExecutor` and the builder does not specify the set of propagated context types.

`mp.context.ManagedExecutor.cleared` :
When `ManagerExecutor.builder()` is used to build a `ManagedExecutor` and the builder does not specify the set of cleared context types.

`mp.context.ManagedExecutor.maxAsync` :
When `ManagerExecutor.builder()` is used to build a `ManagedExecutor` and the builder does not specify the maxAsync attribute.

`mp.context.ManagedExecutor.maxQueued` :
When `ManagerExecutor.builder()` is used to build a `ManagedExecutor` and the builder does not specify the maxQueued attribute.

`mp.context.ThreadContext.propagated` :
When `ThreadContext.builder()` is used to build a `ThreadContext` and the builder does not specify the set of propagated context types.

`mp.context.ThreadContext.cleared` :
When `ThreadContext.builder()` is used to build a `ThreadContext` and the builder does not specify the set of cleared context types.

`mp.context.ThreadContext.unchanged` :
When `ThreadContext.unchanged()` is used to build a `ThreadContext` and the builder does not specify the set of cleared unchanged types.

**Comment by WhiteCat22** [comment]
## Microprofile GraphQL

`mp.graphql.defaultErrorMessage`: The property is read when an application throws an unchecked exception.

`mp.graphql.exceptionsWhiteList`: The property is read when an application throws an unchecked exception.

https://download.eclipse.org/microprofile/microprofile-graphql-2.0/microprofile-graphql-spec-2.0.html#_unchecked_exceptions

`mp.graphql.exceptionsBlackList`: The property is read when an application throws a checked exception.

https://download.eclipse.org/microprofile/microprofile-graphql-2.0/microprofile-graphql-spec-2.0.html#_checked_exceptions

**Comment by pgunapal** [comment]
**MicroProfile Health**

- `mp.health.disable-default-procedures` : This property is N/A for OpenLiberty runtime, as the Open Liberty runtime does not have any default vendor health check procedures.
- `mp.health.default.readiness.empty.response` : This property is read at application startup. 
The above property description should be updated to state that it is available in MicroProfile Health 3.0 and later.
- `mp.health.default.startup.empty.response` : This property is read at application startup.
The above property description should be updated to : `Set this property to UP to change the overall default startup status to UP while deployed applications are starting up.` instead of `Set this property to UP to change the overall default readiness status to UP while deployed applications are starting up.`

**Comment by Channyboy** [comment]
- `mp.metrics.tags`
This value is read during the runtime startup. The value of these tags are appended to the output of each metric.
- `mp.metrics.appName`
This value is read/evaluated during runtime. This is used when multiple applications are deployed to the runtime and there is 
need to avoid metric name collisions. This is defined through  a `microprofile-config.properties` provided under the `META-INF` 
 directory o the application. The value of this tag is appended to the output of each metric originating from that application.

**Comment by jim-krueger** [comment]
## RestClient
All of the properties listed are read during the processing of a method invocation when the RestClient bean is created.

**Comment by teddyjtorres** [comment]
Greetings. For `mp.jwt.decrypt.key.location`, please update this sentence,

From:
```
Specifies the location of the Key Management Key, which the private key to decrypt the Content Encryption Key that is then used to decrypt the JWE ciphertext.
```

To:
```
Specifies the location of the Key Management Key, which is the private key used to decrypt the Content Encryption Key that is then used to decrypt the JWE ciphertext.
```

Thanks.

**Comment by teddyjtorres** [comment]
For all properties in `MicroProfile JSON Web Token`, their "When the runtime reads it" is,

```
This property is read on each request to a protected resource.
```

Thanks.

**Comment by dmuelle** [comment]
Hi @Emily-Jiang - I think the complete draft is ready for review:

https://draft-openlibertyio.mybluemix.net/docs/latest/microprofile-config-properties.html

Right now this is just a reference page to list, describe, and give examples for the properties for each MP API. How and where to specify them is covered on the [External configuration of microservices](https://draft-openlibertyio.mybluemix.net/docs/latest/external-configuration.html) page and the [MicroProfile Config guides](https://openliberty.io/guides/#configuration).

This page is also linked from the External configuration of microservices page and from each relevant MP Feature page. Would be good to look at getting links to it into the MP Config guides as well. If so, I can open an issue on the guides backlogs once this publishes.

If any further edits are needed, just let me know. If not, you can add the `technical reviewed` label to this issue and the doc will publish with the 22.0.0.10 release. Thanks to all who contributed!

**Comment by dmuelle** [comment]
Emily provided sign off [via slack](https://ibm-cloud.slack.com/archives/C31GEJTQD/p1662399362354029?thread_ts=1662141598.909289&cid=C31GEJTQD). Doc will publish with 22.0.0.10.

**Comment by dmuelle** [comment]
Changes are in vNext and will publish with 22.0.0.10- closing this issue
