### ISSUE TITLE
Document the serverSchemaGen command

### ISSUE THREAD

**Issue by jimblye** [OpenLiberty/docs#5118]
Note the similarity to issue #4550  to avoid getting them mixed up   :) 

The serverSchemaGen command is not documented anywhere and the --help option doesn't provide any information at all.
Invoking the command with zero parameters tells you that you should use the server_name as a parameter.

There will be a separate issue to fix the --help option.

The serverSchemaGen command generates a schema for a specific server.

As far as I know right now, the only valid syntax is

serverSchemaGen _serverName_

The schema is generated in the wlp/usr/servers/serverName/schemaGen/server.xsd file

**Comment by dmuelle** [comment]
need to differentiate between schemaGen and serverSchemaGen so customers know which one to use

**Comment by dmuelle** [comment]
issue on the dev side for the help

https://github.com/OpenLiberty/open-liberty/issues/15140


I got the following the message the first time I ran it against a running server:

`$ serverSchemaGen OIDC
CWWKG3002E: The server named OIDC is not configured to accept local JMX requests. Ensure that the server configuration includes the localConnector feature, and that the server is started.`

added `localconnector-1.0` and got 

`CWWKG3008I: The requested server schema was generated in the following directory: /Users/David.Mueller1@ibm.com/wlp/usr/servers/OIDC/schemagen/server.xsd`

**Comment by dmuelle** [comment]
we also need to document any exit codes that apply to this command

**Comment by jimblye** [comment]
@dmuelle  I have created a pull request for open liberty issue 15140.   I'm planning on the updated serverSchemaGen and the new schemaGen command being available in 22.0.0.3

The serverSchemaGen command creates a schema based on the configuration of the server specified in the command.  

This is the output of the --help option:

**Usage: serverSchemaGen server**

**Options:**

**--schemaversion**
**The XSD version to use for schema generation**

**--outputversion**
**The Output version of the generated schema** 

**--encoding**
**The character encoding to use for the output**

**--locale**
**The locale to use for the output**


**Exit codes** from the comments in the code:
 
     /**
     * Return code for invalid option or argument, as defined in this WIKI on January 13th, 2015. This must remain 20.
     */
    private static final int RC_INVALID_OPTION = 20;

    /**
     * Return code for server not found. This could happen for a number of reasons - the server really does not exist,
     * or some variable (WLP_USER_DIR) was not set correctly.
     */
    private static final int RC_SERVER_NOT_FOUND = 21;

    /** Return code for local connector URL not found. */
    private static final int RC_LOCAL_CONNECTOR_URL_NOT_FOUND = 22;

    /** Return code indicating the MBean was not found. */
    private static final int RC_MBEAN_NOT_FOUND = 23;

    /** Return code indicating the MBean reported a bad result. Caller should check the server's log for exceptions. */
    private static final int RC_MBEAN_INVALID_RESULT = 24;

    /**
     * Return code indicating that the WLP_OUTPUT_DIR/logs directory couldn't be found, likely because the environment value is set to
     * something other than what the server is using.
     */
    private static final int RC_SERVER_OUTPUT_NOT_FOUND = 25;

    /** Return code for unexpected errors. The message printed should be used to figure out what happened. */
    private static final int RC_UNEXPECTED_ERROR = 255;

**Comment by dmuelle** [comment]
Thanks @jimblye -We can get this doc ready for 22.0.0.3. A few questions:
@dmuelle answers in **_italics_**
1. What happens if you don't specify a serverName? Does it run against defaultServer?
     _**It just prints out the usage (first line of --help)):
     Usage: serverSchemaGen server**_
     
2. My experience testing the command was that it did not work unless the server you are targeting has the `localconnector-1.0` feature enabled. Is that true in all/most cases?
   _**Not only that, but the server has to be started.   You always get that error message unless the server has the localconnector-1.0 feature and the server is started.**_


3. For the `schemaGen` command, we provide a little more info on some of the corresponding options . Does this info also apply for `serverSchemaGen`?
       _**Yes, that does seem to be the case, which is making me think the --help output is not so accurate, and I should probably update that to match the doc**_


-locale=language | Specifies the language to use in the generated output file, where language is an ISO-639 two-letter lowercase language code, optionally followed by an underscore and the ISO-3166 uppercase two-letter country code.
-- | --
--schemaVersion=1.1 | Specifies that both explicitly named child elements and the xsd:any element are written to the output file.
--outputVersion=2 | Specifies that only the xsd:any element is used in the output file. When this option is specified, unknown elements pass XSD validation at the expense of losing validation for known elements.

**Comment by dmuelle** [comment]
Hi @jimblye - here's the draft for `serverSchemaGen`, when you have a chance, would you review and let me know if any further changes are needed?

https://docs-draft-openlibertyio.mybluemix.net/docs/latest/reference/command/serverSchemaGen.html

two questions:

1. I found that the `--help` option for the command wouldn't work unless you specified a server name, even though the option is for the command and not any particular server- is that expected? If so, ok I've documented it.
2. In the exit codes- `22 indicates that the local connector URL was not found.` - is that likely because the localConnector feature isn't enabled? If so, I could add a reminder to check it

Thanks!

**Comment by dmuelle** [comment]
moving to 22.0.0.5 with #4550

**Comment by dmuelle** [comment]
current draft for review:
https://docs-draft-openlibertyio.mybluemix.net/docs/latest/reference/command/serverSchemaGen.html

**Comment by ramkumar-k-9286** [comment]
Peer Review
---

The schema is created as a file that is named `server.xsd` in the `${server.config.dir}/schemagen` directory.
--->
Removed - **that is**
The schema is created as a file named `server.xsd` in the `${server.config.dir}/schemagen` directory.

----

Generate a schema for an Open Liberty server that is named `myServer`.
--->
Removed - **that is**
Generate a schema for an Open Liberty server named `myServer`.

---

Generate a schema in the Brazilian Portuguese language for **n** Open Liberty server **that is** named `myServer`.
--->
Removed - **that is**, fixed **n** with **an**
Generate a schema in the Brazilian Portuguese language for an Open Liberty server named `myServer`.

---

`--locale=language` - This option specifies the language to use in the generated output file, where language is an ISO-639 two-letter lowercase language code, optionally followed by an underscore and the ISO-3166 uppercase two-letter country code.

**Acrolinx - Sentence too long - 33 words.**

**Suggested**
`--locale=language` - This option specifies the language to use in the generated output file. Language is an ISO-639 two-letter lowercase language code and can be followed by an underscore and the ISO-3166 uppercase two-letter country code.

---

The following exit codes are available for the `serverSchemaGen` command:
--->
The following exit codes are available for the `serverSchemaGen` command.

"." is used for the previous table.

---

This code indicates that the **the** `WLP_OUTPUT_DIR/logs` directory **couldn’t** be found, likely because the environment value is set to something other than what the server is using.
--->
This code indicates that the `WLP_OUTPUT_DIR/logs` directory could not be found, likely because the environment value is set to something other than what the server is using.

---

This code indicates unexpected errors. Use the printed message to figure out what happened.
--->
Do we say **figure out what happened**? - sounds very casual.
This code indicates unexpected errors. Use the printed message **to identify and decipher the errors**.
**Can we use this?**

**Comment by dmuelle** [comment]
Thanks for reviewing @ramkumar-k-9286 - all suggestions incorporated except for the following:

- removing *that is*: as much as I would like to do this, it's against ID standards. For translation purposes, when you use a past  participle like "named", must conjoin it with "that is"
- fixed the definition for --locale=language by removing one word- "generated"
- conjunctions like "couldn't" are permitted

**Comment by dmuelle** [comment]
changes are on vNext and will publish with the 22.0.0.5 docs release- closing this issue.
