### ISSUE TITLE
Content not found error for bells page

### ISSUE THREAD

**Issue by frowe** [OpenLiberty/docs#5191]
Searching for bell returns the following URL: https://www.ibm.com/docs/en/was-liberty/base?topic=configuration-bell which when clicked on results in "We're sorry! Content not found"

**Comment by dmuelle** [comment]
Hi @frowe - this may have been due to a slow server or connectivity issue. I can access the content at https://www.ibm.com/docs/en/was-liberty/base?topic=configuration-bell as expected. This content is also available on the Open Liberty website at : https://www.openliberty.io/docs/latest/reference/config/bell.html.

Closing this issue since I can't reproduce the problem. If I've misunderstood, feel free to re-open and assign to me. Thanks
