### ISSUE TITLE
22.0.0.5: feature 19324 multiple SSL Protocol support

### ISSUE THREAD

**Issue by acdemyers** [OpenLiberty/docs#5283]
**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**

Documentation for feature https://github.com/OpenLiberty/open-liberty/issues/19324
To go in fix pack 22.0.0.5

A new section needs to be added to:

New topic in https://openliberty.io/docs/22.0.0.2/reference/feature/transportSecurity-1.0.html

```
Configure multiple SSL protocols

An SSL protocols can be configured using the sslProtocol attribute.  Multiple SSL protocols can also be configured on the sslProtocol attribute by using a comma separated list from the TLSv1, TLSv1.1, TLSv1.2, and TLSv1.3 protocols values as long as the underlying JDK support.

An example of configuring TLSv1.3 and TLSv1.2 on a SSL configuration:

<ssl id="myDefaultSSLConfig"
      keyStoreRef="defaultKeyStore"
      trustStoreRef="defaultTrustStore"
      sslProtocol="TLSv1.3, TLSv1.2" />
```

Also discussed with Karen that https://ibmdocs-test.mybluemix.net/docs/en/SSAW57_liberty_test?topic=liberty-ssl-configuration-attributes could be updated to link to New topic in https://openliberty.io/docs/22.0.0.2/reference/feature/transportSecurity-1.0.html

**Comment by chirp1** [comment]
Follow these directions to write the documentation:  https://github.com/OpenLiberty/docs

**Comment by chirp1** [comment]
@acdemyers Hi! Ready for you to review my updates at https://docs-draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/transportSecurity-1.0.html

It's the "Configure multiple SSL protocols" section.

**Comment by acdemyers** [comment]
The changes look good.

**Comment by chirp1** [comment]
@acdemyers @dmuelle I made further updates to the topic at https://docs-draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/transportSecurity-1.0.html#configure-specific 
- For the "Default keystore and TLS certificate configurations" I added "You can [configure specific TLS protocols](https://docs-draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/transportSecurity-1.0.html#configure-specific) instead of configuring and enabling all of them by default." so that the paragraph that the sentence is in makes more sense.
- I made further updates to the "Configure specific TLS protocols", which is the section that I added for this issue.

Let me know what you think. Thanks!

**Comment by acdemyers** [comment]
@chirp1 The latest updates look good to me.

**Comment by dmuelle** [comment]
LGTM, thanks

**Comment by chirp1** [comment]
The updated topic is now on the following staging server: https://docs-staging-openlibertyio.mybluemix.net/docs/latest/reference/feature/transportSecurity-1.0.html#configure-specific

**Comment by dmuelle** [comment]
changes are on vNext and will publish with the 22.0.0.5 docs release- closing this issue.
