### ISSUE TITLE
Migrate and reformat SAML examples from IBM docs

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#5308]
Assess and migrate the "tasks" at [Configuring SAML Web Browser SSO in Liberty](https://ibmdocs-test.mybluemix.net/docs/en/SSAW57_liberty_test?topic=liberty-configuring-saml-web-browser-sso-in) and [Configuring SAML Web Inbound Propagation in Liberty](https://ibmdocs-test.mybluemix.net/docs/en/SSAW57_liberty_test?topic=liberty-configuring-saml-web-inbound-propagation-in)to a series of examples on the [SAML Web Single Sign-On](https://www.openliberty.io/docs/22.0.0.3/reference/feature/samlWeb-2.0.html) feature page. Work with an SME from Security team to determine which examples are relevant and useful.

**Comment by dmuelle** [comment]
## analysis: steps to examples

1. n/a, already on feature page
2. minimal configuration- add to default config example
3. already covered in generated doc for samlWebSso20- add link from default config
4. add info to custom config example
5. provide example for PKIXTrustEngine
6. already covered in generated doc
7. insufficient info to complete task
8. already covered in generated doc
9.  already covered in generated doc
10. provide example of multiple SAML
11. provide IdP-initaied sso example
12. provide example to supplement generated doc
13. covered in generated doc
14. provide disableLtpaCookie=false example
15. coordinate with 10 and provide simple authfilter example
16. clusters not supported for OL
17. covered in generated doc

**Comment by dmuelle** [comment]
The session cookie name is automatically generated. You can customize the cookie name by specifying  a new name in the  `spCookieName` attribute.

check on this- not documented in gendoc


also- the task references `trustAnchor` for PKIX engine, but the attribute is `trustAnchorRef` confirm this and that the att just needs to specify the ID of a keyStore- no need to separately configure a trustAnchor

**Comment by dmuelle** [comment]
draft update: https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/samlWeb-2.0.html

**Comment by arunavemulapalli** [comment]
I haven't completed the review yet..
But some changes that I thought that you may start looking at..

Under Default configuration section  - 

Move this following to a new line to make it as a separate point

**The IdP metadata file must be named idpMetadata.xml and copied to the resources/security directory on the server.**

(IdP metadata and SP metadata are different)


Under Customize the default configuration section - 

Remove spHostAndPort and add the following instead (as this is more useful configuration attribute that users may customize..)

**idpMetadata=${server.config.dir}/customizedidpMetadata.xml**


Under Configure a PKIX trust engine section - 

Please update all these references - **trustAnchorRef** to **trustAnchor**


Please add a section to describe the configuration that can be used to create the authenticated Subject (this is the 6th optional point in the WL docs)

Also the points 7 - 9 are optional but should be included here (since most users of this feature do add these attributes..)

**Comment by arunavemulapalli** [comment]
Under Configure Identity provider initiated unsolicited single sign-on section - 

Change the following 

The following example demonstrates the server.xml configuration to specify IdP-initiated SSO, where the IdP signer certificates are in a keystore file that is called serverStore.

To 

The following example demonstrates the server.xml configuration to specify IdP-initiated SSO, where the IdP signer certificates are in a file specified in the serverStore (which is a keyStore element id) configuration

`<samlWebSso20
		id="libertysp"....... 
		...
		...
		<pkixTrustEngine
			trustAnchor="serverStore"
			trustedIssuers="xyz" />
			</samlWebSso20>
  <keyStore
		id="serverStore"
		password="xxxxxxx"
		type="jks"
		location="${server.config.dir}/sslTrust.jks" />
`

**Comment by arunavemulapalli** [comment]
Please change
Use an LTPA cookie to maintain a SAML-authenticated session section - change the title to 
**SP authentication session and SP cookie** (most users probably will be interested in this one...)

You can configure an SP authentication session and session cookie. After SAML assertion is verified and processed, the Liberty SAML SP maintains an authenticated session between the browser and the SP without using an LTPA cookie. The authenticated session timeout is set to **SessionNotOnOrAfter** in the <**saml:AuthnStatement**> if presented, or to **sessionNotOnOrAfter** as configured in the server.xml file, with the default being 120 minutes. 
The session cookie name is automatically generated, and you can customize the cookie name by using the attribute **spCookieName**.
If you want the Liberty SP to create an LTPA cookie from the SAML assertion and use the LTPA cookie for subsequent authentication requests, you can add the configuration **disableLtpaCookie="false"**. If you want to share the LTPA cookie with other servers, you must add the configuration attribute **allowCustomCacheKey="false"**.

**Comment by arunavemulapalli** [comment]
Please add point 13 (from the WL docs) as this is an important aspect of the message flow between the SP and IdP.

Configure signature requirements :
	•	Signing of SAML assertion/s -  All SAML assertions must be digitally signed by the SAML IdP. In the rare case that you want to accept an unsigned assertion, you can explicitly configure **wantAssertionsSigned="false".**
	•	Signature Algorithm - The default signature algorithm is **SHA256**. If you must change the algorithm, use the **signatureMethodAlgorithm** attribute to modify it.
	•	If you do not want SP to sign the SAML AuthnRequest, you can set **authnRequestsSigned=false**.

**Comment by arunavemulapalli** [comment]
I think we need to add point 16 also.

It is not like twas cluster but to support multiple liberty SPs handling the same request

**Comment by dmuelle** [comment]
Thanks so much for reviewing- I am working on implementing your suggestions but I have a few questions.

> Please update all these references - trustAnchorRef to trustAnchor

Looking at the autogenerated reference documentation for [samlWebSso20> pkixTrustEngine](https://openliberty.io/docs/latest/reference/config/samlWebSso20.html), there is no attribute called  `trustAnchor` but there is one ` trustAnchorRef`. Since this reference doc is generated from the Liberty code metatype files, I assumed the error was in the docs. If that's not the case, we need to open an issue in 
[open-liberty](https://github.com/OpenLiberty/open-liberty) to update the code base. Can you confirm which attribute name is correct?

> The session cookie name is automatically generated, and you can customize the cookie name by using the attribute spCookieName

This attribute  is also not documented in the generated reference- can you confirm that it exists? If so, we need to open an issue to update the code base so it shows up in the generated doc.

> I think we need to add point 16 also. It is not like twas cluster but to support multiple liberty SPs handling the same request

Does this step apply to Liberty collectives/clusters? They are only supported in WebSphere Liberty, not in Open Liberty. If this applies to something else, can we provide a little more information to explain what it is?

I left out step 7 because we dont provide any information about how to develop the mentioned user feature- is this documented anywhere?

Lastly, I intentionally left out optional steps 6,8,9, and 13 because they don't contain any code examples and just restate what is already documented in the generated reference doc for [samlWebSso20](https://openliberty.io/docs/latest/reference/config/samlWebSso20.html), which is linked from the "customize" example . 

In general, we try to avoid exhaustively duplicating the generated doc unless that doc is somehow incomplete or insufficient.  If the generated reference for any these attributes is not adequate, we can add code examples and explanations here. But if the definitions in the reference doc are correct, it's better to keep this topic as concise as possible. Let me know what you think- thanks again!

**Comment by arunavemulapalli** [comment]
**trustAnchor** is the correct attribute name

**spCookieName** is an internal attribute. I will open an issue to externalize this one. I've seen customers using this attribute already.

Step 16 - you may be right. Probably this is applicable to WL only.

I will take a look at step 7 to see if we have documentation to develop the user feature mentioned.


6,8,9,13 - let me look at the "customize" example

thank you.

**Comment by dmuelle** [comment]
Hi @arunavemulapalli - the updated draft is available for review:
https://docs-draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/samlWeb-2.0.html

So far, I've made the following changes per your review:

- [x] Moved to a new line to make it as a separate point: The IdP metadata file must be named idpMetadata.xml and copied to the resources/security directory on the server.
- [x] Removed spHostAndPort and add idpMetadata=${server.config.dir}/customizedidpMetadata.xml instead
- [x] Updated all these references - trustAnchorRef to trustAnchor
- [x] Updated  "...where the IdP signer certificates are in a file specified in the serverStore (which is a keyStore element id) configuration"
- [x] Renamed "Use an LTPA cookie to maintain a SAML-authenticated session" section  to "Configure an SP authentication session and SP cookie" and reworked per comments

for the remaining optional steps (6-9, 13) I can add examples as needed to supplement the generated doc. Alternatively, some of the attributes could be added to the "Customize the default configuration" example.

**Comment by dmuelle** [comment]
I'm not sure why `trustAnchor` is showing as `trustAnchorRef` in the generated doc. Looking at the file `com.ibm.ws.security.saml.websso.2.0/resources/OSGI-INF/metatype`, which should be used to generate the reference doc (i think), i see the following at line 149

```xml
<OCD id="com.ibm.ws.security.saml.sso20.pkixtrustengine.metatype" name="%pkixtrustengine" description="%pkixtrustengine.desc" ibmui:localization="OSGI-INF/l10n/metatype">
<AD id="trustAnchor" name="%trustStoreRef" description="%trustStoreRef.desc" 
	        required="false" type="String" ibmui:uiReference="com.ibm.ws.ssl.keystore"/>
```
so it is reusing the description for `trustStoreRef`, but I don't know where the generated doc is getting `trustAnchorRef`.

**Comment by arunavemulapalli** [comment]
looks good to me.


I will open an issue for myself to work with you on adding more example configurations for 6-9 and 13 and maybe 16 (if this can be configured in non-cluster and useful in some other configurations..)

thank you.

**Comment by ramkumar-k-9286** [comment]
Peer Review
---

To enable the SAML Web Single Sign-On 2.0 feature, add the following element declaration into your `server.xml` file, inside the `featureManager` element:
->
To enable the SAML Web Single Sign-On 2.0 feature, add the following element declaration into your `server.xml` file, inside the `featureManager` element**.**

---

[Configure SAML Web inbound propagation](https://docs-draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/samlWeb-2.0.html##inbound)
->
Link not working

---

When the SAML Web Single Sign-on feature is enabled, Open Liberty provides a default SAML configuration with an ID value of `defaultSP`. The SAML Web Single Sign-on feature activates the following two endpoints:
->
When the SAML Web Single Sign-on feature is enabled, Open Liberty provides a default SAML configuration with an ID value of `defaultSP`. The SAML Web Single Sign-on feature activates the following two endpoints**.**

---

For more information about the available configuration attributes, see [samlWebSso20](https://docs-draft-openlibertyio.mybluemix.net/docs/latest/reference/config/samlWebSso20.html).
->
For more information about the available configuration attributes, see [SAML Web SSO 2.0 Authentication](https://docs-draft-openlibertyio.mybluemix.net/docs/latest/reference/config/samlWebSso20.html).

Would the full name here be better?

---

You must specify a non-null URL-safe string as the ID value.
->
Acrolinx - says - Don't use a hyphen after the prefix "non" - sounds odd.

---

When multiple `samlWebSso20` elements are configured, each element can implement single-sign-on with its specified federated IdP and according to its own authentication policy and consuming rules.
->
When multiple `samlWebSso20` elements are configured, each element can implement single-sign-on with its specified federated `IdP` and according to its own authentication policy and rules.

Acrolinx picking up `consuming` - suggesting simpler words like use. but I removed `Consuming` and sounds ok. 

---

The default trust engine for SAML on Open Liberty is the Metadata trust engine, which validates a signature against information that is provided in the configured IdP metadata.
->
 Metadata trust engine -> **metadata** trust engine (caps required?)

---

, you must add the following configurations: - Configure the `PKIXTrustEngine` subelement and import all the IdP signer certificates to the default truststore of the Liberty server, or to the trustAnchor of the PKIXTrustEngine. - Configure the trustedIssuers attribute to list the issuer name of the IdP as it appears in the SAML assertion. The issuer name is used as the EntityID in the metadata.
->
Can we introduce this as 2 bullet points rather than putting it up as a paragraph?

---

If you intend to support unsolicited SSO only, you can [configure SP-initiated unsolicited SSO](https://docs-draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/samlWeb-2.0.html#spsso).
->
THis redirects to the very next line - do we need a link?

---

This scenario is useful if the user’s security context in the SP that is associated with SAML becomes invalid, the SP can redirect the user back to the IdP to start unsolicited SSO again automatically.
->
Acrolinx suggesting line too long - rephrase ->

This scenario is useful if the user’s security context in the SP that is associated with SAML becomes invalid. The SP can redirect the user back to the IdP to start unsolicited SSO again automatically.

---

An Open Liberty SP can also redirect unauthenticated requests to a preconfigured login application without using an `AuthnRequest` instance.
->
 Acrolinx suggestion - An Open Liberty SP can also redirect**-**unauthenticated requests to a preconfigured login application without using an `AuthnRequest` instance.

---

**Comment by dmuelle** [comment]
Thanks for reviewing @ramkumar-k-9286, draft is updated 

https://docs-draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/samlWeb-2.0.html

All suggestions incorporated except for the following

> To enable the SAML Web Single Sign-On 2.0 feature, add the following element declaration into your server.xml file, inside the featureManager element.

This part of the page is in the generated doc 
______________________________________________________
> You must specify a non-null URL-safe string as the ID value.

I think this is an exception to the rule Acrolinx is flagging. IBM terminology/Termbot says to use "non-null"
____________________

> If you intend to support unsolicited SSO only, you can [configure SP-initiated unsolicited SSO](https://docs-draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/samlWeb-2.0.html#spsso). (Do we need link?)

Left it in as sometimes the examples move around on the page when updates are added.
_______

> An Open Liberty SP can also redirect**-**unauthenticated requests 

This is a weird false-positive result in Acrolinx. I'm not sure why it's showing up but I think we should ignore it as a hyphen is not correct here

**Comment by dmuelle** [comment]
content is on vNext and will publish with 22006, closing this issue.
