### ISSUE TITLE
GraphQL Observability section has hyphens before version number in some feature names

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#5577]
Document: Build GraphQL applications with MicroProfile GraphQL
http://openliberty.io/docs/latest/microprofile-graphql.html

Don't think the GraphQL feature names should have the hyphenation. They should be like the other features named in these sentences:

> The [MicroProfile GraphQL-1.0](https://openliberty.io/docs/latest/reference/feature/mpGraphQL-1.0.html) feature integrates with the [MicroProfile Metrics 2.3](https://openliberty.io/docs/latest/reference/feature/mpMetrics-2.3.html) and [3.0](https://openliberty.io/docs/latest/reference/feature/mpMetrics-3.0.html) features.
> 
> The [MicroProfile GraphQL-2.0](https://openliberty.io/docs/latest/reference/feature/mpGraphQL-2.0.html) feature integrates with the [MicroProfile Metrics 4.0](https://openliberty.io/docs/latest/reference/feature/mpMetrics-4.0.html) feature.

**Comment by dmuelle** [comment]
consolidating from #5576 to address both recommendations in one issue:

Document: Build GraphQL applications with MicroProfile GraphQL
http://openliberty.io/docs/latest/microprofile-graphql.html

Just been reading this topic to find out what the GraphQL support is about.

I would suggest that the following paragraph (from the first sub-section), which nicely explains why you should care about GraphQL would be better at the start of that section (and even touched on in the first para/abstract of the article even), rather than talking about schemas etc and how GraphQL works first. Don't really care how it works if you don't understand what the point of it is in the first place.

> "You can use a GraphQL service to obtain data from multiple sources such as APIs, databases, and other services. The GraphQL service can then collate this data into a single object, which simplifies the data retrieval. You make only a single request to the GraphQL service, instead of multiple requests to the individual data sources. GraphQL services require less data fetching than REST services, which results in faster application load times and lower data transfer costs. GraphQL also enables clients to better customize requests to the server."

**Comment by dmuelle** [comment]
@lauracowen - updated the draft at: https://docs-draft-openlibertyio.mybluemix.net/docs/latest/microprofile-graphql.html

- reorganized the paragraphs in the "What is GraphQL?" section per your suggestion
- revised the short description to include what GQL enables you to do (simplify data retrieval)
- removed hyphens from feature names

**Comment by lauracowen** [comment]
When I read it just now, I wondered whether the sentence "GraphQL is an open source...." should be in front of "You can use...". Just seems a slightly stronger start. Then the second paragraph starts "GraphQL uses a schema...".

But I could go either way - up to you. :)  Thanks

**Comment by dmuelle** [comment]
I agree and have updated the draft accordingly- Thanks for your input!

**Comment by dmuelle** [comment]
changes are on vNext and will publish with 22.0.0.7- closing this issue
