### ISSUE TITLE
Improve JSON B docs

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#5596]
see information in #5590

**Comment by dmuelle** [comment]
Hi @KyleAure - here is the draft for the JSON-p/B 3rd paty implementation doc update:

https://docs-draft-openlibertyio.mybluemix.net/docs/latest/json-p-b.html#_third_party_json_p_and_json_b_providers

Let me know if any further changes are needed. If not, you can add the `technical reviewed` label to this issue to sign off and the updates will publish with the next docs release. Thanks for writing this up!

**Comment by dmuelle** [comment]
@ramkumar-k-9286 - would you please peer review this update? Thanks

**Comment by ramkumar-k-9286** [comment]
Peer Review
---

Even developers with no prior experience with JSON can use JSON-B because it’s based around annotations and semantics that are already commonplace for Java developers.
->
Even developers with no prior experience with JSON can use JSON-B because **it is** based **on** annotations and semantics that are already commonplace for Java developers.

---
JSON-B is the preferred API for converting Java objects to and from JSON, thanks to its type safety, ease-of-use, and compile-time feedback. However, in some cases, JSON-P might be a better fit.
->
JSON-B is the preferred API for converting Java objects to and from JSON, thanks to its type safety, **ease of use**, and compile-time feedback. However, in some cases, JSON-P might be a better fit.

---
For example, if data loss is a concern, JSON-P might be preferred. In the following example, JSON data that is being sent between microservices represents a user:
->
**For example, JSON-P might be preferred if data loss is a concern.** In the following example, JSON data **sent** between microservices represents a user.

---
The following example shows a data class:
->
The following example shows a data class.

---
By default, JSON property names match Java field or method names. If matching names are not wanted or not possible, you can define new mappings, as shown in the following example:
->
By default, JSON property names match Java field or method names. If matching names are not wanted or not possible, you can define new mappings, as shown in the following example.

---
Then, configure a library and a Basic Extension using Liberty Libraries (BELL) that provides an implementation of the JSON-P or JSON-B API.
->
Then, configure a library and a Basic Extension **by** using Liberty Libraries (BELL) that provides an implementation of the JSON-P or JSON-B API.

---
For example, Apache Johnzon is a third-party JSON-B implementation. In this example, a server is configured to use Johnzon instead of the default reference implementation, which is Yasson:
->
For example, Apache Johnzon is a third-party JSON-B implementation. In this example, a server is configured to use Johnzon instead of the default reference implementation, which is Yasson.

---
For example, Apache Johnzon also provides a JSON-P implementation. In this example, a server is configured to use Johnzon instead of the default reference implementation for JSON-P, which is GlassFish. However, the server continues to use Yasson for JSON-B:
->
For example, Apache Johnzon also provides a JSON-P implementation. In this example, a server is configured to use Johnzon instead of the default reference implementation for JSON-P, which is GlassFish. However, the server continues to use Yasson for JSON-B.

---

**Comment by dmuelle** [comment]
Thanks for reviewing @ramkumar-k-9286 , all suggestions implemented: https://docs-draft-openlibertyio.mybluemix.net/docs/latest/json-p-b.html

**Comment by dmuelle** [comment]
changes are on vNext and will publish with 22.0.0.7
