### ISSUE TITLE
SEC 380: Distributed security caching updates

### ISSUE THREAD

**Issue by jvanhill** [OpenLiberty/docs#5704]
Documentation changes for the [distributed security cache feature](https://github.com/OpenLiberty/open-liberty/issues/9005).

See attached documentation for proposed changes.

[DocUpdates2.odt](https://github.com/OpenLiberty/docs/files/9419054/DocUpdates2.odt)

**Comment by dmuelle** [comment]
HI @jvanhill I've completed the updates in your draft- though to start I've organized them slightly differently, hopefully to make things easier to find and to minimize the jumping around for users

- created [Distributed caching with JCache](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/distributed-caching-jcache.html) (in `Development > Data Persistence >`)
- updated [Configuring Infinispan as a JCache provider](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/configuring-infinispan-support.html) (in `Development > Data Persistence > Distributed caching with JCache >`)
- moved authcache and logged out SSO example from the appSecurity page to new topics in security (see following)
  - created [Configure the authentication cache](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/authentication-cache.html) (in `Security > Authentication >` )
This topic combines the basic auth cache config info that was previously on the appSecurity feature page with the new distributed authcache info so that all authcahe doc is in `security>Authentication` in one place.
  - created [Track logged-out SSO cookies](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/track-loggedout-sso.html) (in `Security > Single Sign On >`)
This topic combines the basic logged-out cookie config info that was previously on the appSecurity feature page with the new distributed logged out cookie cache info so that all  doc is in `security>SSO` in one place.
- updated [Authentication](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/authentication.html)
- updated [JCache Session Persistence 1.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/sessionCache-1.0.html)


Let me know what edits are needed or if there is a better organizational scheme for this info. Thanks!

**Comment by nstewart0206** [comment]
I think that it would be nice to provide links to the "Configure the authentication cache" and the "Track logged-out SSO cookies" in the "Configuring Infinispan as a JCache provider" document.  I think that the second paragraph or under the Results section as additional information could be good places to put that information.  Since it's not in the same section but is related, people may not realize that these are other caching options available to them.

**Comment by jvanhill** [comment]
@dmuelle - My findings -

`Overall:`
```
I liked the menu better when all the JCache functionality was under "Distributed caching with JCache". I felt everything else should reference back to that location instead. The way you have it now, only session caching is there and that seems odd.
```


`distributed-caching-jcache.html`
```
... including HTTP session caching and configuring a distributed authentication cache or distributed logged-out cookie cache.

    to

... including HTTP session caching, distributed authentication caching and distributed logged-out cookie caching.
````
```
... can improve performance among groups of servers that share common data, such as a user registry.

    to

... can improve performance among groups of servers that share common data.
```
```
The ClassLoader instance from the library that is provided in the cachingProvider element is used.

    to

A unified ClassLoader constructed from all configured libraries in the cachingProvider element is used load the CachingProvider.
```
```
Remove the following under "cacheManager" - technically we don't populate with a CacheLoader, we pass in null.

The ClassLoader instance from the library that is provided in the cachingProvider element is used. For more information, see cacheManager.
```


`authentication.html`
```
Good.

However; I think the list for supported SSO authentication options is missing SSO options (OIDC, OAUTH, SAML, etc).
```

`authentication-cache.html`
```
Not sure about the name of the page: "Configure the authentication cache"? Maybe just "Authentication cache".

After the first paragraph, I would probably have a header of "Configure in-memory authentication cache", that matches "Configure a distributed authentication cache". The should be two separate sections - alternatives to eachother.

Lets rename AuthCache to io.openliberty.cache.authentication in the server.xml snippets.

Not sure we need the ellipses in the XML snippets.
```

`track-loggedout-sso.html`
```
Lets rename LoggedOutCookieCache to io.openliberty.cache.loggedoutcookie in the server.xml snippets.

Not sure we need this sentence: The Application Security feature version 3.0 and later enables the Jakarta Servlet feature by default.

Not sure we need the ellipses in the XML snippets.
```

`configuring-infinispan-support.html`
```
This entire page is somewhat misleading. In OpenShift, we use Datagrid, which is the commercial / openshift version of Infinispan.
```

`sessionCache-1.0.html`
```
Good. Though I wonder if we could move some of the generic configuration of JCache to the JCache specific pages.
```

**Comment by dmuelle** [comment]
Thanks for reviewing @jvanhill @nstewart0206 

all suggestions implemented except

> I liked the menu better when all the JCache functionality was under "Distributed caching with JCache". I felt everything else should reference back to that location instead. The way you have it now, only session caching is there and that seems odd.

My thinking was that configuring an authentication cache and tracking logged out cookies were more about security than JCache per se, for those JCache is just the tool you use to solve a security problem. I can move them back but not sure what to do with the authCache topic since that is not just JCache biut also the local authCache. I could split it into two topics if that's better

## authentication.html
>  I think the list for supported SSO authentication options is missing SSO options (OIDC, OAUTH, SAML, etc).

That list links to sections of the SSO topic, which just lists the most common solutions rather than an exhaustive list. I changed the wording to make it clear that those aren't the only SSO mechanisms we support.

## configuring-infinispan-support.html
> This entire page is somewhat misleading. In OpenShift, we use Datagrid, which is the commercial / openshift version of Infinispan.

I think this page was originally adapted from [this blog post](https://openliberty.io/blog/2020/01/08/infinispan-open-liberty-openshift.html). Is this info still relevant or useful? If not we can remove it and just leave the blog post for those that might be looking for it.

## track-loggedout-sso.html

> Not sure we need this sentence: The Application Security feature version 3.0 and later enables the Jakarta Servlet feature by default.

I left this in so its clear to those using appSecurity 3.0 and later that they dont need to add servlet to the server.xml

## sessionCache-1.0.html

> I wonder if we could move some of the generic configuration of JCache to the JCache specific pages.

Do these examples show anything that isn't already on the new JCache page? If not, we could remove anything that is now redundant and move the infinispan/hazelcast examples to that page and just point to it from here.

**Comment by jvanhill** [comment]
@dmuelle -

Make the following changes in authentication-cache.html:

```
Supported SSO mechanisms
The Open Liberty distributed authentication cache supports caching the subject credentials for the following SSO mechanisms and configurations.

- LTPA

- JWT, when the JSON Web Token Single Sign-On feature is enabled.

- SPNEGO, when the Simple and Protected GSSAPI Negotiation Mechanism feature is enabled and the spnego:includeClientGSSCredentialInsubject attribute is set to false.

- SAML, when the SAML Web Single Sign-On feature is enabled. (via samlWeb-2.0 feature) Need to discuss whether we advertise this… TALK TO TEDDY

- OAuth, when the Social Media Login feature is enabled and the oauth2Login element is configured.

Subjects that are authenticated by unsupported mechanisms are stored in the local cache instead.
```

should be:

```
Supported SSO mechanisms
The Open Liberty distributed authentication cache supports caching the subject credentials for the following SSO mechanisms and configurations.

- LTPA

- JWT, when the JSON Web Token Single Sign-On feature is enabled.

- SPNEGO, when the Simple and Protected GSSAPI Negotiation Mechanism feature is enabled and the spnego:includeClientGSSCredentialInsubject attribute is set to false.

- SAML, when the SAML Web Single Sign-On feature is enabled. The samlWebSso20:spCookieName must be explicitly set and match on all servers that share the authentication cache.

- OAuth, when the Social Media Login feature is enabled and the oauth2Login element is configured.

- OIDC, when the Social Media Login feature is enabled and the oidcLogin element is configured.

- OIDC, when the OpenID Connect Client feature is enabled. The webAppSecurity:ssoCookieName must be explicitly set and match on all servers that share the authentication cache.

Subjects that are authenticated by unsupported mechanisms are stored in the local cache instead.
```

**Comment by dmuelle** [comment]
Hi @jvanhill - I've updated the draft with these changes.

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/authentication-cache.html#dist

**Comment by jvanhill** [comment]
Added the technical reviewed labels as there are some minor edits I pointed out (and sent to David), but we would be ok with it shipping the way it is. I am out for the next week, so I wanted to add it before I left due to the above.

**Comment by dmuelle** [comment]
All changes implemented in  #5920-#5923

**Comment by dmuelle** [comment]
@ramkumar-k-9286  can you provide peer review for the following 3 new topics?

- [Distributed caching with JCache](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/distributed-caching-jcache.html)
- [Authentication cache](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/authentication-cache.html)
- [Track logged-out SSO cookies](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/track-loggedout-sso.html)

**Comment by ramkumar-k-9286** [comment]
Peer Review - Distributed caching with JCache
---

With Open Liberty, you can use [JCache](https://github.com/jsr107/jsr107spec) **caches** in place of local in-memory caches for several features.
-->
With Open Liberty, you can use [JCache](https://github.com/jsr107/jsr107spec) instead of local in-memory caches for several features.

---
A unified `ClassLoader` instance that is constructed from all configured libraries in the `cachingProvider` element is used load the `CachingProvider` instance.
-->
A unified `ClassLoader` instance that is constructed from all configured libraries in the `cachingProvider` element is used **to** load the `CachingProvider` instance.

---
For more information, see [cachingProvider](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/config/cachingProvider.html).
-->
Link does not work

---
For more information, see [cacheManager](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/config/cacheManager.html).
-->
Link does not work

---
If no cache with the value of the name attribute exists for the specified javax.cache.CacheManager instance, Liberty attempts to create one. For more information, see [cache](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/config/cache.html).
-->
If no cache with the value of the name attribute exists for the specified javax.cache.CacheManager instance, **Open** Liberty attempts to create one. For more information, see [cache](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/config/cache.html).

---
For more information, see [cache](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/config/cache.html).
-->
Link does not work

---
Some providers and caching topologies require more complex configuration.
-->
Some providers and caching topologies require more complex **configurations**.

---
A `uri` attribute is also defined on the `cacheManager` element to pass in provider-specific configuration in the form of a provider-defined URI.
-->
A `uri` attribute is also defined on the `cacheManager` element to pass in **a** provider-specific configuration in the form of a provider-defined URI.

---

**Comment by ramkumar-k-9286** [comment]
Peer Review - Authentication cache
---

To improve server performance during single sign-on (SSO) authentication, Open Liberty provides an authentication cache to store a subject after **a** user authentication is successful. 
-->
To improve server performance during single sign-on (SSO) authentication, Open Liberty provides an authentication cache to store a subject after user authentication is successful. 

---
The [cacheManager](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/config/cacheManager.html) element references the library to configure the CachingProvider and CacheManager instances. The [cache](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/config/cache.html) element references the cacheManager element to configure the JCache instance.
-->
both links not working

---
This element also specifies maximum size and timeout values for the authentication cache that replicate the behavior of the local in-memory cache.
-->
This element also specifies **the** maximum size and timeout values for the authentication cache that replicate the behavior of the local in-memory cache.

---
Clearing the distributed cache by using any JCache provider utility does not clear contents of the in-memory cache on any of the Liberty servers.
-->
Clearing the distributed cache by using any JCache provider utility does not clear **the** contents of the in-memory cache on any of the Liberty servers.

---
For more information, see [Configuring Infinispan caches](https://infinispan.org/docs/stable/titles/configuring/configuring.html)in the Infinispan documentation.
-->
For more information, see [Configuring Infinispan caches](https://infinispan.org/docs/stable/titles/configuring/configuring.html) in the Infinispan documentation.

---

**Comment by ramkumar-k-9286** [comment]
Peer Review - Track logged-out SSO cookies
---

This configuration works only on the same server. The LTPA cookie is tracked only on the server where the user logged out. If that same unexpired LTPA cookie is presented to another server where the LTPA keys are shared, it is used until it is also logged-out on that server. To protect multiple servers that share SSO data or configuration, configure a distributed logged-out cookie cache.
-->
Logged out is mentioned in two ways here. I'm not sure if that is intensional. Should we use **logged out** ?

---
The goal is that no cookie is evicted before expiration of its valid lifetime.
-->
The goal is that no cookie is evicted before **the** expiration of its valid lifetime.

---
The following `hazelcast.xml` file example shows a Hazelcast logged-out cookie **cache cache** configuration.
-->
The following `hazelcast.xml` file example shows a Hazelcast logged-out cookie cache configuration.

---
    </timedexpiry-policy-factory> --> </timed-expiry-policy-factory>

---

**Comment by dmuelle** [comment]
Thanks for reviewing @ramkumar-k-9286 , all suggestions implemented except

## Distributed caching with JCache

Links to config elements will work once we get the new generated doc

> Some providers and caching topologies require more complex configurations.

spitting hairs, but i think this reads better as "configuration", as the singular implies the act of configuring, where as the plural implies discrete settings- both are correct but the emphasis is on the developers view, rather than the code details

---

## Authentication cache

> A uri attribute is also defined on the cacheManager element to pass in **a** provider-specific configuration in the form of a provider-defined URI.

similar to the previous, I think the "a" is correct but too specific, various aspects of config are implied by its absence.

## Logged out cookie cache

> Logged out is mentioned in two ways here. I'm not sure if that is intensional. Should we use logged out ?

I think the context is really the same, even though both "user" and "cookie" are mentioned

**Comment by dmuelle** [comment]
updates are on vNext and will publish with 22.0.0.11- closing this issue.
