### ISSUE TITLE
Reorder Dev section of the TOC

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#5721]
per comments from @gcharters and @lauracowen, to foreground the cloud native focus of the OL docs

current order:
[Jakarta EE overview](https://openliberty.io/docs/latest/jakarta-ee.html)
[MicroProfile overview](https://openliberty.io/docs/latest/microprofile.html)
[Cloud-native microservices](https://openliberty.io/docs/latest/cloud-native-microservices.html)

Proposed order:
[Cloud-native microservices](https://openliberty.io/docs/latest/cloud-native-microservices.html)
[MicroProfile overview](https://openliberty.io/docs/latest/microprofile.html)
[Jakarta EE overview](https://openliberty.io/docs/latest/jakarta-ee.html)

**Comment by lauracowen** [comment]
Other thoughts about the TOC that occur to me:

* In the RESTful Services twistie, I think REST clients should probably come before Sync/async.
* I wondered if the async input/output topic should be alongside the sync/async clients topic? But check that for technical accuracy before changing.
* The GraphQL and gRPC topics could go inside a twistie called something like "alternatives to REST". But I appreciate that would require a new topic writing so it's not urgent. Just a thought.
* The rough order of sections within that Dev category could maybe do with reflecting the ordering (to some degree) in the [deep dive tutorial](https://openliberty.io/guides/liberty-deep-dive.html) because that shows the relative importance of technical capabilities. For example, configuration earlier on. Then move some more "advanced" topics to later on in the list: Transaction recovery makes sense to stay with data persistence (I think) but could be towards the bottom;  fault tolerance too (it's quite advanced).
* In Operations, Thread pool tuning appears twice - the first instance doesn't need to be there (it's correct to be under Performance tuning).

Regarding the "differences between MP versions" topics and similar, is there a cut-off point when the older versions of those topics get removed from the latest versions of the docs? MP 2.2 and 2.1 seems really old now. I guess someone might be upgrading old apps - maybe ask Emily? The older versions of the docs will still be there anyway, so the topics will still exist but maybe just avoid collating masses of those topics as we go through time?

I did also think that those topics should probably be with the API reference docs rather than in the main toc. Though I know that would interfere with the generation process. But then we could have:

```
- Cloud-native microservices
- - MicroProfile overview
- - Jakarta EE overview
```
(rather than them being siblings in the toc) And we wouldn't be distracting people with migration-type information when they're just writing an app.

**Comment by dmuelle** [comment]
Additionally, we should look at the Security section- this came up in a convo with @jvanhill today- we probably already have too many top-level topics in security, with more on the way. I can see  opportunities to consolidate some of these

- [Authentication](https://openliberty.io/docs/latest/authentication.html)
- [Authorization](https://openliberty.io/docs/latest/authorization.html)
- [Single sign-on](https://openliberty.io/docs/latest/single-sign-on.html)
- [User registries](https://openliberty.io/docs/latest/user-registries-application-security.html)
- [Authentication filters](https://openliberty.io/docs/latest/authentication-filters.html)
- [Kerberos authentication](https://openliberty.io/docs/latest/kerberos-authentication.html)
- [Secure communication with TLS](https://openliberty.io/docs/latest/secure-communication-tls.html)
- [Automatic certificate management with ACME](https://openliberty.io/docs/latest/acme-cert-management.html)
- [Security hardening](https://openliberty.io/docs/latest/security-hardening.html)
- [Password encryption limitations](https://openliberty.io/docs/latest/password-encryption.html)
- [Audit logs](https://openliberty.io/docs/latest/audit-logs.html)
- [Configuring SPNEGO authentication](https://openliberty.io/docs/latest/configuring-spnego-authentication.html)
- [Configuring a custom user registry](https://openliberty.io/docs/latest/overview.html#configuring-user-registry.adoc)
- [Verifying release package signatures](https://openliberty.io/docs/latest/verifying-package-signatures.html)
- [Security vulnerability list](https://openliberty.io/docs/latest/security-vulnerabilities.html)
- [Troubleshooting security](https://openliberty.io/docs/latest/troubleshooting.html)

**Comment by dmuelle** [comment]
just spitballing...

- [Authentication](https://openliberty.io/docs/latest/authentication.html)
   - [Single sign-on](https://openliberty.io/docs/latest/single-sign-on.html)
   - [Authentication filters](https://openliberty.io/docs/latest/authentication-filters.html)
   - [User registries](https://openliberty.io/docs/latest/user-registries-application-security.html)
   - [Configuring a custom user registry](https://openliberty.io/docs/latest/overview.html#configuring-user-registry.adoc)
    - [Configuring SPNEGO authentication](https://openliberty.io/docs/latest/configuring-spnego-authentication.html)
   - [Kerberos authentication](https://openliberty.io/docs/latest/kerberos-authentication.html)
   - [Password encryption limitations](https://openliberty.io/docs/latest/password-encryption.html)
- [Authorization](https://openliberty.io/docs/latest/authorization.html)
- [Secure communication with TLS](https://openliberty.io/docs/latest/secure-communication-tls.html)
  - [Automatic certificate management with ACME](https://openliberty.io/docs/latest/acme-cert-management.html)
- [Security hardening](https://openliberty.io/docs/latest/security-hardening.html)
- [Audit logs](https://openliberty.io/docs/latest/audit-logs.html)
- [Verifying release package signatures](https://openliberty.io/docs/latest/verifying-package-signatures.html)
- [Security vulnerability list](https://openliberty.io/docs/latest/security-vulnerabilities.html)
- [Troubleshooting security](https://openliberty.io/docs/latest/troubleshooting.html)

hard to know what to do with the authn/authz split, wouldbe easier if they were one topic but it might be (or become) too massive

**Comment by dmuelle** [comment]
Hi @lauracowen  - I took a stab at reorganizing the TOC on draft. I think I got everything in your comment except for moving the sync/async topic into the REST section. I also reorganized the Security section similar to my previous comment except I haven't yet moved SSO under Authentication as there were some topics I felt should go under SSO and wasn't ready to commit to 3rd level nesting- yet. Let me know what you think

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/overview.html

**Comment by lauracowen** [comment]
I like that.

I like that you have the SSO topics together. I agree let's not try for 3 levels yet. Maybe move SSO up to between Authentication and Authorization?

The Jakarta EE entry appears twice (needs to be removed from the top of the Dev section).

I still like the idea of moving those "changes between vx and vy" topics to the Reference section (and just linking to them from the MP and JEE overview topics). They seem like you shouldn't have to care about them unless you know you need to. Is that possible, do you think? Maybe an entry between Features and Commands called "Feature changes between versions"? Or something?

**Comment by dmuelle** [comment]
per @tevans78 comment in #5754 - move the CDI topic out of the restful services section

**Comment by dmuelle** [comment]
@lauracowen 

> I still like the idea of moving those "changes between vx and vy" topics to the Reference section (and just linking to them from the MP and JEE overview topics). They seem like you shouldn't have to care about them unless you know you need to. Is that possible, do you think? Maybe an entry between Features and Commands called "Feature changes between versions"? Or something?

That sounds good to me but we should check w/ @NottyCode - IIRC I originally had these topics under a heading in the reference section and he requested to move them up to be with the overview topics


The basic changes from your original comment in this issue went in with 22.0.0.10, but I'm leaving it opn as I expect to reorder the Security section with the next release, as well as move CDI out of restful services (on draft now) and possibly move the Differences topics to reference.

**Comment by dmuelle** [comment]
updates for dev and security sections are on vNext and will publish with 22.0.0.11. Will continue discussion of whether to move differences topics as we prepare to publish a new one for EE 10 and in this epic for TOC improvements: #5929  
closing this issue.

**Comment by lauracowen** [comment]
I'm becoming more and more in favour of moving the Differences topics to Reference. But then adding a link to the bottom of each of the Jakarta EE and MicroProfile overview topics saying something like "Differences between versions of Jakarta EE [MicroProfile]", then the reader can go browse the changes if that's relevant to them.

**Comment by dmuelle** [comment]
What about nesting these topics in the sections for the respective APIs?

**Comment by dmuelle** [comment]
![Screen Shot 2022-10-26 at 11 28 05 AM](https://user-images.githubusercontent.com/48686014/198069243-a564194a-9e29-4d30-b7f8-5dd8085c615e.png)

**Comment by dmuelle** [comment]
I think it would make sense because most of the changes discussed in these pages have to do with the APIs themselves rather than our feature implementations. But I want to get consensus around where they should go because moving them means manually editing lots of links from the respective feature pages.

**Comment by lauracowen** [comment]
Put all the MP Differences topics in the MP API section together or dispersed according to which version they apply to? So Differences in MP 2.2 would go straight after (or nested beneath) MP 2.2? Or would you just have a number of Differences topics at the end of the MP API section?

**Comment by dmuelle** [comment]
I'm not sure :) 

On the one hand it would make sense to put them close to the version they apply to, on the other, there's also a value in having a clean list of the different API versions to browse through- in which case the Differences topics could go at the end of the list. Also, for context, any feature/API that is mentioned in the differences topics is linked to from the respective feature pages (ie Differences between Open API 3.1 and 3.0 is linked from both 3.1 and 3.0 pages). I expect (hope) that is how most will find this information, along with any links we add from the overview pages.

Part of the challenge is this is sort weird info to think about someone finding from the TOC, unless we foreground it a way that kind of over-emphasizes it

**Comment by lauracowen** [comment]
I think linking it from the relevant places is probably sufficient. That might include a links in the troubleshooting pages (and maybe actually listing specific errors that can occur from not having changed your API properties or whatever's changed).

I think I'm more in favour of the clean list at the end to browse through, rather than interspersing the Differences topics under each API version. Partly for easy browsing and partly because it doesn't distract from scanning down the list of version numbers.

**Comment by dmuelle** [comment]
Differences topics are moved to the reference section in https://github.com/OpenLiberty/docs/pull/6558

closing as completed
