### ISSUE TITLE
New doc to explain how to enable FIPS with Semeru Java 11

### ISSUE THREAD

**Issue by acdemyers** [OpenLiberty/docs#5728]
Semeru 11 recently come up with some instruction on who to run in FIPS mode.  Liberty needs to add a set of instruction on how to configure Liberty to run in Semeru 11 FIPS mode.   

Attached is the new document for configuring Liberty with Semeru 11 FIPS mode.

[Semeru.docx](https://github.com/OpenLiberty/docs/files/9549371/Semeru.docx)

**Comment by dmuelle** [comment]
also need to add a link to the new page from this WL IBM Docs page for info re Semeru 11 Fips

https://www.ibm.com/docs/en/was-liberty/nd?topic=liberty-setting-up-fips-compliance

**Comment by dmuelle** [comment]
Hi @acdemyers - the initial draft for this topic is now on the OL draft site:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/enable-fips.html

Would you review the draft and let me know if any changes are needed? If not, you can add the `Technical reviewed` label to this issue to sign off and the changes will publish with 22.0.0.10. Thanks!

**Comment by acdemyers** [comment]
@dmuelle The document looks good to me.

**Comment by dmuelle** [comment]
Hi @ramkumar-k-9286 - can you provide peer review?


https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/enable-fips.html

**Comment by ramkumar-k-9286** [comment]
Peer Review
---
Java 11 and 17 support for FIPS with Semeru Runtimes **is** available only on RHEL 8 on x86 platforms.
->
Java 11 and 17 support for FIPS with Semeru Runtimes **are** available only on RHEL 8 on x86 platforms.

---
Confirm that your **REHL** operating system is installed in FIPS mode.
->
Confirm that your **RHEL** operating system is installed in FIPS mode.

---
If your **REHL** operating system was not installed in FIPS mode, you must switch it to FIPS mode.
->
If your **RHEL** operating system was not installed in FIPS mode, you must switch it to FIPS mode.

---
For more information about how to enable or check the FIPS status for your RHEL operating system, see [Switching the system to FIPS mode](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/security_hardening/using-the-system-wide-cryptographic-policies_security-hardening?_ga=2.199036333.328645028.1662471426-119974336.1661806438#switching-the-system-to-fips-mode_using-the-system-wide-cryptographic-policies) in the **REHL** documentation.
->
For more information about how to enable or check the FIPS status for your RHEL operating system, see [Switching the system to FIPS mode](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/security_hardening/using-the-system-wide-cryptographic-policies_security-hardening?_ga=2.199036333.328645028.1662471426-119974336.1661806438#switching-the-system-to-fips-mode_using-the-system-wide-cryptographic-policies) in the **RHEL** documentation.

---
Noticed that you have used **FIPS-compliant** - in multiple places in the doc. Should the same logic not be used for FIPS certified - should it not be mentioned as **FIPS-certified** cryptography, **FIPS-certified** algorithms etc.?

---
Step 4 -> URL for the commands being displayed on the Draft Site page -> formatting issue.

**Question:** In FIPS mode, Semeru Runtimes does not support file-based keystores like JKS and PKCS#12.

Should keystores be mentioned like `JKS` and `PKCS#12`?

I ask this because -> in the next bullet it seems to be mentioned so - so a bit confused.

---
You can import trusted certificates in the same way, as shown in the following example, where `trust.p12` is the file that contains the certificate entries [Add Period]

---
In this example, `location=“/tmp/pkcs11cfg.cfg”` specifies the path to the Liberty configuration file that you created in the step 3.
->
In this example, `location=“/tmp/pkcs11cfg.cfg”` specifies the path to the Liberty configuration file that you created in ~the~ step 3.

---

**Comment by dmuelle** [comment]
Thanks for reviewing @ramkumar-k-9286 , all suggestions implemented except the following:

> Java 11 and 17 support for FIPS with Semeru Runtimes are available only on RHEL 8 on x86 platforms.

This is tricky because you have both Java 11 and 17, but "support" is technically singular. Your suggestion essentially results in "Support... are available", which I dont think is correct.

> Noticed that you have used FIPS-compliant - in multiple places in the doc. Should the same logic not be used for FIPS certified - should it not be mentioned as FIPS-certified cryptography, FIPS-certified algorithms etc.?

FIPS certifies certain kinds of cryptography and algorithms, applications and runtimes comply with FIPS by using those cryptography/algorithms, so i think its correct as is 

> Should keystores be mentioned like `JKS` and `PKCS#12...  - n the next bullet it seems to be mentioned so.

On this context, JKS and PCKS#12 are keystore types, not code entities. However `pk12util` is a CLI tool/command that the user enters, so it is monospace.

**Comment by dmuelle** [comment]
Changes are in vNext and will publish with 22.0.0.10- closing this issue
