### ISSUE TITLE
Document: Jakarta EE 10: Support Jakarta Expression Language 5.0

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/docs#5833]
**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**

https://github.com/OpenLiberty/open-liberty/issues/18730

**Comment by isaacrivriv** [comment]
# Expression Language 5.0 Changes
Full list of changes between Expression Language 4.0 and Expression Language 5.0 found [here](https://jakarta.ee/specifications/expression-language/5.0/jakarta-expression-language-spec-5.0.html#changes-between-5-0-and-4-0)
## Generics in API
- Added support for Generics throughout the API where appropriate. This removes the necessity of casting from `Object` to a specific object type in many API calls. 

## Type coercion
- Clarified and implemented support for coercing arrays. More can be read in the Expression Language 5.0 specification, section 1.23.7 [here](https://jakarta.ee/specifications/expression-language/5.0/jakarta-expression-language-spec-5.0.html#coerce-a-to-an-array-of-type-t).
- Added support for coercing Lambda Expressions to a functional interface method invocation. More can be read in the Expression Language 5.0 specification, section 1.23.8 [here](https://jakarta.ee/specifications/expression-language/5.0/jakarta-expression-language-spec-5.0.html#coerce-a-to-functional-interface-method-invocation).

## Expression Language Resolver
- [BeanELResolver](https://jakarta.ee/specifications/expression-language/5.0/apidocs/jakarta.el/jakarta/el/beanelresolver) was updated to also consider default method implementations when looking for property getters, property setters and methods.
- Changes to the documented behavior of the [StaticFieldELResolver](https://jakarta.ee/specifications/expression-language/5.0/apidocs/jakarta.el/jakarta/el/staticfieldelresolver) to explicitly document that `ELResolver.getType()` must return null if either the ELResolver or the resolved property is read-only.
- Since the ELResolver method `getFeatureDescriptors()` has been deprecated in Expression Language 5.0, new default implementation that returns `null` has been added. This is so custom ELResolver implementations do not need to implement the method.

## Method Annotation Access
- New [MethodReference](https://jakarta.ee/specifications/expression-language/5.0/apidocs/jakarta.el/jakarta/el/methodreference) class created to provide access to details of the method to which a `MethodExpression` resolves, including any annotations present on the method, has been added.

## Deprecations

- [ELResolver](https://jakarta.ee/specifications/expression-language/5.0/apidocs/jakarta.el/jakarta/el/elresolver) method [getFeatureDescriptors](https://jakarta.ee/specifications/expression-language/5.0/apidocs/jakarta.el/jakarta/el/elresolver#getFeatureDescriptors(jakarta.el.ELContext,java.lang.Object)) has been deprecated with removal planned for Expression Language 6.0.

## Removed APIs

- Remove the deprecated, mis-spelt method `MethodExpression.isParmetersProvided()` from the API

## Configuration

To use the Expression Language 5.0 feature, add expressionLanguage-5.0 to your server.xml:

```xml
   <featureManager>
       <feature> expressionLanguage-5.0</feature>
   </featureManager>
```

**Comment by dmuelle** [comment]
Hi @isaacrivriv - the draft for these updates is now available for review on the Differences between Jakarta EE 10.0 and 9.1 page:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#el

Let me know if any further edits are needed. If not, you can sign off by adding the Technical reviewed label to this issue and the doc will publish in the same release as EE 10. Thanks!

**Comment by isaacrivriv** [comment]
Looks good @dmuelle thanks for getting this done! Just two major comments we found.
- There's a double `from` in [Support for Java Generics
](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#_support_for_java_generics)
- In [Type coercion](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#_type_coercion) can we change that to **The 5.0 release implements support for [coercing Lambda Expressions to a functional interface method invocation](https://jakarta.ee/specifications/expression-language/5.0/jakarta-expression-language-spec-5.0.html#coerce-a-to-functional-interface-method-invocation) and clarified the specification for coercing arrays. However, Liberty's usage of Tomcat's API and implementation of the Expression Language specification have already followed the clarifications to the specification for [coercing arrays](https://jakarta.ee/specifications/expression-language/5.0/jakarta-expression-language-spec-5.0.html#coerce-a-to-an-array-of-type-t). Due to this, no functional changes for array coercion are added in Expression Language 5.0.**

**Comment by dmuelle** [comment]
Thanks for reviewing @isaacrivriv - I've added those changes

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#el

Had tweak the language in the Type Coercion section just a bit but I think I've preserved the meaning

**Comment by isaacrivriv** [comment]
Changes look good, thanks for working on this @dmuelle!

**Comment by dmuelle** [comment]
Hi @ramkumar-k-9286 this ready for peer review

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#el

**Comment by ramkumar-k-9286** [comment]
Peer Review
---
1. The [Jakarta Expression Language 5.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/expressionLanguage-5.0.html) feature adds support for Java Generics... The link is not working ( believe it will be fixed when associated pages are introduced).

2. Therefore, no functional changes for array coercion are added in Expression Language 5.0.
->
Therefore, no functional changes for array coercion are added in Expression Language 5.0 **feature**.

3. The [BeanELResolver class](https://jakarta.ee/specifications/expression-language/5.0/apidocs/jakarta.el/jakarta/el/beanelresolver) is updated to also consider default method implementations when it looks for property getters,
->
The [BeanELResolver](https://jakarta.ee/specifications/expression-language/5.0/apidocs/jakarta.el/jakarta/el/beanelresolver) **class** is updated to also consider default method implementations when it looks for property getters,
( This is to make it uniform across the paragraph.. other **class** mentions are not added in the links.

4. I did not find the following info mentioned (it is mentioned in the info to be added):
**Configuration**

To use the Expression Language 5.0 feature, add expressionLanguage-5.0 to your server.xml:
`   <featureManager>
<feature> expressionLanguage-5.0</feature>
</featureManager>
`

**Comment by dmuelle** [comment]
Thanks for reviewing @ramkumar-k-9286 

1. link will work after autogen update
2. fixed
3. fixed
4. I dont think we need to state how to enable the feature here, it's standard info unrelated to the differences between versions
