### ISSUE TITLE
Document: Jakarta EE 10: Support Jakarta WebSocket 2.1 (10/21/22 asked for info)

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/docs#5834]
**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**

https://github.com/OpenLiberty/open-liberty/issues/18745

**Comment by chirp1** [comment]
Left slack for Paul, included David, asking when Paul can provide the info to doc.

**Comment by volosied** [comment]
##  Websocket 2.1 Changes
### API Replacement for SPI WsWsocServerContainer#upgrade
- Developers may programmatically upgrade their HTTP requests to a websocket connection via the new API method: [jakarta.websocket.server.ServerContainer#upgradeHttpToWebSocket()](https://jakarta.ee/specifications/websocket/2.1/apidocs/server/jakarta/websocket/server/servercontainer#upgradeHttpToWebSocket(java.lang.Object,java.lang.Object,jakarta.websocket.server.ServerEndpointConfig,java.util.Map)). This means that [com.ibm.websphere.wsoc.WsWsocServerContainer](https://www.ibm.com/docs/en/was-liberty/nd?topic=SSAW57_liberty/com.ibm.websphere.javadoc.liberty.doc/com.ibm.websphere.appserver.api.wsoc_1.0-javadoc/com/ibm/websphere/wsoc/WsWsocServerContainer.htm) is now deprecated, with plans to remove it in the next websocket release. However, it will still be available in previous websocket features.
### Handling of User Properties
- New changes have occurred regarding [user properties](https://jakarta.ee/specifications/websocket/2.1/apidocs/server/jakarta/websocket/session#getUserProperties()). The server sessions' user properties are initially populated by ServerEndpointConfig.getUserProperties(), thus allowing endpoints to retrieve properties set in [ServerEndpointConfig.Configurator#modifyHandshake​](https://jakarta.ee/specifications/websocket/2.1/apidocs/server/jakarta/websocket/server/serverendpointconfig.configurator#modifyHandshake(jakarta.websocket.server.ServerEndpointConfig,jakarta.websocket.server.HandshakeRequest,jakarta.websocket.HandshakeResponse)). Similarly, client sessions' [user properties](https://jakarta.ee/specifications/websocket/2.1/apidocs/client/jakarta/websocket/session#getUserProperties()) are populated via [EndpointConfig.getUserProperties()](https://jakarta.ee/specifications/websocket/2.1/apidocs/client/jakarta/websocket/EndpointConfig.html#getUserProperties()). Note that these initial contents are shallow copies, meaning that ClientEndpointConfig#getUserProperties and ServerEndpointConfig#getUserProperties() are now per endpoint per websocket session. Properties are no longer global between all endpoint instances.
### Client SSL Configuration
- Client websocket applications may now set their SSLContext via [jakarta.websocket.ClientEndpointConfig.Builder#sslContext​](https://jakarta.ee/specifications/websocket/2.1/apidocs/client/jakarta/websocket/clientendpointconfig.builder#sslContext(javax.net.ssl.SSLContext)) , which Liberty will use to establish the wss connection to a server. Please note that this option overrides all of Liberty's SSL configurations and should be used with caution. It is recommended to enable SSL communication via the server.xml as described [here](https://www.ibm.com/docs/en/was-liberty/base?topic=liberty-enabling-ssl-communication-in). Additionally, SSL may be configured via the [wsocOutbound](https://openliberty.io/docs/latest/reference/config/wsocOutbound.html) attribute in the server.xml.
### Other Changes
- A getter has been added for the default platform configurator: [jakarta.websocket.server.ServerEndpointConfig.Configurator#getContainerDefaultConfigurator()](https://jakarta.ee/specifications/websocket/2.1/apidocs/server/jakarta/websocket/server/serverendpointconfig.configurator#getContainerDefaultConfigurator())
- The restriction that endpoints must be added during application deployment has been removed. With 2.1, new endpoints may now be added at any time.
- The method [jakarta.websocket.Session.getRequestURI()](https://jakarta.ee/specifications/websocket/2.1/apidocs/client/jakarta/websocket/session#getRequestURI()) returns the full URI String from the protocol to the query string, if present.
### Deprecations
- The SPI com.ibm.websphere.wsoc.WsWsocServerContainer is now deprecated. 
### Removed APIs
- None
### Configuration
- None

**Comment by volosied** [comment]
@dmuelle  I think this one is good to go.

**Comment by dmuelle** [comment]
Hi @volosied - I've added this info to the draft:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#socket

if any further changes are needed, just let me know. Otherwise, you can sing off by adding the `technical reviewed` label to this issue. Thanks!

**Comment by volosied** [comment]
@dmuelle  Only two comments

1) I would prefer not to use _instance_ in the wording here:  "which enables endpoints to retrieve properties that are set in a [ServerEndpointConfig.Configurator#modifyHandshake](https://jakarta.ee/specifications/websocket/2.1/apidocs/server/jakarta/websocket/server/serverendpointconfig.configurator#modifyHandshake(jakarta.websocket.server.ServerEndpointConfig,jakarta.websocket.server.HandshakeRequest,jakarta.websocket.HandshakeResponse)) instance​."   

Maybe some like: 

which enables endpoints to retrieve properties which could be set in a overridden [ServerEndpointConfig.Configurator#modifyHandshake](https://jakarta.ee/specifications/websocket/2.1/apidocs/server/jakarta/websocket/server/serverendpointconfig.configurator#modifyHandshake(jakarta.websocket.server.ServerEndpointConfig,jakarta.websocket.server.HandshakeRequest,jakarta.websocket.HandshakeResponse)) call for the incoming request. 


2) It would be good to include the https://www.ibm.com/docs/en/was-liberty/nd?topic=SSAW57_liberty/com.ibm.websphere.javadoc.liberty.doc/com.ibm.websphere.appserver.api.wsoc_1.0-javadoc/com/ibm/websphere/wsoc/WsWsocServerContainer.htm link the text.  I did not see it.

Otherwise, looks great. Thank!

**Comment by dmuelle** [comment]
@volosied - thanks for reviewing

1. I've updated the user properties section per your comment: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#_updates_for_for_handling_of_user_properties
2. Sorry,  I should have mentioned this- I omitted the link to the  Liberty javadoc because dev leads have asked us not to link from Open Liberty documentation to IBM Docs, including javadoc. It's a bit awkward I know but interested users can easily find the spi doc by google search.

if any further changes are needed, just let me know. Otherwise, you can sign off by adding the technical reviewed label to this issue. Thanks!

**Comment by dmuelle** [comment]
@ramkumar-k-9286 this is ready for peer review:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#socket

**Comment by ramkumar-k-9286** [comment]
Peer Review
---

Q: With regards to the second heading in topic:
( API Replacement for SPI WsWsocServerContainer#upgrade ) in the Issue
( API replacement for the WsWsocServerContainer#upgrade SPI ) in the doc - Does SPI need to be mentioned in the heading?

Heading : Updates for for handling of user properties
->
Updates **for the** handling of user properties

Also, you can configure SSL by setting the [wsocOutbound](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/config/wsocOutbound.html) attribute in the `server.xml` file.
->
Also, you can configure SSL by setting the [WAS WebSocket Outbound](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/config/wsocOutbound.html) attribute in the `server.xml` file.

Should we be mentioning the expanded name? (WAS WebSocket Outbound)
Also, is WAS WebSocket Outbound an attribute or a configuration?

A getter has been added for the default platform configurator:
->
Should we be mentioning **getter method / getter function**

**Comment by dmuelle** [comment]
Thanks for reviewing @ramkumar-k-9286 - all suggestions incorporated except I think the heading mentioned is OK as is
