### ISSUE TITLE
Document: Jakarta EE 10: Support Jakarta Batch 2.1

### ISSUE THREAD

**Issue by cgianfra** [OpenLiberty/docs#5844]
https://github.com/OpenLiberty/open-liberty/issues/18727

**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**

**Comment by chirp1** [comment]
Left Christopher a slack, included David as to when Christopher can provide us the info to doc.

**Comment by cgianfra** [comment]
**BatchProperty annotation**

The `@BatchProperty` annotation previously could only be used to inject a String value. This has been expanded to allow injection of the following additional types: Boolean, Short, Integer, Long, Float, and Double. Examples:
```
@Inject @BatchProperty(name="b1") Boolean b1;
@Inject @BatchProperty(name="s1") Short s1;
@Inject @BatchProperty(name="i1") Integer i1;
@Inject @BatchProperty(name="l1") Long l1;
@Inject @BatchProperty(name="f1") Float f1;
@Inject @BatchProperty(name="d1") Double d1;
```

**Default JobOperator injection**

Previously, the default JobOperator was only made available from a static factory method, `BatchRuntime.getJobOperator()`. Now, if there is an injection point for a JobOperator and no user-supplied implementation is found, the default JobOperator will be injected automatically. Example:
`@Inject JobOperator jobOperator;`

I tried searching for where this update should go, but couldn't find if there's a spot where we describe getting the default JobOperator from the runtime. Maybe I wasn't checking the right places.

**Comment by dmuelle** [comment]
Thanks @cgianfra - I added a section for these updates to the draft for the Differences between Jakarta EE10 and 9.1 page:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#batch

When you have a chance, would you review the updates to this section and let me know if any changes are needed? If not, you can add the `technical reviewed` label to this issue to sign off and the doc will publish when EE10 GAs.

Also, FYI we do not have much Batch documentation on Open Liberty at this time, though we do have [an issue to migrate some of the Batch info](https://github.com/OpenLiberty/docs/issues/4231) from WebSphere Liberty to Open Liberty. The issue has been iceboxed due to resources but we hope to pick it up again soon.

Thanks

**Comment by chirp1** [comment]
Info to doc received. Approving the epic at https://github.com/OpenLiberty/open-liberty/issues/18727 .

**Comment by dmuelle** [comment]
Hi @ramkumar-k-9286 this is ready for peer reivew:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#batch

**Comment by ramkumar-k-9286** [comment]
Peer Review
---

Suggestion:

The `@BatchProperty` annotation is expanded to allow injection of the following types: `Boolean`, `Short`, `Integer`, `Long`, `Float`, and `Double`. Previously, this annotation could inject only a `String` value. The following example demonstrates the newly added injection types.
->
The `@BatchProperty` annotation is enhanced to enable the injection of the following types: `Boolean`, `Short`, `Integer`, `Long`, `Float`, and `Double`. Previously, this annotation was limited to injecting only `String` values. The following example showcases the newly added injection types.

**Comment by dmuelle** [comment]
@ramkumar-k-9286 - thanks for reviewing. updated with a slightly different edit.
