### ISSUE TITLE
Server Features Overview page should use feature name

### ISSUE THREAD

**Issue by jvanhill** [OpenLiberty/docs#599]
The ref/feature page contains a table of superseded features at the bottom of the page that refers to ldapRegistry-3.0 feature as simply ldapRegistry. The table should use the full feature name so it is not confusing and is consistent since we use the full feature name for all the other features.

**Comment by lauracowen** [comment]
@Charlotte-Holt Do you know why this particular feature is referred to without its version number? Was that on purpose? Also, it is the only one that links to its feature doc - is that intentional too?

**Comment by Charlotte-Holt** [comment]
@lauracowen, I think this was just a mistake on my part. It actually links out to the wrong topic too. It currently links out to ldapRegistry in the config doc (https://openliberty.io/docs/ref/config/#ldapRegistry.html), rather than the feature doc (https://openliberty.io/docs/ref/feature/#ldapRegistry-3.0.html). Do you want me to go ahead and address this really quick today, or add it to the 19.0.0.10 milestone?

**Comment by lauracowen** [comment]
If it's a quick fix, go for it.

**Comment by Charlotte-Holt** [comment]
@jvanhill @lauracowen Updated at https://draft-openlibertyio.mybluemix.net/docs/ref/feature/. If this looks good, I'll merge it to `develop` tomorrow. Thanks!!

**Comment by lauracowen** [comment]
Looks good, thanks.

**Comment by Charlotte-Holt** [comment]
Live at https://openliberty.io/docs/ref/feature/. Closing this issue.
