### ISSUE TITLE
Add docs for Admin Center config validation feature

### ISSUE THREAD

**Issue by k8vance88** [OpenLiberty/docs#6228]
Epic: https://github.com/OpenLiberty/open-liberty/issues/18696

We need to add information to this doc: https://openliberty.io/docs/21.0.0.10/admin-center.html

Under the heading- Manage your server configuration with the Server Config tool, but after the current content, we need to add information on how to test connections to database resources.

Something like this:
Test connection to JDBC, JCA, JMS and Cloudant resources using the Server Config tool

You must have these features enabled on your server in addition to the Admin Center configruation:
```
           <feature>restConnector-2.0</feature>
           <feature>mpOpenApi-1.0</feature>
```
Navigate to the resource you wish to test the connection to. You should see a Test button:
![image](https://user-images.githubusercontent.com/29546393/217090523-f9746a6e-8826-4d92-989a-ac8b9a5c07af.png)

Click Test

Determine which authentication method you would like to use for the test connection: Container authentication, Application authentication or No resource reference.

![image](https://user-images.githubusercontent.com/29546393/217090753-aecc3d38-9018-498d-976d-34da84d4395c.png)

Fill in the required fields and click Connection Test.

The result of the test will be shown below the dialog.

The Admin Center uses REST apis to validate the connections. Provide them a link to the enabling backend docs: https://openliberty.io/docs/21.0.0.10/validating-server-connections.html

Likewise, you should add a link to this new  admin center doc on https://openliberty.io/docs/21.0.0.10/validating-server-connections.htm.

**Comment by dmuelle** [comment]
Thanks @k8vance88 - I have a couple questions when you have a chance

- does this config work with any version of the mpOpenapi feature? The example shows 1.0 but we are about to release 3.1. If it will work with any version, we can clarify that. 
- It also mentions restConnector-2.0 as a prereq- I'm wondering if this would also be a prereq for admin center in general. Our docs are not particularly clear on this, but they do say you have to configure management roles (`admin-role` or `reader-role`) to access admin center. I believe those roles depend on having the rest connector feature enabled (but I'm not certain).
- is connection testing available to both `reader-role` and `admin-role` or do you have to be an admin to test?

**Comment by aknguyen7** [comment]
- It should works,  depends on which version of mpOpenApi feature being use, for example if <feature>mpOpenApi-3.0</feature> then to enable connection factory it would use  <feature>connectors-2.0</feature> instead of <feature>jca-1.7</feature>, to enable JMS it would use <feature>messaging-3.0</feature> instead of <feature>jms-2.0</feature> for compatibility
- restConnector-2.0 is not prereq for admin center in general. It requires together with mpOpenApi feature to enable the test connection button (the last time i tested it). You can login with admin-role or reader-role without restConnector enabled
- admin-role is required to do test connection

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

Could you have a quick look at the draft edits before I send it across for review:

Content Added: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/admin-center.html

Link Added: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/validating-server-connections.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
Hi Ram- looks good, a few comments.

## Set up admin Center

I think we should restructure this section to use numbered steps. You can use the existing language but break into numbered steps, like

1. If the Admin Center feature is not already installed in your runtime, install it 
2. enable admin center feature
3. configure management role
4. specify HTTPS port and configure a keystore 

## Manage your server configuration with the Server Config tool

change this heading to: Manage and test your server configuration with the Server Config tool

You can use the Server Config tool to view and edit Open Liberty server configuration files. To edit configuration files, you must be in the `administrator-role` management role.
---->
You can use the Server Config tool to view and edit Open Liberty server configuration files and to test server connections to different resources. To edit configuration files or test connections, you must be in the `administrator-role` management role.

- Add a heading before the new content "Test server connections to resources with the Server Config tool
- spell out abbreviations on first mention

Since the remainder of the information is in sequential steps, I recommend using numbered steps, roughly outlined

1. enable extra features
5. Select the resource
6. click test
7. choose auth method
8. specify the required fields
9. click connection test

The following features must be enabled on your server in addition to the Admin Center configuration.
--->
To test connections with the Server Config tool, you must enable the feature: restConnector[display=Admin REST Connector] and feature:mpOpenAPI[display=MicroProfile OpenAPI] features in your server.xml file, in addition to the Admin Center feature, as shown in the following example.

```xml
   <featureManager>
      <feature>adminCenter-1.0</feature>
      <feature>restConnector-2.0</feature>
      <feature>mpOpenApi-3.0</feature>
   </featureManager>
```

I'd recommend using a new version of mpOpenApi in the example, like 3.0.


In the Server Config tool, navigate to the resource for which you want to verify the connection. A Test button is present and visible to you.
--->
In the Server Config tool, select the resource for which you want to verify the connection from the **Server** menu in the **Design** tab. 

- Click test---> In the display window for your chosen resource, click the **Test** button


## Validating server connections

I would move the link to be after the table in the introduction. Something like

You can also use Server Config tool in the Liberty Admin Center to test connections to JDBC, JCA, JMS, and Cloudant resources. For more information, see [Manage Open Liberty with Admin Center](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/admin-center.html).

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

Made the corrections. 
Did some rework. Still not able to fix the numbering issue. 

Content Added: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/admin-center.html

Link Added: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/validating-server-connections.html

Regards,
Ramkumar

**Comment by k8vance88** [comment]
@ramkumar-k-9286 I noticed that 1 was duplicated in the numbered list.

**Comment by ramkumar-k-9286** [comment]
> @ramkumar-k-9286 I noticed that 1 was duplicated in the numbered list.

Yes, Katie. I noticed that issue. Clarified this with my team lead and will make the correction and share the doc.

Regards,
Ramkumar

**Comment by ramkumar-k-9286** [comment]
Hi Katie @k8vance88 

Made the corrections.

Content Added: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/admin-center.html

Link Added: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/validating-server-connections.html

Regards,
Ramkumar

CC: David @dmuelle

**Comment by dmuelle** [comment]
Hi Ram- a couple things

- in step 1. there's a syntatx error in the feature macro for the REST connector feature. Also `server.xml` should be in monospace.
- I think we should add a little more detail to that step

To test connections with the Server Config tool, you must enable the feature: restConnector[display=Admin REST Connector] and [MicroProfile OpenAPI](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/mpOpenAPI.html) features in your server.xml file, in addition to the Admin Center feature. You must also enable any features to support the server resource that your are checking the connection to. Then following example also enables the JDBC feature to support a database connection.

then add more detail to the feature code block

```xml
<featureManager>
   <feature>adminCenter-1.0</feature>
   <feature>restConnector-2.0</feature>
   <feature>mpOpenApi-3.0</feature>
   <feature>jdbc-4.3</feature>
   ...
</featureManager>
```
- add descriptive alt text to the two images in this section. See other images specified in this topic for example syntax. Also, add descriptive statements before each image, similar to those elsewhere in the topic.

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

Made the Suggested corrections.

Content Added: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/admin-center.html

Link Added: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/validating-server-connections.html

Regards,
Ramkumar

CC: David @dmuelle

**Comment by dmuelle** [comment]
the current step 2 should be 2 steps

2. After you access the Design tab in the Server Config tool, select a resource in the configuration to see the enabled features and parameter settings. Click the Test button.

--->

2. In the Server Config tool, select the resource for which you want to test the connection from the Server menu in the Design tab.

3.  In the display window for your chosen resource, click the Test button


Also I dont find a link back to this topic from https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/validating-server-connections.html

There should be a link in the introduction of that topic to this new section, saying you can also use admin center to test connections to resources

**Comment by dmuelle** [comment]
Ok sorry- found the link back to this topic from server connections- please disregard my last comment

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Made the Suggested corrections.

Content Added: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/admin-center.html

Link Added: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/validating-server-connections.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
LGTM, thanks
