### ISSUE TITLE
Example config for transportSecurity (and ssl?) feature(s) (MSSEC06)

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#631]
Update https://www.openliberty.io/docs/ref/feature/#transportSecurity-1.0.html (and maybe https://www.openliberty.io/docs/ref/config/#ssl.html) with config examples in https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_ssl.html and in https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_sec_create_certificate.html
and in https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_sec_ssl_endpoint.html and from https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_sec_keystores.html

Also
https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_config_ssl_outbound.html
and
https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_ssl_outbound_filter.html

Also:
https://github.ibm.com/was-liberty/liberty-docs/issues/1643

**Comment by lauracowen** [comment]
@acdemyers In case you weren't aware, I created this issue a while back. However, there are so many potential examples here that we need to be really selective (down to the maybe 2-3 most important ones ideally).

@NottyCode Here's the issue I mentioned - can you take a look and see what you think before @acdemyers spends much time looking at it, pls?

**Comment by dmuelle** [comment]
draft at: https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#transportSecurity-1.0.html

SME reviewed by @acdemyers

**Comment by lauracowen** [comment]
Some minor points and a slightly bigger one at the end:
- Multiple TLS... section:
  - Should there be a blank line after the `sslDefault` line? I generally prefer to keep these examples shorter but in this case there's a blank line between the two `ssl` stanzas (which maybe isn't needed?) which draws the eye away from the most important part of this example, which is the first line.
- Java virtual machine... section:
  - header...the "Default" should be lower-case?
- Outbound... section:
  - Could you break the long lines (esp the `keyStore` stanzas) up a bit so the lines line up a bit more?
  - Is is possible to simplify this example at all? It's quite busy and not easy to tease apart what's being demonstrated. Is having three sets of settings necessary to make the point that you can have different outbound TLS configs?

If you can address those things, I think this is fine to go. Thanks

**Comment by dmuelle** [comment]
- Can you replace this "minimal example" with the one currently in the concept topic (see my comments in #1096). Keep the minimum config to as simple as possible. **done. Brought in default password info from TLS topic**
- Multiple TLS... section:
  - Should there be a blank line after the `sslDefault` line? **put a space in after first line to make consistent stanzas**
- Java virtual machine... section:
  - header...the "Default" should be lower-case? **fixed**
- Outbound... section:
  - Could you break the long lines (esp the `keyStore` stanzas) up a bit so the lines line up a bit more? **revised**
  - Is is possible to simplify this example at all? It's quite busy and not easy to tease apart what's being demonstrated. Is having three sets of settings necessary to make the point that you can have different outbound TLS configs? **simplified to 2 settings- this example is still long because of the keystore/trustore configs but I think they're relevant bcse you wouldn't set up a connection like this without specifying them and we don't have examples elsewhere**

**Comment by lauracowen** [comment]
I got a bit confused reading the first two sections:
- the keystore element should have capital ‘S’?
- In the Default… section, it’s a bit confusing - it talks about “a single keystore element called defaultKeyStore” - should keyStore be highlighted in that sentence? Also, is defaultKeyStore the value of the id attribute, not what the keystore element is called?
- Is the Default… section referring back to the example in the Basic… section? Should they be a single section, maybe shortened a bit?

Aside from that, the rest looks fine, thanks

**Comment by dmuelle** [comment]
Hi @lauracowen - I've reorganized this draft per our slack convo about combining the first two sections.

https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#transportSecurity-1.0.html

**Comment by lauracowen** [comment]
Yep - that makes more sense to me. Is it worth Alaine taking a quick look to make sure it makes sense technically?
Topic looks fine by me though. Thanks

**Comment by dmuelle** [comment]
I reached out to Alaine to review the update- if she approves, I'll move this to `ready to publish` and make a PR to dev

**Comment by dmuelle** [comment]
Alaine approved examples via Slack

**Comment by acdemyers** [comment]
Developer reviewed by Alaine DeMyers

**Comment by Charlotte-Holt** [comment]
@dmuelle This looks good! Just a few minor things:

- In, "If no `keystore` element exists for the `defaultKeyStore` file, this password is used to create a keystore file.", should `keystore` element be "`keyStore` element"
- In, "You can designate a different ssl element in the configuration as the default...", should "ssl" be in backticks? 
- In the heading, "Java virtual machine (JVM) default truststore configuration", I think "virtual" and "machine" should be capitalized
- Maybe use a colon after, " All other outbound TLS connections use the outbound default TLS configuration that is specified by the outboundSSLRef attribute called outboundSSLSettings." to lead into the example that follows?

**Comment by dmuelle** [comment]
Thanks @Charlotte-Holt, addressed your comments in a new revision

- In, "If no `keystore` element exists for the `defaultKeyStore` file, this password is used to create a keystore file.", should `keystore` element be "`keyStore` element" **fixed**
- In, "You can designate a different ssl element in the configuration as the default...", should "ssl" be in backticks? **Fixed**
- In the heading, "Java virtual machine (JVM) default truststore configuration", I think "virtual" and "machine" should be capitalized **Fixed**
- Maybe use a colon after, " All other outbound TLS connections use the outbound default TLS configuration that is specified by the outboundSSLRef attribute called outboundSSLSettings." to lead into the example that follows? **Fixed**

**Comment by dmuelle** [comment]
New URL: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/reference/feature/transportSecurity-1.0.html

**Comment by dmuelle** [comment]
Hi @acdemyers @brutif - I picked up the example you created for #2029 "Provide certificates from an environment variable or a file" and added to draft. We have recently changed our repo structure and that PR was aimed at a branch that is no longer active.

Here's the draft of the example: [Provide certificates from an environment variable or a file](https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/reference/feature/transportSecurity-1.0.html#_provide_certificates_from_an_environment_variable_or_a_file)

I made minor edits per IBM style- can one of you review the draft and let me know if it looks ok?

**Comment by brutif** [comment]
@dmuelle looks good, thanks! Might want to mention PEM format as that's widely understood, perhaps 
The environmental variable must reference either a certificate in the base 64-bit format (PEM format)...

**Comment by dmuelle** [comment]
@brutif thanks for reviewing- so in this sentence

`The environmental variable must reference either a certificate in the base 64-bit format (PEM format) or the path to a file that contains a base 64-bit encode or DER encoded certificate.`

do `the base 64-bit format` and `a base 64-bit encode` mean the same thing? If so, I'd like to use the same term in both cases

**Comment by dmuelle** [comment]
Updated per Bruce's suggestion

**Comment by dmuelle** [comment]
new URL: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/reference/feature/transportSecurity-1.0.html

**Comment by dmuelle** [comment]
Edits

- When the `defaultKeyStore` element is specified in the configuration, Open Liberty builds a TLS configuration around it with an ID attribute value of `defaultSSLConfig`--> When the `defaultKeyStore` value is specified, Open Liberty builds a TLS configuration around it with an ID attribute value of `defaultSSLConfig`. DQTI Ch6 Clarity

- Provide certificates from an environment variable or a file --> Configuration to provide certificates from an environment variable or a file
DQTI ch8 Syle: Make elements parallel

**Comment by dmuelle** [comment]
comments from @utle in #2764 

1) Minor comments - We should consistent whether to have a space at the end of an element `/>` through the doc.  Also, whether to have one line of the attributes unless it does not fix in one line. Here are examples:

`<sslDefault sslRef="customSSLConfiguration"/>
`

```
<ssl id="myDefaultSSLConfig"
      keyStoreRef="defaultKeyStore"
      trustStoreRef="defaultTrustStore"
      trustDefaultCert="true" />
```
2)  Change from
```
<ssl id="outboundSSLSettings"
      keyStoreRef="outboundKeyStore"
      trustStoreRef="outboundTrustStore" >
</ssl>
```
To:
```
<ssl id="outboundSSLSettings"
      keyStoreRef="outboundKeyStore"
      trustStoreRef="outboundTrustStore" />

```
3) The new example should start with a new paragraph to make it's clearer:
From:
` Any value that does not start with the -----BEGIN CERTIFICATE----- tag is treated like a file. In the following example, an environment variable supplies certificates from a file that is called certs.crt:`
To:

```
Any value that does not start with the -----BEGIN CERTIFICATE----- tag is treated like a file.
 
In the following example, an environment variable supplies certificates from a file that is called certs.crt:

```
4) Most of customer will use the certs.crt file, so I think we should have the second sample list first.

5) https://draft-openlibertyio.mybluemix.net/docs/20.0.0.10/reference/config/ssl.html
Need to pick up the latest metatype.properties.

**Comment by dmuelle** [comment]
@utle thanks for reviewing. I made the following changes to [the draft](https://draft-openlibertyio.mybluemix.net/docs/20.0.0.10/reference/feature/transportSecurity-1.0.html) based on your review

- removed spaces from closing tags, put closing tag on same line wherever possible
- switched order of certificate examples and updated explanation per recommendation 

When were the metatype.proerties updated for `ssl`? We should be up to date, I can investigate if content is missing

**Comment by chirp1** [comment]
@dmuelle Hi David,
Here are my comments:
- For "...declaration into your server.xml file,...", Change "into" to "in".
- Spell out TLS on first occurrence. 
- I see an inconsistency with "to enable TLS" in  "The following example shows the minimum configuration to enable TLS: ". Earlier you say "...transportSecurity-1.0 feature is enabled and a keystore is configured. ". I think that the second phrase is more accurate and that "to enable TLS" isn't quite right. Reword the sentence.
- For "certified name (CN) ", check whether "certified name" is correct. I haven't seen it used before as the meaning for CN.
- For the hostname, you might give an example, such as www.example.com. 
- The element in "attribute on the defaultSSLContfig element, as " doesn't seem to be the element used in the example that follows this text. 
-For "see SSL Repertoire. ", you might also want to include a link to https://draft-openlibertyio.mybluemix.net/docs/20.0.0.10/reference/config/sslDefault.html since this link goes with your sslDefault example. 
- Is "trustDefaultCert" the correct spelling? I cannot find it in KC, but can find a slightly different attribute.
- Add a noun after defaultSSLConfig .

**Comment by dmuelle** [comment]
@chirp1 thanks for reviewing. I made the following changes per your review:

- [ ] For "...declaration into your server.xml file,...", Change "into" to "in".  **This sentence is part of the autogen and is the same for all Open Liberty features. If necessary, I can open a doc bug on the Open Liberty websote repo to update the autogen**

- [x] Spell out TLS on first occurrence.

- [x]  inconsistency with "to enable TLS" in "The following example shows the minimum configuration to enable TLS: " **wasn't sure exactly what was missing here but I updated the sentence to clarify that the config shown specifies a keystore:**
`To enable TLS connections, you must enable the Transport Security feature and add the keyStore element to your server.xml file. The following example shows the minimum configuration to specify a keystore:` 

- [x] For "certified name (CN) ", check whether "certified name" is correct. **it wasn't! Updated to "common name"**

- [x] For the hostname, you might give an example, such as www.example.com.

- [ ] The element in "attribute on the defaultSSLContfig element, as " doesn't seem to be the element used in the example that follows this text. **think there may have been a typo here, not sure what the problem was but I don't see an issue with this sentence, which reflects what is in the example:**
`You can designate a different ssl element in the configuration as the default SSL configuration by specifying the sslRef attribute on the sslDefault element, as shown in the following example:`

- [x] Is "trustDefaultCert" the correct spelling? **it wasn't, corrected to `trustDefaultCerts` in all instances**

- [x] Add a noun after defaultSSLConfig

https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/reference/feature/transportSecurity-1.0.html

**Comment by chirp1** [comment]
@dmuelle Hi David,
Just one thing to fix. The rest are comments OK'ing what you did or your findings.
- OK. No further updated on your response for: For "...declaration into your server.xml file,...", Change "into" to "in". This sentence is part of the autogen and is the same for all Open Liberty features. If necessary, I can open a doc bug on the Open Liberty websote repo to update the autogen
- Your updates looks good. What I was getting at is that one sentence said "To enable the Transport Security 1.0 feature, add the following element declaration into your server.xml file" but another said "The following example shows the minimum configuration to enable TLS: ". The point is that to enable to TLS, one seems to just need to enable the Transport Security 1.0 feature as mentioned in the first sentence. However, the second sentence indicates that to enable transport security, that you one must also specify the keystore to enable TLS, which seems wrong. You fixed the problem by changing the wording to "The following example shows the minimum configuration to specify a keystore:". Thanks! No further update needed.
- For "The element in "attribute on the defaultSSLContfig element, ...." I agree .I don't see the problem either. No further update is needed.

- For  defaultSSLConfig- a little tweak - instead of "the defaultSSLConfig ID attribute value.", how about  "the defaultSSLConfig value." or the "the defaultSSLConfig value on the ID attribute.".

**Comment by dmuelle** [comment]
@chirp1 - made that last change and rebuilt

https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/reference/feature/transportSecurity-1.0.html

- [x] For defaultSSLConfig- a little tweak - instead of "the defaultSSLConfig ID attribute value.", how about "the defaultSSLConfig value." or the "the defaultSSLConfig value on the ID attribute.".

**Comment by chirp1** [comment]
@dmuelle Update looks good. Moving to "Ready to Publish".

**Comment by dmuelle** [comment]
moved to `vNext` to publish with 20.0.0.11. Closing this issue.
