### ISSUE TITLE
Add section for Signature Verification for the container images

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/docs#6469]
Update https://openliberty.io/docs/latest/container-images.html to include steps for doing signature verification of the images.

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

Please find the draft link for the doc here:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/authenticate-images-for-open-liberty-operator.html

Please review the same. There are some references to WL in the examples. Will need your help to fix those.

Regards,
Ramkumar.

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Please find the draft link for the doc here:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/verify-images-for-open-liberty-operator.html

Please review the same.

Regards,
Ramkumar.

**Comment by dmuelle** [comment]
## Initial peer review

> Verify the downloaded images and ensure that the images are created by using the image signatures and uploaded by Open Liberty.

this seems wordy and awkward, maybe use the language from the Container image topic:

> You can use the Open Liberty public key to check the signature, verify that the image was created by Open Liberty, and that it was not modified since its release.

---

> To verify the signatures, it is necessary that the machine has the following command-line tools installed.
--->

> Before you can verify image signatures, you must install the following tools:

also, provide links for both tools.

---

- I'm going to wait to suggest anything about the public key as I think we might not end up putting it directly in the doc.

---
> Import the Open Liberty public key on the machine that you prepared in the prerequisites section.
--->
>  Run the following command to Import the Open Liberty public key file to GPG:

---


> Calculate the fingerprint.
--->
Run the following command to calculate the fingerprint:

--- 
- Clean up step 3 so it doesn't use parentheses- that info is redundant anyway with the examples. Also, use complete sentences to introduce each example and describe what the command is doing. Same for step 5.
- put the results under a "Results" heading

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

I've made the suggested corrections in the document:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/verify-images-for-open-liberty-operator.html

Please review the same.

Regards,
Ramkumar.

**Comment by dmuelle** [comment]
> Replace <image_name> with the name of the image you want to pull, and <image_directory> with the name of the directory you just created.

the example doesn't use `<image_name>` or `<image_directory>` ? - **Sorry - forgot to remove those mentions - when I reworked on the section and removed the example**

- This command will pull the... ---> This command pulls the - **Done**

- I dont understand what the example in step 4 is showing- there's no command. Theyre just different example packages with no context. Check with SME as to whether we even need this step. It doesnt seem to show anything and could just be added to the end of the previous step with no additional codeblock - **Will Check with SME**

-  verify the image using --->  verify the image by using - **Done**

> The <image_directory> refers to the location of the copied image, and <x> should be set to 1 for the open-liberty-operator-bundle and open-liberty-operator-catalog images, or 2 for the open-liberty-operator image. For example:

--->

The <image_directory> refers to the location of the copied image. Replace <x> with `1` for the open-liberty-operator-bundle and open-liberty-operator-catalog images, or `2` for the open-liberty-operator image. For example: - **Done**

need to check those 1 and 2 values with SME. - **Will check with SME**

**Comment by ramkumar-k-9286** [comment]
Hi David,

Incorporated the comments. Will share it with SME as suggested.

Draft Link : https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/verify-images-for-open-liberty-operator.html

Regards,
Ramkumar

**Comment by ramkumar-k-9286** [comment]
@mbroz2 

Hi Michal

Draft document for signature verification for container images:

Draft Link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/verify-images-for-open-liberty-operator.html

Could you suggest an SME who could review this topic for us and also clarify certain doubts?

**Clarifications Needed:**

1. Step 4 shows a few examples. can these be integrated with the previous step so that we can avoid an additional code block? ( The step talks about repeating the previous step to verify all images - with an example)

2. Step 5 - We specify replacing `<x>` with `1` for the `open-liberty-operator-bundle` and `open-liberty-operator-catalog` images, or `2` for the `open-liberty-operator` image. would need clarification if these values are correct ?


Regards,
Ramkumar



**Chat response from Michal**

Michal Broz  [14 hours ago](https://ibm-cloud.slack.com/archives/D02MT9VR4JV/p1681924104515119?thread_ts=1681838362.433109&cid=D02MT9VR4JV)
I'll take a look when I can, but in the meantime, you could try 
[@leojc](https://ibm-cloud.slack.com/team/W4WQML8VB)

**Comment by ramkumar-k-9286** [comment]
Hi Leo @leochr 

Could you review the following document?

Draft Link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/verify-images-for-open-liberty-operator.html

**Clarifications Needed:**

Step 4 shows a few examples. can these be integrated with the previous step so that we can avoid an additional code block? ( The step talks about repeating the previous step to verify all images - with an example)

Step 5 - We specify replacing `<x>` with `1` for the `open-liberty-operator-bundle` and `open-liberty-operator-catalog` images, or `2` for the `open-liberty-operator` image. would need clarification if these values are correct?

Regards,
Ramkumar

**Comment by leochr** [comment]
@ramkumar-k-9286 Although it'll be good to point to this page from Open Liberty Operator on how its images can be validated (or even have a separate page for Operator), I think we should use Liberty container image(s) instead as the example. Suggest these:
icr.io/appcafe/open-liberty:kernel-slim-java17-openj9-ubi
icr.io/appcafe/open-liberty:full-java17-openj9-ubi

**Comment by ramkumar-k-9286** [comment]
Hi Leo @leochr 

Made corrections to the document:

**Draft Link:** https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/verify-signatures-for-container-images-in-open-liberty.html

Leo, would need your help with the following:

1. Can you please test the procedure to verify if it works correctly?

2. We have removed the hard copy of the public key and replaced it with a dhe link. Is that correct? Is it necessary to provide a hard copy of the public key on this page?

3. Could you also verify the public key to confirm it is correct?

4. Could you verify Step 5 in the doc, it has information regarding operators which may not be appropriate information in this document.

Regards,
Ramkumar

**Comment by leochr** [comment]
@ramkumar-k-9286 the signing process for Liberty containers and Operators changed, hence I am not entirely sure that the process documented ([here](https://www.ibm.com/docs/en/was-liberty/base?topic=operator-verifying-code-signed-images) for WebSphere Liberty Operator) would work with new images. I opened [here](https://github.com/WASdev/websphere-liberty-operator/issues/473) to follow-up. Since this draft is based on the WLO doc, it likely need to change accordingly

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

Made changes based on the WL document.

Draft link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/verify-signatures-for-container-images-in-open-liberty.html

Please review and suggest corrections.

Regards,
Ramkumar

**Comment by dmuelle** [comment]
## Peer review

Run the following command to Import...
-->
Run the following command to import

----

To create a directory for an each image and pull the image into local storage using Skopeo, follow these steps:
--->
Create a directory for the image and pull it into local storage by using Skopeo.

----

Create a directory with a name of your choice for the image. For example:
--->
Create a directory for the image with a name of your choice, as shown in the following example: 

----

Use Skopeo to copy the container image to the newly created directory. For example.
--->
Use Skopeo to copy the container image to the newly created directory, as shown in the following example:

----

This command pulls the icr.io/appcafe/open-liberty:kernel-slim-java17-openj9-ubi image and store it in the OpenLiberty-image directory.
--->
This command pulls the `icr.io/appcafe/open-liberty:kernel-slim-java17-openj9-ubi` image and stores it in the `OpenLiberty-image` directory. Replace these values with the image that you want to verify. This command also copies the signature file that you use to verify the image.

---

I'd say delete step 4- it's obvious and also probably unlikely users will be verifying multiple images.

---

Also, delete the first example in step 5 and just use the second, providing a brief explanation after the example.

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Review comments incorporated.

Draft link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/verify-signatures-for-container-images-in-open-liberty.html

Please review.

Regards,
Ramkumar

**Comment by dmuelle** [comment]
@ramkumar-k-9286 looks good to me except need to remove the last sentence;

`The use of 1 in the signature file indicates open-liberty-operator-bundle and open-liberty-operator-catalog images. The use of 2 would indicate open-liberty-operator image.`

There's only one image in the topic and as far as I know `signature-1` is the only viable option- though we'll confirm that in technical review

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Suggested comment incorporated.

Draft link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/verify-signatures-for-container-images-in-open-liberty.html

Please review.

Regards,
Ramkumar

**Comment by dmuelle** [comment]
This sentence doesn't apply to open liberty container images and should be removed:

> The use of 1 in the signature file indicates open-liberty-operator-bundle and open-liberty-operator-catalog images.

I'm not sure we need to explain what `1` means since there are no other options. We'll need to confirm in testing/ tech review that all the files and file path values are correct.

**Comment by ramkumar-k-9286** [comment]
Hi @leochr @mbroz2 

Draft link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/verify-signatures-for-container-images-in-open-liberty.html

Updates made based on the WL doc. 

We would need somebody to test out these steps. Please suggest who we should be contacting for the same.

Regards,
Ramkumar

**Comment by leochr** [comment]
@ramkumar-k-9286 The doc looks fine. 

@idlewis  could you please try the instructions and validate them when you get a chance? Thank you

**Comment by idlewis** [comment]
@ramkumar-k-9286 @leochr 

I noticed 3 issues:

1. Why do we need the 'sudo' part of this command? It seemed to work just fine without it for me, and I don't think we should be suggesting people to use sudo unless there is a good reason for it:
```sudo gpg2 --import ol.gpg```

2. Should the fingerprint be generated from the signature? There are very similar instructions for verifying AppConnect signatures here:
https://www.ibm.com/docs/en/app-connect/containers_cd?topic=container-verifying-image-signatures#taskcertc_cont_verifyingimagesignatures__steps__1
and in step 2, they suggest "Calculate the fingerprint" and give a command to do so.

3. I got an error when I ran the verify command:
```FATA[0000] Error verifying signature: Docker reference icr.io/appcafe/open-liberty:kernel-slim-java17-openj9-ubi-amd64 does not match icr.io/appcafe/open-liberty:kernel-slim-java17-openj9-ubi```
I fixed this by using the following for the copy and verify commands:
```
skopeo copy docker://icr.io/appcafe/open-liberty:kernel-slim-java17-openj9-ubi-amd64 dir:./OpenLiberty-image
skopeo standalone-verify ./OpenLiberty-image/manifest.json icr.io/appcafe/open-liberty:kernel-slim-java17-openj9-ubi-amd64  ${fingerprint} ./OpenLiberty-image/signature-1

**Comment by leochr** [comment]
@idlewis Thanks for trying it out quickly

@mcurran-us could you please take a look at Iain's comments? thank you

**Comment by mcurran-us** [comment]
1.  You can remove the sudo from `sudo gpg2 --import ol.gpg`.  Some documentation I've seen has it and some don't.
2. We use to generate the fingerprint from the signature, but the way they initially generated the pgp keys there is no way if the customer has imported multiple keys from IBM into the GPG keystone to tell them which one to use because they all say `[unknown] International Business Machines Corporation <psirt@us.ibm.com>`. See slack conversations [here](https://ibm-cloud.slack.com/archives/C03JYECNF60/p1682628163411999).
3. For the skopeo commands, the user will need to specify the specific image name for their platform, not the fat manifest.

**Comment by ramkumar-k-9286** [comment]
@dmuelle 

Hi David.

Made the DEV suggested corrections.

Draft link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/verify-signatures-for-container-images-in-open-liberty.html

However, I have some doubts that need to be clarified.

Regards,
Ramkumar

**Comment by dmuelle** [comment]
I think the text looks good from an ID perspective but we still need to re-test the updated steps to make sure they work as written- particularly w/r/t the error @idlewis hit with the verify command. It looks like this is sorted now but I'm not sure.

> For the skopeo commands, the user will need to specify the specific image name for their platform, not the fat manifest.

@idlewis @mcurran-us is this fixed in the updated draft- i think the examples use the same image name consistently now but I'm unsure if we need to clarify it further in the text. Would someone test the updated steps as written to be sure Ram's edits fixed the problems from the last run?

**Comment by idlewis** [comment]
Has there been a misunderstanding with step 1? The new draft has completely removed the `gpg` command. I thought the suggestion was just to change the command, by removing `sudo` at the beginning of it?

**Comment by idlewis** [comment]
I'm happy that steps 3 and 4 now work fine for me on my amd64 test machine and that the instructions are clear as they are written. I don't have another platform to test on.

**Comment by dmuelle** [comment]
@ramkumar-k-9286 

> Has there been a misunderstanding with step 1? The new draft has completely removed the gpg command. I thought the suggestion was just to change the command, by removing sudo at the beginning of it?

please restore that example gpg command that was removed from step 1 but don't include `sudo` in the command

**Comment by ramkumar-k-9286** [comment]
@dmuelle

Hi David.

Made the corrections.

Draft link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/verify-signatures-for-container-images-in-open-liberty.html


Regards,
Ramkumar

**Comment by dmuelle** [comment]
LGTM thanks

**Comment by ramkumar-k-9286** [comment]
@dmuelle

Hi David.

Staging site link:
https://docs-staging-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/verify-signatures-for-container-images-in-open-liberty.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
content is on vNExt and will publish with 23.0.0.6
