### ISSUE TITLE
An introductory concept - what is OL? 

### ISSUE THREAD

**Issue by chirp1** [OpenLiberty/docs#647]
Describe why users would be interested in Open Liberty.

**Comment by Charlotte-Holt** [comment]
@cbridgha @lauracowen I'm adding the text of my What is OL topic here. I'm not sure yet how or where these concept modules need to be uploaded for RH, so I'm just pasting the topic below. This topic should read similar to the What is Thorntail page (https://access.redhat.com/documentation/en-us/red_hat_openshift_application_runtimes/1/html/thorntail_runtime_guide/what-is-thorntail_wf-swarm). Please let me know what further updates or additions are necessary. Thanks!! 

= What is Open Liberty

Open Liberty is a lightweight Java runtime for building cloud-native applications and microservices. With Open Liberty, it's simple to add and remove modular features from the latest versions of MicroProfile and Jakarta EE. Because of this modular runtime structure, you need to run only the features that your application needs. And if you need to move to the latest version, Open Liberty's zero migration architecture allows you to upgrade with minimal impact to your current applications and configurations. To learn more about Open Liberty, visit the link:https://openliberty.io/[website].

Open Liberty has a product version of its runtime that runs on OpenShift and is provided as part of a Red Hat subscription. Run Open Liberty on OpenShift to build and deploy cloud-native applications with the benefits of the OpenShift platform. For more information about using Open Liberty with OpenShift, see <link to David's topic about Using OL w/ OpenShift>.

**Comment by lauracowen** [comment]
"has a product version of its runtime" doesn't make sense as a phrase - it's just OL running on OpenShift and you get support through Red Hat like you do for the other runtimes. Maybe: "Open Liberty is one of the Java runtimes available on OpenShift and support is provided as part of a Red Hat subscription." ?

**Comment by Charlotte-Holt** [comment]
@lauracowen Yeah, that's better. I got that sentence from the Thorntail doc to remind myself to include something similar and forgot to make changes to it. Thanks!

**Comment by Charlotte-Holt** [comment]
Draft of this in GitHub at https://github.ibm.com/was-liberty/openliberty-redhat-drafts/blob/master/docs/modules/what-is-openliberty.adoc.

**Comment by cbridgha** [comment]
Hey - yes I chatted with @Charlotte-Holt in slack - the text now is great.

**Comment by chirp1** [comment]
Hi Charlotte, Here are my suggested edits:

Trademark Java and anything else as appropriate.

Change "you need to run only " to "you can run only ".

Change "And if you need to move to the latest version, Open Liberty’s zero migration architecture allows you to upgrade with minimal impact to your current applications and configurations. " to "And with the Open Liberty zero migration architecture, you can upgrade to the latest version with minimal impact to your current applications and configurations. ".

Change "To learn more about Open Liberty, visit the website. " to "For more information, see Open Liberty. ".

For the link in  "For more information about using Open Liberty with OpenShift, see Deploying Open Liberty on OpenShift. " the URL WILL NOT WORK because it is a link to the IBM internal draft repo. Figure out how to link among topics in the Red Hat OpenShift website and then change the link so that it will work when the docs go live.

**Comment by chirp1** [comment]
@dmuelle @Charlotte-Holt 

Hi,

Change "For more information, see the website. " to "For more information, see the Open Liberty site."

For this broken link in "see Deploying Open Liberty on OpenShift.", David and I just now discussed. David will switch this to a link to the actual guide, as he does in another topic. Here is the link: https://openliberty.io/guides/cloud-openshift.html#deploying-microservices-to-openshift

**Comment by chirp1** [comment]
The updates are OK.

**Comment by Charlotte-Holt** [comment]
Doc included in the attachment. Closing this issue. 

[Documentation_for_OL_9:30:2019.pdf](https://github.com/OpenLiberty/docs/files/3681359/Documentation_for_OL_9.30.2019.pdf)
