### ISSUE TITLE
Doc for OL Operator

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#648]
Create a doc that describes the Open Liberty Operator for Kubernetes clusters.

Possibly use the following info:
- https://github.com/OpenLiberty/open-liberty-operator 
- https://operatorhub.io/operator/open-liberty

**Comment by Charlotte-Holt** [comment]
This is going to go in #766. Closing.

**Comment by Charlotte-Holt** [comment]
An intro about the OL Operator will go into #766, but the installation configuration information will be included in the OL docs from 
- https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/user-guide.md
- https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/troubleshooting.md
- https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/observability-deployment-rhocp4.2-4.3.md 

@lauracowen, @dmuelle, and I are working to determine a way to coherently pull this info together in OL doc topics.

**Comment by Charlotte-Holt** [comment]
@leochr Please review https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/open-liberty-operator.html. Thx!

**Comment by leochr** [comment]
@Charlotte-Holt Document looks good! Some comments for consideration:

- _The Open Liberty Operator helps you package, deploy, and manage applications on Kubernetes-based clusters._
The keyword _package_ could perhaps be removed since the_ OL operator doesn't help much with that. Application image, which the users have to create, is a required field for the operator.

- Under _What is the Open Liberty Operator?_ , it'll be good to convey the message that without the operator users would have to create Deployment, Services, Routes and other Kubernetes resources themselves - a big learning curve for most. But with the operator, they just specify the few details for their application (i.e. application image, service port, whether to expose the application outside the cluster or not) and the operator will take care of creating and managing all the Kubernetes resources. Users now have a single resource (OpenLibertyAppllication) to manage instead of many. In addition, the operator continuously monitors the events related to the application in the cluster and takes necessary actions (i.e synchronize data/resources).

- _When you’re deploying an application to Kubernetes, you configure the desired state of your application deployment._
This sentence seems disconnected from the rest. Addressing the above point may resolve this.

- _When you deploy the operator with an application_
I believe it should be _When you deploy an application with the operator_

- _For example, after you upload a new container tag for a new version of an application, update the applicationImage field in the operator deployment file with the new container tag. Then, the operator updates the application on a rolling basis._
OL operator supports _ImageStream_ which can be specified for _applicationImage_. Then the users would only need to push the new image to the relevant image stream and it'll be automatically deployed by operator - so they don't have to update the field manually.

- Serviceability is briefly mentioned under storage. But it'll be good to highlight these day-2 operations as it's one of the key features for Open Liberty available in the operator (separate point or elaborating more would be good)

- Integration with OpenShift Serverless (Knative) is another key feature to consider highlighting.

**Comment by Charlotte-Holt** [comment]
@leochr - Thanks for your feedback! I've addressed all your comments:

- [X] The Open Liberty Operator helps you package, deploy, and manage applications on Kubernetes-based clusters. The keyword package could perhaps be removed since the_ OL operator doesn't help much with that. Application image, which the users have to create, is a required field for the operator.
- [x] Under What is the Open Liberty Operator? , it'll be good to convey the message that without the operator users would have to create Deployment, Services, Routes and other Kubernetes resources themselves - a big learning curve for most. But with the operator, they just specify the few details for their application (i.e. application image, service port, whether to expose the application outside the cluster or not) and the operator will take care of creating and managing all the Kubernetes resources. Users now have a single resource (OpenLibertyAppllication) to manage instead of many. In addition, the operator continuously monitors the events related to the application in the cluster and takes necessary actions (i.e synchronize data/resources).
- [x] When you’re deploying an application to Kubernetes, you configure the desired state of your application deployment. This sentence seems disconnected from the rest. Addressing the above point may resolve this.
- [x] When you deploy the operator with an application. I believe it should be When you deploy an application with the operator
- [x] For example, after you upload a new container tag for a new version of an application, update the applicationImage field in the operator deployment file with the new container tag. Then, the operator updates the application on a rolling basis. OL operator supports ImageStream which can be specified for applicationImage. Then the users would only need to push the new image to the relevant image stream and it'll be automatically deployed by operator - so they don't have to update the field manually.
- [x] Serviceability is briefly mentioned under storage. But it'll be good to highlight these day-2 operations as it's one of the key features for Open Liberty available in the operator (separate point or elaborating more would be good)
- [X] Integration with OpenShift Serverless (Knative) is another key feature to consider highlighting.

Please review https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/open-liberty-operator.html.

**Comment by leochr** [comment]
@Charlotte-Holt Document looks good. Thanks for making the updates. Few minor things I noticed:

- [x] _Then, the operator creates and manages that storage for you. An advanced mode is available that allows the configuration of extra details of the persistent volume._ 
The operator can only create the claim for storage, not the storage itself. Suggestion: _Then, the operator creates and manages the storage claim for you. An advanced mode is available that allows the configuration of extra details of the persistent volume claim._

- [x] _You can enable persistence for your application by specifying only_
This hyperlink is specific to serviceability. It's better to point to the `Persistence` section: https://github.com/application-stacks/runtime-component-operator/blob/master/doc/user-guide.adoc#Persistence 

- [x] _After you implement the operator, you can integrate Open Liberty with monitoring tools in the Kubernetes cluster. _
Wondering whether _implement_ could be misinterpreted. Should it be installed/configured (I am not so sure)? Also, it may be good to specify _logging and monitoring tools_ instead.

**Comment by Charlotte-Holt** [comment]
@leochr I incorporated your updates! Please review https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/open-liberty-operator.html. Thx!

**Comment by leochr** [comment]
@Charlotte-Holt Looks good. Thanks!

**Comment by lauracowen** [comment]
I like it. I learnt something, which is always good. :) Some specific comments:

- "When you deploy an application with the operator," - should that be "When you deploy an application with the Open Liberty operator," (for clarity that it's the OL operator you're talking about from the start and not a generic operator before going into details about the OL one)?
- Not sure that "Deployments, Services, and Routes" need to be either capitalised or monospace when talking conceptually about them; eg [OpenShift docs don't](https://docs.openshift.com/container-platform/3.6/dev_guide/deployments/advanced_deployment_strategies.html). Could link out to Kubernetes' or OpenShift's doc about what they are if that seems necessary/appropriate.
- "With the operator, specify details for your application," - I know why it's phrased in the imperative but as you're not actually instructing the reader at this stage but explaining the concept to them, it would read more naturally as something like "With the operator, you can specify details for your application," or "With the operator, you can just specify details for your application," to make it clearer at the start of the sentence where the sentence is going.
- Typo: "a single `OpenLibertyAppllication`"
- "The Open Liberty Operator is based on the generic Runtime Component Operator," - might be useful to append "which is xxxx". Otherwise, I'm asking "they have common functionality, so what?"
- "The architecture of the Open Liberty Operator follows the basic controller pattern, meaning that the operator container and controller are deployed to a Kubernetes Pod. " - this seems a bit too detailed about how we implemented it. Could it be just "When you use the Open Liberty Operator, the operator container and controller are deployed to a Kubernetes Pod. " or if necessary something like "Like other operators, when you use the Open Liberty Operator, the operator container and controller are deployed to a Kubernetes Pod. "? Rather than describing the architecture, describing what it means to use it.
- When it mentions capability levels, could link out to an explanation of what they are; eg something like https://operatorframework.io/operator-capabilities/ ?
- I like the linking out to OpenShift docs for concept explanations that don't need to be explained here. :) 
- "scale to 0 when it’s idle." should probably be "scale to zero when it’s idle." - it's a thing (and easier to read as a word than a digit)
- "Go to the documentation " -> "See the documentation "? (for consistency with how we word it elsewhere) a couple of places in the topic
- "for a complete list of the enterprise capabilities that are offered by the operator." -> "... by the Open Liberty operator.", and "Serviceability and observability with the operator" to "Serviceability and observability with the Open Liberty operator"? (for clarity- also good for SEO if people search on "Open Liberty operator", esp when it's in an H2 heading). I don't think it needs to be every instance of "the operator".
- "The Operator is also available" - should be either the full name or lower-case

**Comment by Charlotte-Holt** [comment]
- [ ] "When you deploy an application with the operator," - should that be "When you deploy an application with the Open Liberty operator," (for clarity that it's the OL operator you're talking about from the start and not a generic operator before going into details about the OL one)?
- [ ] Not sure that "Deployments, Services, and Routes" need to be either capitalised or monospace when talking conceptually about them; eg OpenShift docs don't. Could link out to Kubernetes' or OpenShift's doc about what they are if that seems necessary/appropriate.
- [ ] "With the operator, specify details for your application," - I know why it's phrased in the imperative but as you're not actually instructing the reader at this stage but explaining the concept to them, it would read more naturally as something like "With the operator, you can specify details for your application," or "With the operator, you can just specify details for your application," to make it clearer at the start of the sentence where the sentence is going.
- [ ] Typo: "a single OpenLibertyAppllication"
- [ ] "The Open Liberty Operator is based on the generic Runtime Component Operator," - might be useful to append "which is xxxx". Otherwise, I'm asking "they have common functionality, so what?"
- [ ] "The architecture of the Open Liberty Operator follows the basic controller pattern, meaning that the operator container and controller are deployed to a Kubernetes Pod. " - this seems a bit too detailed about how we implemented it. Could it be just "When you use the Open Liberty Operator, the operator container and controller are deployed to a Kubernetes Pod. " or if necessary something like "Like other operators, when you use the Open Liberty Operator, the operator container and controller are deployed to a Kubernetes Pod. "? Rather than describing the architecture, describing what it means to use it.
- [ ] When it mentions capability levels, could link out to an explanation of what they are; eg something like https://operatorframework.io/operator-capabilities/ ?
- [ ] I like the linking out to OpenShift docs for concept explanations that don't need to be explained here. :)
- [ ] "scale to 0 when it’s idle." should probably be "scale to zero when it’s idle." - it's a thing (and easier to read as a word than a digit)
- [ ] "Go to the documentation " -> "See the documentation "? (for consistency with how we word it elsewhere) a couple of places in the topic
- [ ] "for a complete list of the enterprise capabilities that are offered by the operator." -> "... by the Open Liberty operator.", and "Serviceability and observability with the operator" to "Serviceability and observability with the Open Liberty operator"? (for clarity- also good for SEO if people search on "Open Liberty operator", esp when it's in an H2 heading). I don't think it needs to be every instance of "the operator".
- [ ] "The Operator is also available" - should be either the full name or lower-case

**Comment by Charlotte-Holt** [comment]
@lauracowen Thanks for the review!! I addressed all your feedback:

- [x] "When you deploy an application with the operator," - should that be "When you deploy an application with the Open Liberty operator," (for clarity that it's the OL operator you're talking about from the start and not a generic operator before going into details about the OL one)?
- [x] Not sure that "Deployments, Services, and Routes" need to be either capitalised or monospace when talking conceptually about them; eg OpenShift docs don't. Could link out to Kubernetes' or OpenShift's doc about what they are if that seems necessary/appropriate.
- [x] "With the operator, specify details for your application," - I know why it's phrased in the imperative but as you're not actually instructing the reader at this stage but explaining the concept to them, it would read more naturally as something like "With the operator, you can specify details for your application," or "With the operator, you can just specify details for your application," to make it clearer at the start of the sentence where the sentence is going.
- [x] Typo: "a single OpenLibertyAppllication"
- [x] "The Open Liberty Operator is based on the generic Runtime Component Operator," - might be useful to append "which is xxxx". Otherwise, I'm asking "they have common functionality, so what?"
- [x] "The architecture of the Open Liberty Operator follows the basic controller pattern, meaning that the operator container and controller are deployed to a Kubernetes Pod. " - this seems a bit too detailed about how we implemented it. Could it be just "When you use the Open Liberty Operator, the operator container and controller are deployed to a Kubernetes Pod. " or if necessary something like "Like other operators, when you use the Open Liberty Operator, the operator container and controller are deployed to a Kubernetes Pod. "? Rather than describing the architecture, describing what it means to use it.
- [x] When it mentions capability levels, could link out to an explanation of what they are; eg something like https://operatorframework.io/operator-capabilities/ ?
- [x] I like the linking out to OpenShift docs for concept explanations that don't need to be explained here. :)
- [x] "scale to 0 when it’s idle." should probably be "scale to zero when it’s idle." - it's a thing (and easier to read as a word than a digit)
- [x] "Go to the documentation " -> "See the documentation "? (for consistency with how we word it elsewhere) a couple of places in the topic
- [x] "for a complete list of the enterprise capabilities that are offered by the operator." -> "... by the Open Liberty operator.", and "Serviceability and observability with the operator" to "Serviceability and observability with the Open Liberty operator"? (for clarity- also good for SEO if people search on "Open Liberty operator", esp when it's in an H2 heading). I don't think it needs to be every instance of "the operator".
- [x] "The Operator is also available" - should be either the full name or lower-case

Let me know if there are further updates that need to be made! https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/open-liberty-operator.html

**Comment by lauracowen** [comment]
Speedy!

I think "Deployments, Services, and Routes," should be lower-case too when in text like this as opposed to talking about the actual entries in the configuration files. I know Kubernetes use upper-case but OpenShift uses lower-case and there's not really any reason to upper-case it (ie I think Kubernetes doc is grammatically wrong). :)


But other than that it looks good and will sign off if you can fix that.

**Comment by Charlotte-Holt** [comment]
@lauracowen Thank you! Just fixed in #3123. Requesting a peer review from @ManasiGandhi: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/open-liberty-operator.html

**Comment by ManasiGandhi** [comment]
@Charlotte-Holt The doc looks good! Few suggestions:

**Short Description**

- [x] Change,

“Operators are extensions to Kubernetes that are customized to automate tasks beyond the initial automation that Kubernetes or OpenShift provide.”
To,
“Operators are extensions to Kubernetes that are customized to automate tasks beyond the initial automation that Kubernetes or OpenShift provides.”

**What is the Open Liberty Operator?**

- [x] Acrolinx is flagging the word ‘desired’.

- [x] Acrolinx is also flagging the sentence “With the operator, you can specify details for your application, including your application image, service port, and whether to expose the application outside the cluster, and the operator creates and manages all Kubernetes resources” as too long. Can you split it into two, for example, “With the operator, you can specify details for your application, including your application image, service port, and whether to expose the application outside the cluster. The operator creates and manages all Kubernetes resources.”

- [ ] “When a discrepancy exists between the..”, you could also say “When there is a discrepancy between the..”, to use active voice.

- [ ] “The Open Liberty Operator is based on the Runtime Component Operator, which is a generic operator that can be imported into runtime-specific operators to provide standardized enterprise capabilities.”

I would suggest breaking down this sentence into two sentences for clarity. For example, “The Open Liberty Operator is based on the Runtime Component Operator. The Runtime Component Operator is a generic operator that can be imported into runtime-specific operators to provide standardized enterprise capabilities.”

- [x] “When you use the Open Liberty Operator, the operator container and controller are deployed to a Kubernetes pod. Then, the operator listens for incoming resources with the kind: OpenLibertyApplication statement.” You could also combine the two sentences into “When you use the Open Liberty Operator, the operator container and controller are deployed to a Kubernetes pod, and the operator listens for incoming resources with the kind: OpenLibertyApplication statement.”

**Operator capabilities**

_Enhanced deployment management_

- [ ] “With the Open Liberty Operator, you can more easily manage applications that are deployed to Kubernetes.” You can also say “With the Open Liberty Operator, you can easily manage applications that are deployed to Kubernetes.” For concreteness. 

_Single-sign on (SSO) delegation_

- [x] “With Open Liberty, you can delegate SSO authentication to external providers. The Open Liberty Operator enables easier configuration and management of single sign-on information for your applications. For more information about SSO configuration with the operator, see the Open Liberty Operator documentation.”

Change to, “With Open Liberty, you can delegate the SSO authentication to external providers. The Open Liberty Operator enables easier configuration and management of the SSO information for your applications. For more information about SSO configuration with the operator, see the Open Liberty Operator documentation.”, for consistency and clarity.

**Serviceability and observability with the Open Liberty operator**

- [ ] “You can also configure and use a single storage for serviceability-related operations, such as gathering server memory dumps and server traces.” I would suggest to use “the” before “serviceability-related operations”.

**Comment by Charlotte-Holt** [comment]
@ManasiGandhi Thanks for the review! I incorporated all the updates above that I checked off. To address the others:

 - “When a discrepancy exists between the..”, you could also say “When there is a discrepancy between the..”, to use active voice. - **I didn't want to use "there is", which is why I structured it with "exists".**

 - “The Open Liberty Operator is based on the Runtime Component Operator, which is a generic operator that can be imported into runtime-specific operators to provide standardized enterprise capabilities.” - **I think breaking it into two sentences makes it choppier, so I left this one alone.** 

- “With the Open Liberty Operator, you can more easily manage applications that are deployed to Kubernetes.” You can also say “With the Open Liberty Operator, you can easily manage applications that are deployed to Kubernetes.” For concreteness. - **I like having "more" in this because it implies a comparison to managing applications without the operator.**

-  “You can also configure and use a single storage for serviceability-related operations, such as gathering server memory dumps and server traces.” I would suggest to use “the” before “serviceability-related operations”. - **I think this reads better without "the" so I left it out.** 

See what you think, and let me know if you think I still need to update these. Thanks!

**Comment by chirp1** [comment]
Hi Charlotte,

Here are my comments:
- Global comment: I think you should link to the Open Liberty Operator documentation once instead of multiple times. Thoroughly review the "Link to essential information" section and other linking sections in the IBM quality guide so that you gain a thorough understanding about linking. I have more specific comments on linking in the comments that follow. If you would like to discuss linking for this topic, we can chat.
- Move your Open Liberty operator link to "Open Liberty operator" in  "When you deploy an application with the Open Liberty operator,".
- Remove the "See the Open Liberty Operator documentation if you want to...... " sentence. Replace it with some examples of the functionality that is common, using text that is the same between the two, i.e. ServiceAccount resource, not "service account" so that the user can find common terms between the two URLs. Doing something like this would get rid of multiple links to the Open Liberty operator doc.
- Instead of "to return to the state that you want.", change want to something more concrete. Hint: see the previous sentence for the answer.
- Remove the "For more information about SSO configuration with the operator...... " sentence since you already linked to the OL Operator docs once.
- I'd remove the "See the documentation in OperatorHub for a complete list of ...." sentence because the information on OperatorHub is not the source for the information. Instead, it is a summary of the information at the Open Liberty Operator link.
- I found at least one occurrence of "Open Liberty operator" when many occurrences have an upper case O for operator. Make them consistent.
- Since this topic is about the Open Liberty Operator, should you be linking to docs in the Runtime Component Operator documentation in, for instance "You can enable persistence for your application by specifying "? If a link is warranted, my thought is it would be to the Open Liberty Operator documentation. However, you should already have a link to the Open Liberty Operator documentation towards the beginning of your topic.. So, I don't think you should have a link in this sentence.
- You didn't mention "observibality" at all the the paragraph about observability. Work the word into the paragraph. Then link this word to the observability documentation. Then, remove the five other links in the paragraph to the observability documentation.
- For "..... that you want to monitor, depending on your needs. ", remove "depending on your needs" to reduce wordiness.
- For "If you need to visualize and track ....", remove "If you need" to reduce wordiness.
- Remove the link from "..'for information about how to install the operator.". Also, the practice is to start the sentence with "For more information....".
- Remove the link from the four bullets in the "Operator installation and configuration' section.
- In "See also", remove the link to "Observability with the Open Liberty Operator ".

**Comment by Charlotte-Holt** [comment]
@chirp1 Thanks! All feedback has been addressed: 

- [x] Global comment: I think you should link to the Open Liberty Operator documentation once instead of multiple times. Thoroughly review the "Link to essential information" section and other linking sections in the IBM quality guide so that you gain a thorough understanding about linking. I have more specific comments on linking in the comments that follow. If you would like to discuss linking for this topic, we can chat.
- [x] Move your Open Liberty operator link to "Open Liberty operator" in "When you deploy an application with the Open Liberty operator,".
- [x] Remove the "See the Open Liberty Operator documentation if you want to...... " sentence. Replace it with some examples of the functionality that is common, using text that is the same between the two, i.e. ServiceAccount resource, not "service account" so that the user can find common terms between the two URLs. Doing something like this would get rid of multiple links to the Open Liberty operator doc.
- [x] Instead of "to return to the state that you want.", change want to something more concrete. Hint: see the previous sentence for the answer.
- [x] Remove the "For more information about SSO configuration with the operator...... " sentence since you already linked to the OL Operator docs once.
- [x] I'd remove the "See the documentation in OperatorHub for a complete list of ...." sentence because the information on OperatorHub is not the source for the information. Instead, it is a summary of the information at the Open Liberty Operator link.
- [x] I found at least one occurrence of "Open Liberty operator" when many occurrences have an upper case O for operator. Make them consistent.
- [x] Since this topic is about the Open Liberty Operator, should you be linking to docs in the Runtime Component Operator documentation in, for instance "You can enable persistence for your application by specifying "? If a link is warranted, my thought is it would be to the Open Liberty Operator documentation. However, you should already have a link to the Open Liberty Operator documentation towards the beginning of your topic.. So, I don't think you should have a link in this sentence. 
- [x] You didn't mention "observibality" at all the the paragraph about observability. Work the word into the paragraph. Then link this word to the observability documentation. Then, remove the five other links in the paragraph to the observability documentation.
- [x] For "..... that you want to monitor, depending on your needs. ", remove "depending on your needs" to reduce wordiness.
- [x] For "If you need to visualize and track ....", remove "If you need" to reduce wordiness.
- [x] Remove the link from "..'for information about how to install the operator.". Also, the practise is to start the sentence with "For more information....".
- [x] Remove the link from the four bullets in the "Operator installation and configuration' section.
- [x] In "See also", remove the link to "Observability with the Open Liberty Operator ".

**Comment by chirp1** [comment]
Hi Charlotte, the article looks nice!
I have just three minor comments:
- For "state of resources that you configure. ", "state that you configure, ", and "to the state that you configure. ", should all three be 'configured" instead of "configure"?
- I seem to still spot one occurrence of "Open Liberty operator" (lower case "operator"). Check your section headers.
- Since we the topics says "The Open Liberty Operator documentation provides details about..." in one sentence in the "Operator installation and configuration" section, now I think that "For more information, see the Open Liberty Operator documentation." isn't necessary.

**Comment by Charlotte-Holt** [comment]
@chirp1 Updates made! https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/open-liberty-operator.html:

- [x] For "state of resources that you configure. ", "state that you configure, ", and "to the state that you configure. ", should all three be 'configured" instead of "configure"?
- [x] I seem to still spot one occurrence of "Open Liberty operator" (lower case "operator"). Check your section headers.
- [x] Since we the topics says "The Open Liberty Operator documentation provides details about..." in one sentence in the "Operator installation and configuration" section, now I think that "For more information, see the Open Liberty Operator documentation." isn't necessary.

**Comment by chirp1** [comment]
Topic looks great! Moving to Ready to Publish.

**Comment by Charlotte-Holt** [comment]
Merged to vNext in #3221. Closing this issue.
