### ISSUE TITLE
Using OL with OpenShift

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#651]
Draft intro- if the doc points to our guide

**Comment by dmuelle** [comment]
## Deploying Open Liberty on OpenShift

When you run Open Liberty applications on OpenShift, you get all the advantages of the most flexible server runtime available to Java developers, combined with a streamlined DevOps process and an intuitive development pipeline. You'll have all the tools to easily build, deploy, and manage cloud native apps and microservices, while running only the features that you need. To learn how to deploy microservices in Open Liberty containers to an OpenShift cluster, see the Open Liberty guide to guide to [Deploying microservices to OpenShift](https://www.openliberty.io/guides/cloud-openshift.html).

### Additional resources
* link:https://www.openliberty.io/guides/getting-started.html[Deploying and packaging applications]
* link:https://openliberty.io/guides/kubernetes-intro.html[Deploying microservices to Kubernetes]

**Comment by cbridgha** [comment]
In addition I would add the link about docker / containerizing Liberty apps - because the OpenShift guide is assuming the user has a docker image ready to go   

https://openliberty.io/guides/containerize.html

**Comment by dmuelle** [comment]
@cbridgha would it make sense to list ` a containerized Open Liberty application` as a prerequisite at the top of this topic, and then include the link in the additional resources?

**Comment by dmuelle** [comment]
running draft at https://github.ibm.com/was-liberty/openliberty-redhat-drafts/blob/master/docs/modules/deploying-openliberty-on-openshift.adoc

**Comment by chirp1** [comment]
Hi David, here is my suggested wording. I mainly reorganized the sentences to discuss deploying in the intro (short description) since the guide is about deploying. 

Deploying Open Liberty on OpenShift

You can deploy microservices in Open Liberty containers to an OpenShift cluster. You have all the tools to easily build, deploy, and manage cloud native applications and microservices, but you run with only the features that you need. 

When you run Open Liberty applications on OpenShift, you get all the advantages of the most flexible server runtime available to Java developers, combined with a streamlined DevOps process, and an intuitive development pipeline. For more information, see Deploying microservices to OpenShift.

Additional resources
Deploying and packaging applications
Deploying microservices to Kubernetes

**Comment by cbridgha** [comment]
@dmuelle Sure that sounds right.

**Comment by chirp1** [comment]
The updates are OK.

**Comment by Charlotte-Holt** [comment]
Doc included in the attachment. Closing this issue. 

[Documentation_for_OL_9:30:2019.pdf](https://github.com/OpenLiberty/docs/files/3681364/Documentation_for_OL_9.30.2019.pdf)
