### ISSUE TITLE
Deploying and packaging apps

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#654]

**Comment by dmuelle** [comment]
this would also cover the `Packaging Jars` topic in the thorntail example fro the boxnote

**Comment by dmuelle** [comment]
##Deploying and packaging applications

Open Liberty is an application server that is designed with modern cloud-native development in mind. It's fully composable, so you run only the features that you need, keeping the server lightweight. Open Liberty supports all MicroProfile and Java EE APIs and deploys to every major cloud platform, including Docker, Kubernetes, and OpenShift. To get started with Open Liberty, learn how to to run and update a simple REST microservice with the Open Liberty guide to [Deploying and packaging applications](https://openliberty.io/guides/getting-started.html).

.Additional resources
* [Deploying microservices to OpenShift](https://www.openliberty.io/guides/cloud-openshift.html)
* [Deploying microservices to Kubernetes](https://openliberty.io/guides/kubernetes-intro.html)

**Comment by cbridgha** [comment]
I think this topic needs more references to packaging basics as well - so pointing them to the reference material like: https://openliberty.io/docs/ref/command/#server-package.html

**Comment by dmuelle** [comment]
Thanks @cbridgha , I've edited the above draft to include `server package`

**Comment by chirp1** [comment]
Hi David, here are my edits. Note that I changed the order of the information. Here is the suggsted wording:

You can package an Open Liberty server, its resources, and its applications in a compressed file that you can store, distribute or deploy to a different location by using the server package command. 

To see usage examples, syntax, and options for the server package command, see server package. 

Open Liberty is an application server that is designed with modern cloud-native development in mind. It's fully composable so that you run only the features that you need, keeping the server lightweight. Open Liberty supports all MicroProfile and Java EE APIs and deploys to every major cloud platform, including Docker, Kubernetes, and OpenShift. To get started with Open Liberty, learn how to to run and update a simple REST microservice with Deploying and packaging applications. 

Also, add a trademark for Java. Check the wiki maybe Voice Gateway/ Voice agent. It tmight tell you how to do a trademark at least in markdown.

**Comment by dmuelle** [comment]
@chirp1 I've made these updates to the doc- except for the Java trademark. I need to ask Laura (and Nicole?)- none of the OL docs currently use trademark tags 
running draft  is at https://github.ibm.com/was-liberty/openliberty-redhat-drafts/blob/master/docs/modules/deploying-and-packaging-applications.adoc

**Comment by chirp1** [comment]
Hi David, I believe Charlotte made additional updates. 

Here are my comments: 

Add an intro for the topic that summarizes what this topic covers / why it is important to users. Make it 1 -2 sentences, generally up to 25 words each, generally 50 words max. So, something like: You can package your applications with either the server package command or containers and then deploy your applications in different environments.

Change "so you run only" to "so that you run only".

You might have other ideas for sprucing the topic.

**Comment by dmuelle** [comment]
updated doc at https://github.ibm.com/was-liberty/openliberty-redhat-drafts/blob/master/docs/modules/deploying-and-packaging-applications.adoc

**Comment by chirp1** [comment]
Change title to "Packaging and deploying applications" since packaging occurs before deploying.

**Comment by chirp1** [comment]
The update here looks good: https://github.ibm.com/was-liberty/openliberty-redhat-drafts/blob/master/docs/modules/packaging-and-deploying-applications.adoc

**Comment by Charlotte-Holt** [comment]
Doc included in the attachment. Closing this issue. 

[Documentation_for_OL_9:30:2019.pdf](https://github.com/OpenLiberty/docs/files/3681361/Documentation_for_OL_9.30.2019.pdf)
