### ISSUE TITLE
Monitoring doc

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#657]
Create a doc for monitoring for use in the RHR docs.

**Comment by dmuelle** [comment]
This topic provides resources that help you monitor microservices and applications that run on Open Liberty.

## Providing metrics
Monitoring microservice metrics helps you pinpoint issues, collect data for capacity planning, and decide when to scale a service up or down. To explore how to provide system and application metrics from a microservice, see the Open Liberty guide to [Providing metrics from a microservice](https://openliberty.io/guides/microprofile-metrics.html).

## Tracing requests
Distributed tracing helps troubleshoot microservices by examining and logging requests as they propagate through a distributed system, allowing developers to tackle the otherwise difficult task of debugging these requests. Without a distributed tracing system in place, it's difficult to analyze workflows and pinpoint when and by whom a request is received or a response is returned.

To learn how to monitor and trace logging requests across microservices in an application, see the Open Liberty guide to link:https://www.openliberty.io/guides/microprofile-opentracing.html[Enabling distributed tracing in microservices].

## Configuring logs 
Open Liberty has a unified logging component that handles messages that are written by applications and the runtime, and provides First Failure Data Capture (FFDC) capability. To learn more about Open Liberty's logging configuration, and to see an index of configuration settings by source, see link:https://www.openliberty.io/docs/ref/general/#logging.html[Logging and tracing].

To learn how to configure access log settings specifically for HTTP endpoints, and to see a list of log format options, see link:https://www.openliberty.io/docs/ref/general/#access-logging.html[HTTP access logging].

.Additional resources
* link:https://openliberty.io/docs/ref/config/#logging.html[Open Liberty server configuration: Logging]
* link:https://www.openliberty.io/docs/ref/general/#health-check-microservices.html[Enabling health checking of microservices]
* link:https://www.openliberty.io/guides/microprofile-health.html[Adding health reports to microservices]
* link:https://openliberty.io/blog/2018/10/05/microprofile-faulttolerance-1.1-metrics.html)[Monitor faults with MicroProfile Fault Tolerance 1.1]

**Comment by chirp1** [comment]
Hi David, 
Nice job!

Here are my comments:
Do you have a title? Maybe "Monitoring your applications"

Change "There following resources are available to help you monitor microservices and applications that run on Open Liberty. " to "You can use microservice metrics, distributed tracing, and unified logging to monitor microservices and applications that run on Open Liberty.". 

Change "see the Open Liberty guide to Providing metrics from a microservice. " to "see Providing metrics from a microservice. ".

Change "it's difficult to analyze workflows and pinpoint when and by whom a request is received or a response is returned." to "it's difficult to analyze workflows and pinpoint when and by whom a request is received or when a response is returned.".

Change "see the Open Liberty guide toEnabling distributed tracing in microservices. " to "see Enabling distributed tracing in microservices. ".

Change "Open Liberty has a unified logging component that handles messages that are written by applications and the runtime, and provides First Failure Data Capture (FFDC) capability. " to "Open Liberty has a unified logging component. It handles messages that are written by applications and the runtime, and provides First Failure Data Capture (FFDC) capability. ". (Break into two sentences.)

Change "To learn more about Open Liberty's logging configuration, and to see an index of configuration settings by source, see Logging and tracing. " to "To learn more about logging, and to see a table of configuration settings by source, see Logging and tracing. ".

Change "log settings specifically for HTTP endpoints, " to "log settings for HTTP endpoints, ".

**Comment by dmuelle** [comment]
@chirp1 
Current title (which I missed including here, sorry) is `Monitoring Open Liberty`. I can change it to `Monitoring your applications` if that works better.

I've made these edits to the docs now in the new openliberty-redhat-drafts repo, and in the comment above. Note that I had already moved the Logging section into it's own doc- `configuring-logs.adoc`. I've m,ade these edits in that doc and in the repsective GH issue #679

**Comment by dmuelle** [comment]
Current running draft is in https://github.ibm.com/was-liberty/openliberty-redhat-drafts/blob/master/docs/modules/providing-metrics.adoc

and https://github.ibm.com/was-liberty/openliberty-redhat-drafts/blob/master/docs/modules/tracing-requests.adoc

**Comment by chirp1** [comment]
Hi Charlotte/David, here are my suggested updates:

Change the title from "Configuring logging" to "Logging" or "Application logging", etc.

Change "Open Liberty has a unified logging component. It handles messages that are written by applications and the runtime, and provides First Failure Data Capture (FFDC) capability." to "Open Liberty has a unified logging component that handles messages that are written by applications and the runtime, and provides First Failure Data Capture (FFDC) capability.".

Change "The following example uses the server.xml file to configure log files to be stored in JSON format: " to "The following example shows how to configure log files that are stored in JSON format:".

Change "It is also possible to configure logging by using" to "You can also configure logging by using".

Change "To learn more about Open Liberty’s logging configuration, see example configurations and a table of configuration settings by source, see Logging and tracing. " to "For more information about Open Liberty logging, see Logging and tracing. "

Change "To learn how to configure access log settings for HTTP endpoints, and to see a list of log format options, see HTTP access logging." to "For information about logging for HTTP endpoints,see HTTP access logging.".

**Comment by chirp1** [comment]
For the monitoring topic, change "or a when response is returned." to "or when a response is returned.".

**Comment by dmuelle** [comment]
updated doc at https://github.ibm.com/was-liberty/openliberty-redhat-drafts/blob/master/docs/modules/enabling-monitoring-microservices.adoc

**Comment by chirp1** [comment]
The update are OK.

**Comment by Charlotte-Holt** [comment]
Doc included in the attachment. Closing this issue. 

[Documentation_for_OL_9:30:2019.pdf](https://github.com/OpenLiberty/docs/files/3681360/Documentation_for_OL_9.30.2019.pdf)
