### ISSUE TITLE
OL features doc (RHR)

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#658]
Create a feature doc for use in RHR docs. Link out to https://openliberty.io/docs/ref/feature/.

**Comment by Charlotte-Holt** [comment]
Hi @lauracowen and @cbridgha - I've included the doc that I currently have for features below. I have it in a .adoc file, but until David and I know exactly where these files need to go, I think it's best to just include the info this way. Please review. I was unsure exactly how much information to include in the RHR docs, so let me know your thoughts. I link out in several places to the OL docs. 


= Features

The Open Liberty runtime is composed of features, which are the discrete units of functionality that enable you to control the pieces of the runtime environment that are loaded into a server. You can add or remove features from the server configuration to control what functions the server can perform. Because features are pluggable and modular, you need to run only the features that your application requires. To learn more about features in Open Liberty, see the link:https://openliberty.io/docs/ref/feature/[Feature overview].

== Using features

The Open Liberty runtime contains default configuration settings. Specify the features that you need, along with any additions or overrides to the default settings, in the `server.xml` file and any other included files. For more information about the server configuration, see the link:https://openliberty.io/docs/ref/config/[Server configuration overview].

Each feature is configured by using the `feature` element that is enclosed within the `featureManager` element in the `server.xml` file. The following example configures the link:https://openliberty.io/docs/ref/feature/#servlet-4.0.html[Java Servlets 4.0] feature:

----
<server>
  <featureManager>
    <feature>servlet-4.0</feature>
  </featureManager>
</server>
----

== Zero-migration

With Open Liberty's zero-migration architecture, you can use existing, unmodified configuration and application files with an updated version of Open Liberty without unexpected changes in behavior. New APIs and behaviors are added in new features, and your existing APIs and behaviors are supported in new product versions. Changes in API behavior happen only in new feature versions so that you can choose the appropriate feature version for your application. These versioned features continue to be supported across Open Liberty updates.

.Additional resources

* link:https://openliberty.io/docs/ref/feature/[Open Liberty feature overview]
* link:https://openliberty.io/docs/ref/config/[Open Liberty server configuration overview]

**Comment by cbridgha** [comment]
Looks good

**Comment by Charlotte-Holt** [comment]
Draft of this is in GitHub at https://github.ibm.com/was-liberty/openliberty-redhat-drafts/blob/master/docs/modules/features.adoc.

**Comment by chirp1** [comment]
Hi Charlotte, Here are my suggested changes:

Change "discrete units of functionality" to "discrete functions".

For "see the Feature overview. ", change it to "see the feature overview. " (lowercase f) or "see Feature overview." (Remove "the".).

Change "Specify the features that you need, along with any additions or overrides to the default settings, in the server.xml file and any other included files " to "In the server.xml file and any other included files, specify the features that you need, along with any additions or overrides to the default settings.".

For "see the Server configuration overview. ", change it to "see the server configuration overview." (lowercase s) or "see Server configuration overview." (Remove "the".)

Change "feature element that is enclosed within the featureManager" to "feature element inside the featureManager".

This wording, which I see comes from a guide, took me a bit to study and understand: "Changes in API behavior happen only in new feature versions so that you can choose the appropriate feature version for your application."  I think we could make it clearer. How about "An API behavior change is made available as a new version of a feature so that you can choose the appropriate feature version for your application.". 

For "additional resources", since you already used both links earlier in the topic, remove "Additional resources" and its links from the topic.

**Comment by lauracowen** [comment]
@Charlotte-Holt @chirp1 Re the API behavior wording - it might be worth creating a PR for that back in the original as well.

**Comment by Charlotte-Holt** [comment]
@lauracowen Okay, will do this sometime today. I can incorporate all of these edits in the PR.

**Comment by chirp1** [comment]
@dmuelle @Charlotte-Holt 
Hi! A few more comments...

Change "discrete units of functionality" to "discrete functions".
Change "You can also use Open Liberty’s Maven plug-in" to "You can also use the Open Liberty Maven plug-in".

**Comment by dmuelle** [comment]
Updated doc at https://github.ibm.com/was-liberty/openliberty-redhat-drafts/blob/master/docs/modules/features.adoc

**Comment by Charlotte-Holt** [comment]
@lauracowen I made the API language change (and others that Karen suggested that fit into the doc) to the OL doc and built it to the draft site: https://draft-openlibertyio.mybluemix.net/docs/ref/feature/. If this looks good, I'll go ahead and open the PR to `develop`.

**Comment by Charlotte-Holt** [comment]
Doc included in the attachment. Closing this issue. 

[Documentation_for_OL_9:30:2019.pdf](https://github.com/OpenLiberty/docs/files/3681357/Documentation_for_OL_9.30.2019.pdf)
