### ISSUE TITLE
Testing a container doc (RHR) 

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#659]
Create a doc for Testing a container for use in RHR docs. Link out to [Testing microservices with the Arquillian managed container](https://openliberty.io/guides/arquillian-managed.html).

**Comment by Charlotte-Holt** [comment]
@lauracowen @cbridgha Here's what I currently have for this doc:

# Testing with a container

You can use an [Arquillian Liberty managed container](https://github.com/OpenLiberty/liberty-arquillian/tree/master/liberty-managed) and JUnit with Maven to develop tests for your microservices. An Arquillian Liberty managed container is an Arquillian container adapter that can start, stop, and test a local Open Liberty process over a remote protocol. To learn how to develop and run tests for your microservices, see the Open Liberty guide to [Testing microservices with the Arquillian managed container](https://openliberty.io/guides/arquillian-managed.html).

.Additional resources

* [Open Liberty managed container documentation](https://github.com/OpenLiberty/liberty-arquillian/tree/master/liberty-managed)
* [Arquillian Liberty managed container adapter](http://arquillian.org/modules/arquillian-liberty-managed-container-adapter/)

**Comment by Charlotte-Holt** [comment]
Draft of this is in GitHub at https://github.ibm.com/was-liberty/openliberty-redhat-drafts/blob/master/docs/modules/testing-with-container.adoc.

**Comment by chirp1** [comment]
Hi Charlotte,

Here are my suggested changes:

Change "To learn how to develop and run tests for your microservices, see the Open Liberty guide to Testing microservices with the Arquillian managed container." to "To learn how to develop and run tests for your microservices, see  Testing microservices with the Arquillian managed container."

Remove the "Open Liberty managed container documentation" link in the "Additional resources" section since you used the same link in the paragraph above it.

**Comment by Charlotte-Holt** [comment]
@chirp1 Updated! Thank you!

**Comment by Charlotte-Holt** [comment]
Doc included in the attachment. Closing this issue. 

[Documentation_for_OL_9:30:2019.pdf](https://github.com/OpenLiberty/docs/files/3681346/Documentation_for_OL_9.30.2019.pdf)
