### ISSUE TITLE
Update Documentation for MicroProfile Metrics 5.1

### ISSUE THREAD

**Issue by Channyboy** [OpenLiberty/docs#6792]
**Brief summary now as placeholder (further details to be added in):**

Related to: https://github.com/OpenLiberty/open-liberty/issues/25217

MP Metrics 5.1 will include a few new MP Config properties that will allow users to customize the output of the Histogram and Timer metrics w.r.t. quantiles output and histogram buckets (new). These properties only apply during start time.
See (https://github.com/eclipse/microprofile-metrics/pull/779)

 - mp.metrics.distribution.percentiles
 - mp.metrics.histogram.buckets
 - mp.metrics.timer.buckets
 - mp.metrics.distribution.percentiles-histogram.enabled
- mp.metrics.distribution.histogram.max-value
- mp.metrics.distribution.histogram.min-value
- mp.metrics.distribution.timer.max-value
- mp.metrics.distribution.timer.min-value

Updates would be needed to 
- https://openliberty.io/docs/latest/microprofile-config-properties.html#metrics (update properties)
- https://openliberty.io/docs/latest/microservice-observability-metrics.html (mention the use of propreties)

**Comment by dmuelle** [comment]
Hi @Channyboy - the updates for this feature are now available for review on the draft site:

- https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/microprofile-config-properties.html#metrics
- https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/microservice-observability-metrics.html

If any further changes are needed, just let me know. When you're satisfied with the update, you can add the `technical reviewed` label to this issue to sign off and the changes will publish with the 23.0.0.12 doc release. Thanks!

**Comment by dmuelle** [comment]
Hi @ramkumar-k-9286 this issue is ready for peer review

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/microprofile-config-properties.html#metrics
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/microservice-observability-metrics.html

**Comment by ramkumar-k-9286** [comment]
Peer Review
---

**Microservice observability with metrics**

---

Should MicroProfile Metrics 5.0 and MicroProfile Metrics 5.1 mentions be linked to the MicroProfile Metrics pages?

---

The property accepts a value from 1 to 5 and is defaulted to 3 if no value is specified.
->
The property accepts a value from `1` to `5` and is defaulted to `3` if no value is specified.

---

**Comment by ramkumar-k-9286** [comment]
Peer Review
---

**microprofile-config-properties #metrics**

---

**mp.metrics.defaultAppName**

The value for this property is defined at the server level and is used in conjunction with the `mp.metrics.appName` property when you run in a MicroProfile Metrics 5.x environment.
->
The value for this property is defined at the server level and is used **along with** the `mp.metrics.appName` property when you run in a MicroProfile Metrics 5.x environment.


However, without a similar tag value provided for servlet metrics that are created in the server context, a registration exception is thrown.
->
However, without a similar tag **value that is provided** for servlet metrics that are created in the server context, a registration exception is thrown.

Also **thrown** is getting picked up by Acrolinx -> might need to replace thrown with maybe - displayed.

---

**mp.metrics.distribution.histogram.buckets**

Accepts a comma-separated list of float and integer values greater than 0.
->
Accepts a comma-separated list of float and integer values greater than `0`.

Value precedence is right-to-left, so that values that are specified later in the property definition take precedence over previously-specified values.
->
Value precedence is right-to-left, so that values that are specified later in the property definition take precedence over **previously specified** values.
(Not sure -  is right-to-left so values ? is that correct?) 

over previously-specified values ->  over **previously specified** values (across multiple properties )
Value precedence is right-to-left so that values that -> Value precedence is right-to-left so values that (across multiple properties )

----

**mp.metrics.distribution.histogram.max-value**

When the `mp.metrics.distribution.percentiles-histogram.enabled` is configured to provide a default set of histogram buckets for a histogram metric, this property configures a upper bound for that default set of histogram buckets.
->
When the `mp.metrics.distribution.percentiles-histogram.enabled` **property** is configured to provide a default set of histogram buckets for a histogram metric, this property configures **an** upper bound for that default set of histogram buckets.
Also... **upper** picked up Acrolinx (accessibility)

Value precedence is right-to-left, so that values that are defined later in the property definition take precedence over earlier values.
->
Value precedence is right-to-left so that values that are defined later in the property definition take precedence over earlier values.
(Not sure -  is right-to-left so values ? is that correct?) 

---

**mp.metrics.distribution.histogram.min-value**

**lower** picked up Acrolinx (accessibility)

over previously-specified values ->  over **previously specified** values (across multiple properties )

Value precedence is right-to-left so that values that -> Value precedence is right-to-left so values that (across multiple properties )

---

**mp.metrics.distribution.percentiles**

Setting the property with a metric name but no percentile values disables percentile output for that metric.
->
Acrolinx Suggestion: Setting the property with a metric name but no percentile **values disable** percentile output for that metric.

over previously-specified values ->  over **previously specified** values (across multiple properties )

Value precedence is right-to-left so that values that -> Value precedence is right-to-left so values that (across multiple properties )

---

**mp.metrics.distribution.percentiles-histogram.enabled**

Values defined later take precedence over values before (i.e., right to left precedence).
->
Values **that are** defined later take precedence over values before (i.e., **right-to-left** precedence).

( i.e. getting picked up by Acrolinx)

---

**mp.metrics.distribution.timer.buckets**

Specifies a list of metric names that are paired with custom sets of histogram buckets for the metric to track and output.
->
Not clear - please rephrase

Float values will not be accepted.
->
Float values **are not accepted**.

over previously-specified values ->  over **previously specified** values (across multiple properties )

Value precedence is right-to-left, so that values that -> Value precedence is right-to-left so values that (across multiple properties )

---

**mp.metrics.distribution.timer.max-value**

When the `mp.metrics.distribution.percentiles-histogram.enabled` is configured
->
When the `mp.metrics.distribution.percentiles-histogram.enabled` **property** is configured

**upper** picked up Acrolinx (accessibility)

over previously-specified values ->  over **previously specified** values (across multiple properties )

Value precedence is right-to-left, so that values that -> Value precedence is right-to-left so values that (across multiple properties )
---

**mp.metrics.distribution.timer.min-value**

When the `mp.metrics.distribution.percentiles-histogram.enabled` is configured to
->
When the `mp.metrics.distribution.percentiles-histogram.enabled` **property** is configured to

**lower** picked up in Acrolinx (accessibility)

over previously-specified values ->  over **previously specified** values (across multiple properties )

Value precedence is right-to-left, so that values that -> Value precedence is right-to-left so values that (across multiple properties )

---

**mp.metrics.<registry>.enabled**

This property is available starting in MicroProfile Metrics 5.0 .
->
This property is available starting in MicroProfile Metrics **5.0.**

---

**mp.metrics.<registry>.<property>**

This property is available starting in MicroProfile Metrics 5.0 .
->
This property is available starting in MicroProfile Metrics **5.0.**

---

**mp.metrics.smallrye.histogram.precision**

The property accepts a value from 1 to 5 and is defaulted to 3 if no value is specified. 
->
The property accepts a value from `1` to `5` and is defaulted to `3` if no value is specified. 

This property is available starting in MicroProfile Metrics 5.0 .
->
This property is available starting in MicroProfile Metrics **5.0.**

---

**mp.metrics.smallrye.timer.precision**

The property accepts a value from 1 to 5 and is defaulted to 3 if no value is specified. 
->
The property accepts a value from `1` to `5` and is defaulted to `3` if no value is specified. 

This property is available starting in MicroProfile Metrics 5.0 .
->
This property is available starting in MicroProfile Metrics **5.0.**

---

**Comment by dmuelle** [comment]
Thanks @ramkumar-k-9286 - draft is updated

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/microprofile-config-properties.html#metrics
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/microservice-observability-metrics.html
