### ISSUE TITLE
clarify the difference between installFeature and installServerFeatures

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#6827]
we have two command options for the featureUtility command:  installFeature and installServerFeatures. With recent changes to 
installFeature  to better manage dependencies, we still recommend installServerFeatures to install the specific set of features for a given server. Our docs don't make clear the distinction between these two options from a strategic POV. When would you use one vs the other?

**Comment by dmuelle** [comment]
- https://openliberty.io/docs/latest/reference/command/featureUtility-installFeature.html
- https://openliberty.io/docs/latest/reference/command/featureUtility-installServerFeatures.html

**Comment by ramkumar-k-9286** [comment]
**Slack Conversation With Andrew**

Ramkumar K [3:38 PM]
Hi Andrew.
Had a question with regard to https://github.com/OpenLiberty/docs/issues/6827
What is the difference between the following commands:
installFeature
installServerFeatures
Could you explain the scenario under which each of these commands is used?
Planning to add a clarification to the documents on when these individual commands would be preferred over the other.
Thanks
Ramkumar.


Andrew Rouse
  [3:41 PM](https://ibm-cloud.slack.com/archives/D05NPD8CX7H/p1692785491249029)
This is really a question for the install team, but as they're not online I'll tell you what I know.
featureUtility installFeature installs a list of features given on the command line. featureUtility installServerFeature installs the features required by a particular server.xml.
[3:42](https://ibm-cloud.slack.com/archives/D05NPD8CX7H/p1692785533575279)
If you have a server configuration and you want to install everything needed to run it, you should use featureUtility installServerFeature (edited) 


Ramkumar K
  [3:43 PM](https://ibm-cloud.slack.com/archives/D05NPD8CX7H/p1692785629473289)
Should i confirm with the install team a well?


Andrew Rouse
  [3:44 PM](https://ibm-cloud.slack.com/archives/D05NPD8CX7H/p1692785646637679)
I think that's all documented already on https://openliberty.io/docs/latest/reference/command/featureUtility-installFeature.html and https://openliberty.io/docs/latest/reference/command/featureUtility-installServerFeatures.html
[3:44](https://ibm-cloud.slack.com/archives/D05NPD8CX7H/p1692785671650629)
Yeah, I would check what you're planning to change with [#was-install](https://ibm-cloud.slack.com/archives/C30NGGFH6)







Ramkumar K
  [3:45 PM](https://ibm-cloud.slack.com/archives/D05NPD8CX7H/p1692785749290089)
Yes, it is. but just wanted to add a little more clarity/detail on when featureUtility installFeature and featureUtility installServerFeature are used







Andrew Rouse
  [3:47 PM](https://ibm-cloud.slack.com/archives/D05NPD8CX7H/p1692785868125909)
To be honest, I don't really know when we're expecting users to call featureUtility at all. I think usually users would  fall into one of the following scenarios:
They're developing using the maven or gradle plugin, which will install the required features for them (similar to featureUtility installServerFeature)
They're deploying using docker, and installServerFeature will be run for them as part of the container build
They downloaded everything up front anyway





[3:49](https://ibm-cloud.slack.com/archives/D05NPD8CX7H/p1692785946915009)
featureUtility installFeature is conceptually easy to understand (it installs the requested features and their dependencies) but featureUtility installServerFeature is usually what users should use.





[3:50](https://ibm-cloud.slack.com/archives/D05NPD8CX7H/p1692786009564369)
I think the only situation I've heard of where the customer couldn't use installServerFeature was that they wanted to create a standard liberty install that they would use for all their deployments. I.e. they were pre-deciding what their install would look like before they'd decided what features they would actually use.







Ramkumar K
  [3:50 PM](https://ibm-cloud.slack.com/archives/D05NPD8CX7H/p1692786040748299)
the confusion is then why provide featureUtility installFeature which is why we wanted to provide that additional bit of explanation.







Andrew Rouse
  [3:51 PM](https://ibm-cloud.slack.com/archives/D05NPD8CX7H/p1692786105546619)
Yeah, you'd have to ask the install team why they did it.







Ramkumar K
  [3:52 PM](https://ibm-cloud.slack.com/archives/D05NPD8CX7H/p1692786142224839)
Ok. Will do. Thanks for the explanations.







Andrew Rouse
  [3:52 PM](https://ibm-cloud.slack.com/archives/D05NPD8CX7H/p1692786165081729)
I know that websphere liberty has had similar functionality for many years with installUtility install, so part of it may be wanting to retain that functionality for customers who were still using it.







Ramkumar K
  [3:53 PM](https://ibm-cloud.slack.com/archives/D05NPD8CX7H/p1692786212320919)
ok. Thanks.
Will followup with the install team





[3:53](https://ibm-cloud.slack.com/archives/D05NPD8CX7H/p1692786221444189)
Thanks Andrew.





[3:53](https://ibm-cloud.slack.com/archives/D05NPD8CX7H/p1692786227751339)
Good Day!





[3:53](https://ibm-cloud.slack.com/archives/D05NPD8CX7H/p1692786236499109)
:sun2:







Andrew Rouse
  [3:56 PM](https://ibm-cloud.slack.com/archives/D05NPD8CX7H/p1692786417561189)
:blob-yw:

**Comment by ramkumar-k-9286** [comment]
HI David @dmuelle 

Added a note to the installFeature page. Draft link:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/command/featureUtility-installFeature.html

Please review the same.

Regards,
Ramkumar.

**Comment by dmuelle** [comment]
I think this is not quite right- you can install multiple features with installFeatrue, you just have to list them individually. So the benefit is not so much that you can install more than one feature

> The featureUtility installFeature command manually installs an individual Open Liberty feature. However, if you have a server.xml file with multiple feature definitions, you might want to ensure all these features are installed. For that particular server configuration, you can use the featureUtility installServerFeatures command.

---->

> The featureUtility installFeature command installs one or more Open Liberty features that you list on the command line. However, to automatically install all the features that specified in your server configuration,  use the <featureUtility installServerFeatures > (link) command instead. The featureUtility installServerFeatures command is the recommended tool to install a specific set of features for your server in most cases.

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Made the suggested corrections. Draft link:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/command/featureUtility-installFeature.html

Please review the same.

Regards,
Ramkumar.

**Comment by dmuelle** [comment]
LGTM- send to staging when you have a chance. Thanks

**Comment by dmuelle** [comment]
nm- spoke too soon. There's a typo

However, to automatically install all the features that specified in your server configuration,
--->
However, to automatically install all the features that _are_ specified in your server configuration,

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Made the suggested correction. Draft link:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/command/featureUtility-installFeature.html

Please review the same.

Regards,
Ramkumar.

**Comment by dmuelle** [comment]
LGTM- send to staging when you have a chance. Thanks

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Staging link:

https://docs-staging-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/command/featureUtility-installFeature.html

Please review the same.

Regards,
Ramkumar.

**Comment by dmuelle** [comment]
Content is on vNext and will publish with 23.0.0.9. Closing as completed.
