### ISSUE TITLE
Add template for feature issues

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#6902]
create a Git issue template for feature issues to help developers provide structured descriptions of new features that help doc team hit the ground running on new feature doc

**Comment by dmuelle** [comment]
Hi @chirp1 @ramkumar-k-9286 the feature issue template is now available for review. To see it, just click the "New Issue" button and select "Open a feature issue" from the options.

**Comment by chirp1** [comment]
@dmuelle My thoughts:

- For the [page with the doc templates](https://github.com/OpenLiberty/docs/issues/new/choose):
  - Change "Open an feature issue" to "Open a feature issue".
  - In the description, change "....to satisfy documentation requirements...." to "....to specify documentation requirements....".
  
- For the content of the template:
  - Remove "Use this template for updates associated with Open Liberty development epics." since they new this when the picked the template.
  - Remove the bold tagging throughout the template. The section headers display as bold or bigger text. The content in the section can be regular instead of bold text. 
  - Remove "Title the issue Documentation:<Development epic name> and provide some sort of header for the first section. 
  - Include instructions about the title as the first list item in the same list as the epic link and the target ga.
  - Add a section an operating system section, something like "Does the epic apply to all operating systems?, and then list items of "Yes", "No" with a check box for each. And then if no, include something like "Specify operating systems____".

**Comment by chirp1** [comment]
@dmuelle LGTM
