### ISSUE TITLE
MP 6.1 and 6.0 Difference

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/docs#7062]
This is a docs issue for the MicroProfile 6.1 umbrella feature.

We will need a new page which describes the differences between MP 6.0 and MP 6.1 (Similar to this one - https://openliberty.io/docs/latest/reference/diff/mp-41-50-diff.html).

A good starting point for this content would be to take the MP 6.1 section of the 22.0.0.13-beta blog post - https://openliberty.io/blog/2023/09/26/23.0.0.10-beta.html#mp61

**Comment by Emily-Jiang** [comment]
This should list the difference between:
MP Telemetry 1.0 and 1.1
MP Metrics 5.0 and 5.1

**Comment by Emily-Jiang** [comment]
@benjamin-confino can you provide the MP Telemetry difference and @Channyboy covers the metrics part.

**Comment by Emily-Jiang** [comment]
There is no functional differences between MP Config 3.0 and 3.1. Only a minor spec clarification and some TCKs updates to make TCKs working with CDI Lite.

**Comment by Channyboy** [comment]
Since @yasmin-aumeeruddy made an initial PR that only contains the telemetry content. I'll add the content for the metrics section here for @ramkumar-k-9286  to consolidate.

---------

[#metrics]
== Differences between MicroProfile Metrics 5.0 and 5.1

The MicroProfile Metrics 5.1 release introduces a swathe of new MicroProfile Config properties used to customize the metric data that is tracked and output by the histogram and timer metrics. The new properties introduced in MicroProfile Metrics 5.1 allow you to define a custom set of percentiles as well as a custom set of histogram buckets for the Histogram and Timer metrics. There are also additional configuration properties for enabling a default set of histogram buckets, including properties for defining an upper and lower bound for the bucket set.

The new properties are as follows:
|===
|Name| Description
|mp.metrics.distribution.percentiles | Customize the percentile/quantile output for histogram and timers
|mp.metrics.distribution.histogram.buckets | Customize the set of histogram-buckets to be output by histogram metric
|mp.metrics.distribution.timer.buckets | Customize the set of histogram-buckets to be output by timer metric
|mp.metrics.distribution.percentiles-histogram.enabled | Enable a pre-set list of histogram-buckets for the histogram or timer metric
|mp.metrics.distribution.histogram.min-value | Upper bound bucket for pre-set list of histogram-buckets for histogram metric
|mp.metrics.distribution.histogram.max-value | Lower bound bucket for pre-set list of histogram-buckets for histogram metric
|mp.metrics.distribution.timer.min-value | Upper bound bucket for pre-set list of timer-buckets for histogram metric
|mp.metrics.distribution.timer.max-value | Lower bound bucket for pre-set list of timer-buckets for histogram metric
|===

For detailed information on the properties and how to use them, see xref:microprofile-config-properties.adoc#metrics[MicroProfile Config properties: MicroProfile Metrics].

For example, the below sample of MicroProfile Config definitions are configuring the `alpha.timer` timer metric to output the 50th, 70th, 75th and 80th percentile along with histogram-buckets that track and output the count of durations that fall within 0-100ms, 0-200ms, and 0-1 seconds. These values are ranges because the histogram buckets work cumulatively .
```
mp.metrics.distribution.percentiles=alpha.timer=0.5,0.7,0.75,0.8
mp.metrics.distribution.timer.buckets=alpha.timer=100ms,200ms,1s
```

The corresponding Prometheus output for the alpha.timer metric at the /metrics REST endpoint is:

```
# HELP alpha_timer_seconds_max  
# TYPE alpha_timer_seconds_max gauge
alpha_timer_seconds_max{scope="application",} 5.633
# HELP alpha_timer_seconds  
# TYPE alpha_timer_seconds histogram <1>
alpha_timer_seconds{scope="application",quantile="0.5",} 0.67108864
alpha_timer_seconds{scope="application",quantile="0.7",} 5.603590144
alpha_timer_seconds{scope="application",quantile="0.75",} 5.603590144
alpha_timer_seconds{scope="application",quantile="0.8",} 5.603590144
alpha_timer_seconds_bucket{scope="application",le="0.1",} 0.0 <2>
alpha_timer_seconds_bucket{scope="application",le="0.2",} 0.0 <2>
alpha_timer_seconds_bucket{scope="application",le="1.0",} 1.0 <2>
alpha_timer_seconds_bucket{scope="application",le="+Inf",} 2.0  <2><3>
alpha_timer_seconds_count{scope="application",} 2.0
alpha_timer_seconds_sum{scope="application",} 6.333
```
<1> The Prometheus metric type is histogram. Both the quantiles/percentile and buckets are represented under this type.
<2> The le tag represents less than and is for the defined buckets which are converted to seconds.
<3> Prometheus requires that a +Inf bucket which count all hits.

---

Additionally, the `@RegistryScope` annotation that can be optionally used when injecting a metric registry is now a CDI qualifier.

**Comment by ramkumar-k-9286** [comment]
Hi @benjamin-confino 
As requested by Emily, can you provide the MP Telemetry difference?

**Comment by ramkumar-k-9286** [comment]
@Emily-Jiang @Channyboy @yasmin-aumeeruddy

Hi, 
A new page which describes the differences between MP 6.0 and MP 6.1 is done.

draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/diff/mp-60-61-diff.html

Please review the same, when you have time.

Regards,
Ramkumar


CC @dmuelle

**Comment by Emily-Jiang** [comment]
can you remove this following:

> and replaces MicroProfile OpenTracing with MicroProfile Telemetry.
> 
> Therefore, MicroProfile OpenTracing moves out of the umbrella release and becomes a stand-alone specification. For more information about Jakarta EE 10 Core Profile, see the [Core Profile specification](https://jakarta.ee/specifications/coreprofile/10/).

as these are identical bits for both MP 6.0 and MP 6.1.

Instead, the first paragraph should be replaced by the following:

MicroProfile 6.1 is a minor release. It includes the minor changes from Config 3.1, Metrics 5.1, Telemetry 1.1. 

For Config 3.1, there is no functional change apart from some TCK updates and a minor spec clarification (The "profile-specific" concept only influences which value is to be surfaced per config source).

**Comment by ramkumar-k-9286** [comment]
@Emily-Jiang 

Hi,
Suggested corrections have been made.

draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/diff/mp-60-61-diff.html

Please review the same when you have time.

Regards,
Ramkumar

CC @dmuelle

**Comment by Emily-Jiang** [comment]
> @Emily-Jiang
> 
> Hi, Suggested corrections have been made.
> 
> draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/diff/mp-60-61-diff.html
> 
> Please review the same when you have time.
> 
> Regards, Ramkumar
> 
> CC @dmuelle

For some reason, I don't see any of my suggested changes reflected in the new draft doc.

**Comment by ramkumar-k-9286** [comment]
@Emily-Jiang 

Hi, 
It might have been a build issue.

I checked the draft build; the changes made are now displayed:

draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/diff/mp-60-61-diff.html

Please review the same when you have time.

Regards, 
Ramkumar

**Comment by Emily-Jiang** [comment]
@ramkumar-k-9286 I can now see the updates. Can you update this sentence:

> The update makes it clear that the profile-specific feature has no functional impact and influences only the values that are chosen from each configuration source.

The update makes it clear that the profile-specific feature influences only the values that are chosen from each configuration source not among the configuration sources. The TCK updates ensure the tests working with CDI Lite.

**Comment by ramkumar-k-9286** [comment]
@Emily-Jiang

Hi,
Suggested changes have been made.

draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/diff/mp-60-61-diff.html

Please review it when you have time.

Please add the `Developer Reviewed` label if you are satisfied with the changes.

Regards,
Ramkumar

**Comment by Emily-Jiang** [comment]
looks good! Thanks @ramkumar-k-9286

**Comment by dmuelle** [comment]
## Peer review

MicroProfile 6.1 is a minor release. It includes the minor changes from Config 3.1, Metrics 5.1, Telemetry 1.1.
--->
MicroProfile 6.1 is a minor release. It includes minor changes for the MicroProfile Config 3.1, Metrics 5.1, and Telemetry 1.1 features.

----

The changes for Config 3.1 are minor specification refinements and TCK improvements. The update makes it clear that the profile-specific feature affects only the values that are selected from each configuration source, not among the configuration sources. The TCK updates make sure that the tests are compatible with CDI Lite.

--->

The changes for MicroProfile Config 3.1 are minor specification refinements and TCK improvements. The update clarifies that the profile-specific properties affect only the values that are selected from each configuration source, not among the configuration sources. The TCK updates make sure that the tests are compatible with CDI Lite.

Also, this info should go in a "Differences between MicroProfile Config 3.1 and 3.0" section, which should be included in the anchor list

----

introduces a swathe of new MicroProfile Config properties that are used to customize
--->
introduces a set of new MicroProfile Config properties that customize

----

MicroProfile Metrics 5.1 introduces new properties that make it possible for you to specify a custom range of percentiles and a custom set of histogram buckets specifically for Histogram and Timer metrics.
--->
MicroProfile Metrics 5.1 introduces properties that specify a custom range of percentiles and a custom set of histogram buckets specifically for histogram and timer metrics.

----

Broken link:
For more information on the properties and how to use them, see the [MicroProfile Config properties: MicroProfile Metrics](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/diff/mp-60-61-diff.html#microprofile-config-properties.adoc#metrics).

----

Also, the @RegistryScope annotation, suitable for use during metric registry injection, is now a CDI qualifier.
--->
Also, the `@RegistryScope` annotation, suitable for use during metric registry injection, is now a CDI qualifier.

----

MicroProfile Telemetry 1.1 equips developers with the most recent Open Telemetry technology; this feature now uses OpenTelemetry-1.29.0, upgraded from 1.19.0
--->
MicroProfile Telemetry 1.1 equips you with the most recent Open Telemetry technology. This feature now uses OpenTelemetry-1.29.0, upgraded from 1.19.0

**Comment by ramkumar-k-9286** [comment]
@dmuelle 

Hi,
Peer review comments were incorporated.

draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/diff/mp-60-61-diff.html

Regards,
Ramkumar
