### ISSUE TITLE
Asynchronous I/O

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#727]
Take from https://developer.ibm.com/wasdev/docs/asynchronous-io-what-is-it-and-why/ and update as necessary to apply to current versions and to cloud-native microservices development.

**Comment by dmuelle** [comment]
https://github.ibm.com/was-WASdev/WASdevnet-website/tree/master/developer.ibm.com/wasdev/docs/asynchronous-io-what-is-it-and-why

backup copy of that async I/O WASdev article

**Comment by Charlotte-Holt** [comment]
First point of contact: Martin Mulholland (who wrote the blog)

**Comment by Charlotte-Holt** [comment]
@pnicolucci Here's a link to the first draft: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/async-io.html. Please review and let me know if you have any suggestions.

**Comment by Charlotte-Holt** [comment]
@pnicolucci I've incorporated your requested updates. Please review the topic at https://draft-openlibertyio.mybluemix.net/docs/21.0.0.1/async-io.html and let me know if further updates are needed. Thanks!

**Comment by pnicolucci** [comment]
@Charlotte-Holt  sorry for the delay. The link doesn't look to be valid any longer can you post a new one and I'll review ASAP?

**Comment by pnicolucci** [comment]
Changes look good!

**Comment by ManasiGandhi** [comment]
@Charlotte-Holt #peerreview. The doc looks good and you have addressed the points very well. Just a few edit suggestions:

- [x] Your example descriptions do a good job of elaborating on the comments in the code. Could you remove the comments inside the code blocks?

 **Short Description**

- [x] Edit suggestion: "With asynchronous read and asynchronous write, inbound data can be processed more quickly and outbound responses can be written more quickly than with synchronous read and synchronous write." to, "Asynchronous read and asynchronous write help you process inbound data and write outbound responses faster than synchronous read and synchronous write."

**Asynchronous read**

- [x] In "In asynchronous read, the application relinquishes the thread after the first packet is received from the client and is redispatched when the second packet arrives." could you elaborate on what is being redispatched here? Is it the thread? In that case could you update the sentence to "In asynchronous read, the application relinquishes the thread after the first packet is received from the client and the thread is redispatched when the second packet arrives.", or as appropriate?
- [x] "With asynchronous read, you remove this variable so you have better, more consistent throughput." Could you specify the variable in "this variable"?

**Register a WriteListener**

- [x] This example shows a service method that includes the two steps that are required to perform asynchronous write." Could you add a noun to "asynchronous write", for example "function", "operation", as appropriate.

**Write an outbound response**

- [ ] Also, for "IllegalStateException" in, " A second write of data that’s performed after a call to the isReady method is effectively a synchronous write and results in an IllegalStateException", should there be a noun added, for example, "class", or it's implied IllegalStateException is an exception and doesn't need a noun added?
- [x] In "The isReady method is called before every write of data.", Acrolinx is flagging "write" in this sentence.
- [x] Also, Acrolinx is flagging the word "perform".
- [x] "If the onWritePossible method returns when the isReady method returns true and more data must be written, the container doesn’t call the onWritePossible method again until the isReady method is called and returns false.", the sentence is long. Could you split it in two sentences?
- [x] "If the response data isn’t available before the WriteListener object is registered, the method needs to return when the isReady method is true even though some of the response data wasn’t written.", the sentence is long, can you shorten or split it.

**Comment by Charlotte-Holt** [comment]
@ManasiGandhi Thanks for the review! I addressed all your feedback except

> Also, for "IllegalStateException" in, " A second write of data that’s performed after a call to the isReady method is effectively a synchronous write and results in an IllegalStateException", should there be a noun added, for example, "class", or it's implied IllegalStateException is an exception and doesn't need a noun added?

I think that because it's implied that `IllegalStateException` is an exception, it's okay in this instance. "`IllegalStateException` exception" seems very clunky. 

Update to latest draft: https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.3/async-io.html

**Comment by dmuelle** [comment]
## Peer Review
Nice work on a complex topic @Charlotte-Holt - a few suggestions

### Short desc
The second sentence reads  a bit awkwardly : "you can benefit your server.." maybe...

By following the requirements for implementing asynchronous read and asynchronous write, you can benefit your Open Liberty server, particularly if large amounts of post data or response data must be processed.
-->
Asynchronous read and asynchronous write can improve the throughput of your Open Liberty server, particularly if large amounts of post data or response data must be processed.


### Asynchronous read

- two packets of data that are sent 1 second apart by the client.
-->
two packets of data that are sent one second apart by the client.
Similar for the other two instances of "1 second"

- If throughput is affected by the rate at which data is received, it takes only a few bad clients and throughput drops.

Reads a bit awkwardly, I think "it takes only a few bad clients..." is an expletive construction, maybe:

If throughput is affected by the rate at which data is received, a few bad clients can significantly reduce throughput.


### Read and store inbound data

- Avoid modal "should"
If it returns false, all currently available data was read, so the thread should be relinquished. 
-->
If it returns false, all of the currently available data was read, so the thread is relinquished. 

-  Although I _think_ I get the gist, the second bullet point about the "While" loop is really hard to understand. It might be easier if these two consecutive sentences were parallel:

" If the onDataAvailable method returns when the isReady method returns true and more data is available to be read, the container doesn’t call the onDataAvailable method again until the isReady method is called and returns false. If the onDataAvailable method returned when the call to the isReady method returned true and all of the data wasn’t read, your application must call the onDataAvailable method again to restart the read. "

The second sentence uses "returned" where the first used "returns". And the second sentence has the clause "when the call to the.." which the first does not. I think both these sentences are talking about opposing cases of the same conditions and that would come through clearer if the sentences were more strictly parallel.

### Process inbound data

- The onAllDataRead method performs the business logic based on the inbound data, _as shown in the following example_:

### Asynchronous write

- But in asynchronous write, a thread isn’t occupied while it waits for the client to acknowledge receipt of data. As a result, throughput can be increased because a thread isn’t held to wait for the client to acknowledge receipt of data. 

I think you could make this more concise, like

But in asynchronous write, throughput can be increased because the thread isn’t occupied while it waits for the client to acknowledge receipt of data

### Asynchronous write sample code

The following examples show the key requirements for how you might implement asynchronous write in your code. 
-->
The following examples show the key requirements to implement asynchronous write in your code. 

- Should [the ReadListener.onAllDataRead method](https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.2/async-io.html#readlistener-onalldataread)  be the [ReadListener.onAllDataRead](https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.2/async-io.html#readlistener-onalldataread) method ?

### Register a WriteListener --> Register a WriteListener object/implementation

WriteListener implementation or WriteListener object ? Doc uses both but should prob be one consistently and also add to the heading (assuming they refer to the same thing...)

### Write an outbound response

- Data is written a second time after a call to the isReady method is effectively a synchronous write and results in an IllegalStateException

I feel like something is missing here- Should is be "Data _that_ is written...". The two "is" clauses w/out a "that" or "and" make the meaning hard to pin down.

**Comment by Charlotte-Holt** [comment]
@dmuelle I incorporated all your feedback. Thanks! Could you take a looks and add the `peer reviewed` label if this is good to go to editorial review?

**Comment by chirp1** [comment]
Hi Charlotte, Very nice job on writing the OL topic from the WASdev topic!
Here are my comments:
- global update: where you reference "true" and "false", usually as return values, changing the wording to, for example returns a true value, returns a false value. Also, highlight "true" and "false".
- Change "...entire time it takes to receive the data sent by the client." to "...entire time that it takes to receive the data that the client sends.". (Get rid of empty "it".)
- Change "Assume that it takes 0.1 seconds to process each inbound packet, so the..." to "Assume that each inbound request takes 0.1 seconds to process so that the ...". (Get rid of empty "it".)
- "Otherwise, the servlet and the ReadListener object compete to process." seems awkward, How about "Otherwise, the servlet processing and the ReadListener object processing compete with each other.".
- Euter put a noun after   "IllegalStateException " or  say the English, such as ".....effectively a synchronous read and results in an illegal state exception for the method.". I saw a comment in your issue about using "exception" for the noun. You can use "exception".
- For "The onDataAvailable method doesn’t return unless the isReady method returns false or all data is read.", from looking at the async.html article on wasdev, I think that the sentenc should be "The onDataAvailable method isn't called unless the isReady method returns false and all data is read. ". (replaced "doesn't return" with "isn't called" and "or" with "and".
- Change "...the inbound data is being processed." to "...the inbound data is processed.".
- Change "In this simple example, the data is..." to "The data is... " (Remove "In this simple example,".)
- For "In the previous asynchronous example code, the ReadListener.onAllDataRead method...", From looking at Martin's WASdev article, I think he intead means "in this situation" as I don't see a reference to WriteListener. So, I would say, replace "In the previous asynchronous example code," with something like, "In this situation, the ReadListener.onAllDataRead method...".
- For "response data can be sent without blocking.". Something needs to come after "blocking". Maybe something like "without blocking other processes". Paul might have a better answer. 
- Change "In this example, the service method ..." to "The service method...".
- Remove "are" from "After these steps are complete,...".
- Change "After these steps are complete, " to "After these steps complete, ".
- Change "Otherwise, the servlet and the WriteListener object compete to process. " to something like "Otherwise, the servlet processing and the WriteListener object processing compete with each other.".
- Change "results in an IllegalStateException. " to "results in an IllegalStateException exception. "
- Change "....response data wasn’t written." to "...response data isn’t written." (Use present tense.)
- Change "...response data is being processed." to "response data is processed.".
- Some sentences are repeated. In the second to the last bullet, the repeated part starts with "One effect of this requirement is that all of the response data ..." and goes to the end of the paragraph. Then, the second to the last paragraph repeats the information and has a little more information. Resolve the situation with the repeating content.

**Comment by Charlotte-Holt** [comment]
@chirp1 I addressed your feedback:

https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.3/async-io.html

- [x] global update: where you reference "true" and "false", usually as return values, changing the wording to, for example returns a true value, returns a false value. Also, highlight "true" and "false".
- [x] Change "...entire time it takes to receive the data sent by the client." to "...entire time that it takes to receive the data that the client sends.". (Get rid of empty "it".)
- [x] Change "Assume that it takes 0.1 seconds to process each inbound packet, so the..." to "Assume that each inbound request takes 0.1 seconds to process so that the ...". (Get rid of empty "it".)
- [x] "Otherwise, the servlet and the ReadListener object compete to process." seems awkward, How about "Otherwise, the servlet processing and the ReadListener object processing compete with each other.".
- [x] Euter put a noun after "IllegalStateException " or say the English, such as ".....effectively a synchronous read and results in an illegal state exception for the method.". I saw a comment in your issue about using "exception" for the noun. You can use "exception".
- [x] For "The onDataAvailable method doesn’t return unless the isReady method returns false or all data is read.", from looking at the async.html article on wasdev, I think that the sentenc should be "The onDataAvailable method isn't called unless the isReady method returns false and all data is read. ". (replaced "doesn't return" with "isn't called" and "or" with "and".
- [x] Change "...the inbound data is being processed." to "...the inbound data is processed.".
- [x] Change "In this simple example, the data is..." to "The data is... " (Remove "In this simple example,".)
- [x] For "In the previous asynchronous example code, the ReadListener.onAllDataRead method...", From looking at Martin's WASdev article, I think he intead means "in this situation" as I don't see a reference to WriteListener. So, I would say, replace "In the previous asynchronous example code," with something like, "In this situation, the ReadListener.onAllDataRead method...".
- [x] For "response data can be sent without blocking.". Something needs to come after "blocking". Maybe something like "without blocking other processes". Paul might have a better answer.
- [x] Change "In this example, the service method ..." to "The service method...".
- [x] Remove "are" from "After these steps are complete,...".
- [x] Change "After these steps are complete, " to "After these steps complete, ".
- [x] Change "Otherwise, the servlet and the WriteListener object compete to process. " to something like "Otherwise, the servlet processing and the WriteListener object processing compete with each other.".
- [x] Change "results in an IllegalStateException. " to "results in an IllegalStateException exception. "
- [x] Change "....response data wasn’t written." to "...response data isn’t written." (Use present tense.)
- [x] Change "...response data is being processed." to "response data is processed.".
- [x] Some sentences are repeated. In the second to the last bullet, the repeated part starts with "One effect of this requirement is that all of the response data ..." and goes to the end of the paragraph. Then, the second to the last paragraph repeats the information and has a little more information. Resolve the situation with the repeating content.

**Comment by chirp1** [comment]
Hi Charlotte,
I have comments on your changes, plus I spotted a few other things to change;
- Globally, change "wasn't" to "isn't.
- Globally, change "was" to "is". 
- My suggested fix for the empty "it" still had the empty "it" in it. How about if you change "...for the entire time that it takes to receive the data that the client sends.  to "...for the entire time that the client takes to send the data.". 
- For my suggested word of "Assume that each inbound request takes 0.1 seconds to process so that the ...".", include the "that".
- I believe this sentence is supposed to be removed as the sentence following it is the update from one of my previous comments: "Otherwise, the servlet and the WriteListener object compete to process".
- Change "...response data wasn’t yet written." to "...response data isn’t yet written.".
- For "...isReady method is a value of true" to "isReady method is set to the true value".
- I still seem to see "One effect of this requirement is that all of the response data must be available before the WriteListener object is registered." at the end of the next to the last bullet. It wasn't in the bullet in the WASdev article. How about if you remove this sentence? It says the same thing as "One effect of this second requirement is that all of the response data must be available before the WriteListener object is registered. ", which starts the next to the last paragraph.

**Comment by Charlotte-Holt** [comment]
@chirp1 Updates made!

https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.3/async-io.html

- [x] Globally, change "wasn't" to "isn't.
- [x] Globally, change "was" to "is".
- [x] My suggested fix for the empty "it" still had the empty "it" in it. How about if you change "...for the entire time that it takes to receive the data that the client sends. to "...for the entire time that the client takes to send the data.".
- [x] For my suggested word of "Assume that each inbound request takes 0.1 seconds to process so that the ...".", include the "that".
- [x] I believe this sentence is supposed to be removed as the sentence following it is the update from one of my previous comments: "Otherwise, the servlet and the WriteListener object compete to process".
- [x] Change "...response data wasn’t yet written." to "...response data isn’t yet written.".
- [x] For "...isReady method is a value of true" to "isReady method is set to the true value".
- [x] I still seem to see "One effect of this requirement is that all of the response data must be available before the WriteListener object is registered." at the end of the next to the last bullet. It wasn't in the bullet in the WASdev article. How about if you remove this sentence? It says the same thing as "One effect of this second requirement is that all of the response data must be available before the WriteListener object is registered. ", which starts the next to the last paragraph.

**Comment by chirp1** [comment]
The updates look good!

**Comment by Charlotte-Holt** [comment]
Merged to `vNext` in https://github.com/OpenLiberty/docs/pull/3727 and KC spreadsheet updated.
