### ISSUE TITLE
Can we provide guidance for Spring Boot major.minor (x.y.*) versions supported by thinning utility at a given Liberty version?  Micro? (x.y.z)?

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/docs#7284]
Do we need a doc process for capturing items like this somewhere?

support for 3.2 thinning in 24.0.0.1:  https://github.com/OpenLiberty/open-liberty/pull/27276
@hlhoots

**Comment by dmuelle** [comment]
Hi Scott- the current doc includes the following guidance as prereq for configuring thin SB apps :

> If your application uses Spring Boot 3.0.4+, enable the [springBoot-3.0](https://openliberty.io/docs/latest/reference/feature/springBoot-3.0.html) feature.

Does that cover the current capability? I would expect we would explicitly "announce" support for new versions in a release post, but not necessarily update the doc unless the 3.0 statement is no longer current. I'm not sure how this update was tracked-  since there was no dev epic, it didn't show up in any release announcements.

**Comment by dmuelle** [comment]
consolidating this issue with #7296
