### ISSUE TITLE
Doc changes needed for RESTful Metrics

### ISSUE THREAD

**Issue by jim-krueger** [OpenLiberty/docs#745]
Adding monitor and mpmetrics information for RESTful Resourse methods.

https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_monitor10.html
1.  Needs to add "WebSphere:type=REST_Stats,name=* for RESTful resource methods

2.  Need to add a link to a RESTful resource method monitoring page with the description, "You can use a restful MXBean for RESTful resource method monitoring of Liberty.

3.  We will need a new page similar to https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_mon_webapp.html

3a.  The page can be called RESTful resource method monitoring

3b.  It should contain this information:
You can use a restful MXBean for RESTful resource method monitoring of Liberty.

Performance data is available for each RESTful resource method  in the web application. Each method has its own MXBean.
The ObjectName for identifying each restful MXBean is:

WebSphere:type=REST_Stats,name=<AppName><ModuleName>/<MethodName>

For example:

WebSphere:type=REST_Stats,name=MyApp.MyModule.com.test.MyResource.myMethod()

This MXBean is responsible for reporting REST_Stats for each resource method. Following key data is available for the REST_Stats MXBean:

    Request Count
    Cumulative Response Time
    Servlet Name
    Application Name

Counter definitions (Attributes to MXBean)

        AppName: Name of the application.
        ServletName: Name of the servlet.
        RequestCount: Number of hits to this servlet.
        ResponseTime: Cumulative response time (nano-seconds).
        Description: Description of counter.
        RequestCountDetails: RequestCount Details that include the request count.
        ResponseTimeDetails: ResponseTime Details that include the number of snapshots that are taken, minimum values, and maximum values.

**Comment by chirp1** [comment]
Jim and I discussed this issue. The updates will go into Open Liberty only. Since the writers are working down a prioritised backlog, the updates might be made after eGA. Jim will update the GA blog with enough info so that users can use the Epic.

**Comment by Charlotte-Holt** [comment]
@jim-krueger I made these updates in https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/jmx-metrics-list.html. Please review and let me know if any additional updates are needed. Thx!

**Comment by jim-krueger** [comment]
@Charlotte-Holt  I have a couple changes that should be made:

1. Missing attribute:  "MethodName".   Units: "Not applicable".  Description: "The name of the RESTful resource method"

2. Change attribute: "Description".  The description should be "A general description for these attributes."

3.  Change attribute: "RequestCount".  The UNITs should be "Integers".  The description should be "The number of hits to this RESTful resource method."

4.  Remove attribute:  "ServletName".   This attribute is not valid for the REST_Stats MSBean

**Comment by Charlotte-Holt** [comment]
Hi, @jim-krueger. Thanks for the feedback. I incorporated all of these updates into https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/jmx-metrics-list.html#rest-stats, except the units for `RequestCount`. I'm assuming it's a counter? We have other counters that have units as "Not applicable", for example `ReceivedMessagesCount`, so I'm thinking they either all need to be changed to "Integers" or they all need to be "Not applicable" for consistency in the doc. 

@Channyboy Can you provide the info that needs updating from your side, and I'll add it into the doc?

**Comment by Channyboy** [comment]
@Charlotte-Holt 
|MXBean attribute| Units| Description|
|---|---| ---|
|MinuteLatest | Minute<1> | The latest (most-recent)  minute in which an update was made to this MXBean. The latest minute can be the _current_ on-going minute. |
|MinuteLatestMaximumDuration| Nanoseconds | The longest recorded _ResponseTime_ **within<2>** the _latest (most-recent) minute_ in which an update was made to this MXBean. The latest minute can be the _current_ on-going minute. |
|MinuteLatestMinimumDuration| Nanoseconds | The shortest recorded _ResponseTime_ **within<2>** the _latest (most-recent) minute_ in which an update was made to this MXBean. The latest minute can be the _current_ on-going minute. |
|MinutePrevious | Minute<1>  | The second-most recent minute (prior to the _MinuteLatest)_  in which an update was made to this MXBean.|
|MinutePreviousMaximumDuration| Nanoseconds | The longest recorded _ResponseTime_ **within<2>**  the second-most recent minute (prior to the _MinuteLatest)_ in which an update was made to this MXBean.|
|MinutePreviousMinimumDuration| Nanoseconds |The shortest  recorded _ResponseTime_ **within<2>**  the second-most recent minute (prior to the _MinuteLatest)_ in which an update was made to this MXBean.|


<1> Minutes since Epoch (00:00:00 UTC on January 1, 1970)
<2>Within is defined as 0:00:00 - 0:59:999

**Comment by Charlotte-Holt** [comment]
@Channyboy Thank you! I added these metrics: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/jmx-metrics-list.html#rest-stats. Please review these changes and let me know if further updates are needed.

**Comment by Channyboy** [comment]
The changes made look good!

**Comment by jim-krueger** [comment]
Looks good to me as well!  Thanks

**Comment by Charlotte-Holt** [comment]
These changes are now all incorporated into the JMX metrics topic (#1286) that will publish in 20.0.0.12. Closing this issue.
