### ISSUE TITLE
Liberty docs are not task docs

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/docs#7657]
This [page](https://openliberty.io/docs/latest/prepare-mptelemetry.html) has been written as a task and Liberty docs are not tasks.

It is also wrong for a dev topic to link to an ops topic for important context.

**Comment by lauracowen** [comment]
To clarify, I think Alasdair's point is not that we don't document how-to information at all in the Liberty docs, but that we don't make everything into a WebSphere Liberty-style task topic when it's not necessary. In particular in this instance, no one cares about preparing their development environment for Telemetry; that's not a something someone would have in their heads to do. What they care about is adding observability to their applications. Enabling the telemetry feature is a minor step in that, not a whole task in itself.

The reason that we care about this is that the approach of adding many tasks in the Liberty IBM Docs has led to many unnecessary topics, bloating the entire set of docs and making it harder to find the information you actually need. That's not to say that the OL docs are perfect by any means, but laying the Liberty IBM Docs format on them like this is not going to help.

It mostly comes down to understanding the target audience and ensuring that the information that user audience needs, and only the information that they need, is provided, as concisely as possible.

**Comment by lauracowen** [comment]
I general, I don't think it's necessarily bad to link to topics for aimed at other users _as long as that information is relevant to the user you're currently writing for_ (and it's clear what info you're expecting them to read there).

In this particular case, though, I agree with Alasdair because the developer needs to understand things like application vs runtime-level configuration in the context of the app they're developing and what to choose etc. The current approach of just linking to the OPERATIONS topic is dumping and running - how is the developer meant to decide what to set? The "preparing dev env" topic is fairly uninformative and doesn't need to exist, but the info the developer actually needs isn't available to them. That info should be provided in a topic in the DEVELOPMENT section couched in language that makes sense to the developer in an intro/overview topic called something like "Observability in microservices" in the DEVELOPMENT section.

**Comment by dmuelle** [comment]
copying these comments to #7655 to address with the greater revision of telemetry/observability docs
