### ISSUE TITLE
Basic registry for development 

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#892]
From LC: Introduce basic registry (username/password) for developers to use when securing their app during development - not for production use. With basic registry, the user registry is in the `server.xml` file so it's easy to work with but it's not secure or appropriate for production use. Quickstart security provides an even easier way for developers to do basic security, though it's limited to one user. 

- Link to the securityUtility command topic for encrypting a password (#364)
- Link to the guide for an example of where the app uses it to simplify at development time: https://openliberty.io/guides/security-intro.html#configuring-the-user-registry 
- Link to the appSecurity feature gen doc with its example configs (#894)
- The title here doesn't need to be *Basic registry for development*. Reconsider the title when/after writing the topic.

**Comment by dmuelle** [comment]
draft now up for review at:

https://draft-openlibertyio.mybluemix.net/docs/ref/general/#basic-registry.html

**Comment by ManasiGandhi** [comment]
This is very well written and easy to understand.

**Comment by lauracowen** [comment]
Fab - thank you - as Manasi says, it's really well written and easy to follow.

A minor suggestion is to make the 'for development purposes' bit more explicit in the topic title? (so that it is clearly different from other topics maybe?)

I don't know if Bruce has seen this yet but when I originally defined this topic, I got the concepts of basic user registry and basic authentication confused. I think you've got it correct for basic user registry but can you make sure that it's all applicable and I haven't told you something that's about basic auth instead (I think it's all fine though in your topic).

**Comment by dmuelle** [comment]
review comments addressed in #980

**Comment by dmuelle** [comment]
updated draft at https://draft-openlibertyio.mybluemix.net/docs/ref/general/#basic-registry.html

**Comment by dmuelle** [comment]
Updates per Ajay Reddy's review:

* replace "application" references with "Open Liberty server" where appropriate
* add hash encoding to pwd example in basicRegistry
* update terminology to specify hash encoding vs encryption

 https://draft-openlibertyio.mybluemix.net/docs/ref/general/#basic-registry.html

**Comment by lauracowen** [comment]
- we should give them explanation of whether to use the server.xml or the `userRegistry.xml` file (is this the "adjacent XML file" mentioned previously or is that an include for the server.xml or something else?). Or tell them which is best and why. Guide them to use the easiest/best option that will make them most productive. I suspect the server.xml option is the one we'd want them to do but check why they might use the other?
- Rather than specifying how to configure it with the specific element name, just explain that you can specify two users and a group with passwords, for example, Asha who belongs to the admin group and Hiro who doesn't belong to any groups, so that you can test what they can each access with their different permissions. I'd rather not include xml config examples in the concept topics but if the text before is less instructional and more explanatory, it's not too bad, though not essential. Make sure to link to the config examples available in the feature doc.
- Good point to make about securing passwords. The link maybe needs to be explicit about being in the section further down the topic (right-click > open in new tab just got page not found; only left-click worked).
- QuickStart security, point to the example in the feature doc. Maybe also introduce this section as _why_ you might use this. eg If you only need to quickly test a single user, xxx (or something?). Make it clear why this is an option. I see here you've referred back again to the Asha example, so if you feel it's necessary to include the example config here, make it clearly an illustration of your scenario. Don't say "To use this element, enable xxx feature." Instead, point them to the feature doc for info about configuring/enabling. I know this sounds like splitting hairs but we need to avoid duplication of config examples/instructions (because they easily get out of sync) and also to encourage users to go find config examples consistently in the feature doc so they get used to finding them there. 
- In the User password security section, point them at the `securityUtility` command topic. I don't think you need to provide an example here of how to run the command - there should be an example in the command topic - if there isn't, add this simple hashing one as I think that's something the command is maybe commonly used for?

**Comment by dmuelle** [comment]
- we should give them explanation of whether to use the server.xml or the `userRegistry.xml` file **talked w/ ajay about this- there's no security specific reason to use a separate file. It's just a matter of personal preference- like all config in Liberty it can be in server.xml or in another file. Since we talk about tis in the server config overview, prob don't need to mention here? I've removed refs from this doc**
- **Rather than specifying how to configure it with the specific element name, just explain that you can specify two users and a group with passwords, for example, Asha who belongs to the admin group and Hiro who doesn't belong to any groups, so that you can test what they can each access with their different permissions. ** removed the example and simplified thexplanation, adding a link to config. see if that does the job**
- Good point to make about securing passwords. The link maybe needs to be explicit about being in the section further down the topic **removed the link since the example is gone**
- QuickStart security, point to the example in the feature doc. Maybe also introduce this section as _why_ you might use this. eg If you only need to quickly test a single user, xxx (or something?).**revised**  
- In the User password security section, point them at the `securityUtility` command topic. I don't think you need to provide an example here of how to run the command -**revised**

https://draft-openlibertyio.mybluemix.net/docs/ref/general/#basic-registry.html

**Comment by lauracowen** [comment]
Cool, thanks. Let's set this to publish then.

**Comment by dmuelle** [comment]
Requesting full peer review from @rw2513

**Comment by Rwalls1** [comment]
This was a well-written and concise topic, I just have a few comments:
- I think the opening sentence or short description could be enhanced here. The current sentence that starts with “Open Liberty provides” seems to mainly reiterate what the title implies. I think it could be more useful to highlight what’s most important for users or developers to know about basic user registries. While that distinction is hinted at in the following paragraphs, I think the purpose could be more clearly defined in the opening description in order for readers to immediately recognize why they should be reading the topic.
- When linking to other topics, you use two different syntaxes, such as “For more information” and “For configuration examples”. I think you should maintain one syntax throughout the topic for consistency purposes.
- In the “Application Security feature” section, I think it may help to add an additional clause or sentence, maybe even a hyperlink,  to briefly explain the significance of the Java EE security API that is mentioned in the sentence that says, "The appSecurity-3.0 feature provides the core capability for the Java EE Security API."  I think that would provide some helpful context that would further highlight the importance of the application security feature.
- For the sentence, "The basic user registry provides a fast and easy way to test the access to your protected application.”  I don’t think the phrase “fast and easy” adds much value here without an additional point of comparison to another method. Also, I think framing it in that way makes too broad of an assumption that could potentially be misleading so it might be best to rephrase this sentence if possible.

**Comment by dmuelle** [comment]
Addressed in #1444 

- updated shortdesc with a definition of user registry
- made linking syntax consistent
- removed statement re Java EE Security API as it's not necessary to understand basic user registry concept, and likely to go out of date with transition from Java->jakarta
- removed "fast and easy" sentence, combined remaining sentence with following pp

**Comment by arkarkala** [comment]
Developer Reviewed

**Comment by dmuelle** [comment]
This content was moved into a single topic for User registries, tracked in https://github.com/OpenLiberty/docs/issues/1784
Removed this draft from draft site
Closing this issue
