### ISSUE TITLE
SSO configuration with LTPA cookies

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#897]
From LC: This is a new concept topic that covers what LTPA is and why would you be using it. It's a form of cookie that is used to track authentication for single sign-on. When the end-user logs in, the server creates an LTPA cookie that says who the user is and then gets shared with other runtimes. It's a proprietary format by IBM/tWAS, and a more standard alternative to doing the same thing is JWT.

Source of information: 
LTPA section of https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/cwlp_authentication.html#cwlp_authentication__ltpa (this needs a better introduction to what it is)

**Comment by Rwalls1** [comment]
@areddy Please review: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#/docs/concept/sso-config-ltpa.html.

**Comment by lauracowen** [comment]
I know Ajay's not looked yet but I had a quick look and have a couple of comments about reframing the information for cloud-native microservices:

- Can you avoid talking about "application servers" in this way? Users aren't accessing app servers; they're accessing applications (eg websites). And authentication-related data is securely transmitted between microservices or services, not between servers (architecturally, yes, each app is on its own OL appserver but it's the app that matters).
- I'm not sure what it means "when they are connected to a domain name system" - can you explain it more clearly? Users are primarily accessing websites, not servers/DNS. And they're not accessing resourcse on other servers. It might be that a microservice is requesting info from another service under the user's authentication details and therefore doesn't need to re-authenticate as long as the services are in the same domain. Basically, the technical info seems to be there (as far as I understand how it works) but can you reframe it all to be a bit to be more applicable to cloud etc? Have a chat with @dmuelle  (or a peer review).
- I think the sentence "To enable…" is broken.

**Comment by Rwalls1** [comment]
@areddy Please review: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#sso-config-ltpa.html

**Comment by Rwalls1** [comment]
#1183

**Comment by Rwalls1** [comment]
@areddy Please review: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#sso-config-ltpa.html

**Comment by Rwalls1** [comment]
@lauracowen Please review: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#sso-config-ltpa.html

**Comment by Rwalls1** [comment]
@lauracowen Please review: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#sso-config-ltpa.html.

**Comment by Rwalls1** [comment]
@NottyCode Please review: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#sso-config-ltpa.html

**Comment by NottyCode** [comment]
1. I don't think the intro paragraph meshes with my understanding of LTPA. It is almost there, but not quite:

> Lightweight Third Party Authentication (LTPA) provides a method of single sign-on (SSO) configuration support to authenticate users only once when they are accessing applications. With LTPA enabled, you can encrypt, digitally sign, and securely transmit authentication-related data between applications.

It makes it sound like the intent is the end user generates an LTPA token and sends it and that is the authentication. In fact an LTPA token is generated as a result of authentication, it is then used to track the authentication session. Also while you can use LTPA to authenticate multiple applications the most common use is within an application.

2. This sentence makes it sound like LTPA is an alternative to HTTP, TLS or TCP and it isn't. It is an authentication token:

> Secure communication between applications can be enabled by using the LTPA protocol.

3. To me this suggests that it would protect session data, but it doesn't because it is just an authentication token.

> To enable the SSO feature, cryptographic keys are used to encrypt and decrypt user data that passes between applications with the LTPA protocol.

4. This sentence is much longer than it needs to be:

> When security is enabled for an Open Liberty application, LTPA is configured by default during the application start time

could simply be:

> LTPA is enabled by default when using the appSecurity features.

5. I don't want to say this because this is a security vulnerability being disclosed:

> The default location of the automatically generated LTPA keys files is ${server.output.dir}/resources/security/ltpa.keys and the default password that is used to protect the keys is WebAS.

I understand the security team have a feature to fix this

6. I think it is misleading to talk about importing LTPA keys into an application:

> This same password is required when you import the LTPA keys into another application.

7. The section "Customizing SSO configuration with LTPA cookies" feels mistitled because we haven't defined an LTPA token, in fact this section does it.

8. I don't think this sentence makes sense, it implies that a 2nd attempt would fail, but I think what is meant is you don't need to send userid/password on the second attempt, but instead send the LTPA token

> With SSO configuration support, you must authenticate only once when you access resources such as HTML, JavaServer Pages (JSP) files, and servlets or access resources in multiple applications that share LTPA keys.

9. The configuration section confused me because there is info about configuring in the prior section and it took me a while to realize this is the LTPA cookie section.

10. I don't understand this sentence:

> When a user passes authentication on one of the applications that are accessed, authentication information that is generated by the application is transported to the web browser in a cookie. 

11. Not sure why we focus on changing the cookie name and not setting the secure or samesite cookie properties which seems far more likely a scenario.

**Comment by Rwalls1** [comment]
@lauracowen Please review: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#sso-config-ltpa.html

**Comment by lauracowen** [comment]
Hi Richard,

Alasdair and I took a look at some of the SSO topics last night and we agreed we need to make some changes to how the SSO info is presented. We currently have too much info about the abstract concepts that people could better obtain elsewhere. I'm going to chat with Charlotte about it this afternoon but please can you hold off working on this topic in the meantime?

Thanks,

Laura

**Comment by lauracowen** [comment]
Superceded by #1676 so I'm closing this issue.
