### ISSUE TITLE
Threading (and why you probably don’t need to tune Open Liberty)

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#90]
We're publishing a blog post about why you don't need to tune Open Liberty (because of its auto-tuning algorithm) which should then be converted to a concept topic in the OL docs.

Blog post is here:

https://openliberty.io/blog/2019/04/03/liberty-threadpool-autotuning.html

There is potentially an argument for the Threading Settings section being a separate reference topic but the whole point is that we don't want to encourage people to changing these settings unless they really need to so I don't think we should have a separate reference topic - they should see this info only in context of the explanatory conceptual info. I could be convinced otherwise but let's start with just a single concept topic, get it reviewed, and then see what feedback we get.

Also (ask Laura), create a redirect from the blog post URL to the new topic when done.

I think this will be part of an "About Open Liberty" or "Open Liberty Architecture" or similar set of topics. @NottyCode is currently investigating what information to include there.

**Comment by dmuelle** [comment]
draft available for review at:

https://draft-openlibertyio.mybluemix.net/docs/ref/general/#Threading.html

**Comment by lauracowen** [comment]
Where it refers to the `coreThreads` and `maxThreads` towards the end, can you link here as well: https://draft-openlibertyio.mybluemix.net/docs/ref/config/#executor.html 

Otherwise, looks great. Happy for it to publish.

**Comment by chirp1** [comment]
@dmuelle Hi David, Here is the start of my review comments. I'll add to the list and let you know when I'm done.
- Rerun Acrolinx and fix the various outstanding issues. Note that "It is" is not flagged, but fix it in the same way that you would fix "there is".

**Comment by dmuelle** [comment]
Ran acrolinx again- score:98. Points lost for trademark on java (which I can add if need be) and the word "perform", which in this context I believe is correct.

**Comment by dmuelle** [comment]
- I see "automated thread pool tuning", auto-tuning, and autonomic tuning. I believe that all three variations are intending to say the same thing but are using different words that don't necessarily have the same definition. I believe that automatic or some variation of the word is what we want to use. So, when we say auto-tuning, we mean automatic tuning. Would you investigate the correct word usage? **used "self-tuning" consitently throughout**
- Rename the file so that it follows our naming convention. **what is our convention? I thought we decided against the "csec-filename" approach**
- Change the "Autonomic thread pool tuning" subtitle as it is similar to and might end up as the same name as the topic title after you make other editorial updates. How about something like "Thread pool controller behavior" since the section is about the thread pool controller. **revised**
- Change "... since the server was started." to "... from the time the server started." I think that makes the sentence clearer as "since" could mean "because", which I believe is not the intent. **revised**
- For "throughput at the various pool sizes", "at" seems a little odd. How about "throughput for the various pool sizes "? **revised**
- As mentioned in previous discussions, reword "the current cycle’s throughput" so that you are not using a possessive for an inanimate object. **revised**
- "flips a coin" is an idiom. Change the wording so that normal tehcnical wording is used. **revised**
- For "Performance is recorded as a weighted moving average for each pool size, so it reflects historical results but adjusts quickly to changing workload characteristics.", the grammar seems a little off for "pool size, so it". How about something like "Performance is recorded as a weighted moving average for each pool size. This performance reflects historical results but adjusts quickly to changing workload characteristics.". **revised**
- Change "smaller or larger pool size, decides whether to" to "smaller or larger pool size, the thread pool controller decides whether to" as the subject seems to be missing. **revised**
- This wording seems to be grammatically incorrect: "Increases, decreases, or leaves the pool size unchanged". Would you fix the wording? **revised**
- For "to resume normal execution.", as discussed previously, we don't want to use "execution". How about "to resume normal operation."? **revised**
- Change " to break out of the" to " to break out of the". (I don't think the extra "out of" is needed.)**revised**
- For "bounds for coreThreads and maxThreads", as discussed previously, put a noun after a term or change the term into human readable words. I see the two terms mentioned in multiple places, but with no noun. So, make sure that the terms are written correctly. **revised**
- Since the next section is about manual tuning, change "When to tune the Open Liberty thread pool" to include some variation of manual, maybe "Manual thread pool tuning". **revised**
- Change "spin up" to "create". (Spin up apparently has something to do with hard disk drives. Did you look up the term?) **revised**
- When I read "However, in some situations, setting the coreThreads or maxThreads attributes might be necessary." I was confused because I didn't see an explanation of when setting the attributes might be necessary. You could remove "When to tune the Open Liberty thread pool". I don't think you need a separate sub-section title. And then for "The following configuration settings are available for the Open Liberty default executor pool:", you could reword or add another sentence  specifically mention that the manual tuning is discussed in the setting descriptions. **revised**
- As appropriate, put information under the "Where to next" and "See also" headings. **added See Also**

**Comment by dmuelle** [comment]
doc is published at : https://www.openliberty.io/docs/ref/general/#thread-pool-tuning.html

**Comment by dmuelle** [comment]
@chirp1 approved this topic, adding the editorial reviewed label
