### ISSUE TITLE
Authorization in Open Liberty

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#927]
From LC:  New concept topic about authorization in Open Liberty - determines who can access a service, and which services/resources an authenticated user can access. Some resources can be accessed by anyone while others can only be accessed by certain authorized users. A backend microservice can be accessed by another microservice only if the microservice making the call is requesting on behalf of an authorized user. JSON Web Tokens are one way to pass the authorization credentials from the requesting microservice to the microservice they are trying to access.

**Scenario 1**: This topic needs to be written for a developer writing cloud-native apps that will be containerized and deployed to the cloud. 

**Resources**:
- https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/cwlp_authorization.html

**Comment by dmuelle** [comment]
Rough draft is now available for review at

https://draft-openlibertyio.mybluemix.net/docs/ref/general/#authorization.html

**Comment by dmuelle** [comment]
Updates per Ajay Reddy review:
*  replace "application" references with "Open Liberty server" where appropriate
* include info on default mapping between matching role and group names

**Comment by lauracowen** [comment]
This topic explains/covers a lot more now and makes it worth having as a separate topic. Thanks.

I think, though, it needs the structure tightening up a bit though because it currently looks like a large block of text that's not that easy to navigate, and it seems to switch back and forth between concepts within and between paragraphs.

- I think there need to be more sub-headings to signpost what's coming:
  - have the first two paras as the introductory section as they are - they're a nice intro to the concept.
  - then maybe a sub-heading of "Defining roles in the application code"
  - then another of "Defining roles in the server configuration"? (if that's accurate?)
  - then one of "Authorizing requests between web services" or something just before the para starting "Authorization occurs not only between...."
- paras 3 and 4 seem to overlap a bit awkwardly. If para 3 is meant to summarise what will then be described in more detail, maybe move the two sentences about how you can avoid defining roles to further down the topic? It currently feels like para 3 talks about mapping the roles from the app to the server config, then repeated a bit in para 4. Also, the first sentences of both para 3 and 4 seem to imply that the whole of each para will be about defining roles in the application, which isn't quite true. Would it work to discuss how to define the roles in the application in one para. Then how they're mapped in the server config in the next para?
- paras 5-7 also seem to talk about defining roles in the app, while para 8 talks about an alternative method relating to the server.xml again. Can this info be grouped with the related info in earlier paras?

Also (very minor suggestion):
- in the intro para: what about "...which resources an authenticated user can access." to tie it back to authentication straight away? (or is that not strictly accurate wording)

**Comment by dmuelle** [comment]
Hi @lauracowen - I've revised the draft per your comments. I add some subheadings and regrouped the information somewhat so each section is more self-contained

- define roles in application code
- set application resource permissions
- authorize requests between web services

I added a link to the JWT SSO topic 

re your minor suggestion- I hesitate to add "authenticated user.." to the opening para because it is possible to authorize a user who is not authenticated, as described in the @permitAll section.


https://draft-openlibertyio.mybluemix.net/docs/ref/general/#authorization.html

**Comment by lauracowen** [comment]
Hi, thanks, that's better. Some more feedback:
- maybe put diagram from Authentication topic here as well? Provides an illustration, links it back to the Authentication topic, and breaks up the page. May need to call out from the text which steps are Authz-related?
- web.xml...right, I talked to Alasdair about this...
  - almost anything you can do in web.xml you can do more directly in annotations. So we should talk about using annotations as the obvious thing anyone would do. Then add secondarily, almost as an afterthought, that you can use web.xml otherwise. Then link to a reference topic that specifies the web.xml schema (we need to create that topic if we do that).
  - Is there a topic in KC that contains the web.xml schema? Liberty is picky about it so it needs to be clear what can/can't be put in the web.xml (if we need to say anything).
  - We need to know though whether there's anything you can't do here with annotations that you can do with the web.xml approach. If so, we need to call that out here. If we find there's nothing that can't be done with annotations, we maybe only need a reference to web.xml at the end of the topic, not sure.
- ibm-application-bnd.xml file - I talked to Alasdair about this too...
  - `.bnd` should be the full file name `ibm-application-bnd.xml` (ie it's an xml file not a bnd file).
  - where it says you can use .bnd or stanzas in server.xml, lead with the server.xml option.
  - I think `HomeServlet.java` is just an example file, not a standard file. If that's a valid/useful alternative approach, it needs the purpose of HomeServlet.java explaining.

**Comment by dmuelle** [comment]
- maybe put diagram from Authentication topic here as well? Provides an illustration, links it back to the Authentication topic, and breaks up the page. May need to call out from the text which steps are Authz-related? **added the draft diagram for now, also some text description just before**
- web.xml...right, I talked to Alasdair about this...
  - almost anything you can do in web.xml you can do more directly in annotations. So we should talk about using annotations as the obvious thing anyone would do. Then add secondarily, almost as an afterthought, that you can use web.xml otherwise. Then link to a reference topic that specifies the web.xml schema (we need to create that topic if we do that). **revised- the only link to web.xml schema i could find is in the `Securing an application` guide- which is also my source for including it in this doc- same with the application-bnd approach mentioned below. The discussion here really comes out of that guide- which I guess is an older guide?**
  - 
  - We need to know though whether there's anything you can't do here with annotations that you can do with the web.xml approach. **talked to ajay- there's nothing you can't do with annotations and in general they are easier to debug than a separate file. But he said people tend to have opinions about which is better and it's not necessarily in the scope of this doc to take a side. I left it in for now since one of our guides explains how to do it.**
- ibm-application-bnd.xml file - I talked to Alasdair about this too...
  - `.bnd` should be the full file name `ibm-application-bnd.xml` (ie it's an xml file not a bnd file).
  - where it says you can use .bnd or stanzas in server.xml, lead with the server.xml option. **fixed**
  - I think `HomeServlet.java` is just an example file, not a standard file. If that's a valid/useful alternative approach, it needs the purpose of HomeServlet.java explaining. **HomeServlet.java is a standard file- though there's not much out there to explain exactly what it is. The guide calls it "The doorway to your application" without additional explantation- not sure if that's helpful. This is also something i included because it's in the guide. I think its safe to assume that in most cases this is not the preferred approach for microservices- but- is it a problem if we don't doc it, but then the guide shows it?**

**Comment by lauracowen** [comment]
> **revised- the only link to web.xml schema i could find is in the `Securing an application` guide- which is also my source for including it in this doc- same with the application-bnd approach mentioned below. The discussion here really comes out of that guide- which I guess is an older guide?**

The guide only shows an example `web.xml` definition, I think? The XML schema would define the structure required by any web.xml file (in a format like this: https://www.w3schools.com/xml/xml_schema.asp). I don't know if we document it anywhere but someone in the security team must be able to provide a copy of it.
       
> **talked to ajay- there's nothing you can't do with annotations and in general they are easier to debug than a separate file. But he said people tend to have opinions about which is better and it's not necessarily in the scope of this doc to take a side. I left it in for now since one of our guides explains how to do it.**

Okay, I disagree with his view of the scope of the doc. If we think there is a better way, we should lead with that. If the alternative approach is valid but not what we'd recommend as best practice, we can say later on in the topic that it's available and that it can be used in certain situations (specifying what those situations are). But it needs to be really clear and up-front what we expect the majority of users to do, because we need to help them decide what to do and give them default approaches to reduce the number of decisions they need to make.

I also think it might be worth describing the two options in the way he did: "using annotations" and "easier to debug", "using a separate file" and why that's useful (then say how that works). Alasdair hasn't seen much debate around this - people prefer annotations. So we should talk mainly about annotations, and then be really clear in what circumstances using a separate file might be useful.

>  **HomeServlet.java is a standard file- though there's not much out there to explain exactly what it is. The guide calls it "The doorway to your application" without additional explantation- not sure if that's helpful. This is also something i included because it's in the guide. I think its safe to assume that in most cases this is not the preferred approach for microservices- but- is it a problem if we don't doc it, but then the guide shows it?**

I had a look at the guide, I think it's just the name of the file used in the guide (the doorway to the application you're creating in the guide rather than a universal description of a standard file). I think it's just a servlet (in the Java it extends the standard HTTPServlet class). So you could maybe say "you can define the @ServletSecurity annotation in a servlet class...".

Also:
- It needs to be clearer why/when you'd use the @ServletSecurity annotation approach instead of @RolesAllowed annotation. Is the @ServletSecurity annotation part of the Java Security spec? What does @ServletSecurity provide that @RolesAllowed doesn't? It seems more faffy to set up because you then have to do some XML config as well.
- where you mention "or XML configuration", you haven't already talked about doing anything in the XML config in this section so it doesn't really make sense at this stage.
- This sentence is a bit odd "Roles can be defined in the application by setting the @DeclareRoles annotation in the server.xml file." because you don't set annotations in the server.xml file (annotations go in the Java code).

**Comment by dmuelle** [comment]
@lauracowen: I've revised this topic to get a clearer picture of using annotations vs deployment descriptor (at a high level at least) and also when you would use @rolesAllowed vs @servletSecurirty. I've also added the diagram per your suggestion. Note this is the revised diagram from design.

I also added some brief code examples- really just because there are several concepts at work here- annotations vs dd, ejb security vs servlet, and I think the code helps distinguish them. Let me know what you think. This has changed enough that it needs to go back to SME review but I'd like to get the basic content sorted first

**Comment by lauracowen** [comment]
- It feels like it needs a sub-heading before the servlet security paragraph as there are a lot of paragraphs in the Defining... section. But I'm not sure how to word it - Defining roles for front-end resources? Does that mean anything by itself?
- Don't think this link is constructed properly (it's treating the guides as if they're under the docs part of the site URL): https://draft-openlibertyio.mybluemix.net/docs/ref/general/guides/security-intro.html#adding-authentication-and-authorization
- Is it worth linking to this guide from the annotations info above as well? I think it uses annotations too, doesn't it? At the moment, it feels a bit like we're telling them to use annotations but our own guide takes the web.xml route...and it's not clear why. I _think_ the guide uses a combination of the two? (presumably according to whether they need to separate the security config or not?
- "where to next" heading - can't remember which we decided on but is this right?

**Comment by dmuelle** [comment]
Thanks @lauracowen draft is updated

- added a subheading for "Configuring servlet security roles"
- fixed broken link and added similar guide links in preceding sections so users know our guides cover recommended config
- changed Where to Next to See Also per recent discussions

**Comment by teddyjtorres** [comment]
The draft looks fine.

"developer approved"

**Comment by Rwalls1** [comment]
## Peer review
- To use a more active voice and be more concise, I think you should change "this information is used to determine whether the user is authorized to access the resource.” to “this information determines whether the user is authorized to access the resource.
- I think you can remove the triangular brackets from element names in the paragraphs, such as <security-role>, as Laura recently gave direction that they aren’t needed. 
-I think you should append “(SSO)” to “single-sign on” as that would make the “SSO” acronym used later in the topic clearer and also maintain consistency with how we reference acronyms. 
- I think you could change "In some cases, an application needs to know only whether a user is authenticated or not.” to something like “In some cases, an application needs to know only the user’s authentication status” to be more concise. I think that would still retain the same meaning.
- I think you should change "For an example of using the @RolesAllowed annotation to configure authorization, see the” to “For more information, see”. This would be more concise and would help to maintain a consistent syntax when referencing links across all topics. There are also two other instances in this topic where a similar update would apply to link references.
- I think you should change "Set the rolesAllowed attribute” to something like “You can set the rolesAllowed attribute.” I think we generally want to avoid stating commands in topics that aren’t tasks.
- The hyperlink text that states, " such as with JSON Web Tokens (JWT)” needs to have the link updated to point to https://draft-openlibertyio.mybluemix.net/docs/ref/general/#single-sign-on.html. The current link points to a topic that is being removed.

**Comment by dmuelle** [comment]
Thanks for reviewing @Rwalls1 - addressed your comments in a new revision

-  change "this information is used to determine whether the user is authorized to access the resource.” to “this information determines whether the user is authorized to access the resource. **done**
- remove the triangular brackets from element names in the paragraphs **done**
- append “(SSO)” to “single-sign on” **done**
- change "In some cases, an application needs to know only whether a user is authenticated or not.” to something like “In some cases, an application needs to know only the user’s authentication status” to be more concise. **done**
- change "For an example of using the @RolesAllowed annotation to configure authorization, see the” to “For more information, see”. **done here and throughout**
- I "Set the rolesAllowed attribute” to something like “You can set the rolesAllowed attribute.” **revised**
- The hyperlink text that states, " such as with JSON Web Tokens (JWT)” needs to have the link updated to point to https://draft-openlibertyio.mybluemix.net/docs/ref/general/#single-sign-on.html. **updated**

**Comment by dmuelle** [comment]
new draft URL: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/authorization.html

**Comment by chirp1** [comment]
@dmuelle Hi David, as I'm reviewing Charlotte's Application configuration hardening topic, I'm wondering if "user role" in your Authorization topic should just be "role".

**Comment by dmuelle** [comment]
I've updated the doc to changes instances of "user role" and "security role" to just "role" DQTI CH6 "Use technical terms consistently and appropriately"

rearranged intro to servlet security example so its parallel with other example intros- DQTI Ch 8 Make elements parallel

**Comment by dmuelle** [comment]
comments from @utle in https://github.com/OpenLiberty/docs/issues/2747#issue-712874204

- The diagram of Authorization should show the authorization. 
- Not sure if we need to mention the ibm application bind is still supported?

**Comment by dmuelle** [comment]
@utle - thanks for reviewing

**The diagram of Authorization should show the authorization.**

- This diagram was included from the Authentication topic, I believe at @lauracowen request. Should it be removed from this topic? We can remove it and work on developing another but will likely require design help unless changes are minor. Can you be more specific about how to represent authorization at a high level?

**Not sure if we need to mention the ibm application bind is still supported?**

Do you mean specifying roles in an `ibm-application-bnd.xmi` file or the `ibm-application-bnd.xml` file? I can add a mention that these files are supported, but we don't currently have any other documentation in Open Liberty for them to point users to. 

Are these files likely to be relevant to most users in containerized scenario? [In the KC](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/cwlp_authorization.html), recommends configuring roles in the server.xml instead:
"The advantage of using the server.xml file for mapping roles to users is that your application does not need to be packaged into an EAR file and it is easier to update."

**Comment by jvanhill** [comment]
`During authentication, the user’s identity and roles are confirmed`
- Technically, only the user's idenity is confirmed during authentication. The roles are confirmed in authorization. However; perhaps we consider creating the subject with their roles / groups as 'authentication'. @utle @arkarkala , your opinion?

**Comment by utle** [comment]
The roles are confirmed in authorization.

**Comment by utle** [comment]
@dmuelle  yes, `ibm-application-bnd.xmi file or the ibm-application-bnd.xml file `. Maybe, we don't want to call them out here since we want customer to defined them in the server.xml file.

**Comment by dmuelle** [comment]
I've updated the draft to clarify that roles are part of authorization, not authentication. We are reviewing this diagram to determine if it should be edited or replaced.

**Comment by chirp1** [comment]
@dmuelle Hi David, 
Here are my authorization comments:
- Remove extra words: Change "...to be secure, it must be able to manage ..." to "...to be secure, it must manage ...".
- Would you rework the second paragraph so that a mention of authorization happens in about the second sentence instead of the last sentence in the paragraph, and maybe work in the word "authorization" in place of "authorized". The info for the example is fine as it is.
- Remove directly from "directly in the source code". 
- Placement of "in the source code" seems a little misplaced. Might you mean something more like "by setting the @RolesAllowed annotation in the source code"?
- As with the Authentication topic, use "SSO provider" or "SSO identity provider" consistently.
- For the diagram, are the microservices within the application or outside of it?
- Can we make the authorization process in the diagram more detailed? Although this authorization topic in KC is for a web container and authorization servers, it gives and idea of how to go about providing authorization details: https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/cwlp_authorization.html  Then you could have steps specifically for authorization, like you have authentication leaning steps in your authentication topic?
- Do we want noun phrases for the section titles  to be consistent with the section titles in the Authentication topic, other topics?
- You say "name attribute of the security-role element " but say "The group name elements ". Should the wording instead be something like "the name attributes on the group elements"?
- Change "you do not need specify " to "you do not need to specify".
- What does development mean in "separate from development? Do you mean development environment, for instance? Clarify what you mean by "development".
- You say "...you can configure roles in the servlet code. If you want to specify roles in the servlet code..." reword so that you aren't saying roles and servlet code in back-to-back sentences.
- Remove 'be able to" from "requesting service often must be able to demonstrate", and avoid using the phrase in general when possible.

**Comment by dmuelle** [comment]
@chirp1 thanks for reviewing, I made the following changes per your review:

- [x] Remove extra words: Change "...to be secure, it must be able to manage ..." to "...to be secure, it must manage ...".

- [x] Would you rework the second paragraph so that a mention of authorization happens in about the second sentence instead of the last sentence in the paragraph, and maybe work in the word "authorization" in place of "authorized". **revised**

- [x] Remove directly from "directly in the source code".

- [x] Placement of "in the source code" seems a little misplaced. Might you mean something more like "by setting the @RolesAllowed annotation in the source code"?

- [x] use "SSO provider" or "SSO identity provider" consistently.

- [ ] For the diagram, are the microservices within the application or outside of it? **I think they are external- a web service or API that the application needs to communicate with to get resources the user is requesting. Most likely, if they are protected resources, the microservice will get the role info it needs from JWT, whether directly or perhaps mapped against separate authorization schema for that microservice.** 

- [ ] Can we make the authorization process in the diagram more detailed? **Yes but I would suggest that we remove the diagram for now and oipen a new issue to design a replacement. We might need design team resources (though maybe not) and the new diagram would need to be reviewed by security team. I think we can publish the doc without it and add it in an upcoming release.** 

- [ ] Do we want noun phrases for the section titles to be consistent with the section titles in the Authentication topic, other topics? **I think since the subsections in the topic describe different ways authorization is applied for an app, the short, declarative subheadings ("Define roles in your application code") are more clear and direct than an equivalent noun phrase ("Role definition in your application code"). I can rework them if necessary.**

- [x] You say "name attribute of the security-role element " but say "The group name elements ". Should the wording instead be something like "the name attributes on the group elements"? **updated**

- [x] Change "you do not need specify " to "you do not need to specify".

- [x] "...you can configure roles in the servlet code. If you want to specify roles in the servlet code..." reword so that you aren't saying roles and servlet code in back-to-back sentences

- [x] Remove 'be able to" from "requesting service often must be able to demonstrate"

**Comment by dmuelle** [comment]
published at https://www.openliberty.io/docs//latest/authorization.html

draft link: https://draft-openlibertyio.mybluemix.net/docs//latest/authorization.html
