### ISSUE TITLE
Hardening Liberty servers in production

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#929]
From LC:  Overview topic. Best practices in production. Intro to types of intrusions and vulnerabilities - managing protection of server/OS, stopping unauthorized users getting at traffic in a network, locking down apps (link to each for more detail and examples). All from the perspective of securing Liberty when running in containers in the cloud.

**Scenario 2**:  Ops users with containers deployed to Kubernetes/OpenShift

**Resources**:
- Slide 8 of Jim's hardening slides (https://ibm.box.com/s/u1wedojgzqtsup5icnzh828e2ia10waj and https://ibm.box.com/s/kp5ght7l9cypnwt4s7vcs3cxz91enjl6)

**Comment by Charlotte-Holt** [comment]
@arkarkala - A draft is available for review at https://draft-openlibertyio.mybluemix.net/docs/ref/general/#hardening-intro.html. Please provide any feedback that you have. Thanks!

**Comment by chunlongliang-ibm** [comment]
after section "Use user registries that are safe for production", add following new section

Use web single-sign on: It is common to use single-sign on (SSO) technologies (such as SAML or OpenID Connect) instead of direct user registry access from Liberty for user authentication. SSO can be used to eliminate the requirement of user registry, also provides better security (especially when combined with two factor authentication) and regulatory compliance.  If you use SSO, maintain your SSO configuration in a separate include file, not in the server.xml file.

**Comment by chunlongliang-ibm** [comment]
At the end of "Enable the transportSecurity feature" section, add following
"
When using  single-sign on (SSO) technologies for user authentication, make sure all SSO endpoint URLs (for example, OpenID Connect DiscoveryURL) are using HTTPS scheme, and client must perform a TLS server certificate check.
"
So the new section looks like this:

**Enable the transportSecurity feature**: The Transport Security feature enables the SSL feature to support SSL connections and adds the ability to configure outbound transports. Additionally, disable non-SSL ports by setting them to -1 in the server.xml file, and use only certificates that are signed by a certificate authority for public-facing production servers. Also, enable SSL in your client and web server. Using SSL connections throughout your network communication flow helps protect your server from network intrusions. 

When using  single-sign on (SSO) technologies for user authentication, make sure all SSO endpoint URLs (for example, OpenID Connect DiscoveryURL) are using HTTPS scheme, and client must perform a TLS server certificate check.

**Comment by Charlotte-Holt** [comment]
Working draft at https://draft-openlibertyio.mybluemix.net/docs/ref/general/#hardening-intro.html

**Comment by Charlotte-Holt** [comment]
@lauracowen @chirp1 - This is ready for your review. Thanks!

**Comment by lauracowen** [comment]
- Link to the security config topic has wrong file name (I haven't checked the other links).
- I wondered whether that link should come at the end of the Best Practices list? I was a little confused about whether I was intended to go off to look at that topic first or not. I think the way this should be used is to review the Best practices list then go find out more about how to do it in the separate topic? I see why it's at the top though, but it's useful to have a link at the end of each section as a kind of - look here next for more about this.
- Is it worth making the "Best practices" heading say "Best practices summary" so that it's clear there's a longer version in the other topic?
- Maybe "see the downloads page" rather than "go to" (I'm not sure why but it's less about getting the download from there, more about finding the info to put in maven/docker from that page).
- Last bullet point, can you lead with JAX-RS annotations before the web.xml option? Annotations is what we'd prefer.

Otherwise looks great, thanks.

**Comment by Charlotte-Holt** [comment]
@lauracowen I incorporated all of your updates. Thanks for the review! David noticed that having the same section headings (i.e., Best practices) would be an accessibility issue, so I updated those to be unique.

**Comment by Charlotte-Holt** [comment]
Requesting full peer review from @Rwalls1

**Comment by Rwalls1** [comment]
This a good topic, I just a have few comments: 
- I think you should separate the opening paragraph into two paragraphs just to make it clearer what the short description is. So I think put the sentence starting with  “Different types of security” on a separate line to make that distinction.
- For “Open Liberty admin” make sure to verify whether that is standard terminology
- I think you should remove the parentheses around "(such as SAML, JWT, or OpenID Connect)” and use commas to surround the phrase 
-For the sentence, “Use AES encryption for passwords instead of Base64 encoding”, I think it could be important to briefly provide context for that distinction by possibly introducing what AES encryption is and why it should be used in these scenario rather than Base64 encoding or another encryption method
-For the sentence, "Replay attacks and man-in-the-middle (MITM) attacks are two examples of network intrusions.”,  since you specified these two examples I think it would be good to briefly describe what they are here to add more context.

**Comment by Charlotte-Holt** [comment]
@Rwalls1 Thanks for your review! I addressed all your comments except the final two because the more detailed topics on hardening go into these issues, but I wanted to leave this topic more high-level.

**Comment by jtmulvey** [comment]
Approved.

**Comment by chirp1** [comment]
Hi Charlotte, 
The topics is coming along nicely!
I have some comments:
- Make further updates to your topic by carefully going through the cheat sheet and your topic. The cheat sheet is located at https://apps.na.collabserv.com/wikis/home?lang=en-us#!/wiki/W93fb765ee31c_4aa7_98f6_a02c0f1a2ebf/page/Peer%20review%20cheat%20sheet .
- Try working server configuration, network, and application configuration into your short description.
- Investigate the "fix pack" phrase and rewrite as appropriate. 
- Investigate the "insecure" term and rewrite as appropriate.
- Update the sub-section title of "Use user registries that are safe for production:" since you also mention repositories in the paragraph that applies to the title.
- See David about the sub-section titles in terms of accessibility. Are they bold or a header? A header would likely be good for someone using Jaws to find the section easily.
-

**Comment by Charlotte-Holt** [comment]
@chirp1 Thanks for your review! Lots of good catches. I made updates and spoke with @dmuelle about accessibility for the bold best practices. He said that he ran the DAP tool and it's not flagging anything, so I left those as they were.

**Comment by chirp1** [comment]
@Charlotte-Holt Hi Charlotte, I did a preliminary look at the hardening topics. I ran them through Acrolinx. I see various things that you can fix in each of your topics. Would you go back through Acrolinx, your style guide, and the cheat sheet page on the wiki, and make corrections as appropriate?

**Comment by chirp1** [comment]
@Charlotte-Holt Hi Charlotte, I have various comments:
- This topic seems like a parent topic of the network, server configuration, and application configuration hardening topics, but displays as a peer topic in the current nav and the Antora nav. How about if you make this topic the parent topic?
- I mentioned that some of the best practices in this hardening server in production topic weren't in the server configuration hardening topic. I'm finding other bits and pieces that are in this hardening servers in production topic, but not in the more detailed topic. For instance, "If you use SSO for user authentication,......" "virtual host", and "jax-rs" info are not in the Application Configuration hardening topic. However, don't just fix these things that I'm mentioning in this comment. Pick through this hardening servers in production topic, and add info to the other three hardening topics as appropriate. 
- I'm also finding that you have links to various other topics like authentication, SSO and the like in these best practices sections of this "hardening severs in production" topic. I think that in various cases the links are inappropriate because they take the user on a tangent and away from the more detailed information for various best practices in the server configuration, networking, and application configuration topics.
- You have sections in the server configuration, network, and application configuration best practices that aren't in the 'hardening servers in production" best practices topic.To me, they should also be mentioned in 'hardening servers in production".
- Also, in my opinion, you should have all the best practices that are listed in the three individual topics in this "hardening servers in production" topic. HOWEVER, I don't think you should have the detail that you have now for each of the best practices. Instead, I'd like to see something like:    
_Summary of server configuration hardening best practices
_<one or two sentence intro to the bullets>_
- Open Liberty Docker images
- Current Open Liberty version
- Installation violation
    - UNIX file permissions
    -  And so on.....
The title between the two topics should more closely match. A few might require an extra sentence or so, but I think most would not. I'm suggesting having these bulleted lists with little to know detail as I think that doing so would cut down on the inconsistencies between this parent-like topic and a given child topic and make the set of hardening topics clearer.
- Another question would be where to add the links? Should each bulleted best practice be a link to the detailed info in the appropriate hardening topic, should the links be "To learn more about ways to prevent..." that you already have in the "hardening servers for production" topic, or a combination of the two?
- Would you go through the cheat sheet and this topic in detail and fix any editorial issues as? I spot a variety of  editorial issues.

**Comment by Charlotte-Holt** [comment]
@chirp1 Thanks for your feedback. 

- [X] This topic seems like a parent topic of the network, server configuration, and application configuration hardening topics, but displays as a peer topic in the current nav and the Antora nav. How about if you make this topic the parent topic? - Yes, agreed. 
- [X] I mentioned that some of the best practices in this hardening server in production topic weren't in the server configuration hardening topic. I'm finding other bits and pieces that are in this hardening servers in production topic, but not in the more detailed topic. For instance, "If you use SSO for user authentication,......" "virtual host", and "jax-rs" info are not in the Application Configuration hardening topic. However, don't just fix these things that I'm mentioning in this comment. Pick through this hardening servers in production topic, and add info to the other three hardening topics as appropriate.
- [X] I'm also finding that you have links to various other topics like authentication, SSO and the like in these best practices sections of this "hardening severs in production" topic. I think that in various cases the links are inappropriate because they take the user on a tangent and away from the more detailed information for various best practices in the server configuration, networking, and application configuration topics.
- [X] You have sections in the server configuration, network, and application configuration best practices that aren't in the 'hardening servers in production" best practices topic.To me, they should also be mentioned in 'hardening servers in production".
- [x] Also, in my opinion, you should have all the best practices that are listed in the three individual topics in this "hardening servers in production" topic. HOWEVER, I don't think you should have the detail that you have now for each of the best practices. Instead, I'd like to see something like:
- Summary of server configuration hardening best practices
- one or two sentence intro to the bullets
- Open Liberty Docker images
- Current Open Liberty version
- Installation violation
- UNIX file permissions
- And so on.....
- [X] For this example, the titles in the bulleted list in the "hardening servers in production" should more closely match the titles of the sections in the server configuration hardening topic. A few might require an extra sentence or so, but I think most would not. I'm suggesting having these bulleted lists with little to know detail as I think that doing so would cut down on the inconsistencies between this parent-like topic and a given child topic and make the set of hardening topics clearer.
- [X] Another question would be where to add the links? Should each bulleted best practice be a link to the detailed info in the appropriate hardening topic, should the links be "To learn more about ways to prevent..." that you already have in the "hardening servers for production" topic, or a combination of the two? - I left the links at the bottom. 
- [X] Would you go through the cheat sheet and this topic in detail and fix any editorial issues as? I spot a variety of editorial issues.
- [X] Also, in the cheat sheet, go to the style guide link and do a deep dive into how to write these hardening topics so that they fit together properly.

**Comment by Charlotte-Holt** [comment]
@chirp1 Topic at https://draft-openlibertyio.mybluemix.net/docs/20.0.0.10/security-hardening.html.

**Comment by chirp1** [comment]
Hi Charotte,
This topic is looking much better! I like the layout. 
- You have multiple items to correct that are mentioned on the peer review cheat sheet: https://apps.na.collabserv.com/wikis/home?lang=en-us#!/wiki/W93fb765ee31c_4aa7_98f6_a02c0f1a2ebf/page/Peer%20review%20cheat%20sheet Some items appear to have been in the topic. Others seem to have been introduced with your latest updates. Very carefully review the cheat sheet and your documentation, and make corrections as appropriate. Whenever you make updates to a topic, review the peer review cheat sheet.
- This topic doesn't yet seem to be the parent topic of the other hardening topics. Correct the table of contents. 
- I think that having bullets at the top for server configuration, network, and application configuration are good. However, I think that they shouldn't link to the other topics at this point as the links immediately take the user away from this main topic. Review linking in the IBM style guide: https://learning.oreilly.com/library/view/developing-quality-technical/9780133119046/ch10.html#ch10lev1sec3 Note the discussion on "wild goose chase" and "hopscotching". A possible way to change the topic is to instead link the bullets to the server configuration, network, and application configuration sections in this parent hardening topic. Then add to each of the three sections in your main topic  "For more information....." a link to its corresponcing server configuration, network, or application configuration topic. 
- For "Use include files to hold portions of the configuration when necessary.", it's missing the reference to "outside of the server.xml file.".
- Remove references to "OS" in all your topics. Just use "operating system".
- Remove "Configuring your applications to run on.." Since you didn't give a reason for any of the other best practices.
- Add to "Restrict the number of sessions that can be created for applications." the phrase "that use in-memory sessions".
- For this topic and other topics (i.e. the networking hardening topic), remove "IHS" for IBM HTTP Server. IHS is not an approved short name.
- Change "they are not authorized to." Add a word after "to", such as "have": "they are not authorized to have.".
- For the "Require a confidential transport guarantee between client and server." link ensure that in the "Confidential transport guarantee" section in the "Application configuration security hardening" topic that you include "between client and server". Also, add in "the", such as "for the client and the server".

**Comment by Charlotte-Holt** [comment]
@chirp1 Thx for the review! I addressed your comments: 
- [x] You have multiple items to correct that are mentioned on the peer review cheat sheet: https://apps.na.collabserv.com/wikis/home?lang=en-us#!/wiki/W93fb765ee31c_4aa7_98f6_a02c0f1a2ebf/page/Peer%20review%20cheat%20sheet Some items appear to have been in the topic. Others seem to have been introduced with your latest updates. Very carefully review the cheat sheet and your documentation, and make corrections as appropriate. Whenever you make updates to a topic, review the peer review cheat sheet.
- [X] This topic doesn't yet seem to be the parent topic of the other hardening topics. Correct the table of contents.
- [X] I think that having bullets at the top for server configuration, network, and application configuration are good. However, I think that they shouldn't link to the other topics at this point as the links immediately take the user away from this main topic. Review linking in the IBM style guide: https://learning.oreilly.com/library/view/developing-quality-technical/9780133119046/ch10.html#ch10lev1sec3 Note the discussion on "wild goose chase" and "hopscotching". A possible way to change the topic is to instead link the bullets to the server configuration, network, and application configuration sections in this parent hardening topic. Then add to each of the three sections in your main topic "For more information....." a link to its corresponding server configuration, network, or application configuration topic. - **These bullets do currently link down the sections in the topic.** 
- [X] For "Use include files to hold portions of the configuration when necessary.", it's missing the reference to "outside of the server.xml file.".
- [X] Remove references to "OS" in all your topics. Just use "operating system".
- [X] Remove "Configuring your applications to run on.." Since you didn't give a reason for any of the other best practices.
- [x] Add to "Restrict the number of sessions that can be created for applications." the phrase "that use in-memory sessions".
- [x] For this topic and other topics (i.e. the networking hardening topic), remove "IHS" for IBM HTTP Server. IHS is not an approved short name.
- [x] Change "they are not authorized to." Add a word after "to", such as "have": "they are not authorized to have.".
- [x] For the "Require a confidential transport guarantee between client and server." link ensure that in the "Confidential transport guarantee" section in the "Application configuration security hardening" topic that you include "between client and server". Also, add in "the", such as "for the client and the server".

**Comment by lauracowen** [comment]
@Charlotte-Holt While I understand why @chirp1 asked for the hardening overview topic to be a 'parent' topic in the navigation, can you make it a single flat list of four topics under the existing "Security hardening" twisty for now?

We don't currently have any other topics that are organised hierarchically like that and it's jarring to have to click twice to get to the topics. It's also not obvious that there's a topic to read at all in the "Security hardening for production" entry, so readers could miss it completely if they're just clicking the twisty arrow. There's no need to explicitly show the hierarchy of information in the navigation - it's clear from the topic what's there (could even put "overview" on the end of the main topic's title to clarify?).

If we start having "parent" topics in lower levels of the nav, we'll end up with lots of pointless parent topics that are just there for the sake of it. We should just stick to the strategy we had of maybe working towards having landing pages on the top-level twisties (which we haven't got to yet even) but not beneath that.

It's fine (and much simpler) to have a navigation that shows:
```
V Security hardening for production
   Security hardening overview
   Server configuration
   Network
   Application configuration
```

**Comment by Charlotte-Holt** [comment]
@lauracowen Updated the nav, and rebuilding now. Thx!

**Comment by chirp1** [comment]
Hi Charoltte,
- In the intro paragraph I see "It is important ...". We want to avoid "it is" in our topics. See "there, here, or it followed by a be verb." in the peer review cheat sheet. https://apps.na.collabserv.com/wikis/home?lang=en-us#!/wiki/W93fb765ee31c_4aa7_98f6_a02c0f1a2ebf/page/Peer%20review%20cheat%20sheet . You could just change "It is important to harden your..." to "Harden your..."/
- Change "Carefully map user roles." to "Carefully map roles.". <= Since we switched from "user roles" to "roles" in the "Application configuration security hardening" topic and David's Authorization topic.

**Comment by Charlotte-Holt** [comment]
@chirp1 Addressed! Rebuilding now.

**Comment by chirp1** [comment]
Looks good! Moving to Ready to Publish.

**Comment by Charlotte-Holt** [comment]
Published at https://openliberty.io/docs/20.0.0.10/security-hardening.html
