### ISSUE TITLE
Server configuration security hardening

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#930]
From LC:  "Operating systems in a container - make sure to frame in terms of containers and K8s deployments, not traditional server installations. Following points taken from Jim's presentation (but check there for anything I've missed too).     

- If production users take our existing Docker images, the OS permissions, etc will be set up for them already. However, many like to build their own images, which means they'll have to set up this stuff for themselves. Start the topic by referring to the supplied images so that they know that's the easier approach and that it is already secured/hardened. But then go into a section that describes how the images are hardened and what things you need to do to make your own image secure/hardened (maybe a checklist, maybe just sub-sections but make it easy for someone to read and mentally check off whether they've done something or not)     

- Stay current with Liberty versions, continuous delivery with zero migration policy (we commit to it so when you upgrade a version you don't have to do anything - can continue to use existing feature version if you want).        

- Stay current on CVEs - staying on the latest version ensures you get the latest security fixes asap - check what are best practices for ensuring up-to-date Liberty versions in containers - e.g., always use 'latest' or does that cause other problems? what's typical for how long containers exist before they get rebuilt and redeployed (because that will determine how long an old version of Liberty is kept in production without recent security updates) - as Jim what the advice is for that. 

- Review UNIX file permissions (owner, group, other; read, write, execute) 

- See slide for example of 750 permissions - make sure the right people have the right permissions. 

- Installation Manager (? not really a K8s thing so can probably ignore?) 

- Non-IM installations (archive) - ensure service zone and permissions (see slide - if relevant to K8s? prob not?). Admin panels on Windows? Again, not sure relevant? 

- I think securing Docker containers (layers and containers and then K8s security) is more important here. But OS-level security is important in creating the image/layer for the Docker image - probably UNIX? (eg RHEL or Ubuntu). eg user:group details when creating Dockerfile (see the containerizing guide, and see slide for recommendations of folder permissions). What about starting server permissions? Maybe this is outside of OL and is more a case of understanding how to deploy in Docker and K8s safely (but still need to set permissions inside the container so what should they be)? (re slide 28) 

- What happens with validating installation when you're in containers? Is it necessary to do and when do you do it - when testing your container image?? (slide 19) 

- Who needs access to configuration (slide 20) - maybe similar but does anyone need access to admin the server in a container? how does that work? Assume they use version control or config management system to manage their config changes (rather than ad hoc changes directly to the server, it's now good practice to track/audit config changes by making them under version control/config management and then rebuild the container and redeploy it). 

- Ultimately though it largely comes down to UNIX file permissions being set properly. 

- Slide 21 - wlp directory and file permissions (750 - owner all, group execute, other none). Multiple people potentially need to access server.xml write access - but wouldn't this be done in version control (Eg GitHub) then rebuilt and redeployed? Giving people access to read output files - would that be handled by who has access to say Prometheus and Grafana and how those apps have access permissions set up? 

- The stuff documented in Jim's talk that's not relevant to containers would still need documenting but as Scenario 3. 

- Include file processing - what are likely configurations of include files in containers? eg different includes in different layers? or mounted directories?? 

- Use encryption for pw instead of base64 encoding - use securityUtiltiy to do encryption. 

- If using basicRegistry - do 1-way hash for pw in server.xml (not for production anyway so maybe just move this to the 'intro security' topics rather than the hardening topics) 

- configDropins - can override server.xml using the folder configDropins/overrides. Can also use the configDropins/defaults. 

- See summary of user registries. "

**Scenario 2**: Ops users with containers deployed to Kubernetes/OpenShift

**Comment by Charlotte-Holt** [comment]
Working draft at https://draft-openlibertyio.mybluemix.net/docs/ref/general/#os-hardening.html

**Comment by ManasiGandhi** [comment]
@Charlotte-Holt Just a few suggestions for your topic,

- Under 'Open Liberty Docker images' in the second paragraph, 'The simplest way to securely run Open Liberty ..' add a noun after 'Open Liberty'
- In the same section, in the first bullet point 'Confirm that the Open Liberty server’s identity doesn’t own the server’s config..' remove the apostrophe in 'server's' in both instances, and other instances in the topic.
- In the  'Installation validation' section, add a noun after 'MD5 checksum', maybe 'function'?
- In the 'UNIX file permissions' section, in the first sentence it says 'users and groups for a file '. Change it to 'users and groups of a file '.
- Rephrase the second sentence 'All UNIX files have the following attributes where permissions are assigned' to 'All UNIX files where permissions are assigned have the following attributes '. In the last sentence 'Generally, the last digit file permission should end in 0 ', you can change 'should' to 'must' if it is appropriate for the context. In the last sentence of the section, 'This ensures that these images don’t run as root by default. ' you can say 'This feature' or if there is anything more specific in this context.

**Comment by lauracowen** [comment]
OS security hardening - looks great. :)
- “The server ID only owns…” - does that mean that it should be set so that the server ID only owns? Or is that a statement about the default situation? I wasn’t quite sure if it was an instruction or description, I think.
- Is it possible to link somewhere for how to AES encrypt the sensitive info in the server.xml? eg I think securityUtility command encrypts passwords for this purpose - whether there’s anything else that needs encrypting and if the cmd can do that too, I don’t know… Ah, I just saw you mention it in the end paragraph. Maybe you could just make the words “AES encrypt” into a link to the securityUtility command topic? (if that’s appropriate)
- Is this checklist necessary even if you use the provided Docker image? Or is it that you should do these things to make your own from-scratch Docker image as secure as the provided one? (I don’t know.)
- What does it mean to “extend an OL image for production use”? I think the images are for production use. Does it mean if you want to adapt the production-ready image with custom settings/content?
- Processing include files section - where it says “…by using the onConflict tag…“, the sentence construction means it could be read as the user could override the config by using the onConflict tag, but I think you mean that you can prevent users being able to override the config by using the onConflict tag? Maybe split into two sentences if you agree it needs to be clearer?
- If you’re able to move the securityUtility command across from the KC in a similar format to your server commands, you could link to it from here.
- Maybe could add a final paragraph summing up that doing these things secures the OS in your container… Then say also need to consider app config hardening and the other topic, and link to the topics? Would help the reader know where to go next and emphasise that there are the three(?) areas to look at.

**Comment by Charlotte-Holt** [comment]
@lauracowen Thanks! :) After talking with @jtmulvey, my understanding was that the images on Docker Hub for OL do have base-level security enabled, but they aren't hardened, and customers that want to harden for production will modify need to modify their images for production-level hardening. So I _think_ the checklist would apply to scenarios where users built their own image or used an existing OL image from Docker Hub.

**Comment by lauracowen** [comment]
Great, happy to put this ready to publish. :)

**Comment by Charlotte-Holt** [comment]
Requesting full peer review from @ManasiGandhi

**Comment by ManasiGandhi** [comment]
@Charlotte-Holt The topic looks good! Here are a few suggestions,

1. In the first paragraph, change “It’s also a best practice to ensure that the Liberty server’s configuration file system, which is the path where the WLP_USER_DIR environment variable points, is only writable to authorized server administrators.” To “It’s also a best practice to ensure that the Liberty server configuration file system, which is the path where the WLP_USER_DIR environment variable points, is only writable to authorized server administrators.” (remove apostrophe mark from server as it is inanimate).
2. In the second paragraph, change, “A container that runs in production should have only the tools and packages that you need to run your application.” To” A container that runs in production must have only the tools and packages that you need to run your application.”
3. In the first bullet point under ‘Open Liberty Docker images’, change, “Confirm that the Open Liberty server identity doesn’t own the directory where the server config is stored and has only read access to it” to “Confirm that the Open Liberty server identity doesn’t own the directory where the server config is stored and is restricted to read-access to the directory”, or phrase it in accoding to your choice.  Acrolinx flagged the position of ‘only’.
4. In the fourth bullet point “Use the Transport Security feature instead of the SSL feature”, both the links open to a blank page under “Server Features”. Can you replace them with these links, https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#transportSecurity-1.0.html for Transport Security feature https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#ssl-1.0.html for SSL feature if they are appropriate?
5. Under “Current Open Liberty version”, change,” Open Liberty’s zero migration policy means that you can move to a later version without changing anything in your server config”, to, “Open Liberty zero migration policy means that you can move to a later version without changing anything in your server config.” 
6. Under “Installation validation”, is there a noun that can follow ‘Open Liberty’ in this sentence “The output message that you receive indicates whether Open Liberty was validated successfully.” For example, “Open Liberty installation”.
7. Under “UNIX file permissions”, in the sentence “For each of these attributes, there are three bits assigned as an octal digit.” Change the word “three” to the numeral “3” as suggested by Acrolinx. Use your discretion. Here is the link for reference https://ibmid.acrolinx.cloud/htmldata/en/rules/help/use_numerals.html  In the same section, in this sentence “For example, when all three bits are on for an attribute, this is represented as a 7, which indicates all access (read, write, and execute)”, can you avoid the parentheses? Maybe say “indicates read, write, and execute access”? Also, in ” Generally, the last digit file permission should end in 0 because others shouldn’t have access to protected information”, can you add “in the” before “file permission”, if it works? Remove the parentheses in “By default, Open Liberty Docker images run with USER 1001 (non-root) as part of group 0.” if possible.
8. In the first bullet point under “Access control”, can you split this sentence “This ID needs to read its config and write to logs, but when hardening a server, this ID should be configured only with read access to its own config files” into two sentences, and change “should to “must”, “This ID needs to read its config and write to logs. However, when hardening a server, this ID must be configured only with read access to its own config files.” 
9. Under “Process include files”, in the first bullet point, remove parentheses from “When sensitive information needs to be available for select users or groups (for example, database administrators) but not the larger group with read access to the server config.”
10. Under “Password encryption”, in this sentence “AES encryption is also preferable to XOR encryption because any XOR-encoded password is visible to any administrator.” Can you change it to “AES encryption is also preferable to XOR encryption because an XOR-encoded password is visible to any administrator”, to avoid repetition.

**Comment by jtmulvey** [comment]
I approve :-)

**Comment by chirp1** [comment]
@Charlotte-Holt Hi Charlotte, I did a preliminary look at the hardening topics. I ran them through Acrolinx. I see various things that you can fix in each of your topics. Would you go back through Acrolinx, your style guide, and the cheat sheet page on the wiki, and make corrections as appropriate?

**Comment by chirp1** [comment]
Hi Charlotte,
The topic is looking nice!
Here are my comments. Feel free to contact me to discuss any of them.
- Run Acrolinx again. I spot at least three or four items outside of the code that can be cleaned up. 
- Go through the peer review cheat sheet and fix outstanding items. I spot at least two things to fix. The cheat sheet is at https://apps.na.collabserv.com/wikis/home?lang=en-us#!/wiki/W93fb765ee31c_4aa7_98f6_a02c0f1a2ebf/page/Peer%20review%20cheat%20sheet
- "You can find Open Liberty Docker images and related information in Docker Hub." seems out of place as the sentence tells where to find the images without first discussing them. I see a few solution,  but see if you can come up with an alternative. Also, the topic links to the Open Liberty images on Docker Hub twice. See if you can rework the documentation to have the link in there only once.
- Put a noun after any terms, including the following four strings:
- webAppSecurity ssoRequiresSSL=’true’ 
- webAppSecurity httpOnlyCookies=’true’ 
- httpOptions removeServerHeader="true" 
- webContainer disableXPoweredBy="true" 
- For the term "server config", avoid using it. Search WebSphere Liberty for the string and see the one way that it is used.
- Avoid "config", too. Use "configuration" instead.
- For "use sudo to switch to this ID to update the config.", by default, sudo is root. Possibly more specific info needs to be added here because a user might inadvertently forget to specify an ID and run as root even if they don't want to run as root- maybe something that includes an example with sudo -u, or maybe spcify the su command instead.
- For, "but not the larger group with read access to the server config.", instead of "read access", would that be "read only acces"?
- Change "only their portion" to "only a portion".
- Change "by using the following config:" to "by using the following config statement:".
- Change "is used for decrypting" to "is used for decryption".
- For "your network and application configuration ", do you mean 'your network configuration and your application configuration", or do you mean "your application configuration and your network"? Correct as appropriate.

**Comment by Charlotte-Holt** [comment]
@chirp1 Thanks for the feedback! 

- [X] Run Acrolinx again. I spot at least three or four items outside of the code that can be cleaned up.
- [ ] Go through the peer review cheat sheet and fix outstanding items. I spot at least two things to fix. The cheat sheet is at https://apps.na.collabserv.com/wikis/home?lang=en-us#!/wiki/W93fb765ee31c_4aa7_98f6_a02c0f1a2ebf/page/Peer%20review%20cheat%20sheet
- [X] "You can find Open Liberty Docker images and related information in Docker Hub." seems out of place as the sentence tells where to find the images without first discussing them. I see a few solution, but see if you can come up with an alternative. Also, the topic links to the Open Liberty images on Docker Hub twice. See if you can rework the documentation to have the link in there only once.
- [X] Put a noun after any terms, including the following four strings:
- [X] webAppSecurity ssoRequiresSSL=’true’
- [X] webAppSecurity httpOnlyCookies=’true’
- [X] httpOptions removeServerHeader="true"
- [X] webContainer disableXPoweredBy="true"
- [ ] For the term "server config", avoid using it. Search WebSphere Liberty for the string and see the one way that it is used.
- [ ] Avoid "config", too. Use "configuration" instead.
- [ ] Add a noun after "sudo".
- [ ] For "use sudo to switch to this ID to update the config.", by default, sudo is root. Possibly more specific info needs to be added here because a user might inadvertently forget to specify an ID and run as root even if they don't want to run as root- maybe something that includes an example with sudo -u, or maybe spcify the su command instead.
- [ ] For, "but not the larger group with read access to the server config.", instead of "read access", would that be "read only acces"?
- [X] Change "only their portion" to "only a portion".
- [X] Change "by using the following config:" to "by using the following config statement:".
- [X] Change "is used for decrypting" to "is used for decryption".
- [X] For "your network and application configuration ", do you mean 'your network configuration and your application configuration", or do you mean "your application configuration and your network"? Correct as appropriate.

**Comment by chirp1** [comment]
Hi Charlotte, I'll check through by comments that you addressed after you return this issue to the editorial column. I'm putting this issue back in the in progress column because I'm finding some inconsistencies with the hardening topics now that I'm reading the parent "Security hardening for production" topic. In this parent topic it summarizes best practices for the server configuration. However, 
- Stay up to date with Open Liberty - OK. In the server configuration topic.
- Use user registries that are safe for production - not discussed. Need to add discussion to the server configuration topic.
- Use web single-sign on - not discussed. Need to add discussion to the server configuration topic.
- Carefully configure file permissions - OK. In the server configuration topic
- Encrypt passwords- OK. In the server configuration topic.

In my opinion, I think that you should discuss user registries and single sign on in the server configuration topic so that all the best practice information for server configuration can be found in once place. Currently, the user has to look in both this server configuration topic and the  "Security hardening for production" topic to get the full picture of the server configuration best practices. However, the user won't necessarily think to look in both places. As a comparison, the "Security hardening for production" topic lists two best practices for Application hardening, and both of those best practices are discussed in the Application hardening topic. The server configuration, Application, and Network configuration topics should all be parallel. Each of these topics should discuss their best practices that are mentioned in the "Security hardening for production" topic,

**Comment by Charlotte-Holt** [comment]
@chirp1 I see what you mean! Thanks for pointing this out. I've updated the topic to include those two points in the **Access control** section.

**Comment by chirp1** [comment]
Returning this topic so that you make updates to go with the "Hardening servers in production" topic.

**Comment by Charlotte-Holt** [comment]
@chirp1 I updated the parent topic and moved the info from the sever configuration summary section to this topic.

**Comment by Charlotte-Holt** [comment]
@chirp1 Topic at https://draft-openlibertyio.mybluemix.net/docs/20.0.0.10/server-configuration-hardening.html.

**Comment by chirp1** [comment]
Hi Charlotte, 
Here are my latest comments:
- Remove OS. Just use operating system.
- Change "users are able to log in to" to "users log in to". <= Get rid of extra words.
- For the paragraph of "One of the ways to protect against ", move the best practices under the appropriate sections since all the other best practices are in sections.
- For "Basic server configuration hardening best practices", include OL Docker images in the title since the best practices apply to the OL Docker images, too. Reword the title to make it shorter.
- Remove parentheses from WLP_USER_DIR. 
- Add a noun for "to -1".
- For "Use the Transport Security feature instead of the SSL feature.", how about if you say something like "Use Transport Layer Security (TLS) instead of the SSL." Then, add a link to " Use the Transport Security feature instead of the SSL feature. for "Transport Layer Security (TLS)", but don't have one on SSL.
- The four statements have various ticks/back ticks for "true". My guess is that the ticks/back ticks should be the same.
- For "A container that runs in production must have only the tools and ", I think "only" should be removed.
- Change "Although Open Liberty Docker images have basic security that’s already configured, take" to something like "Then, take".
- Move the link on "Docker Hub" to the appropriate, like how we moved other links in other topics.
- I believe these sentences pertain to Docker images: "Container images in Docker Hub are updated every time a new version of Open Liberty is released. Use the most recent images from Docker Hub for the containers that you run in production.". If so, How about if you move them to the "Open Liberty Docker images" section?
- For "following attributes: file owner, group, and other", I believe that it's just "owner", not "file owner". remove "file".
- For "administrators to use sudo authority to switch to this ID to update the configuration.", too many "to" words. Reword.
- For "while other users might need limited write access.", to what might they need access?
- Change QA to quality assurance.
- For "OpenID Connect, for better security.", remove "for better security" since you say the same thing that is in the next sentence in the topic.
- For "in two primary situations", remove "primary" (unnecessary word).
- As mentioned in the peer review cheat sheet, reword "it is important", which is discussed in the next bulleted item:
- Change "In this situation, it is important to ensure that a user can’t override configuration in the server.xml file. To prevent users from overriding configuration in the server.xml file, use the onConflict tag in the <include> element:" to "In this situation, ensure that a user can’t override the configuration in the server.xml file by using the onConflict tag in the <include> element:".
- Change "If you update configuration in the server.xml file or /dropins directory" to "If you update the configuration in the server.xml file or the /dropins directory". 
- Similar to other topics, remove the tick marks in the "securityUtility encode command" link so that the entire text shows the link.
- Wording goes from "Use AES encryption" in one sentences to "plain text encryption" in the next sentence, and "AES encryption" in the next sentence. Reword so that users understand what is going on without having to click on the "securityutility encode command" link.
- Think that the "Other potential vulnerabilities" section can be removed since it really just points to the application and network hardening topics and is the only one of the three topics to link to the other two topics at the end.

**Comment by Charlotte-Holt** [comment]
@chirp1 Thx for the review! I've made the following updates:

- [x] Remove OS. Just use operating system.
- [x] Change "users are able to log in to" to "users log in to". <= Get rid of extra words.
- [x] For the paragraph of "One of the ways to protect against ", move the best practices under the appropriate sections since all the other best practices are in sections.
- [x] For "Basic server configuration hardening best practices", include OL Docker images in the title since the best practices apply to the OL Docker images, too. Reword the title to make it shorter. **KLD 9/22/20: I see that you changed the title to "Basic best practices". I think that is fine. Instead of adding Docker images to the header title, how about if you work docker images into the first two sentences of the topic?**
- [x] Remove parentheses from WLP_USER_DIR.
- [x] Add a noun for "to -1".
- [x] For "Use the Transport Security feature instead of the SSL feature.", how about if you say something like "Use Transport Layer Security (TLS) instead of the SSL." Then, add a link to " Use the Transport Security feature instead of the SSL feature. for "Transport Layer Security (TLS)", but don't have one on SSL.
- [x] The four statements have various ticks/back ticks for "true". My guess is that the ticks/back ticks should be the same.
- [x] For "A container that runs in production must have only the tools and ", I think "only" should be removed. **Charlotte: I think "only" needs to stay in this sentence, because I was trying to emphasize that there shouldn't be any tools that aren't necessary (nothing extraneous)". KLD: 9/22/20: OK I agree.**
- [x] Change "Although Open Liberty Docker images have basic security that’s already configured, take" to something like "Then, take".
- [x] Move the link on "Docker Hub" to the appropriate, like how we moved other links in other topics.
- [x] I believe these sentences pertain to Docker images: "Container images in Docker Hub are updated every time a new version of Open Liberty is released. Use the most recent images from Docker Hub for the containers that you run in production.". If so, How about if you move them to the "Open Liberty Docker images" section? **This one was hard. I see what you're saying, but I feel like the information is more relevant to the OL current version section, rather than to the Docker images section. Could move it, though! KLD: 9/22/20: OK. So, here's a further thought from me. The problem is that the Docker image info is in a section whose title doesn't mention docker images. So, the user might skip over the section titled "Current Open Liberty version". So, my thought is either move the docker image info to the Docker section on change the title of "Current Open Liberty version" to include the Docker image. What do you think?**
- [x] For "following attributes: file owner, group, and other", I believe that it's just "owner", not "file owner". remove "file".
- [x] For "administrators to use sudo authority to switch to this ID to update the configuration.", too many "to" words. Reword.
- [x] For "while other users might need limited write access.", to what might they need access?
- [x] Change QA to quality assurance.
- [x] For "OpenID Connect, for better security.", remove "for better security" since you say the same thing that is in the next sentence in the topic.
- [x] For "in two primary situations", remove "primary" (unnecessary word).
- [x] As mentioned in the peer review cheat sheet, reword "it is important", which is discussed in the next bulleted item:
- [x] Change "In this situation, it is important to ensure that a user can’t override configuration in the server.xml file. To prevent users from overriding configuration in the server.xml file, use the onConflict tag in the element:" to "In this situation, ensure that a user can’t override the configuration in the server.xml file by using the onConflict tag in the element:".
- [x] Change "If you update configuration in the server.xml file or /dropins directory" to "If you update the configuration in the server.xml file or the /dropins directory".
- [x] Similar to other topics, remove the tick marks in the "securityUtility encode command" link so that the entire text shows the link.
- [x] Wording goes from "Use AES encryption" in one sentences to "plain text encryption" in the next sentence, and "AES encryption" in the next sentence. Reword so that users understand what is going on without having to click on the "securityutility encode command" link.
- [x] Think that the "Other potential vulnerabilities" section can be removed since it really just points to the application and network hardening topics and is the only one of the three topics to link to the other two topics at the end.

I left some boxes unchecked because I'm going to ping you to discuss them to make sure I understand.

**Comment by Charlotte-Holt** [comment]
@chirp1 Final updates made. Let me know if anything else needs to be done on this one! https://draft-openlibertyio.mybluemix.net/docs/20.0.0.10/server-configuration-hardening.html

**Comment by chirp1** [comment]
Hi Charlotte,
I have a few minor tweaks:
- Change "the SSL" to "SSL".
- In the "Best practices" section", change the last two bullets so that they follow the same pattern as the bullets that are third and fourth from the bottom so that they read "Add the blah statement to the server.xml file.
- For "Although Open Liberty Docker images have basic security that’s already configured, you need to harden an image if you intend to use it in production.", it still has the long phrase of "Although Open Liberty Docker images have basic security that’s already configured". Also, the "Open Liberty Docker images" section talks about hardening but isn't specific as to what the user does to harden a Docker image. I think that the hardening to be done are the Docker images best practices discussed elsewhere in this "Server configuration security hardening" topic. So, maybe the sentence could instead read something like "Then, if you intend to use the Open Liberty Docker image in production, harden it by following the best practices for Open Liberty Docker images, which are described in this topic.". 
- For "...If you use a custom registry,....", for consistency, should the wording be "custom user registry" instead of "custom registry"?

**Comment by Charlotte-Holt** [comment]
- [x] Change "the SSL" to "SSL".
- [x] In the "Best practices" section", change the last two bullets so that they follow the same pattern as the bullets that are third and fourth from the bottom so that they read "Add the blah statement to the server.xml file.
- [x] For "Although Open Liberty Docker images have basic security that’s already configured, you need to harden an image if you intend to use it in production.", it still has the long phrase of "Although Open Liberty Docker images have basic security that’s already configured". Also, the "Open Liberty Docker images" section talks about hardening but isn't specific as to what the user does to harden a Docker image. I think that the hardening to be done are the Docker images best practices discussed elsewhere in this "Server configuration security hardening" topic. So, maybe the sentence could instead read something like "Then, if you intend to use the Open Liberty Docker image in production, harden it by following the best practices for Open Liberty Docker images, which are described in this topic.". 
- [x] For "...If you use a custom registry,....", for consistency, should the wording be "custom user registry" instead of "custom registry"?

**Comment by chirp1** [comment]
Updates look good! Moving to the Ready to Publish column.

**Comment by Charlotte-Holt** [comment]
Published at https://openliberty.io/docs/20.0.0.10/server-configuration-hardening.html
