### ISSUE TITLE
Network security hardening

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#941]
From LC:  Frame in terms of containers and K8s as well as the network itself. 
- Firewalls, web serviers, and topologies
- Firewalls - use them - don't run Liberty in DMZ (where web server and datapower etc might be). See topology diagram. Keep Liberty locked down in Private zone.
- Keep web server within firewall. Harden connectivity at transport level. At HTTP layer, define which IP origins can be allowed to login/authenticate. When not using web servers and got users inside firewall logging in directly to Liberty server, set <webcontainer> and <htttpDispatcher> elements in server.xml to only allow certain headers to connect from within firewall.
- What's the advice for where to put things in the cloud? Is this determined by the cloud or do you have to decide for yourself?
- Web servers can go in DMZ but be careful what you decide.
- Transport level security/SSL
- TLS (SSL) is a must. Only use CA signed certs (either purchased or own org's signed certs but not self-signed certs).
- Lock down TCP ports - only expose SSL-enabled ports.
- Use transportSecurity over SSL-1.0. ts is better than ssl - pulls in ssl feature but gives ability to add outbound SSL config.
- Use mutual (2-way) ssl/tls (see diagram slide 43).
- Some z/OS.
- Crypto, LDAP, LTPA etc
- Secure links to LDAP servers - have SSL enabled when connecting to LDAP (see example config in slide 49) and encrypt the pw.
- LTPA best practices
- SSO - WebSphere-specific using cookies.
- make sure cookies sent over https instead of http
- replace LTPA keys regularly (need to do it manually with Liberty).
- Restrict use of LTPA to HTTP requests (not used for JavaScript requests). (see slide 51)
- Disable automated config and app updates in production - eg disable use of configDropins for getting app updates (see slide 52 for example config).
- See other recommendations on slide 54 eg
- config apps to run on virtual host
- disable default welcome page
- remove server headers
- disable Powered-By header.
- disable http session overflow
- secure access to JMX connector for remote admin services.

**Scenario 2**: Ops users with containers deployed to Kubernetes/OpenShift

**Resources**:
- https://ibm.box.com/s/u1wedojgzqtsup5icnzh828e2ia10waj
- https://ibm.box.com/s/kp5ght7l9cypnwt4s7vcs3cxz91enjl6
- https://developer.ibm.com/wasdev/docs/configuring-ssl-liberty/

**Comment by Charlotte-Holt** [comment]
Working draft at https://draft-openlibertyio.mybluemix.net/docs/ref/general/#network-hardening.html

**Comment by covener** [comment]
Looks pretty good, just a few minor suggestions/corrections

- addition to firewall section:  The backend firewall, or overall network design, should limit ingress to trusted addresses and limit egress to the minimum addresses required by the application.

- correction for accuracy: "TLS uses signed public keys to protect" should perhaps be "TLS uses key-pairs and signed X509 certificates to protect"

- clarification: "With Open Liberty, proxies are configurable" -> "With Open Liberty, ingress proxies are configurable"

- trustedHeaderOrigin/trustedSensitiveHeaderOrigin confusion:  Based on defaults, one is essentially a whitelist while one is a blacklist so these two go together -- we list IP addresses in trustedSensitiveHeaderOrigin to _include_ them.    trustedHeaderOrigin does not have an authentication impact.

   - "This parameter ensures that only specified IP origins are permitted to authenticate:" -> "This  
    parameter permits proxies using the specified IP addresses to pass along certificate details on 
   behalf of clients"

    - The example with trustedHeaderOrigin should use trustedSensitiveHeaderOrigin instead.  
        @wtlucy  check my work please?

**Comment by wtlucy** [comment]
@covener you're right, the trustedHeaderOrigin section is a little confusing.  What you've said is right: both props act as whitelists for trusted remote IPs, but the default values are 
* `trustedHeaderOrigin="*"` - non-sensitive private headers are trusted from any remote endpoint 
* `trustedSensitiveHeaderOrigin="none"` - sensitive private headers are not trusted at all

I agree that `trustedSensitiveHeaderOrigin` should be used instead in the example, since the client certificate private header (used for mutual auth) is considered "sensitive".

**Comment by Charlotte-Holt** [comment]
@covener @wtlucy - Thanks! Feedback incorporated into https://draft-openlibertyio.mybluemix.net/docs/ref/general/#network-hardening.html.

**Comment by lauracowen** [comment]
Looks great, thanks. Some specific questions/comments:

- Any chance of a diagram to illustrate the firewalls? At least create an issue to add one later?
- Mutual auth section. From the opening paragraph, it's not clear what "mutual authentication" is. The para implies it's to do with running multiple apps on a server but the name (and the paragraph further down) suggests it's a handshake/certificate authentication, regardless of how many apps are on the server. The sentences "For production environments, use mutual (2-way) TLS authentication whenever possible. Mutual authentication is certificate-based authentication for clients." would be great as the first two sentences of this section instead of buried further down.
- Although Liberty can support multiple apps per server, it's not best practice (even before cloud it wasn't best practice on Liberty, but especially not cloud), so can we remove mention of multiple apps on a server? Instead, you could mention (not in the opening para) that the configuration for mutual auth is on a per-app basis (in the web.xml). If you had an ear file running on an OL server and that contained two war files, you could have different configs for each of the ear files (each has its own web.xml config). That's a legit way of having multiple 'apps' on a single server (see https://openliberty.io/guides/maven-multimodules.html for background). So maybe talk in terms of ears/wars instead of "multiple apps"? Check with Ajay though.
- two modes - what determines which mode OL or the app is running in? Is there a config setting for doing this?
- the info about 'proxies' seems like it can be in its own paragraph at the end of the section. Or maybe the penultimate paragraph before a short para about the per-app/web.xml stuff from above.
- LDAP servers - it feels like this config example should be in the LDAP user registry autogen topic. Maybe the other config examples should too but they're shorter at least and it feels like it'd be confusing to have someone keep going to a different topic for them. It may be that, in the LDAP example case, both this topic and the LDAP autogen topic could point to a single include file that contains just the LDAP with TLS config example and description (so that we can ensure they're not maintained differently in future). But at the very least, it seems like it would be missing important info from the LDAP user registry autogen topic if it's only here and it doesn't seem too unreasonable to have to go to the autogen topic in this particular case.
- Minor style thing - I wonder if when you use the "(1)", "(2)" etc callouts, there should be a lead-in sentence saying something like "In the example configuration:". The call-outs aren't that bright in the code example (maybe Design should look at that) so it's not so obvious what the "(1)", "(2)" etc are referring to at a glance.
- Automated updates (a minor structural suggestion) - I wonder if it needs to say sooner in this section that the recommendation is to disable automatic config updates. The first sentences say that config updates should be carefully controlled, then it goes on to explain how dropins and configdropins work across about three short paragraphs. Then it kind of subtley says you can disable this monitoring. Maybe state that up-front (like you've done in the welcome page section after it), then describe how that all works by default so they can see why it matters, then show how to do it.
- welcome page section - what's the different between "type of server" and "which server"? I guess one shows that it's Open Liberty vs Wildfly vs...etc? What's the other show? (give an example of each maybe).

**Comment by Charlotte-Holt** [comment]
@lauracowen I addressed all your comments. To note, I created #1397 to create a diagram to add to this topic. I pinged @jtmulvey about it, and he said we should start from scratch to create a rough draft before sending it to design. Also, the other outstanding issue is the LDAP config example. I started to create a new file to include in both topics, but I noticed that the [LDAP feature topic](https://openliberty.io/docs/ref/feature/#ldapRegistry-3.0.html) already has a TLS example in the **LDAPS** section. I also reached out to Jim about this, and he said that the current example is good to keep in the hardening topic, as it's basic and secure, but the example in the LDAP feature topic is also secure and a more robust config example. Thoughts on keeping both as they are?

**Comment by lauracowen** [comment]
@Charlotte-Holt 
- diagram - that sounds fine.
- LDAP config - it sounds like the "basic and secure" one is the one we'd want people to start with, then if they need more to increase robustness (for some reason?) they could use the one in the LDAP feature topic. Which suggests they should both be in the LDAP feature topic really with an explanation along those lines.

**Comment by Charlotte-Holt** [comment]
Requesting peer review from @ManasiGandhi: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#network-hardening.html

**Comment by Charlotte-Holt** [comment]
@lauracowen I went back to Jim, and we agreed to take the example out of this topic and just keep the example in the LDAP feature topic. I added a short paragraph under the LDAP servers section.

**Comment by ManasiGandhi** [comment]
@Charlotte-Holt A clear and well written topic. Few suggestions,


1.	Under “Firewalls”, in the second sentence, “It’s not recommended to run workloads in the demilitarized zone (DMZ)”, acrolinx is flagging the word “reccomended”, use your discretion. The last sentence in the paragraph ,“The backend firewall, or overall network design, should limit ingress traffic to trusted addresses and limit egress traffic to the minimum addresses required by the application,” instead of  “should limit ingress” can you say “must limit ingress”
2.	In the second sentence under “Security in container environments”, “When Open Liberty is deployed in container environments, segment network traffic based on users, teams, applications, etc. Collections of containers, or pods, apportioned by namespace, offer the ability to provide IP and port isolation”, remove “ etc.” and replace it with “so on ” or “more” or some other term. Also, the remove the upper case C from the word “Collections”.
3.	Under “TLS connectivity”, in the last sentence of the first paragraph, “The auto-generated certificate is convenient for development purposes, but certificates used in production should be signed by a trusted authority, such as Verisign”, instead of “but certificates used in production”, can you say, “but certificates that are used in production”. Also, replace the “should” with “must”. In the second paragraph, in the sentence “Disable non-TLS ports wherever possible. Exposing only TLS-enabled ports requires careful consideration of the server.xml file because some features may automatically enable non-TLS ports”, replace “may” with “can” or “might”.
4.	Under “Mutual authentication”, in the first sentence “For production environments, use mutual (2-way) TLS authentication whenever possible.”, remove the parentheses and maybe say “use mutual or 2-way”. In the sentence, “If you use mutual authentication in conjunction with a proxy, consider using the httpDispatcher parameter with the trustedHeaderOrigin or trustedSensitiveHeaderOrigin options”, instead of “mutual authentication in conjunction with”, can you say “mutual authentication along with”. 
5.	In the fourth paragraph under “LTPA best practices”, in the sentence, “In production environments, the cookie for LTPA should be used only for HTTP requests and not for anything else, such as JavaScript applications”, replace “should” with “must”.
6.	Under “Welcome page and headers”, in the sentence, “For production, you can disable Open Liberty’s welcome page. The welcome page is enabled by default, and accessing the / root context displays the Open Liberty homepage. Disable this homepage by setting the enableWelcomePage custom property to false in the server.xml file:” replace the two instances of the word “homepage” with “home page”.
7.	Under JMX connector, the sentence “When you use the IHS web server, you can secure access to the Open Liberty JMX connector for remote administrative services in the web server plug-in by removing or commenting out the following entries:” is too long according to acrolinx. Can you make it shorter.

**Comment by jtmulvey** [comment]
@Charlotte-Holt nice job. I approve.

**Comment by chirp1** [comment]
@Charlotte-Holt Hi Charlotte, I did a preliminary look at the hardening topics. I ran them through Acrolinx. I see various things that you can fix in each of your topics. Would you go back through Acrolinx, your style guide, and the cheat sheet page on the wiki, and make corrections as appropriate?

**Comment by chirp1** [comment]
Hi Charlotte, Another nice job! Here are my comments:
- Make the intro 2 sentences.
- "The DMZ is an intermediary zone where proxy and web servers run that is located between public and private networking zones." seems to have incorrect grammar in it. 
- I like using "you/your" frequently", but I feel that for "Typically, your network setup includes two firewalls ", since the network setup is typical, I'd use "a" instead of "your".
- "messaging traffic between Open Liberty messaging engines": among?
- Change "config" to "configuration".
- Put a noun after terms. Specifically put a noun before or after a value. For example, 'set the ABC attribute to the XXX value" or 'set the ABC attribute to  the value of XXX".
- For "This parameter permits proxies by using the specified IP addresses to pass along certificate details on behalf of clients: " work into the sentence or in another sentence that the information that follows is an example.
- Reword "For production purposes, the cookie that carries the LTPA token (ltpaToken2) must be protected." to remove the parentheses.
- Include "following" in "Set the option in the server.xml file to require that LTPA cookies are sent over TLS connections: " to introduce to the user that something is coming next. 
- Ensure that terms are called the same thing throughout your writing. I believe, for example, that the Open Liberty welcome page and the Open Liberty home page  are the same thing. If so, make the wording consistent.
- Don't italicize headers, such as the X-Powered-By header.
- Use the official name for the server. IHS is not the official name.
- For the following code clarify the English wording or remove the comment marks of . The wording currently is confusing because you say "by removing the following entries:". However, I believe the user wants to remove "<Uri..../>.

**Comment by Charlotte-Holt** [comment]
@chirp1 Addressing your feedback:

- [X] Make the intro 2 sentences.
- [X] "The DMZ is an intermediary zone where proxy and web servers run that is located between public and private networking zones." seems to have incorrect grammar in it.
- [X] I like using "you/your" frequently", but I feel that for "Typically, your network setup includes two firewalls ", since the network setup is typical, I'd use "a" instead of "your".
- [X] "messaging traffic between Open Liberty messaging engines": among?
- [X] Change "config" to "configuration".
- [X] Put a noun after terms. Specifically put a noun before or after a value. For example, 'set the ABC attribute to the XXX value" or 'set the ABC attribute to the value of XXX".
- [ ] For "This parameter permits proxies by using the specified IP addresses to pass along certificate details on behalf of clients: " work into the sentence or in another sentence that the information that follows is an example.
- [X] Reword "For production purposes, the cookie that carries the LTPA token (ltpaToken2) must be protected." to remove the parentheses.
- [ ] Include "following" in "Set the option in the server.xml file to require that LTPA cookies are sent over TLS connections: " to introduce to the user that something is coming next.
- [ ] Ensure that terms are called the same thing throughout your writing. I believe, for example, that the Open Liberty welcome page and the Open Liberty home page are the same thing. If so, make the wording consistent.
- [X] Don't italicize headers, such as the X-Powered-By header.
- [X] Use the official name for the server. IHS is not the official name.
- [ ] For the following code clarify the English wording or remove the comment marks of . The wording currently is confusing because you say "by removing the following entries:". However, I believe the user wants to remove "<Uri..../>.

**Comment by chirp1** [comment]
Returning this topic so that you make updates to go with the "Hardening servers in production" topic.

**Comment by Charlotte-Holt** [comment]
@chirp1 Updated! Topic at https://draft-openlibertyio.mybluemix.net/docs/20.0.0.10/network-hardening.html.

**Comment by chirp1** [comment]
Hi!
- The short description is looking better. Maybe make hardening more of a definition and lead with the hardening sentence. You use both network intrusion and network attack. I think you can use just one term, and to me, more likely network attack. Also, the the first sentence, which is about network intrusion, is a little hard to decipher for "and can alter traffic and steal network resources" as I had to determine whether the phrase went with "unauthorized users" or "network intrusions". 
- I think that "also enable TLS in your client and web server" might need a little refining. I don't think "your" is quite right as many clients would be coming to the web server from the internet. Also, I don't think TLS would be enabling TLS in the client. I think that would already be done in the client (browser). With TLS being a protocol- maybe what is meant is that when using TLS, that a private connection between a client and the server is established and that data between them is encrypted.
- Change "auto-generated" to "automatically generated". <==Use complete words.
- Change "a secure HTTP scheme (HTTPS)" to "the HTTPS protocol". (to address parentheses, wordiness, and incorrect noun of "scheme" to describe HTTP and HTTPS)
- To clarify  my "Use the official name for the server. IHS is not the official name." comment, don't have an unofficial name in the documentation. 
- Review the peer review cheat sheet and make changes as appropriate for "should".
- For "some features might automatically enable non-TLS ports.", do we have features that automatically enable non-TLS ports? If so, is "might" necessary?
- For "configurable by application.", I think a definite or indefinite article is missing before "application".
- For "it can be used for application authentication", is "application" the correct word? I think the word should be "client".
- For "clientAuthenticationSupported attribute" and "clientAuthentication attribute", look at what the links look like. in this case, I can't tell that the attribute names are part of the link. My suggestion is that you don't use back ticks when you are using a term or word in a link.
- For, "If your Open Liberty deployment does not include any proxies, set the following parameters in the server.xml file:", describe why a user would set the parameters.
- For "you use LTPA with SSO.", is "with SSO" needed? You mentioned SSO in terms of LTPA in the previous sentence.
- For "disabling HTTP session overflow", add the custom property that does the disabling into the text for the section. I think the custom property is "allowOverflow="false"".

**Comment by Charlotte-Holt** [comment]
@chirp1 I updated the doc with your review suggestions. Thx! 

- [x] The short description is looking better. Maybe make hardening more of a definition and lead with the hardening sentence. You use both network intrusion and network attack. I think you can use just one term, and to me, more likely network attack. Also, the the first sentence, which is about network intrusion, is a little hard to decipher for "and can alter traffic and steal network resources" as I had to determine whether the phrase went with "unauthorized users" or "network intrusions".
- [x] I think that "also enable TLS in your client and web server" might need a little refining. I don't think "your" is quite right as many clients would be coming to the web server from the internet. Also, I don't think TLS would be enabling TLS in the client. I think that would already be done in the client (browser). With TLS being a protocol- maybe what is meant is that when using TLS, that a private connection between a client and the server is established and that data between them is encrypted.
- [X] Change "auto-generated" to "automatically generated". <==Use complete words.
- [x] Change "a secure HTTP scheme (HTTPS)" to "the HTTPS protocol". (to address parentheses, wordiness, and incorrect noun of "scheme" to describe HTTP and HTTPS)
- [x] To clarify my "Use the official name for the server. IHS is not the official name." comment, don't have an unofficial name in the documentation. - **I don't see IHS in this topic, so I'm not sure what to change for this one.** 
- [x] Review the peer review cheat sheet and make changes as appropriate for "should".
- [x] For "some features might automatically enable non-TLS ports.", do we have features that automatically enable non-TLS ports? If so, is "might" necessary?
- [x] For "configurable by application.", I think a definite or indefinite article is missing before "application".
- [x] For "it can be used for application authentication", is "application" the correct word? I think the word should be "client". - **Jim confirmed that "application authentication" is correct**
- [x] For "clientAuthenticationSupported attribute" and "clientAuthentication attribute", look at what the links look like. in this case, I can't tell that the attribute names are part of the link. My suggestion is that you don't use back ticks when you are using a term or word in a link.
- [x] For, "If your Open Liberty deployment does not include any proxies, set the following parameters in the server.xml file:", describe why a user would set the parameters.
- [x] For "you use LTPA with SSO.", is "with SSO" needed? You mentioned SSO in terms of LTPA in the previous sentence.
- [x] For "disabling HTTP session overflow", add the custom property that does the disabling into the text for the section. I think the custom property is "allowOverflow="false"".

**Comment by chirp1** [comment]
Hi Charlotte,
A few comments: 
- Oddly, IHS showed up in the JMX connector section in the version of the topic that I saw even though, from looking at your pull requests, you had removed the reference previously. Maybe I was looking at a different branch that had a back-level version.
- Nice explanation for "If your Open Liberty deployment doesn’t include any proxies, ....".

Some things to fix/investigate:
- The opening paragraph- a little tweak- update it so that it's two sentences.
- Custom property references in the topic. I've been researching its use. Would you research it, too? I don't think it is the right term. We can discuss and come up with something for the team to use consistently for these things in the server.xml file. I also seem to see these things called "option" in your topic. We want to be consistent with the terms.

**Comment by Charlotte-Holt** [comment]
@chirp1 Updates made! I _think_ I got the custom property thing right. After searching around, I went with "configuration element" and "attribute". 

- [x] The opening paragraph- a little tweak- update it so that it's two sentences.
- [x] Custom property references in the topic. I've been researching its use. Would you research it, too? I don't think it is the right term. We can discuss and come up with something for the team to use consistently for these things in the server.xml file. I also seem to see these things called "option" in your topic. We want to be consistent with the terms.

**Comment by chirp1** [comment]
The updates look Moving to Ready to publish.

**Comment by Charlotte-Holt** [comment]
Published at https://openliberty.io/docs/20.0.0.10/network-hardening.html
