### ISSUE TITLE
Application security hardening

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#942]
From LC:  Frame in terms of writing apps with Maven build tools and deploying apps in containers to K8s etc. ⁃	Java EE role-based authorization (see example slide 57). If you don't config the server.xml, by default will use the group name that the server is running under as the group name - be aware.

- Java EE security relies on roles and mappings to users and groups in a registry. Annotations and web.xml are used to define the roles and ibm-application-bnd.xm* and server.xml files are used to bind th eroles to the users/groups.
- web.xml takes precedence if conflicts. server.xml takes prece over ibm-applicatilon… if conflict.
- see other point about role mapping binding on slide 58)
- see list of other things on slide 59).
- Never set web server doc root to WAR.
- don't serve servlets by class name -it's possible but off by default so don't enable it.
- verify servlet aliases are secure (see example on slide 61 of unsafe vs safe).
- don't put sensitive info in WAR root
- define default error handler so can present a clean error back
- consider disabling file serving and directory browsing (this is off by default anyway - make sure it's off for production use).
- ensure apps specifiy transport guarantee of confidential in web.xml etc.
- see slide 64 for others. But also run IBM AppScan or similar on apps as early as poss to identify vulnerabilities (See URL on ibm.com)

**Scenario 2**:  Ops users with containers deployed to Kubernetes/OpenShift

**Resources**:
- https://ibm.box.com/s/u1wedojgzqtsup5icnzh828e2ia10waj
- https://ibm.box.com/s/kp5ght7l9cypnwt4s7vcs3cxz91enjl6)

**Comment by lauracowen** [comment]
- "can lead to users with access to sensitive information" is a bit ambiguous. I think it might be better phrased as "can lead to users having access to sensitive information" (at first I read it as a sentence with an error in it: "can lead to users with access to sensitive information" doing what?)
- couple of typos "int he" and in a couple of places "ibm-application-bnd.xmi" (should be `.xml` no `.xmi`)
- `ibm-web-ext.xmi` should also be `.xml` not `.xmi` throughout.
- "It’s likely that you must list all the methods if you are using multiple constraints." - "It's likely that..." is a bit vague when it's just said that you must list all the methods. Maybe flip the sentence around... "If you are using multiple constraints, list all the methods." (or something like that?)
- Maybe in the lead-in sentence before the XML example, say which file this is for eg "you must add a security constraint in the web.xml file for..."?
- can we assume that people are using Servlet 3.1 or higher and show that in the example. Then maybe have a note underneath saying to omit those lines if lower than 3.1? Let's assume people are at the latest then, when absolutely necessary, flag up where they should make changes for lower versions. Unless the additional lines are ignored by lower versions (as opposed to throwing errors), in which case maybe nothing is needed, or we just say they're ignored.
- are any of these specialise .xml files mentioned anywhere else in the docs? I know David is looking for the web.xml schema (alasdair said it'd be useful to publish the schema as OL is picky about the XML syntax being accurate). But ibm-web-ext.xml, ibm-application-bnd.xml, etc - maybe we need a topic showing which file is in which directory, what it's for, and its schema ( @NottyCode?) ? Is there anything like that in the KC already?
- why/when would you put `CONFIDENTIAL` in the web.xml versus in the ibm-web-ext.xml file? (ie which file is best practice to use? if either, how do you decide which to use?)

**Comment by Charlotte-Holt** [comment]
@lauracowen I addressed your above feedback. The only thing left open was your question about the specialized XML files - I don't think we currently have a topic planned for this, but maybe it could be useful. I found a topic about [Application bindings](https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/cwlp_app_bindings.html) in the KC that could be helpful in writing a new topic. A bit of this information is covered in this application config hardening topic, but certainly not all of it.

**Comment by Charlotte-Holt** [comment]
Requesting full peer review from @Rwalls1

**Comment by Rwalls1** [comment]
This topic was well-written, I just have a few comments:
- For the opening paragraph that starts with “If your application isn’t properly secured” I think the short description could be more concise and clear. I think maybe the sentence that starts with “Before you can run an application” could be the new first sentence. Then you could combine the other two sentences to say something like: "By hardening the application configuration, you can provide security that prevents the unauthorized exposure of sensitive information.
- In the sentence that starts with “For conflicts in a servlet’s role”, there are two instances where add possessives to inanimate things so I think you should change “in a servlet’s role mapping” to “in the role mapping of a servlet” and change “between an application’s web.xml file” to “between the web.xml file of an application”
- With the phrase “overwrites the one from the application”, I think you should change “the one” to “the role” to avoid any possible confusion.
- With “which means that code, raw JSPs, and more”, you should specify a noun after more to avoid any confusion.
- The phrase “Each URL to be secured must be specified” reads a bit awkwardly so maybe change it to “Each URL that is secured must be specified”
- I think you can remove the phrase “Be Cautious” as it seemingly doesn’t add much value on its own can be implied from the rest of the paragraph
- The sentence that starts with “If a servlet has more than one alias” should probably be broken up into two sentences to make it simpler and easier to read
- For the phrase, "raw exception stack dump of the error", I think it would be good clarify exactly what this referring to or maybe just provide an example of what it looks like.

**Comment by Charlotte-Holt** [comment]
@Rwalls1 Thanks for your review. I incorporated your comments. I'm waiting on an example of a raw exception stack dump from @una-tapa.

**Comment by una-tapa** [comment]
Hi, According to WebContainer team (Evan),  customer reported the raw exception as security exposure, revealing the internal code details.  So Evan took an apar to suppress the exception.  Please delete the description from the draft.

**Comment by jtmulvey** [comment]
Approved.

**Comment by chirp1** [comment]
@Charlotte-Holt Hi Charlotte, I did a preliminary look at the hardening topics. I ran them through Acrolinx. I see various things that you can fix in each of your topics. Would you go back through Acrolinx, your style guide, and the cheat sheet page on the wiki, and make corrections as appropriate? Also, "check out" is slang. Would you change the wording so that you aren't using slang?

**Comment by chirp1** [comment]
Hi Charlotte, here are my comments:
- Go through the cheat sheet at https://apps.na.collabserv.com/wikis/home?lang=en-us#!/wiki/W93fb765ee31c_4aa7_98f6_a02c0f1a2ebf/page/Peer%20review%20cheat%20sheet
- Rewrite the introductory paragraph to make it more meaningful to the user, employing recommendations in the short description. You can probably use infro form the second paragraph as the intro paragraph, but make the intro two sentences.
- Run Acrolinx again. I spot three issues that are outside of code examples that could be changed.
- Change config to configuration. 
- The sentence is a little long and has multiple thoughts: "If you don’t configure user roles in the server.xml file, Open Liberty uses the group names that a user is attached to as the role names for the user by default. " How about if you rearrange it to make it a little clearer by having the "by default" towards the front along with the "if". The implied "then" follows:  "If you don’t configure user roles in the server.xml file, by default, Open Liberty uses the group names that a user is attached to as the role names for the user.'.
- For "in the web.xml of " put a noun after web.xml.
- Change "the role from the server.xml file overwrites the role from the application. " to "the security role from the server.xml file overwrites the security role from the ibm-application-bnd.xml file."
- Do "role-mapping binding information" and "application binding information" the same thing? If so, use just one of the terms. We want to be consistent in the terms that we use.
- Also, I found "This example applies only when application binding information isn’t specified for the application in the ibm-application-bnd.xml or server.xml files. " a little confusing as it is placed after the example. Maybe instead of the "When the role-mapping binding information for... paragraph, rewrite it to something like "When the role-mapping binding information isn’t specified for the application in the ibm-application-bnd.xml or server.xml files, the group name and role name must be the same. For example, if the role name is manager, then a user who belongs to a manager group has access to that resource.".
- For "If the web server document root is set to the WAR root, the web server serves up all the contents of the WAR file without interpretation. If the web server serves up this information, it means that code, raw JSPs, and other resources are served to your users." check the clarity index on the Acrolinx scorecard for these sentences and rewrite them. The clarity index for them is 28. I was able to rewrite them to get 60. 
- The "Avoid placing sensitive information...." paragraph has information that is redundant with the "WAR files contain application..." paragraph graph that proceeds it. Rewrite the second paragraph or merge the paragraphs to get rid of the redundancies. I think the main points from the second paragraph include "the web container serves files from the WAR root", sensitve information in the WAR file goes "in the WEB-INF directory, as permitted by the servlet specification.", and "Information in this directory is never served by the web container.". 
- Research URL versus URI and change accordingly.
- Reword "(such as /servlet)" so that you don't have parentheses.
- Put a noun after "/servlet/com.ibm.sample.MyServlet ".
- Change "than one alias, for example " to "than one alias. For example "
- This statement is confusing "multiple URLs can access the same servlet class or there might be many servlets". You said for "for example", but you gave two examples, not one. As mentioned previously, research URL versus URI. And then, how do the examples relate to the alias? I'd like to see it specifically mentioned. Are you saying that each servlet class has a different alias for each URL (or URI)? I don't understand the "might be many servlets" in relations to multiple aliases.
- For "If that is not appropriate, ", put a noun after "that" or reword to remove "that". 
- Don't use Latin terms. In this case, don't use "etc.".
- Put a noun after "GET, POST, PUT, HEAD ".
- The differences between the "When the <deny-uncovered-http-methods> element is specified " paragraph and the "If the <deny-uncovered-http-methods> element isn’t specified " are subtle. I had to reread and study the paragraphs to understand the subtleties. "is" versus "isn't. "unprotected and not accessible " and "unprotected and accessible " We want to help the reader out so that, as much as possible, they don't have to reread and study the material to understand it. To fix this issue, you could, for instance have an introductory paragraph that explains what is going on with the two paragraphs. If you have an intro paragraph, then you could likely make each of the two paragraphs a bullet item in a bulleted list.
- Change "specify transport guarantee of CONFIDENTIAL " to "specify the transport guarantee with a value of CONFIDENTIAL " or "specify the transport-guarantee element with a value of CONFIDENTIAL "

**Comment by Charlotte-Holt** [comment]
@chirp1 

- [ ] Go through the cheat sheet at https://apps.na.collabserv.com/wikis/home?lang=en-us#!/wiki/W93fb765ee31c_4aa7_98f6_a02c0f1a2ebf/page/Peer%20review%20cheat%20sheet
- [X] Rewrite the introductory paragraph to make it more meaningful to the user, employing recommendations in the short description. You can probably use infro form the second paragraph as the intro paragraph, but make the intro two sentences.
- [ ] Run Acrolinx again. I spot three issues that are outside of code examples that could be changed.
- [X] Change config to configuration.
- [X] The sentence is a little long and has multiple thoughts: "If you don’t configure user roles in the server.xml file, Open Liberty uses the group names that a user is attached to as the role names for the user by default. " How about if you rearrange it to make it a little clearer by having the "by default" towards the front along with the "if". The implied "then" follows: "If you don’t configure user roles in the server.xml file, by default, Open Liberty uses the group names that a user is attached to as the role names for the user.'.
- [X] For "in the web.xml of " put a noun after web.xml.
- [X] Change "the role from the server.xml file overwrites the role from the application. " to "the security role from the server.xml file overwrites the security role from the ibm-application-bnd.xml file."
- [ ] Do "role-mapping binding information" and "application binding information" the same thing? If so, use just one of the terms. We want to be consistent in the terms that we use.
- [X] Also, I found "This example applies only when application binding information isn’t specified for the application in the ibm-application-bnd.xml or server.xml files. " a little confusing as it is placed after the example. Maybe instead of the "When the role-mapping binding information for... paragraph, rewrite it to something like "When the role-mapping binding information isn’t specified for the application in the ibm-application-bnd.xml or server.xml files, the group name and role name must be the same. For example, if the role name is manager, then a user who belongs to a manager group has access to that resource.".
- [ ] For "If the web server document root is set to the WAR root, the web server serves up all the contents of the WAR file without interpretation. If the web server serves up this information, it means that code, raw JSPs, and other resources are served to your users." check the clarity index on the Acrolinx scorecard for these sentences and rewrite them. The clarity index for them is 28. I was able to rewrite them to get 60.
- [ ] The "Avoid placing sensitive information...." paragraph has information that is redundant with the "WAR files contain application..." paragraph graph that proceeds it. Rewrite the second paragraph or merge the paragraphs to get rid of the redundancies. I think the main points from the second paragraph include "the web container serves files from the WAR root", sensitve information in the WAR file goes "in the WEB-INF directory, as permitted by the servlet specification.", and "Information in this directory is never served by the web container.".
- [ ] Research URL versus URI and change accordingly.
- [ ] Reword "(such as /servlet)" so that you don't have parentheses.
- [ ] Put a noun after "/servlet/com.ibm.sample.MyServlet ".
- [ ] Change "than one alias, for example " to "than one alias. For example "
- [ ] This statement is confusing "multiple URLs can access the same servlet class or there might be many servlets". You said for "for example", but you gave two examples, not one. As mentioned previously, research URL versus URI. And then, how do the examples relate to the alias? I'd like to see it specifically mentioned. Are you saying that each servlet class has a different alias for each URL (or URI)? I don't understand the "might be many servlets" in relations to multiple aliases.
- [ ] For "If that is not appropriate, ", put a noun after "that" or reword to remove "that".
- [ ] Don't use Latin terms. In this case, don't use "etc.".
- [ ] Put a noun after "GET, POST, PUT, HEAD ".
- [ ] The differences between the "When the element is specified " paragraph and the "If the element isn’t specified " are subtle. I had to reread and study the paragraphs to understand the subtleties. "is" versus "isn't. "unprotected and not accessible " and "unprotected and accessible " We want to help the reader out so that, as much as possible, they don't have to reread and study the material to understand it. To fix this issue, you could, for instance have an introductory paragraph that explains what is going on with the two paragraphs. If you have an intro paragraph, then you could likely make each of the two paragraphs a bullet item in a bulleted list.
- [ ] Change "specify transport guarantee of CONFIDENTIAL " to "specify the transport guarantee with a value of CONFIDENTIAL " or "specify the transport-guarantee element with a value of CONFIDENTIAL "

**Comment by chirp1** [comment]
Returning this topic so that you make updates to go with the "Hardening servers in production" topic.

**Comment by Charlotte-Holt** [comment]
@chirp1 I updated the parent topic and moved the info from the application configuration summary section to this topic.

**Comment by Charlotte-Holt** [comment]
@chirp1 Topic at https://draft-openlibertyio.mybluemix.net/docs/20.0.0.10/application-configuration-hardening.html.

**Comment by chirp1** [comment]
Hi Charlotte,
Thanks for making the updates that I mentioned. Somehow, I spotted a few more things that I didn't previously. But, we're almost done!
- For "by following some best practices.", I think that (1) we want the user to follow all the best practices and (2) we want to reduce wordiness / unnecessary words. Wordiness is discussed in the IBM style guide. Remove the misleading and unnecessary word. 
- For "....privileges when they run it.", I think you can clarify the point. How about something like "... privileges when they run it and gain access to sensitive information". Then, rework the second paragraph a little so that it fits better with the opening paragraph.
- For " If the information that is being specified can have multiple values, the values from the server.xml file are added to the values from the application. For example, if the ibm-application-bnd.xml file defines two security roles and the server.xml file defines one role, all three security roles are used.", the wording seems a bit vague and unclear,  and "value" doesn't seem like the right word. Again, the IBM style guide could help with the wording, possibly in the clarity section: https://learning.oreilly.com/library/view/Developing+Quality+Technical+Information:+A+Handbook+for+Writers+and+Editors,+Third+Edition/9780133119046/ch06.html#ch06lev1sec2 or other sections such as this one on writing and rewriting: https://learning.oreilly.com/library/view/Developing+Quality+Technical+Information:+A+Handbook+for+Writers+and+Editors,+Third+Edition/9780133119046/ch02.html#ch02lev1sec2 Since the section is about roles, does the "value", maybe "role" and some other words could replace "value". For the example, maybe you could include actual roles, etc to more concretely describe the example.
- For "If a conflict exists between the ibm-application-bnd.xml and server.xml files", give an example of a conflict. See the references to the style guide in the previous bullet for help.
- For "a single generic URI, such as /servlet, serves all servlets. The component of the path after the base is " you call "/servlet" two different things- "generic URI" and "base". Review the peer review cheat sheet and correct: https://apps.na.collabserv.com/wikis/home?lang=en-us#!/wiki/W93fb765ee31c_4aa7_98f6_a02c0f1a2ebf/page/Peer%20review%20cheat%20sheet
- For "Secure servlets", I think we want to say at the beginning of the section that the user should not use the class name in production. We don't say that point until the second sentence of the second paragraph. Would you rewrite the paragraph to get the class name info at the beginning.  Also, I believe the implication is that if somebody wants to use the class name, it should be used in pre-production. So, specify in what stage, i.e. pre-production, that the class name can be used. Again, see the IBM style guide as needed to see how to rewrite the section: https://learning.oreilly.com/library/view/developing-quality-technical/9780133119046/toc.html.
- Change "carefully double check " to "carefully check" to get rid of the extra word.
- For "If you are using multiple constraints, list all the methods.", this sentence seems redundant with the first sentence in the paragraph. Remove the sentence or rewrite the paragraph as appropriate to make what is going on clear. Refer to the IBM style guide as needed. Also, the naming of the constraints seems inconsistent- "authorization constraints" in the first sentence of the paragraph and "constraints" in the second sentence. See the "Peer review cheat sheet" for the discussion about consistently naming terms.

**Comment by Charlotte-Holt** [comment]
@chirp1 Thx for the review! I've made the following updates:

- [x] For "by following some best practices.", I think that (1) we want the user to follow all the best practices and (2) we want to reduce wordiness / unnecessary words. Wordiness is discussed in the IBM style guide. Remove the misleading and unnecessary word.
- [x] For "....privileges when they run it.", I think you can clarify the point. How about something like "... privileges when they run it and gain access to sensitive information". Then, rework the second paragraph a little so that it fits better with the opening paragraph.
- [x] For " If the information that is being specified can have multiple values, the values from the server.xml file are added to the values from the application. For example, if the ibm-application-bnd.xml file defines two security roles and the server.xml file defines one role, all three security roles are used.", the wording seems a bit vague and unclear, and "value" doesn't seem like the right word. Again, the IBM style guide could help with the wording, possibly in the clarity section: https://learning.oreilly.com/library/view/Developing+Quality+Technical+Information:+A+Handbook+for+Writers+and+Editors,+Third+Edition/9780133119046/ch06.html#ch06lev1sec2 or other sections such as this one on writing and rewriting: https://learning.oreilly.com/library/view/Developing+Quality+Technical+Information:+A+Handbook+for+Writers+and+Editors,+Third+Edition/9780133119046/ch02.html#ch02lev1sec2 Since the section is about roles, does the "value", maybe "role" and some other words could replace "value". For the example, maybe you could include actual roles, etc to more concretely describe the example.
- [x] For "If a conflict exists between the ibm-application-bnd.xml and server.xml files", give an example of a conflict. See the references to the style guide in the previous bullet for help. **KLD: 9/23/20 Where you say "the information that", can it be anything other than security roles? If so, what?.... I think that "user role" is mentioned in the "Authorization topic", but "user role" maybe should just be "role"..... For the security roles, maybe we could give some examples, like admin, user, viewer, etc so that the user gets more concrete examples.**
- [x] For "a single generic URI, such as /servlet, serves all servlets. The component of the path after the base is " you call "/servlet" two different things- "generic URI" and "base". Review the peer review cheat sheet and correct: https://apps.na.collabserv.com/wikis/home?lang=en-us#!/wiki/W93fb765ee31c_4aa7_98f6_a02c0f1a2ebf/page/Peer%20review%20cheat%20sheet
- [x] For "Secure servlets", I think we want to say at the beginning of the section that the user should not use the class name in production. We don't say that point until the second sentence of the second paragraph. Would you rewrite the paragraph to get the class name info at the beginning. Also, I believe the implication is that if somebody wants to use the class name, it should be used in pre-production. So, specify in what stage, i.e. pre-production, that the class name can be used. Again, see the IBM style guide as needed to see how to rewrite the section: https://learning.oreilly.com/library/view/developing-quality-technical/9780133119046/toc.html.
- [x] Change "carefully double check " to "carefully check" to get rid of the extra word.
- [x] For "If you are using multiple constraints, list all the methods.", this sentence seems redundant with the first sentence in the paragraph. Remove the sentence or rewrite the paragraph as appropriate to make what is going on clear. Refer to the IBM style guide as needed. Also, the naming of the constraints seems inconsistent- "authorization constraints" in the first sentence of the paragraph and "constraints" in the second sentence. See the "Peer review cheat sheet" for the discussion about consistently naming terms.

I left some boxes unchecked because I'm going to ping you to discuss them to make sure I understand.

**Comment by chirp1** [comment]
The updates look good! Moving to Ready to Publish.

**Comment by Charlotte-Holt** [comment]
Published at https://openliberty.io/docs/20.0.0.10/application-configuration-hardening.html
