### ISSUE TITLE
Example config for spnego feature (SPNEGO)

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#954]
https://www.openliberty.io/docs/ref/feature/#spnego-1.0.html

**Comment by Charlotte-Holt** [comment]
@utle Please review https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#spnego-1.0.html.

**Comment by utle** [comment]
In order to make SPNEGO authentication work for Liberty, customer have to configure the following:
1) Browser
2) KDC - MS AD machine
3) Configure the Liberty 

This article along is part of the 3). If customer just configure what is in this article, the SPNEGO authentication will not work.

**Comment by Charlotte-Holt** [comment]
@utle I created #1479 to cover the additional SPNEGO config. After we have that topic, it'll link to and from this feature topic. Can you please review these feature config examples?

**Comment by utle** [comment]
The feature config examples looked to me.

**Comment by lauracowen** [comment]
@Charlotte-Holt Is it worth holding out this topic from publishing until we have the other article? Then this page can link to that article (as it doesn't sound as if the config here alone will be that useful). What do you think?

**Comment by Charlotte-Holt** [comment]
@lauracowen Yes, I think so. I talked with Ut about it too, and I think we could go ahead and get this one reviewed, but hold off on publishing it until we have the other topic (which I just started and should hopefully have a draft of soon). Then, we can give this topic one last look to make sure it makes sense in context with the new SPNEGO configuration topic.

**Comment by ManasiGandhi** [comment]
@Charlotte-Holt The doc looks good! Some minor suggestions,

- In the first paragraph under examples, it says "To enable SPNEGO authentication, you must also configure your browser, KDC, and Open Liberty. For information about how to configure these other items, see Configuring SPNEGO authentication in Open Liberty." You can change it to "To enable SPNEGO authentication, configure your browser, KDC, and Open Liberty. For information, see Configuring SPNEGO authentication in Open Liberty." for conciseness and consistency. Also, you could specify what KDC stands for, as it has not been mentioned anywhere else in the doc.

-  "The client’s GSS credentials are not added to the user subject upon successful authentication." Is the client in this sentence a person or can it be also an inanimate object, for example, a server or an application in some cases? If so, then possibly rephrase the sentence to "The client GSS credentials are not added to the user subject upon successful authentication."

- Could you change this sentence "The Kerberos configuration and keytab files used by the server are given specific locations within the server configuration directory instead of within their default locations.",  to, 
"The Kerberos configuration and keytab files that are used by the server are given specific locations within the server configuration directory instead of within their default locations."Acrolinx asked to add 'that' after 'files'.

**Comment by Charlotte-Holt** [comment]
Thanks, @ManasiGandhi! 

- First point - I added what KDC stands for. Good catch! I kept the rest the way it is, though, because Ut wanted me to emphasize that SPNEGO requires that you configure the other pieces, otherwise it won't work. We can see what @chirp1 thinks, but I wanted to try to emphasize that the other pieces are necessary. 
- Second point - Updated! 
- Third point - Updated!

**Comment by Charlotte-Holt** [comment]
@chirp1 Topic at https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/reference/feature/spnego-1.0.html.

**Comment by dmuelle** [comment]
need to replace `${server.config.dir}` variable with an example (use `server1` for consistency ) per #1877. Once the file is updated, please mark it off from the checklist in that issue- thanks!

**Comment by Charlotte-Holt** [comment]
Updates made:

- "Specify attributes within the [`authFilter` element](https://openliberty.io/docs/20.0.0.10/reference/config/authFilter.html) in the `server.xml` file..." **-->** "Specify attributes within the [authFilter element](https://openliberty.io/docs/20.0.0.10/reference/config/authFilter.html) in the `server.xml` file..." - **DQTI, Chapter 8, Style, Use consistent tagging**
- "The client GSS credentials are not added to the user subject upon successful authentication." **-->** "The client GSS credentials aren't added to the user subject upon successful authentication." - **DQTI, Chapter 8, Style, Spell terms consistently**

**Comment by Charlotte-Holt** [comment]
Published at https://openliberty.io/docs/20.0.0.11/reference/feature/spnego-1.0.html. Still requires final editorial review.

**Comment by chirp1** [comment]
Hi Charlotte,
I liked that you explained the examples in some detail. Here are the rest of my comments:
- Remove "If you want to learn more about single sign-on (SSO) ..." sentence because the SSO link has little info and points back to your Configuring SPNEGO authentication  link which has the detail.
- Change "For more information about how to configure these other items, " to "For more information, ".
- Change your approach on how to describe the filter example because the 1,2,3 in circles and the table that goes with it are creating accessibility issues. I ran JAWS on the page. The 1,2,3 in circles with the descriptions don't look like they are in a table to sighted users, but it is a table for those using JAWS. So, what JAWS users here and sighted users see is inconsistent. Also, the numbers in the example make it hard to understand what is going for JAWS users. .Try instead explaining each statement, maybe in a list. So, something like "For the host statement, blah.", and so on.
- For "...LTPA, see Authentication. ", change the link to the SSO topic at https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/single-sign-on.html#_ltpa because the Authtentication topic says little about LTPA and link to the SSO topic.
- How about removing the highlighted text from attribute names, for example, disableLtpaCookie attribute.

**Comment by Charlotte-Holt** [comment]
@chirp1 Thanks! I made updates for all items that you mentioned:

- [x] Remove "If you want to learn more about single sign-on (SSO) ..." sentence because the SSO link has little info and points back to your Configuring SPNEGO authentication link which has the detail.
- [x] Change "For more information about how to configure these other items, " to "For more information, ".
- [x] Change your approach on how to describe the filter example because the 1,2,3 in circles and the table that goes with it are creating accessibility issues. I ran JAWS on the page. The 1,2,3 in circles with the descriptions don't look like they are in a table to sighted users, but it is a table for those using JAWS. So, what JAWS users here and sighted users see is inconsistent. Also, the numbers in the example make it hard to understand what is going for JAWS users. .Try instead explaining each statement, maybe in a list. So, something like "For the host statement, blah.", and so on. 
- [x] For "...LTPA, see Authentication. ", change the link to the SSO topic at https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/single-sign-on.html#_ltpa because the Authtentication topic says little about LTPA and link to the SSO topic.
- [x] How about removing the highlighted text from attribute names, for example, disableLtpaCookie attribute. - **Talked with @chirp1 about this, and we're going to leave elements and attributes monospaced. Karen's opening a doc bug in the `openliberty.io` repo to make the monospaced text on the site more readable.**

Link to draft: https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.1/reference/feature/spnego-1.0.html

**Comment by chirp1** [comment]
Hi Charlotte,
Nice job on reworking the 1,2,3 circles. Just a few minor tweaks: 

- [x] You have two words in a row that are the same. See if you can find the words and remove the extra word.
- [x] Change "disabled, so a mechanism" to " disabled so that a mechanism".
- [x] For my "For "...LTPA, see Authentication. " comment that I made previously, check whether the link in your topic is correct and make adjustments accordingly.

**Comment by Charlotte-Holt** [comment]
@chirp1 I made all your requested updates: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.2/reference/feature/spnego-1.0.html. Thanks!

**Comment by chirp1** [comment]
@Charlotte-Holt The updates look good! Moving to Ready to Publish.

**Comment by Charlotte-Holt** [comment]
Merged to `vNext` in #3530
